### ISSUE TITLE
Hitting escape in a modal dialog kills the dialog

### ISSUE THREAD

**Issue by aitchnyu** [JedWatson/react-select#944] opened 2016-05-06 19:03 UTC
I use react-bootstrap modals. It listens to escape key to close itself. I use a select widget inside a modal window. While the dropdown is showing, I hit escape which closes the dropdown as well as the modal. I guess the select widget should suppress that keypress after closing the dropdown so that its not propagated to the modal hosting it.

**Comment by gojohnnygo** [comment] 2016-05-07 19:57
@aitchnyu Looks like the quick and easy solution is to add `event.stopPropagation();` [here](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L422) (in addition to `event.preventDefault();`).

I'm not sure if the modal use case is big enough for a PR, though. So you may have to fork your own.

**Comment by eisenjulian** [comment] 2016-07-04 10:55
I'm having the same issue. What did you end up doing? Forking?

**Comment by aitchnyu** [comment] 2016-07-04 17:13
@eisenjulian I no longer use a modal, hope you work around or resolve this.

**Comment by tailsu** [comment] 2017-03-06 11:14
That's not the root cause. react-select already does a `stopPropagation` [here](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L498). The problem arises because react-select stop the keyDown event, but react-bootstrap's Modal [listens to keyUp](https://github.com/react-bootstrap/react-overlays/blob/master/src/Modal.js#L439), not keyDown.

You can disable the closing of Modals with escape using `keyboard={false}`.

Maybe react-select should also move the escape handling logic into a keyUp handler, I'm not sure.

**Comment by asaadmahmood** [comment] 2019-07-26 13:56
Any updates on this?

**Comment by bladey** [comment] 2020-06-03 03:15
Hello -

In an effort to sustain the `react-select` project going forward, we're closing issues that appear to have been resolved via community comments or issues that are now redundant based on their age.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you, and we'll re-open it if necessary.

**Closed by bladey** 2020-06-03 03:15 UTC
Labels: bug-unconfirmed

**Comment by gcangussu** [comment] 2021-08-23 22:22
We can build on top of @imornar's solution so we can have the ESC keyup stopped only if `react-select` is using that ESC keystroke to close the menu. This is useful to implement, for example, the following behavior:

Inside a modal window the focus is on a `react-select` element with its options menu opened.
1. ESC closes the options menu and keeps the modal opened
2. ESC closes the modal

```js
import Select, { components } from "react-select";

function MySelect(props) {
  return (
    <Select {...props} components={{ SelectContainer, ...props.components }} />
  );
}

function SelectContainer(props) {
  const shouldStopEscKeyUpRef = useRef(false);

  const innerProps = {
    ...props.innerProps,
    onKeyDown(event) {
      if (props.selectProps.menuIsOpen && event.key === "Escape") {
        shouldStopEscKeyUpRef.current = true;
      }
      props.innerProps.onKeyDown(event);
    },
    onKeyUp(event) {
      if (shouldStopEscKeyUpRef.current && event.key === "Escape") {
        event.stopPropagation();
        shouldStopEscKeyUpRef.current = false;
      }
    },
  };

  return <components.SelectContainer {...props} innerProps={innerProps} />;
}
```

**Comment by thisKeeWord** [comment] 2021-09-17 20:34
@gcangussu After making a selection, hitting the "esc" key doesn't exit the Modal as it ideally should.

**Comment by thisKeeWord** [comment] 2021-09-20 15:27
I'll give that a shot. I tried console.logging in the `onKeyDown` method in `innerProps` after that `if` statement, and I don't remember seeing anything logged. I'll have to double check.

**Comment by gcangussu** [comment] 2021-09-21 11:13
@thisKeeWord you could try something like this to debug:
```jsx
<Modal>
  <div onKeyDown={e => console.log('keydown', e)} onKeyUp={e => console.log('keyup', e)}>
    <Select {...props} />
  </div>
</Modal>
```

If you don't see the console log it could mean that either

- the focus is in another element of the document, which is not inside the `div` or
- something is blocking the event propagation to the `div`.

You could also try using `onKeyDownCapture` and `onKeyUpCapture` to debug.

I can only say for sure that the solution I've shared above works nicely with [reactstrap's modal](https://reactstrap.github.io/components/modals/).

**Comment by thisKeeWord** [comment] 2021-09-21 14:41
@gcangussu I'm also using reactstrap's modal. I'll keep trying. I think it could be that I'm using a `SingleValue` component from react-select. That might be what's causing it to not bubble up once I click on an option and try to click the "esc" key.

**Comment by thisKeeWord** [comment] 2021-09-22 02:21
It does seem like the "esc" key naturally gets lost. I added the focus back to the `Select` component once the `onChange` handler gets called. Even though that does add the class back to the element, it doesn't make it the primary element. So I'm curious if your solution works once the user clicks on an option and then hits the "esc" key to close the modal.

**Comment by gcangussu** [comment] 2021-09-22 13:25
> I'm also using reactstrap's modal. I'll keep trying. Just to make sure, does your solution work when the user clicks the "esc" key after clicking on a dropdown item?

Yes it does. And by _it does_, just to be clear, this is what we have: (1) user clicks on dropdown, (2) list of options are shown, (3) user presses "esc", (4) list of options are not shown anymore, (5) user presses "esc", (6) the modal is closed.

> I'm curious if your solution works once the user clicks on an option and then hits the "esc" key to close the modal.

Yes, it works on this case too, closing the modal on "esc" after selecting an option. Since the options menu is closed the "esc" keyup propagates to the modal component, thus closing it.

**Comment by thisKeeWord** [comment] 2021-09-22 15:25
@gcangussu Ok. I'll take a look. I think it may be something we're doing that's causing it to not happen the way you have it. Thanks!
