### ISSUE TITLE
text-align: center causes infinite recursion

### ISSUE THREAD

**Issue by savvopoulos** [JedWatson/react-select#549] opened 2015-10-30 11:30 UTC
I'd suspect autosize, but no idea.

To repro:
1. https://jedwatson.github.io/react-select/

2. With the inspector, edit the topmost div of a Select:
![image](https://cloud.githubusercontent.com/assets/747519/10844664/adfebbb2-7f01-11e5-8c67-c76c48530080.png)

3. Add text-align: center:
![image](https://cloud.githubusercontent.com/assets/747519/10844676/cf807910-7f01-11e5-861d-4b580dd63e79.png)

4. Back to the select, type something. After the third keystroke or so the typing will freeze, and eventually "RangeError: Maximum call stack size exceeded" is thrown.

**Comment by petetnt** [comment] 2015-10-30 11:57
Duplicate of #540

**Comment by JedWatson** [comment] 2015-11-01 12:09
Closing (duplicate)

**Closed by JedWatson** 2015-11-01 12:09 UTC
