### ISSUE TITLE
Form Validations Feature Request

### ISSUE THREAD

**Issue by getaaron** [JedWatson/react-select#4162] opened 2020-08-14 02:02 UTC
Currently React Bootstrap supports [Native HTML5 form validation](https://react-bootstrap.github.io/components/forms/#forms-validation-native). This is a feature request for react-select to support form validation with a similar API.

## What's your use case? (Tell us about your application and what problem you're trying to solve.)

Our app is [ScheduleBot](https://schedulebot.app), an automated human workforce scheduling tool. It has lots of forms, sometimes with really strict frontend validation requirements.

## What interface do you have in mind? (What new properties or methods do you think might be helpful?)

A simple interface would add `validated` and `error` props. Currently we're working around this lack of functionality with a simple wrapper component:

```js
<FormSelect
  validated={validated}
  error={itemID ? null : "Please select an item."}
  options={items}
  …
```

The implementation is simple:

### `FormSelect.js`

```js
 import React from "react";
 import Select from "react-select";

 import "./FormSelect.css";

 export function FormSelect({ validated, error, ...rest }) {
   const className = validated && error ? "select-error is-invalid" : null;

   return (
     <>
       <Select className={className} {...rest} />
       {validated && error ? <div class="invalid-feedback">{error}</div> : null}
     </>
   );
 }
```

### `FormSelect.css`

```css
.select-error div {
     border-color: #dc3545;
 }
```

## Can you point to similar functionality with any existing libraries or components? (Working demos can be helpful.)

See https://react-bootstrap.github.io/components/forms/#forms-validation-native for example.

**Comment by Gr3yShad0w** [comment] 2020-08-14 10:57
Duplicate of #1453

**Comment by bladey** [comment] 2020-08-24 03:33
Hey @getaaron, as @Gr3yShad0w mentioned we've got quite a detailed validation issue at the moment, we'll reference back to this issue as well to take it into account, thank you!

**Closed by bladey** 2020-08-24 03:33 UTC
Labels: issue/enhancement, issue/reviewed
