### ISSUE TITLE
react-select is altering the case of what I type

### ISSUE THREAD

**Issue by StokeMasterJack** [JedWatson/react-select#1343] opened 2016-11-02 19:00 UTC
react-select is altering the case of what my user types. If I type "Foo". It displays "foo".

I can fix this by setting ignoreCase={false}. 

But then the react-select filters my list in a case-sensitive way. Which I don't want. 

In fact, I am using async and mysql is doing the filtering. So I don't really want react-select to do any filtering all.

So I need to configure react select such that:

1. It doesn't alter what my user types (as in switch the case).
2. It doesn't do any filtering (because I am doing that server-side)

**Comment by scags9876** [comment] 2016-11-04 23:19
Duplicate of https://github.com/JedWatson/react-select/issues/1106 ?

**Comment by bladey** [comment] 2020-05-27 06:14
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.

**Closed by bladey** 2020-05-27 06:14 UTC
