### ISSUE TITLE
[V2] IE11 vertical scrollbar

### ISSUE THREAD

**Issue by rogier2012** [JedWatson/react-select#2816] opened 2018-07-20 15:00 UTC
Opening the first select component of the demo page in Internet Explorer 11 shows a scrollbar, but clicking on this scrollbar closes the selector menu.

**Comment by 4dom2dom** [comment] 2018-08-29 04:15
I have the same issue in IE11. Hope it will be get soon carried out.

**Comment by 4dom2dom** [comment] 2018-09-13 09:08
The issue is discussed here https://github.com/JedWatson/react-select/issues/1020. Unfortunately, it is not fixed.

**Comment by andrey99z** [comment] 2018-09-28 00:13
Here is quick patch for current version based on Rakid's code: 
```
   componentDidMount() {
        const select = this.rs.select;
        if (!select.onInputBlurPatched) {
            const originalOnInputBlur = select.onInputBlur;
            select.onInputBlur = e => {
                if (select.menuListRef && select.menuListRef.contains(document.activeElement)) {
                    select.inputRef.focus();
                    return;
                }
                originalOnInputBlur(e);
            }
            select.onInputBlurPatched = true;
        }
    }
```
(assuming that this.rs is ref to React-select component)
HTH

**Comment by pohsoon** [comment] 2018-10-11 03:31
Nice. This quick patch works in my IE 11.

**Comment by M-Yankov** [comment] 2019-08-13 12:45
> 
> 
> Here is quick patch for current version based on Rakid's code:
> 
> ```
>    componentDidMount() {
>         const select = this.rs.select;
>         if (!select.onInputBlurPatched) {
>             const originalOnInputBlur = select.onInputBlur;
>             select.onInputBlur = e => {
>                 if (select.menuListRef && select.menuListRef.contains(document.activeElement)) {
>                     select.inputRef.focus();
>                     return;
>                 }
>                 originalOnInputBlur(e);
>             }
>             select.onInputBlurPatched = true;
>         }
>     }
> ```
> 
> (assuming that this.rs is ref to React-select component)
> HTH

The code works good, but in my case I am using `react-window` to replace the MenuList component. In that case `select.menuListRef` is always null. Any idea how to fix this ?

**Comment by andrey99z** [comment] 2019-08-13 22:04
Upgrade to the current version? This seem to be fixed now and the patch is not needed anymore.

**Comment by M-Yankov** [comment] 2019-08-14 05:13
> 
> 
> Upgrade to the current version? This seem to be fixed now and the patch is not needed anymore.

Yes it fixed, I was editing my previous comment with the solution I found, but obviously I forgot to click save 🤓

**Comment by bladey** [comment] 2020-05-28 05:15
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Closed by bladey** 2020-05-28 05:15 UTC
