### ISSUE TITLE
Support for defaultProps will be removed warning

### ISSUE THREAD

**Issue by websiddu** [JedWatson/react-select#5687] opened 2023-07-01 16:51 UTC
There is warning shown when using react-select 

```
Warning: NoOptionsMessage: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at NoOptionsMessage (webpack-internal:///(app-client)/./node_modules/react-select/dist/index-6ea50319.esm.js:667:24)
    at div
    at eval (webpack-internal:///(app-client)/./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at MenuList (webpack-internal:///(app-client)/./node_modules/react-select/dist/index-6ea50319.esm.js:637:24)
    at ScrollManager (webpack-internal:///(app-client)/./node_modules/react-select/dist/Select-ce3716e1.esm.js:819:23)
    at div
    at eval (webpack-internal:///(app-client)/./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Menu (webpack-internal:///(app-client)/./node_modules/react-select/dist/index-6ea50319.esm.js:607:24)
    at MenuPlacer (webpack-internal:///(app-client)/./node_modules/react-select/dist/index-6ea50319.esm.js:559:24)
    at div
    at eval (webpack-internal:///(app-client)/./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at SelectContainer (webpack-internal:///(app-client)/./node_modules/react-select/dist/index-6ea50319.esm.js:795:24)
    at Select (webpack-internal:///(app-client)/./node_modules/react-select/dist/Select-ce3716e1.esm.js:1144:90)
    at eval (webpack-internal:///(app-client)/./node_modules/react-select/dist/react-select.esm.js:59:92)
```

<img width="1105" alt="image" src="https://github.com/JedWatson/react-select/assets/968912/972c8079-32cf-4ad7-b91f-0131cd3f90f2">

**Comment by Rall3n** [comment] 2023-07-01 18:24
Duplicate of #5596.

**Closed** 2023-07-01 18:24 UTC
Labels: issue/bug-unconfirmed
