### ISSUE TITLE
Event swallowed when pressing Enter

### ISSUE THREAD

**Issue by kembuco** [JedWatson/react-select#212] opened 2015-05-27 21:53 UTC
Currently pressing enter when the select list isn't open causes the keypress event to be swallowed.  Preventing the default behavior of enter when the select list is open seems like the right behavior.  However, it prevents things like form submission if the list is closed.  

I can submit a pull request with a fix for this.  Basically, it just adds an else clause that returns if the select list isn't open.

**Comment by dcousens** [comment] 2015-05-28 02:36
Fixed in #212

**Closed by dcousens** 2015-05-28 02:36 UTC

**Comment by sstern6** [comment] 2017-12-22 02:23
This seems to be re occurring in version 1.1.0.  On a form with an onSubmit, the enter causes the dropdown to open, and the onSubmit wont fire.

**Comment by sstern6** [comment] 2018-01-02 18:17
@dcousens youre right, this way fixed in https://github.com/JedWatson/react-select/issues/212, but for some reason on master it was changed. https://github.com/JedWatson/react-select/blob/master/src/Select.js#L454.

**Comment by jnachtigall** [comment] 2018-01-08 09:29
@dcousens Looks like a regression. Could this be reopened?

> but for some reason on master it was changed. https://github.com/JedWatson/react-select/blob/master/src/Select.js#L454.

@sstern6 this link point to the wrong line now, here's one with a fixed git hash: https://github.com/JedWatson/react-select/blob/7bc9363ad139546e296778774b7d16e7cdf72d55/src/Select.js#L487-L494 
`<Enter>` is always prevented, so the form is never submitted on `<Enter>`.
