### ISSUE TITLE
Select in IOS doesn't work

### ISSUE THREAD

**Issue by Kalmanos** [JedWatson/react-select#2891] opened 2018-08-03 12:07 UTC
need help with react-select! The onChange doesnt trigger in ios safari/chrome

**Comment by Kalmanos** [comment] 2018-08-03 14:46
onChange event doesnt trigger at all
the menu with the options pops up and when you try to select it , it dissapears

**Comment by itaitay** [comment] 2018-08-20 07:32
We also encountered it - were you able to resolve it @kalmanos ?

**Comment by kevinnio** [comment] 2018-09-11 15:06
@Kalmanos Since that we ran into a similar issue. Did you have any luck fixing this?

**Comment by attilavago** [comment] 2019-01-31 18:09
Any news on this?

**Comment by adamsoffer** [comment] 2019-02-12 22:02
same

**Comment by GeorgeMarcus** [comment] 2019-02-25 21:58
Same

**Comment by CharlieBreval** [comment] 2019-04-02 08:59
Same there

**Comment by Bitfroest** [comment] 2019-04-02 09:18
OS:  
MacOS Mojave on Macbook Air '17  
Version 10.14  

I noticed this bug as well in old versions of Safari: Safari 2 doesn't work with the same issue. onChange is not triggered and select is disappearing on click.

In the latest Versions it works at least on my end.
Safari 12 works as expected
Chrome 71.0 works as expected

**Comment by CharlieBreval** [comment] 2019-04-02 10:23
Hello, I am using the last verions of react-select (2.4.2) and I solved this problem by removing the ```<button>``` in every option of my react select. 

Indeed, on devices using touch events, the propagation looks to be different and the handleChange is not triggered.

**Comment by Bitfroest** [comment] 2019-04-02 11:04
@CharlieBreval I didn't find any `<button>` tags. In [Option.js](https://github.com/JedWatson/react-select/blob/master/src/components/Option.js) there is already a `<div>` rendered.

Could you be more specific please?

**Comment by CharlieBreval** [comment] 2019-04-02 12:16
@Bitfroest Well, in my case I was rendering a button inside the Option Component (so as children of the Option component). -> https://github.com/JedWatson/react-select/blob/master/src/components/Option.js#L82
If you are rendering a button, remove it.

**Comment by eliasrodeloso** [comment] 2020-04-13 02:41
Any news on this problem?, I have v3 and the package doesn't use Fastclick, any luck on this?

**Comment by bitupon** [comment] 2020-07-20 05:03
Is this issue still exists ?

**Comment by ebonow** [comment] 2020-12-19 19:05
Greetings all,

In an effort to curb the tide of open issues, I will be closing this issue as this no longer appears to be an issue. If someone feels this is still relevant or has a specific issue regarding iOS, please feel free to create a new issue including the following information:
- hardware
- ios version
- react-select version
- codesandbox link and reproduction steps to encounter bug

**Closed by ebonow** 2020-12-19 19:05 UTC
Labels: issue/bug-unconfirmed, issue/reviewed

**Comment by konojack** [comment] 2021-03-25 09:51
Yes, the issue still exists, I tried to use hints in this topic (event.preventDefault() with onBlur or blurInputOnSelect={false}):
https://github.com/JedWatson/react-select/issues/2692

It doesn't work at iOS in mobile devices - option doesn't change and onChange event is not firing.

**Comment by ebonow** [comment] 2021-03-25 16:49
@konojack 

Would you kindly follow the provided directions above so we can better identify, track, and fix issues?

**Comment by konojack** [comment] 2021-03-25 18:25
Thanks for your reply. I fixed it - in my case 'fastclick' lib causes that issue.
I have added props to 'react-select'
`optionRenderer={option => <div className="needsclick">{option.label}</div>}`

**Comment by ippossebon** [comment] 2021-12-22 16:12
> Thanks for your reply. I fixed it - in my case 'fastclick' lib causes that issue. I have added prop to 'react-select' component with class "needsclick" and finally it works fine. `formatOptionLabel={option => <div className="needsclick">{option.label}</div>}`

I also thank you for your reply!

We had the same issue using 'fastclick'.  We removed and everything worked as expected! No need to add extra classes if you remove the lib (in our case was fine)
