### ISSUE TITLE
prevent keyboard from opening automaticaly

### ISSUE THREAD

**Issue by LiranBri** [JedWatson/react-select#3526] opened 2019-04-27 11:22 UTC
Hello,
when the user press the component when filter is enabled, two things happens:
1. options are rendered so he can choose from
2. keyboard is opened so he can type to filter

is it possible to disable #2, so it will happen only when user clicks again?
if not, is it possible to auto hide the keyboard when he starts scrolling through the options?

on small mobile devices, the keyboard hides the options and user must manually close the keyboard (on iphone i think its not even possible)

**Comment by crobinson42** [comment] 2019-08-30 22:36
@JedWatson @LiranBri I'm in the same boat - I have posted a stackoverflow question here to accomplish this: https://stackoverflow.com/questions/57733799/react-select-dont-focus-input-when-opening-options-list

**Comment by andrewringler** [comment] 2019-10-08 13:05
Here is a screenshot of what this currently looks like on IOS 13.1.2, Safari iPhone SE, with a react-select inside a modal dialog about 1/3 of the way down the page.

![IOS_ReactSelect](https://user-images.githubusercontent.com/691187/66397795-91b85680-e9aa-11e9-82e6-358a928b7f08.jpg)

As @LiranBri said there is actually no way to hide the IOS keyboard without disabling the control, so we are limited to just seeing however many options fit above the IOS keyboard.

I am not sure what a reasonable solution is? On non touch devices react-select lets you click into the control on the blinking cursor to enter typing mode, it looks like on touch devices react-select enters typing mode immediately on control focus? Perhaps we should have a keyboard icon or something inside the control to enter typing mode instead on touch devices?

**Comment by Vadorequest** [comment] 2020-01-04 20:02
I'm encountering the same issue, and I'd love an option to avoid the keyboard to open automatically when focusing the input as well. (option #2)

It's a blocker for my app, because I rely on onMenuClose event to sync the selected choices (they're not sync on onChange event), and it's broken on mobile because the onMenuClose event isn't triggered even though the menu is visually closed once selecting a choice in the menu. (it's another issue, but if the menu would have been closable by default it could have been a workaround for me)

**Comment by seba9999** [comment] 2020-10-13 19:42
I'm facing this too ... :'( 

IMO it should trigger the list when users click the arrow and open the list PLUS focusing the input ( and btw open the keyboard ) if the user click the input part of the react-select :)

**Comment by Methuselah96** [comment] 2020-11-14 16:40
I've started [a fork](https://github.com/react-select-oss/react-select) of react-select. Feel free to resubmit this issue on the fork and/or submit a PR to resolve this issue on the fork and we can get it merged and released.

**Comment by ebonow** [comment] 2020-12-07 22:02
Greetings @LiranBri ,

I may have actually inadvertently solved this with my response to this issue: https://github.com/JedWatson/react-select/issues/4279#issuecomment-739743520

It seems that a user had this very same idea and was trying to remove the DummyInput and understand how to render the menu without it. I think the response was fairly elaborate if you are curious about the how it all works.

Long story short, as long you can render a control with at least one-focusable item, open the menu, and give focus to that item, the react-select menu will operate as expected

[Here is a working demo](https://codesandbox.io/s/react-select-focus-testing-270xv) with one button giving itself focus and enabling the menu arrow commands.

I will close this issue for now given the age of this, but I can re-open it if there are problems/concerns/questions.

**Comment by crobinson42** [comment] 2020-12-07 22:04
@ebonow I wouldn't say this issue is closed. I would vote that this functionality be added as some sort of prop to the component, ie: `inputFocusOnClick={false}`

**Comment by ebonow** [comment] 2020-12-07 22:43
@crobinson42 I think you make a good point, though I don't believe we would want to add another prop as much as we'd want to replace the DummyInput to entirely avoid this situation for mobile users when isSearchable is false.

I'll add this as a discussion point with the team and reopen this issue.

**Comment by ebonow** [comment] 2020-12-18 23:42
Greetings everyone,

I am unable to reproduce this issue **as long as the prop `isSearchable` is set to false**. Testing on the homepage of react-select allows the user to toggle `Searchable` and when it is unchecked, I do not see a keyboard. 

<img width="240" alt="Screen Shot 2020-12-18 at 5 31 59 PM" src="https://user-images.githubusercontent.com/1007579/102672863-aae49780-4157-11eb-9a86-853ed657b49c.png"><img width="250" alt="Screen Shot 2020-12-18 at 5 31 47 PM" src="https://user-images.githubusercontent.com/1007579/102672865-ab7d2e00-4157-11eb-80e2-a2197c22be20.png">

If anyone can create a reproducible demo of this behavior, we would gladly reopen this ticket, but as it stands this does not appear to be still an issue.

**Closed by ebonow** 2020-12-18 23:42 UTC
Labels: category/question, issue/reviewed

**Comment by diegys** [comment] 2021-07-07 14:36
What about when you don't want to disable the search? `focusInputOnMenuOpen` prop would be nice.

**Comment by Vuliniar** [comment] 2022-11-17 09:24
As @diegys suggested, it would be great to have such a prop that will 'softly' hide the keyboard initially on the menu open.

**Comment by btex88** [comment] 2023-04-13 22:26
*********SOLUTION*********
Set the prop `isSearchable` to false.

```
    <ReactSelect
      isSearchable={false}
      classNames={classNames}
      unstyled
      placeholder={placeholder}
      onChange={({ value }) => handleChange(value)}
      options={options}
      classNamePrefix=react-select"
    />
```

**Comment by rever96** [comment] 2023-11-11 09:14
pls add this feature.
We want the select to be searchable but to choose when the keyboard appear on mobile device:
- onfocus (the current one)
- when user click the input again after he focussed it

**Comment by danhickman** [comment] 2025-07-23 22:12
I also need a way to not open the mobile keyboard when the DropdownIndicator component is selected but I still want to make the control searchable if they select the textbox portion of the control.  I don't see that a solution to the original was ever provided.  Why was it closed?
