### ISSUE TITLE
Dropdown closes when click on scroll in IE11

### ISSUE THREAD

**Issue by tknysh** [JedWatson/react-select#1020] opened 2016-06-10 15:05 UTC
![](http://g.recordit.co/H95HgaDpoz.gif)

**Comment by twschiller** [comment] 2017-10-18 15:35
Potential regression of #495?

Related issues:
- #848
- #846

**Comment by acromarco** [comment] 2017-10-24 14:59
According to my research, this bug (re-)appeared with IE11 in Win7 after this security update https://support.microsoft.com/en-us/help/4040685/cumulative-security-update-for-internet-explorer 
With the new IE11 version 11.0.9600.18816 this bug is reproducible, but everything worked fine with the older version 11.0.9600.17420.

**Comment by acromarco** [comment] 2017-10-25 13:12
selectize is also affected by this IE11 bug and they have probably found a fix https://github.com/selectize/selectize.js/issues/1004

**Comment by acromarco** [comment] 2017-10-26 09:21
I wonder if this is already fixed with https://github.com/JedWatson/react-select/commit/2da6ff6a352c8720fe59ca037524dbff9109af96 because adding tabIndex={-1} should fix it.

**Comment by sushant-at-nitor** [comment] 2017-11-30 10:29
Code on [this line](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L347) should add one more condition to fix this issue.

`if (this.menu && (this.menu === document.activeElement || this.menu.contains(document.activeElement))) {`

`document.activeElement.classList.contains(<configured class name for menu renderer>)` 

OR

Let [this line](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L353) decide whether to set new state to hide menu options or to continue to show them, stop further execution of code.

```
const result = this.props.onBlur(event);

if(result === false){
  this.focus();
  return;
}
```

**Comment by stephanebarbey** [comment] 2018-01-26 15:03
Is this issue still open? (or any chance that the fix by sushant-at-nitor gets integrated?)

**Comment by jojo-tutor** [comment] 2018-02-07 00:06
just add this code: 
```
handleOnBlur() {
    const e = null
    throw e
  }
```

**Comment by AO17** [comment] 2018-07-31 13:17
if this has been fixed (see [merge](https://github.com/sushant-at-nitor/react-select/commit/791ca1deee611b1e618db3b66b8cbd9ec77400c9) above):

1. Why is this issue still open?
2. I still have the same issue, if the fix has been merged, why is the bug still occuring?

**Comment by maeln** [comment] 2018-08-02 14:30
I can confirm that I have the same issue with the latest version of react-select.

**Comment by maeln** [comment] 2018-08-03 12:27
To expand on @jojo-tutor "fix-hack", you can do this if you still want your select to close when it lose focus:
```
 onBlur={() => {
        const focusedElement = document.activeElement
        if (focusedElement.className.includes('<<your-select-class>>')) {
          const e = null
          throw e
        }
}}
```

But it's a dirty hack, we should find a proper fix.

**Comment by AO17** [comment] 2018-08-15 13:43
@JedWatson will this be fixed soon?

**Comment by rakid** [comment] 2018-08-23 07:46
Confirm issue with the V2.

Tested in the examples provided by react-select, same issue.

Hope it will be resolved soon.

**Comment by rakid** [comment] 2018-08-25 16:40
@JedWatson any suggestions?

**Comment by madhan-dhamodaran** [comment] 2018-09-12 19:18
@JedWatson @james4388 @rakid ,

Any updates on @rakid 's merge? This is a blocker for me and I am in need of this for my project.

Please advise. 

Thanks,
MAdhan

**Comment by ahce** [comment] 2018-09-21 17:38
@JedWatson @gwyneplaine 
Please check this.

**Comment by blake59** [comment] 2018-10-16 13:09
Any update on this?

**Comment by ihor** [comment] 2018-10-23 13:28
Hey guys! Do you have any estimated when the fix will be released? Thanks!

**Comment by igorkaine** [comment] 2018-11-08 16:33
+1

**Comment by mtunski** [comment] 2018-11-19 10:43
+1

**Comment by MaximeNoulin** [comment] 2019-01-23 16:56
It seems that it (v2.1.2 #3013 ) fixed the sync Select but not the Async one, someone would have any idea why?

**Comment by aviranmz** [comment] 2020-05-04 07:18
version 2.4.4 still have the same issue in IE11 -> when the list is open and you try to click on the croll the menu is close - i cant upgrade to v3 - any solution?

**Comment by bladey** [comment] 2020-06-05 03:49
Hello -

In an effort to sustain the `react-select` project going forward, we're closing issues that appear to have been resolved via community comments or issues that are now redundant based on their age.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

@MaximeNoulin and @aviranmz feel free to open up a new issue if it is still a problem, however note we are focusing on v3 as mentioned above.

**Closed by bladey** 2020-06-05 03:49 UTC
Labels: bug-unconfirmed

**Comment by David-moonsite** [comment] 2021-02-28 11:28
> just add this "onBlur" handler to the props of Select:
> 
> ```
> handleOnBlur() {
>     const e = null
>     throw e
> }
> ```

Works for me ,
now dropdown doesn't close when I click outside the dropdown

**Comment by Spomsoree** [comment] 2021-12-21 09:56
> just add this "onBlur" handler to the props of Select:
> 
> ```
> handleOnBlur() {
>     const e = null
>     throw e
> }
> ```

This worked for me on version 4.3.1
