### ISSUE TITLE
react-select does not scroll into view selected option

### ISSUE THREAD

**Issue by Aror** [JedWatson/react-select#3769] opened 2019-09-21 01:52 UTC
I expect that the following will result in the selected option being shown as soon as the dropdown is opened. It does not. It highlights the selected option but you have to scroll to it in order to see it. 

```
<Select
   options={[...Array(121).keys()].map(num => {return {value: num, label: num}})}
   value={{label: 20, value: 20}}
   isOptionSelected={(option) => (option.value == 20) ? true : false}
 />
````

**Comment by akinorimiz** [comment] 2019-11-08 07:18
You can use a custom component.

```jsx
const Option = (props) => {
    const ref = useRef();

    useEffect(() => {
        props.isSelected && ref.current.scrollIntoView();
    }, [props.isSelected]);

    return (
        <components.Option {...props} innerRef={ref} />
    );
};
```

**Comment by andreme** [comment] 2019-11-12 17:15
Duplicate of #3535 and #3648

**Comment by harryo** [comment] 2019-12-17 11:09
> You can use a custom component.
> 
> ```js-jsx
> const Option = (props) => {
>     const ref = useRef();
> 
>     useEffect(() => {
>         props.isSelected && ref.current.scrollIntoView();
>     }, [props.isSelected]);
> 
>     return (
>         <components.Option {...props} innerRef={ref} />
>     );
> };
> ```

This breaks keyboard navigation. When using arrow keys, the focused option is not visible if too far from the currently selected option.

**Comment by harryo** [comment] 2019-12-18 13:11
The underlying issue is that the focused option is in view, rather than the selected option, and that is correct. But when opening the menu, the selection option should get focus, and hence appear in view. For a fix, see https://github.com/JedWatson/react-select/pull/3813, unfortunately still not merged....

**Comment by bladey** [comment] 2020-05-28 04:18
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Closed by bladey** 2020-05-28 04:18 UTC

**Comment by russyDev** [comment] 2022-07-09 07:53
Issue still exist

**Comment by ycldz** [comment] 2023-02-15 06:02
Is the problem solved or has anyone solved it?

**Comment by ammarsiddique-whizpool** [comment] 2023-08-02 11:47
Facing same issue, have fixed it like this

**create a function onMenuOpen** 


const onMenuOpen = () => {
  setTimeout(()=>{
    const selectedEl = document.getElementsByClassName("MyDropdown__option--is-selected")[0];
    if(selectedEl){
      selectedEl.scrollIntoView({behavior:'smooth', block:'nearest', inline: 'start'});
    }
  },15);
};


**Update the select tag**
  <Select options={ChapterOptions}
                    className ={"MyDropdown"}
                    classNamePrefix={"MyDropdown"}
                    onMenuOpen={onMenuOpen}
                    menuPosition={'fixed'} 
                    value={selectedOptionChapter} // Set the selected option using the state variable
                    placeholder={props.selectedSurah + " - " + props.Surah_name} onChange={(e) => handleChapterChange(e)} />
                    
**These are the main things for scrolling itno selected option**
className ={"MyDropdown"}
classNamePrefix={"MyDropdown"}
onMenuOpen={onMenuOpen}
menuPosition={'fixed'}

**Comment by mikkpokk** [comment] 2023-08-10 21:21
@ammarsiddique-whizpool Issue only exists if you don't take selected `value` from your list of `options`

Use this instead.

```jsx
<Select
    options={ChapterOptions}
    value={selectedOptionChapter && ChapterOptions.find(option => option.value === selectedOptionChapter?.value)}
    className ={"MyDropdown"}
    classNamePrefix={"MyDropdown"}
    onMenuOpen={onMenuOpen}
    menuPosition={'fixed'}
    placeholder={props.selectedSurah + " - " + props.Surah_name} onChange={(e) => handleChapterChange(e)} />
```

**Comment by mikkpokk** [comment] 2023-11-02 22:47
@mrudowski This is long time ago closed ticket and original ticket does not address menuPortal issue.

Please open new ticket to address the problem and let's see when community is able to address the cause and fixes it.

**Comment by mrudowski** [comment] 2023-11-02 22:55
yes, sorry for that
I've opened new ticket couple of minutes later: https://github.com/JedWatson/react-select/issues/5775

**Comment by azuev** [comment] 2023-11-06 15:38
> @ammarsiddique-whizpool Issue only exists if you don't take selected `value` from your list of `options`
> 
> Use this instead.
> 
> ```js
> <Select
>     options={ChapterOptions}
>     value={selectedOptionChapter && ChapterOptions.find(option => option.value === selectedOptionChapter?.value)}
>     className ={"MyDropdown"}
>     classNamePrefix={"MyDropdown"}
>     onMenuOpen={onMenuOpen}
>     menuPosition={'fixed'}
>     placeholder={props.selectedSurah + " - " + props.Surah_name} onChange={(e) => handleChapterChange(e)} />
> ```
> 
> In case you component receives a lot of other props (causes multiple re-renders) use this:
> 
> ```js
> import {useMemo} from 'react'
> // ...
> 
>     // Insert it before return
>     const chapterValue = useMemo(() => {
>         return selectedOptionChapter && ChapterOptions.find(option => option.value === selectedOptionChapter?.value)
>     }, [selectedOptionChapter, ChapterOptions])
>     // ...
>     
>     return (
>         <Select
>             options={ChapterOptions}
>             value={chapterValue}
>             className ={"MyDropdown"}
>             classNamePrefix={"MyDropdown"}
>             onMenuOpen={onMenuOpen}
>             menuPosition={'fixed'}
>             placeholder={props.selectedSurah + " - " + props.Surah_name} onChange={(e) => handleChapterChange(e)} />
>     )
> ```

not working with react-hook-form :(
