### ISSUE TITLE
menuIsOpen does not work on mobile device

### ISSUE THREAD

**Issue by armspkt** [JedWatson/react-select#3806] opened 2019-10-08 10:56 UTC
![image](https://user-images.githubusercontent.com/49720317/66390359-bafdd480-e9f4-11e9-8ed7-c1c7c46ff8dd.png)

https://xi0os.csb.app/

https://codesandbox.io/s/react-codesandboxer-example-xi0os

When I try to use menuIsOpen props to control state react-select, it works only on desktop
but for mobile look like event onClick does not fire.

**Comment by Xartok** [comment] 2019-10-12 13:36
On mobile you should use the onTouchStart event instead of onClick. [Here](https://codesandbox.io/s/react-codesandboxer-example-hsq2t)'s a modified codesandbox with the update.

**Comment by armspkt** [comment] 2019-10-13 16:07
@Xartok thanks for helping, but I don't understand why can't we just use `onClick` event.
Why `onClick` still work on mobile when I use it with div element?

**Comment by bladey** [comment] 2020-06-23 06:53
Hi @armspkt,

I wanted to check in and see if you were still encountering this issue, or managed to find a reason why `onClick` wasn't working for you. We're triaging issues at the moment to sustain the project going forward.

**Comment by armspkt** [comment] 2020-06-23 08:30
@bladey This issue still happens on the mobile device.

**Comment by ebonow** [comment] 2020-12-07 20:51
@armspkt 

> thanks for helping, but I don't understand why can't we just use `onClick` event.
- The innerProps passed to the `IndicatorsContainer` contain eventBindings for `onTouchEnd` and `onMouseDown`.
- These events fire earlier in the event lifecycle than `onClick`.
- The attached methods prevent the event call from carrying through to the onClick event

Here is the code to see for yourself what is going on.
https://github.com/JedWatson/react-select/blob/998c979b4ed51ee39b87c9b2f0f03da440017dcf/packages/react-select/src/Select.js#L952-#L968

> Why `onClick` still work on mobile when I use it with div element?
The div likely doesn't have a `onTouchEnd` method calling `event.stopPropagation`, so your click event would be completely unimpeded.

Given that this is not a bug, I will be closing this issue, but am open to further discussing any questions.

**Closed by ebonow** 2020-12-07 20:51 UTC
Labels: issue/bug-unconfirmed, issue/reviewed
