### ISSUE TITLE
React Select Version > 5.0.0 is incompatible with other libraries

### ISSUE THREAD

**Issue by stanley355** [JedWatson/react-select#5230] opened 2022-06-17 07:44 UTC
## Are you reporting a bug or runtime error?
A bug: Installed JSX components can't be used after installing React-select
How to reproduce: 
- Create next.js App with typescript
- Install React select with version > 1.27.6 as for me I installed 1.28.1
- Install library `pure-react-carousel` (newest)
- Create a simple Carousel Component import and use the following component to your carousel component:
![image](https://user-images.githubusercontent.com/53996155/174250450-a889f7dd-2766-43b0-a115-27ac78027d01.png)
- The issue will come out some third party component can't be used as JSX element:
E.g my carousel component
![image](https://user-images.githubusercontent.com/53996155/174250622-0cad2de9-dd43-4685-a1c9-8575e1ae2a8f.png)

And for the next.js built in component will get similar error:
![image](https://user-images.githubusercontent.com/53996155/174250783-da79c5f9-7c6f-486d-867b-6bb100e89957.png)

Anybody having similar issue?

**Comment by Methuselah96** [comment] 2022-06-17 11:53
Sounds like you have two copies of `@types/react` installed. Usually the easiest way to resolve this is to delete your package lock file and re-install your packages.

**Comment by stanley355** [comment] 2022-06-18 02:05
> Sounds like you have two copies of `@types/react` installed. Usually the easiest way to resolve this is to delete your package lock file and re-install your packages.

I've tried removing my `node-modules` and `yarn lock` file, and `yarn install` yet the issue persists

**Comment by Methuselah96** [comment] 2022-07-03 15:39
The issue is that you have multiple copies of `@types/react` installed. I would recommend looking in your `yarn.lock` to see what those copies are. If the two copies are `@types/react` 17 and 18, you need to follow the steps [here](https://github.com/facebook/react/issues/24304#issuecomment-1094565891).

**Comment by Methuselah96** [comment] 2022-07-08 13:50
It's not a mistake, `@types/react-transition-group` does correctly depend on `@types/react`. See https://github.com/facebook/react/issues/24304, https://github.com/facebook/react/issues/24304#issuecomment-1094565891, and https://github.com/microsoft/DefinitelyTyped-tools/issues/433 for more details. Closing this since this is not an issue with `react-select`.

**Closed by Methuselah96** 2022-07-08 13:50 UTC
Labels: issue/bug-unconfirmed, awaiting-author-response
