### ISSUE TITLE
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code

### ISSUE THREAD

**Issue by ammar-bay** [JedWatson/react-select#5306] opened 2022-08-13 19:54 UTC
I am getting these errors when I add Creatable or even select in my code: 
![image](https://user-images.githubusercontent.com/93938575/184508670-df1600d9-85d2-4071-b472-60f307845f7c.png)
![image](https://user-images.githubusercontent.com/93938575/184508805-23b2ec62-014a-4788-8ccb-9cb5da562c9b.png)
![image](https://user-images.githubusercontent.com/93938575/184508814-279153dc-d756-42d4-a105-f3c3877045d3.png)
Can you plz guide me why am I getting these errors and any possible solution?
I followed this link for implementation: https://www.digitalocean.com/community/tutorials/react-react-select

**Comment by Rall3n** [comment] 2022-08-15 08:11
Duplicate of #4246.
 
 Issue has already been resolved in newer versions of `react-select` (>3.1.0). Please update your projects dependencies.

**Closed by Rall3n** 2022-08-15 08:11 UTC
Labels: issue/bug-unconfirmed
