### ISSUE TITLE
[V2] Cannot use Createable together with custom getOptionLabel, getCustomValue

### ISSUE THREAD

**Issue by lindskogen** [JedWatson/react-select#2888] opened 2018-08-02 19:30 UTC
Using Createable together with custom `getOptionLabel` and `getCustomValue` fails with error:
`Cannot read property 'toLowerCase' of undefined`.

Type into the select box:
https://codesandbox.io/s/1oxo1xkxp7

**Comment by mike1808** [comment] 2018-08-06 16:06
it is hardcoded to use `.value` and `.label` keys. duplicate of #2630

**Comment by bladey** [comment] 2020-05-28 01:23
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Closed by bladey** 2020-05-28 01:23 UTC
