### ISSUE TITLE
Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object

### ISSUE THREAD

**Issue by manastasiou** [JedWatson/react-select#3889] opened 2019-12-30 15:35 UTC
Hi,

i get the following error when i try to use react-select/async.

> Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object

I just import the async like this

`import AsyncSelect from 'react-select/async';`

and then i use it as follows:
`const Test = () => {
    const [displaySelect, setDisplaySelect] = useState(false);
    
    useEffect(() => {
        setDisplaySelect(true);
    }, [])

    return (
        <div>
            { displaySelect &&  <AsyncSelect options={[{value: 'ts', label:'test'}]} /> }
        </div>
    )
}

export default Test;`

I added the setDisplaySelect because we use server side rendering and another error regarding emotion was being displayed. Do you have any ideas what goes wrong?

**Comment by alexristich** [comment] 2020-01-06 11:53
Could it be related to an incorrect import somewhere else in that file?
Perhaps this helps: https://stackoverflow.com/a/42814137

The code snippet you included seems to be okay.

Regarding the async select, instead of using `options`, I believe you should be using `defaultOptions` instead. See example and source code here: https://react-select.com/async#defaultoptions

**Comment by ankitdimania-eligible** [comment] 2020-03-11 14:44
I'm facing this same issue. I get
> "#<ExecJS::ProgramError: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.>"

I have a blank very new rails project, and it renders fine in client side and server side, but as soon as I add following line, it starts to fail with the above error.
`import Select from "react-select";`

Please note, the import statement and Select box works fine in client side, just failing issue with server side rendering.

**Comment by ebonow** [comment] 2021-01-14 02:41
Can you confirm if this is still an issue? I know there are others successfully using react-select with SSR, so let us know how we can better help identify whatever issues you are running into.

**Comment by ebonow** [comment] 2021-01-28 23:13
In an effort to maintain the list of reported and confirmed issues, I will be closing this issue.  If you feel this was closed prematurely @ankitdimania-eligible  or have other concerns, please feel free to reply and we can re-open this if applicable.

**Closed by ebonow** 2021-01-28 23:13 UTC
Labels: awaiting-author-response, issue/bug-unconfirmed

**Comment by ebonow** [comment] 2021-04-23 17:08
@kyrstenkelly , 

If it is working fine locally but not in production, then it appears to be something in the way babel is compiling the code. Since both errors seem to be thrown at the `Input` component, I think it could be possible that the optional chaining operator is causing the problem since the aria-label is used by the input.

```js
    "aria-label": typeof label === "string" ? label : label?.toString(),
```

Any reason not to simply cast it as a string without the type check?
```js
    "aria-label": String(label),
```

Also worth noting that you may want to declare some defaults or throw warnings in the cases of 'null' or 'undefined', but that's implementation minutia.  In any case, I'd start there. Please let me know if this helps, though nothing else immediately stands out to me.

**Comment by kyrstenkelly** [comment] 2021-04-23 17:21
@ebonow Thank you for the response, I appreciate your help! I did two things yesterday:

1. Filtered out any undefined props so we're not passing a bunch of unnecessary things (although this didn't solve the problem)
2. Modified our build script (this fixed the issue)

Our component library is mostly used to provide consistent styles, so we rarely use 3rd party libs, which I think is why this issue hasn't arisen before. I modified our Rollup config to export a `umd` bundle instead of `cjs` (along with messing with some other settings), and that actually resolved the issue! 

For whatever reason, the way we were bundling things wasn't properly resolving `default` exports from node_modules, I believe. We use one other third party lib and it's always worked fine, but we do not use the default export in that case.
