### ISSUE TITLE
Erasing value issue

### ISSUE THREAD

**Issue by gregdymek** [JedWatson/react-select#3129] opened 2018-10-20 11:16 UTC
when I erase the value using backspace I'm getting empty array as the value, I think it would be better if I receive the same value as I get for isClearable (I think it's null)

**Comment by Thebarda** [comment] 2018-10-22 08:10
Duplicate of : #2682

**Comment by Thebarda** [comment] 2018-10-22 08:55
Duplicate of : #2682

**Closed** 2018-11-21 23:09 UTC
