### ISSUE TITLE
 React Select not menu options not showing up on Chrome 72

### ISSUE THREAD

**Issue by varun8255** [JedWatson/react-select#3870] opened 2019-12-02 07:09 UTC
Hi,

While i open a form with chrome 72 the react select with isOpen attribute true the menu list is not showing up only in chrome 72 and in other versions its working fine. When i hover over the react select then the menu is showing up. Can you please suggest what the issue is for this particular version of chrome.

**Comment by bladey** [comment] 2020-05-28 04:14
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by dfdumaresq** [comment] 2020-06-16 20:12
Hello - I am having a similar issue in Chrome Version 83.0.4103.106. 
I am running "react-select": "3.1.0" and the dropdown options menu is not being displayed. It works in Firefox.

**Comment by bladey** [comment] 2020-06-16 23:22
Hi @dfdumaresq,

I can't reproduce this with the `menuIsOpen` prop, see here - https://codesandbox.io/s/react-select-v3-sandbox-13swo

Were you using `isOpen` instead?

**Comment by dfdumaresq** [comment] 2020-06-17 16:41
Thanks for the reply @bladey . I cannot reproduce our issue with your [example](https://codesandbox.io/s/react-select-v3-sandbox-fw85t?file=/example.js) either.

We were using an invalid className and that caused the menu to remain hidden. Once we used the correct className the issue resolved.

**Comment by bladey** [comment] 2020-06-18 00:41
Thanks for the feedback @dfdumaresq, glad it's working now. I'll close this issue, let me know if you'd like it re-opened due to further issues.

**Closed by bladey** 2020-06-18 00:41 UTC
Labels: bug/unconfirmed

**Comment by AnantAgarwal45** [comment] 2024-02-09 09:28
Hello react select is not working on chrome but working on firefox, safari , what can be issue? please help me!

currently I'm using react select version - 3.2.0
