### ISSUE TITLE
Uncaught TypeError: Cannot read property '_currentElement' of null

### ISSUE THREAD

**Issue by ziweizhou** [JedWatson/react-select#128] opened 2015-04-16 06:42 UTC
Hello

Not sure why I am getting this error message when I try to create a simple Select 
```
var Select = require("react-select");
var TaskList = React.createClass({
  render: function() {
    return (
      <div>
            <Select multi={false} placeholder={'Select your favourite(s)'}
              value={'AL'}
              options={[{ value: 'AL', label: 'Alabama' }]}
          />
          </div>
       
    );
  }
});
```

error message
`Uncaught TypeError: Cannot read property '_currentElement' of null`

Thanks

**Comment by ZaphyrVonGenevese** [comment] 2015-04-28 11:13
I have the exact same issue. Did you resolve it?

**Comment by ZaphyrVonGenevese** [comment] 2015-04-29 06:30
Hi, so I took a look at it a bit more and I found out, that the problem was (in my case) in `gulpfile.js`. To be specific, the `debowerify` transform for `browserify`. After deleting it, everything works fine. Hope this will help.

**Comment by dcousens** [comment] 2015-05-07 02:05
@ZaphyrVonGenevese are you talking about your own `gulpfile.js`? 
In which case, should I close this issue?

**Comment by ZaphyrVonGenevese** [comment] 2015-05-08 07:49
@dcousens Yes, I am talking about my own `gulpfile.js`. For me, feel free to close it.

**Closed** 2015-05-09 12:27 UTC
Labels: bug	(unconfirmed)

**Comment by JohnMorales** [comment] 2015-05-18 16:30
I'm assuming that it has something to do with somehow bringing in an older version of react.

I was having the same error message, in my case I was depending on browserify's `reactify` transform and letting that dependency bring in react as needed. 

The fix was explicitly depending on react >= 0.12 in my dev-dependencies got rid of the error. 

It might sense to add a note in the README for people that bump into this one. The fix is easy, but it's not clear what to do or why when you get this error.

**Comment by adampatterson** [comment] 2015-12-30 17:18
So what was the cause? I have the same issue and in searching for a solution other people were saying that it had to do with multiple different things. In my case I changed `componentDidMount` to`componentWillMount`

**Comment by ongmin** [comment] 2016-01-14 06:26
@ any updates?

**Comment by Pines-Cheng** [comment] 2016-03-29 08:28
what was the cause?has any one know?
