### ISSUE TITLE
Dropdown not appearing on first click

### ISSUE THREAD

**Issue by kuroshio** [JedWatson/react-select#1994] opened 2017-09-13 07:09 UTC
When clicking a dropdown, there is no response the first time it's clicked. Clicking the dropdown a second time displays the options as expected. In addition, the dropdown closes once an option is clicked. 

~~Again, this only happens in the production build. Everything works as expected in development.~~ In addition, everything was working working fine on RC5, but I just upgraded to RC9 and started experiencing these issues in production build. 

Note, I'm using react-select in the create-react-app boilerplate.

**Comment by JedWatson** [comment] 2017-09-13 07:15
This is a known issue we've been tracking in #1980

I've updated that to be specific to the test that should have caught this, let's use this one to track actually fixing the bug.

The information about dev vs. production environments is new - I hadn't realised that before. @jochenberger that may be useful information when debugging why the tests don't fail?

**Comment by JedWatson** [comment] 2017-09-13 07:19
Related PRs / issues for this bug: #1527 #1580 #1902

The problem will probably be somewhere around [line 263 of Select.js](https://github.com/JedWatson/react-select/blob/v1.0.0-rc.7/src/Select.js#L263)

**Comment by jochenberger** [comment] 2017-09-13 07:25
See also #1986

**Comment by JedWatson** [comment] 2017-09-13 07:27
OK looked into this further, and I can't reproduce the difference between production and development - @kuroshio can you give us any more information about that?

Seems like the root cause is that `openOnFocus` is being used when the component is clicked. That's not what it was designed for - we need a different prop if we want to control whether the component opens on first click.

Unfortunately I missed the implication when I merged #1527

`openOnFocus` controls whether the menu opens when the control is focused either programatically or by the keyboard. By design it **should** default to `false`.

However, clicking a select component (in my experience) will **always** open the menu. If we want to support being able to click the control _without_ opening the menu, we should add another prop called `openOnClick` which defaults to `true`.

@jonashaag @hakunin @lauterry would you like to comment on this? it would be great to better understand the use-case for the prop.

**Comment by gwyneplaine** [comment] 2017-09-13 07:35
@JedWatson the current prop `openAfterFocus ` does what you are proposing for `openOnClick`. 

I would suggest renaming this prop to openOnClick or a name that is more indicative of the described behaviour. (unless there are strong arguments to the contrary)

**Comment by kuroshio** [comment] 2017-09-13 07:37
@JedWatson My apologies, the same thing is now happening in development, different behaviour must have been due to browser cache

**Comment by jochenberger** [comment] 2017-09-13 07:40
@gwyneplaine: if we do that, then it should probably default to `true`.

**Comment by haipham23** [comment] 2017-09-13 09:03
as @gwyneplaine mentioned, set `openOnFocus={true}` would fix the issue.

**Comment by hakunin** [comment] 2017-09-13 11:32
@JedWatson We were using `openOnFocus={false}` to be able to click the area of the select and have only a certain item (that was always there) open the select. 

Like this:
![screenshot 2017-09-13 13 30 48](https://user-images.githubusercontent.com/65846/30375141-c6dfeace-9887-11e7-900d-52ff461d9230.png)

We've moved away from using select for that and essentially re-implemented select box behavior, but now we have control over it

![screenshot 2017-09-13 13 32 34](https://user-images.githubusercontent.com/65846/30375222-0d2b284a-9888-11e7-880a-0bc1e81ed6ec.png)

**Comment by JedWatson** [comment] 2017-09-13 12:36
Done. There's now a `openOnClick` prop which defaults to true, and I've removed the old `openAfterFocus` prop. The `openOnFocus` prop works as expected.

Really glad to have fixed this behaviour 😁

**Closed** 2017-09-13 12:36 UTC

**Comment by jochenberger** [comment] 2017-09-14 04:48
On second thought, the name "openOnClick" might is a little bit confusing. The menu does actually open on click, just not when the Select does not have focus. But while "openOnClickWhenNotFocussed" might be more correct, it is also more clumsy.

**Comment by elghali** [comment] 2017-11-02 10:18
But even when "openOnClick" prop is set to `false` the menu still opens, is the props not working? or am I expecting a wrong behavior?
