### ISSUE TITLE
Input Message didn't disappear after input select 

### ISSUE THREAD

**Issue by mvnnn** [JedWatson/react-select#2475] opened 2018-03-27 15:16 UTC
When I try to add new input message using onNewOptionClick method then input message didn't disappear from input box.
```
<Select.Creatable
          {...input}
          options={value}
          backspaceRemoves={true}
          value={value}
          multi={true}
          placeholder="Add..."
          noResultsText="Add unique text"
          promptTextCreator={promptTextCreatorFn(promptText)}
          onBlur={null}
          onSelectResetsInput={true}
          onBlurResetsInput={true}
          onChange={this.onChangeFn(input)}
          onNewOptionClick={this.onChangeSelectFn(input)}/>
```

**Comment by rodrigo-brito** [comment] 2018-04-24 18:01
Same problem here!

**Comment by rodrigo-brito** [comment] 2018-04-24 18:27
Maybe the problem is here: https://github.com/JedWatson/react-select/blob/4ecb645d1f8814f8d4f1f530cb19eebd790ebfe6/lib/Creatable.js#L74-L79

When a custom function is given, the state `isClose` from `select` is not changed. It is called in `this.select.selectValue(option)`

**Comment by flexdinesh** [comment] 2020-03-22 10:00
Hey @mvnnn [v1 of react-select is no longer maintained](https://github.com/JedWatson/react-select/pull/3786). 

We recommend maintaining your own v1 fork if you want to address `v1` issues. We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest versions.

We highly recommend [upgrading from v1 to v2](https://react-select.com/upgrade-guide). Chances are this issue might already be fixed or non-existent in v2.

I'm closing this issue/PR now. Feel free add your thoughts in #3981 and reference this issue/PR if needed.

**Closed by flexdinesh** 2020-03-22 10:00 UTC
Labels: v1 deprecated
