### ISSUE TITLE
Use Plain text as options will result in "Uncaught TypeError: Cannot use 'in' operator to search for 'options' in ..."

### ISSUE THREAD

**Issue by jackykwandesign** [JedWatson/react-select#5087] opened 2022-03-01 10:24 UTC
We have a long string array to put into the Select, and we don't want to wrap into {label, value} format and use plain array, but with this approach the React-Select components will not allow us to do
```ts
import Select from 'react-select'
<Select
	options={["asd", "zxczx"]}
	getOptionLabel={(option) => option}
	getOptionValue={(option) => option}
/>

```
![image](https://user-images.githubusercontent.com/46065771/156151539-e5dd5e2e-7736-4203-8660-2c039152f8a5.png)

**Comment by Rall3n** [comment] 2022-03-15 06:37
Thank you @vjee.

@jackykwandesign I will close this as being a duplicate of #5032.

**Closed** 2022-03-15 06:37 UTC
Labels: issue/bug-unconfirmed
