### ISSUE TITLE
onClear

### ISSUE THREAD

**Issue by tim-phillips** [JedWatson/react-select#1309] opened 2016-10-16 00:01 UTC
It could be nice to have an onClear prop where I could set a function to run when the select is cleared. That way I can update my state when the clear button is clicked. 

I'm working around this by checking for an empty value in onChange.

**Comment by jfelipebc** [comment] 2016-10-21 20:55
Hi @babenzele, 

I had the same inconvenient, you can try this temporary solution:

import React from 'react';
import ReactDOM from 'react-dom';
import ReactSelect from 'react-select';
import 'react-select/dist/react-select.css';

function triggerMouseEvent (node, eventType) {
    var clickEvent = document.createEvent ('MouseEvents');
    clickEvent.initEvent (eventType, true, true);
    node.dispatchEvent (clickEvent);
}

export default class DropDownList extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      value: ''
    }
  }

  onChange() {

  }

  onClear(){
    e.preventDefault();
    let clearElement = ReactDOM.findDOMNode(this).querySelector('.Select-clear-zone');
    triggerMouseEvent(clearElement, 'mousedown');
  }

  render() {


    return (
      <div>
        <ReactSelect
          options={this.props.data}
          name='form-field-name'
          value={this.state.value}
          onChange={this.onChange.bind(this)}
          placeholder={this.props.placeholder}/>
        <span className="input-group-btn">
          <button className="btn btn-sm btn-default btn-clear"
                  type="button"
                  onClick={() => this.onClear()}
                  title="Quitar">
            <span className="icon-cerrar"></span>
          </button>
        </span>
      </div>
    )
  }
}

**Comment by babenzele** [comment] 2016-10-23 03:54
@jfelipebc Thanks! That's a good move putting the onClear on the clear button's onClick.

**Comment by robhadfield** [comment] 2016-12-02 22:09
It would be great to have an onClear prop - I have a number of select boxes on the first page and athough the onChange event is fired, nothing is passed with it. It would be great to be able to pass the item object back up the onClear chain.

**Comment by meep26** [comment] 2019-07-26 10:22
is onClear implemented in current version?

**Comment by sclavijo93** [comment] 2019-08-22 17:39
Hi! I really need the onClear prop :(

**Comment by beatrizf13** [comment] 2019-11-14 14:50
News? This is extremely important! Especially if the implementer uses the new react api with hooks! ⚛ ⚓

**Comment by nikitaindik** [comment] 2019-12-04 09:11
Docs are not super "clear" on this, but looks like you can use second argument to onChange to detect clearing.

```javascript
<Select onChange={(selectedOption, triggeredAction) => {
  if (triggeredAction.action === 'clear') {
    // Clear happened
  }
}} />
```

Hope this helps.

**Comment by arnaudjaspard** [comment] 2020-03-02 21:41
> Docs are not super "clear" on this, but looks like you can use second argument to onChange to detect clearing.
> 
> ```js
> <Select onChange={(selectedOption, triggeredAction) => {
>   if (triggeredAction.action === 'clear') {
>     // Clear happened
>   }
> }} />
> ```
> 
> Hope this helps.

Thanks it helps, but only solves a part of the problem for me sinceis onFocus is triggered just after that so in my case it clears the state I'm using to set style on focus.
I managed with a setTimeout but it is not elegant, An alternative would be to get the value with onFocus but event.target.value is always empty for some reason. I'll spend more time to check again

**Comment by badkuzu** [comment] 2020-07-24 22:21
Hey guys,
I've been struggling with this today, and I found that actually if you use a custom DropdownIndicator component, then the indicator component actually fires an event when you click the "x" button and clear the input.
There is no handler for that though, so you have to look at `props.hasValue` which will change from `true` to `false` when you clear the input :)

Check this sandbox that I made:
https://codesandbox.io/s/react-codesandboxer-example-gjhij?file=/onClearEventMod.js

I just need to figure out how to actually pass the state update from this component to the one which contains my react-select input. If someone has a hint, I'd appreciate.

**Comment by cseas** [comment] 2020-09-28 12:57
Any update on whether an onClear prop can be added to the library? Or can there be an alternate solution where we can override the `onClick` used by ClearIndicator?

**Comment by Methuselah96** [comment] 2020-11-14 16:43
I've started [a fork](https://github.com/react-select-oss/react-select) of react-select. Feel free to resubmit this issue on the fork and/or submit a PR to resolve this issue on the fork and we can get it merged and released.

**Comment by ebonow** [comment] 2020-12-07 00:48
Greetings,

The onChange handler is meant to deal with the clear button. I understand it's not documented perhaps as well as it could be and documentation is certainly on the docket of things to address, but this is still a one and a half line code implementation to achieve the result being asked for.

[Sandbox: ](https://codesandbox.io/s/react-select-onclear-j6s9r)

``` JS 
const selectRef = useRef();
const onChange = (_, { action }) =>action === "clear" && setTimeout(() => selectRef.current.select.blur(), 1);
```

Yes, setTimeout is not ideal, but it does accomplish adding this to the end of the event queue after the state changes.

Given the age of this post, I will be closing this so we can continue to focus our efforts on bugs and issues. Please let me know if anyone has any issues with the provided sandbox/solution.

**Closed by ebonow** 2020-12-07 00:48 UTC
Labels: issue/enhancement, issue/reviewed

**Comment by uhetz** [comment] 2021-03-09 10:35
Hi to all.

Actually you can just check, if the value is null. In TS you must do that anyway. So, If it's null, then that was just cleared, like:

`onChange={ (v) => v?.value ? onSelect(v.value) : onDeselect() }`

I'm passing here to my AutoComplete child component the events _onSelect_ and _onDeselect_ from its parent component.

**Comment by brendomaciel** [comment] 2021-11-12 15:11
> ```js
> const selectRef = useRef();
> const onChange = (_, { action }) => action === "clear" && setTimeout(() => selectRef.current.select.blur(), 1);
> ```

Does this still work? This "clear" action doesn't seems to exist anymore.

**Comment by ebonow** [comment] 2021-11-12 16:45
@brendomaciel 

`clear` is still a supported action passed by the actionMeta of the onChange callback and should still be working.

![Screen Shot 2021-11-12 at 8 30 38 AM](https://user-images.githubusercontent.com/1007579/141501400-3f531b17-d304-4958-8cc5-041af9c65350.png)

What doesn't work in the sample code I provided above is the "blur" since the refs have changed from v4 -> v5. For v5, the code would instead look something like...

``` jsx
const onChange = (_, { action }) => action === "clear" && setTimeout(() => selectRef.current.blur(), 1);
```

Note that this is for an UNCONTROLLED input. For a controlled input (value is passed to the Select via its prop), then yes you would of course need to change the `value` in state onChange.

``` jsx
const [ value, setValue ] = useState();

const selectRef = useRef();

const onClear = setTimeout(() => selectRef.current.blur(), 1);

const onChange = (selected, { action }) => {
  if (action === "clear") {
    onClear();
  }
  setValue(selected);
};

return <Select ref={selectRef} value={value} onChange={onChange} {...otherProps} />
```

That said, your solution of creating a custom ClearIndicator component would also be a viable approach.

**Comment by ebonow** [comment] 2021-11-12 20:18
@brendomaciel not sure what is happening in your implementation, but there doesn't appear to be any issues with the solution I suggested https://codesandbox.io/s/sad-grothendieck-ev5c8?file=/src/App.js

**Comment by brendomaciel** [comment] 2021-11-12 20:49
@ebonow Thank you very much for your time and insights. I will investigate and, if I found, I will share the cause here.

**Comment by dkrefta** [comment] 2023-07-17 23:14
Seems that still not working for some weird reason haha because if I create an example that is dumb works, but anyway, I used the example of @ebonow to fix my project, also thanks :)

here is how I create the ClearIndicator:

```
const ClearIndicator = ({
  innerProps,
  clearValue,
}: {
  innerProps: any;
  clearValue: () => void;
}) => {
  const handleClick = (event: React.MouseEvent<HTMLDivElement, MouseEvent>) => {
    event.stopPropagation();
    clearValue();
  };

  return (
    <div {...innerProps} onMouseDown={handleClick}>
      <Icon icon="close" size={16} color="black" />
    </div>
  );
};

```

**Comment by forrestwilkins** [comment] 2023-11-29 20:53
I resolved the issue by just checking wether `option` is `null` since that's what's passed on clear.

**Comment by invinciblemuffi** [comment] 2024-01-23 04:46
> @brendomaciel
> 
> `clear` is still a supported action passed by the actionMeta of the onChange callback and should still be working.
> 
> ![Screen Shot 2021-11-12 at 8 30 38 AM](https://user-images.githubusercontent.com/1007579/141501400-3f531b17-d304-4958-8cc5-041af9c65350.png)
> 
> What doesn't work in the sample code I provided above is the "blur" since the refs have changed from v4 -> v5. For v5, the code would instead look something like...
> 
> ```js
> const onChange = (_, { action }) => action === "clear" && setTimeout(() => selectRef.current.blur(), 1);
> ```
> 
> Note that this is for an UNCONTROLLED input. For a controlled input (value is passed to the Select via its prop), then yes you would of course need to change the `value` in state onChange.
> 
> ```js
> const [ value, setValue ] = useState();
> 
> const selectRef = useRef();
> 
> const onClear = setTimeout(() => selectRef.current.blur(), 1);
> 
> const onChange = (selected, { action }) => {
>   if (action === "clear") {
>     onClear();
>   }
>   setValue(selected);
> };
> 
> return <Select ref={selectRef} value={value} onChange={onChange} {...otherProps} />
> ```
> 
> That said, your solution of creating a custom ClearIndicator component would also be a viable approach.

This Worked well for me. As expected. For reference I am pasting my code in case if it can be of help to others
`const onUpdatedBySelectOptions = (selectedUpdatedByName, userAction) => {
    const {action, removedValue} = userAction
    if(action === 'select-option') {
      const selectedEmails = selectedUpdatedByName.map(item=>item.value)
      setUpdatedByName(selectedEmails)
    }
    if(action === 'remove-value') {
      const removedEmails = selectedUpdatedByName.filter((item) => item !== removedValue.value);
      setUpdatedByName(removedEmails);
    }
    if(action === 'clear') {
      setUpdatedByName([]);
    }
  };`
  `<Select
                  options={ allUpdatedByEmailIds }
                  isMulti
                  onChange={onUpdatedBySelectOptions}
                />`
