### ISSUE TITLE
Dropdown remains fixed in place and doesn't scroll with parent container

### ISSUE THREAD

**Issue by bladey** [JedWatson/react-select#4088] opened 2020-06-15 04:46 UTC
_This issue is a round-up of multiple past issues documenting the same bug. Feel free to check out the linked issues below for more information. This issue is the source of truth going forward to investigate the issue, report findings, and implement a bug fix._

**Issue:** 

![Screen Capture on 2020-06-15 at 14-43-03](https://user-images.githubusercontent.com/737821/84618854-c061d600-af16-11ea-94a0-2448f5470821.gif)

Dropdown remains fixed in place and doesn't scroll with parent container.

The commit responsible for this issue is located here - https://github.com/JedWatson/react-select/commit/691a01171969da89e20097f9d603651bb18a8510

Version `v3.0.4` does not have this bug however the latest release `v3.1.0` does.

**Issues:**

https://github.com/JedWatson/react-select/issues/4554
https://github.com/JedWatson/react-select/issues/4020
https://github.com/JedWatson/react-select/issues/4052
https://github.com/JedWatson/react-select/issues/3734
https://github.com/JedWatson/react-select/issues/4085
https://github.com/JedWatson/react-select/issues/3929
https://github.com/JedWatson/react-select/issues/3349
https://github.com/JedWatson/react-select/issues/3646

**Examples:**

https://codesandbox.io/s/react-select-v3-sandbox-forked-lgkms
https://codesandbox.io/s/compassionate-cookies-85j2n
https://codesandbox.io/s/react-select-v3-sandbox-kr5wf
https://codesandbox.io/s/festive-dirac-izf5y
https://codesandbox.io/s/react-codesandboxer-example-xy47y

If anyone would like to share any further information, please do so.

**Comment by mjb95** [comment] 2020-06-15 08:50
Hi - for info, I have explicitly tested this by installing v3.0.4 and v3.0.3, and I experience the same issue in both versions.  Is it possible that the bug existed even before the commit that you have highlighted above?

**Comment by palashkaria** [comment] 2020-06-25 13:09
I think @mjb95 is right, as this is the behaviour of React Select in v2 also; menuPosition fixed & portal, both do not update the positioning of the Menu on scroll - so the menu is stuck. All the sanboxes here have menuPosition fixed, and portal, and nothing related to it was changed in that commit.

The bug mentioned by @bladey is related to a _workaround_ (`menuShouldBlockScroll`) to handle the issue of the menu not scrolling - as mentioned in this comment https://github.com/JedWatson/react-select/issues/3929#issuecomment-604866966.


This sandbox demonstrates that bug it better: on opening the menu, the scroll stops working completely.
https://codesandbox.io/s/elegant-sky-51tlo?file=/src/App.js



@bladey I suggest we separate these issues, as `menuShouldBlockScroll` is a completely separate issue, would not be fix this problem (& it should be done anyway).


This would only be solved if something like tether.js is pulled into the lib (which has been proposed before) #810 has most of the problems/solutions related to this in one place - and IMO it is still not resolved. (see a hacky solution in this comment, which extends the Select class and uses react-tether + react-dimensions: https://github.com/JedWatson/react-select/issues/810#issuecomment-398563946)

**Comment by srinivasmerugu** [comment] 2020-07-09 13:33
Hi @bladey Could you please let us know if this would be prioritised and made available in next patch release please.

**Comment by bladey** [comment] 2020-07-16 05:23
@srinivasmerugu we'll get to it as soon as we can, any updates will be provided here.

**Comment by mjb95** [comment] 2020-07-30 10:37
Hi, has any progress been made on this issue?

**Comment by lohithvecham** [comment] 2020-09-21 07:44
Hi, anyone have any updates on this? 
In my case, it's happening in the Chrome-75 version but not in 78 or 80 versions.

**Comment by HodayaGruz** [comment] 2020-09-24 11:22
> Hi, anyone has any update on this?
> In my case, it's happening in the Chrome-75 version but not in 78 or 80 versions.

i see it happening in chrome 85.
when do you think it will fix?

**Comment by narojisivamurthi1230** [comment] 2020-11-05 13:35
how much time it take to push this commit?

**Comment by Methuselah96** [comment] 2020-11-14 16:35
I've started [a fork](https://github.com/react-select-oss/react-select) of react-select. Feel free to resubmit this issue on the fork and/or submit a PR to resolve this issue on the fork and we can get it merged and released.

**Comment by colin-oos** [comment] 2020-11-19 18:09
Are you guys changing the `menuPortalTarget`? I ran into this issue because I was using `menuPortalTarget` so the dropdown would display outside of my modal. I found out that the problem was because I was using `document.body` as my target but it was in fact my modal, not the body, that was scrolling. Using my modal as the target instead of `document.body` fixed the issue for me.

**Comment by MenachemICTBIT** [comment] 2020-11-24 12:12
@colin-oos How do you target a specific element? I have a div that I want to use as my target, how would I reference it?

**Comment by qenibas** [comment] 2020-11-27 10:00
Same issue here, got a lot of modals with height bigger than my screen (added overflow: scroll) - when do you think it'll be fixed?

**Comment by colin-oos** [comment] 2020-11-30 15:57
> @colin-oos How do you target a specific element? I have a div that I want to use as my target, how would I reference it?

You could use a [React Ref ](https://reactjs.org/docs/refs-and-the-dom.html) or if you give your `div` an `id` then you can use javascript `document.getElementById('my-divs-id')` and pass that result into `menuPortalTarget`. If you use a react ref, I believe you'd need to pass `this.myDivsRef.target` into `menuPortalTarget` (I haven't actually tried with a react ref though)

**Comment by BlackNightFury** [comment] 2020-12-08 17:29
@bladey How is it going? It's been very serious issue.....

**Comment by umanga907** [comment] 2020-12-16 16:17
This is bad. No way i could out a way to fix this. Can someone help please.

**Comment by MenachemICTBIT** [comment] 2020-12-16 16:22
Here's what I've been using. It's really hack-y and caused other problems, but it's the best I could do.

Because the position is fixed, if you need to scroll , the menu is pinned to the fixed position. The trick was to add an event listener that checks where the scroll occurs, and closes the menu if scrolling outside. The major problem this caused was, since it's used on a data table, the entire table rerenders every time you scroll, causing major stuttering. If your use case is more like a side menu, it might work.

I ended up using a different dropdown, in large part, because of this issue.

`	<Select
							isClearable
							value={value || ''}
							menuPortalTarget={document.body}
							menuPosition={'fixed'}
							// HACK: Specifying class name to force close dropdown. Issue with react-select libray (dropdown fixed position).
							// This CSS selector will almost certainly cause problems during deployment.
							closeMenuOnScroll={(e: any) => !e.target.classList.contains('css-4ljt47-MenuList')}
							options={suggestions}
						/>`

**Comment by srinivasmerugu** [comment] 2021-01-05 09:01
@bladey How is it going? Could you please provide an update on this. Issue still present in latest versions.

**Comment by Slapbox** [comment] 2021-01-23 21:38
We're not able to use any positioning other than `fixed` without it mangling our app by shifting the page upwards and offscreen, but using `fixed` we see this issue.

@Methuselah96 is there any plan to address this? I see it's been removed from any milestones? I really hope this can get fixed. I spent 6 hours trying to work around this issue without any success whatsoever, or even clues about how to fix it besides relying on `fixed` positioning - which has its own issues like this.

**Comment by ebonow** [comment] 2021-01-23 21:49
Greetings @Slapbox , 

Part of the version 4 release included a refactor of the scrollCaptor and menuPositioning into a single scrollManager. We have also added a `menu` to the existing PR's which address menu behavior so that we can address them holistically instead of ad hoc. 

I'm currently focused on addressing some of the underlying accessibility gaps with the aria live implementation, but hope to focus on the menu issues right after.

**Comment by Methuselah96** [comment] 2021-01-23 21:51
@Slapbox What's your use case? Are you using it in a modal? What are you using for `menuPortalTarget`? If you could create a CodeSandbox detailing your specific problem that would be the most helpful. Many of the issues described above have to do with setting the `menuPortalTarget` to `document.body` when the body is not the element that's actually scrollable.

**Comment by Slapbox** [comment] 2021-01-23 22:20
Hey @ebonow and @Methuselah96, thanks for your speedy replies!

@ebonow that makes sense to address them all in a holistic way. This issue isn't what I'd describe as urgent, but it is definitely important. I'm just glad to know that it's still on the radar of the maintainers.

@Methuselah96 specifically we use it in a frameless Electron window, and what happens is it shifts the custom window border/titlebar we implement. The most exact match for our issue is https://github.com/JedWatson/react-select/issues/1843

Unfortunately I'm not sure how to recreate the issue. I spent hours tracking things like `scrollHeight` and `offsetTop` for the root element of React-Select, and traversing upwards through every node. I couldn't find any differences in any properties I could think to check between before opening the menu (non-broken layout) and after (broken layout.)

The only, only, only other thing that remedied the issue was using `html { contain: content; }` which prevents the contents of `html` from affecting the layout outside of it, but that workaround has a number of issues too.

At first I didn't realize `menuPortalTarget` didn't have to be a React portal, so I tried using our own portal created with React-DOM, but the outcome was the same. 

I then tried `document.body` when I saw that suggested many times, which eventually led me to passing in the DOM node for the scrollable container our React-Select resides within, but even that made no difference in behavior. I confirmed the menu renders at the expected place in the DOM, so the inability of any of these options to affect the issue really confuses me.

I also tried `menuShouldScrollIntoView` and `menuPlacement="auto"` while grasping at straws. I then tried 3.2 and 4.0 in the past half hour, but the behavior (without `position="fixed"`) is the same. I didn't expect it to be fixed, but just to confirm it persists in the newest versions.

**Comment by thexpand** [comment] 2021-01-24 02:45
This issue doesn't only concern scrolling, actually. It's also the same when you resize the window - the fixed menu, which renders in a portal (in my case that would be the document.body), doesn't update its position when I resize the window. While it's highly unlikely that someone resizes their window while the menu is opened, I can't neglect the case when one has opened the menu on his smartphone and wanted to rotate it (which is basically changing the window size). The only way to reset the position in such cases is to close the menu and re-open it again manually.

**Comment by ebonow** [comment] 2021-01-24 02:49
@thexpand the issue you describe might be related to the issues described here.
https://github.com/JedWatson/react-select/issues/3533#issuecomment-761741263

**Comment by srinivasmerugu** [comment] 2021-02-25 14:00
Just to reiterate , the issue is still exist in latest version as well (4.1.0)
I am using menuPortalTarget={document.body} and using it in a Modal/SlideIn.

Please find the video attached.

Could you please address this asap . It's been pending from long time.

Thanks in advance!

https://user-images.githubusercontent.com/29884577/109163264-26d60e00-779f-11eb-8397-748b61be4ae1.mp4

**Comment by ebonow** [comment] 2021-02-25 16:27
@srinivasmerugu Understood and agree that this is high priority. There are several open issues regarding menu alignment specifically when used with portaling. v4.2 should be getting released soon. Depending on how far out the TypeScript conversion goes, this would likely be the next big initiative to get resolved.

It was just brought up in a chat about how to handle this and we may look into using Popper so it is on our radar.

**Comment by Ksenia0479** [comment] 2021-03-09 20:02
Hi @ebonow, do you have any update on this?

**Comment by ebonow** [comment] 2021-03-10 03:42
Hi @Ksenia0479 ,

Unfortunately, nothing specifically. Most of our last weekly meeting revolved around getting #4414 wrapped up and getting v4.2 released. A majority of the focus now is converting Flow to Typescript. The time table for that release will likely be about 2-3 weeks, so depending on progress, we may or may not get another release in before that.

This is something on my list to discuss as there are several issues/PR's related to menu behavior which can be mostly summed up by:
1) Positioning of portalled menu detaching from the select position
2) Calculating available menu height
3) Default option focus

I'll inquire to whether we want to address as is or look to using Popper (again apparently) and hope to have a follow up soon.

**Comment by Methuselah96** [comment] 2021-05-07 16:22
By way of an update, we have finished the Flow to TypeScript conversion and we're taking a look at this issue as our next focus. Depending on how extensive the changes have to be to fix this, this might end up in either v5 or v6 (if this requires breaking changes). Thanks everyone for your patience.

**Comment by srinivasmerugu** [comment] 2021-05-08 02:30
@Methuselah96, @ebonow Thanks for taking this issue as the next focus. Please consider it as on high priority.

**Comment by larry-han-au** [comment] 2021-07-12 11:25
I used a workaround to disable the outter scrollable when the dropdown is open. In my case, I just set the `overflow: hidden` from `overflow: scrolll`. Hope this works for someone's case.

**Comment by darija-blossom** [comment] 2021-09-02 08:11
> Are you guys changing the `menuPortalTarget`? I ran into this issue because I was using `menuPortalTarget` so the dropdown would display outside of my modal. I found out that the problem was because I was using `document.body` as my target but it was in fact my modal, not the body, that was scrolling. Using my modal as the target instead of `document.body` fixed the issue for me.

After searching for solution for few days this comment by  
@colin-oos saved me. It worked for me. I just selected the modal content div.
https://github.com/JedWatson/react-select/issues/4088#issuecomment-730547287

**Comment by Methuselah96** [comment] 2021-10-13 13:32
It has not been addressed yet. The plan is still to either release it in a minor release in v5 or in a major release in v6.

I would love to give an estimate of when this issue will be resolved, but unfortunately it is hard to give a realistic estimate since the work required to fix it is not trivial and the amount of time I have to work on open-source is not always consistent. On the scale of weeks, months, or years I think months is the most likely.

If you would like it to be accommodated more quickly, considering sponsoring me on GitHub Sponsors. If I get $50/month worth of sponsors from 5 or more new sponsors then my estimate would become weeks. Not because it'll suddenly be worth my time, but because I want to encourage people to put their money where their mouth is. Alternatively, fork it and do it yourself. I can't promise that we'd merge it back in, but it will get you out of your bind.

I hope this doesn't come across as uncaring, I just want to set realistic expectations. Having a library that's consistently maintained is more valuable than having a library where the maintainers get burned out.

**Comment by ArekMiszcz** [comment] 2021-11-26 13:46
Hope it'll help someone. The problem is because MenuPortal by default is appending into document body. That's why scroll has no effect on this portal. So the solution could be changing menuPortalTarget into container which wrapping select component and has relative position. Moreover by using menuPortal style its position should be changed into static (by default it's set as absolute). Thanks to it menuPortal is relative to select component and scroll has effect on this menu.

**Code example**

```
const refSelectContainer = React.useRef(null);
<div ref={refSelectContainer} className={classes.select}>
   <SelectComponent
      ...
      menuPortalTarget={refSelectContainer.current}
      styles={{
        menuPortal: base => ({
           ...base,
           position: 'static',
           zIndex: 1000
        })
      }}
```

**Styles**

```
select: base => ({
   ...base,
   position: 'relative'
})
```

**Comment by Etheryte** [comment] 2021-11-26 15:11
@ArekMiszcz Similar suggestions have been brought up in the older tickets linked above, that approach only works in layouts where overflow breakout isn't necessary and doesn't address the general problem. In fact in most of the layouts where this does work you wouldn't need portaling to begin with. Glad if it fixes the issue for you though.

**Comment by danielavpr** [comment] 2021-11-30 19:57
This isn't a fix for the issue, but I think it's a nice workaround. I added `menuShouldBlockScroll={true}` prop and it blocks the body from scrolling when the select is open, that in my opinion is better user interaction.

**Comment by dbousamra** [comment] 2021-12-05 23:06
Still an issue. Cannot figure a way to work around it.

**Comment by aleksey-turets** [comment] 2021-12-30 14:29
Hope this helps someone
```
<div id="scrollContainer" style={{ overflowY: 'auto' }}>
  <Select
    menuPortalTarget={document.body} // Or document.getElementById('scrollContainer')
    styles={{
      menuPortal: base => ({ ...base, zIndex: 9999 }),
    }}
    closeMenuOnScroll={event => {
      return event.target.id === 'scrollContainer';
    }}
  />
</div>
```

**Comment by corwinstephen** [comment] 2022-02-01 18:37
This seems like another one where the simplest fix is just to add `menuPosition='fixed'`. Upon further reading around that attribute, it looks like it's actually supposed to work properly (update its position on page scroll) and the fact that it doesn't is a longstanding bug. Weirdly, I noticed that if you scroll, and then hover over the open select menu, its position updates to the correct one.

I'm not sure why it's taken them so long to fix this, but it does seem like it will get fixed eventually. In the mean time, I think it should be fine to use fixed here the way it is.

**Comment by Methuselah96** [comment] 2022-02-01 18:46
I'm not sure of your particular situation, but using `menuPosition='fixed'` will not fix it for most people. If you go to [the Cypress tests](https://react-select.com/cypress-tests), scroll down in the portalled example, uncheck "Block Scroll", click "Fixed", and try scrolling either the page or the portal container it will not update the menu until you hover over it.

The attribute never worked properly because it has never recalculated the position on page scroll. I made substantial progress on this task a few months before I got sidetracked by release Redux DevTools 3.0. I hope to get back to it soon and my estimate is still months, but not years.

**Comment by man-trackunit** [comment] 2022-02-09 07:42
May I suggest taking a look at [Floating UI](https://floating-ui.com) instead of popper when implementing this? Also, awesome work you do here. 💪  I'll see if I can convince my org to sponsor you.

**Comment by gajrajantino** [comment] 2022-03-21 08:18
Why does this issue doesnt occur on the official website? https://react-select.com/home

**Comment by gajrajgchouhan** [comment] 2022-03-21 08:34
I was able to fix the issue using this [commit](https://github.com/medusajs/admin/pull/335/commits/b08dc752056cca215c85c22e3e87e67848fb937a#diff-cb89df882625f370b05ebf40c3ab3453206e7725ef9c059bdccd822a5105b1fbR264) !!

```js
closeMenuOnScroll={(e) => {
    return e.target.contains(containerRef.current);
}}
```

I was looking for solution involving refs and without assigning unique IDs to the container. Hope this helps someone!

**Comment by Methuselah96** [comment] 2022-03-21 14:23
> Why does this issue not occur on the official website? https://react-select.com/home

This issue is only occurs when using portalling or fixed menu positioning.

**Comment by andrew-aladev** [comment] 2022-04-26 18:11
Hello, I've reviewed `react-select` source code and found that it is easy to fix this issue: just rerender it on viewport update (scrolling, window resizing, etc). Rerender calls `renderMenu` function and everything will be fine. It will be good to add something like `debounce` for viewport events.

**Comment by Etheryte** [comment] 2022-04-26 18:37
@andrew-aladev I doubt that's a realistic option, you'd have to consistently rerender at 60fps on top of everything else the browser is doing to avoid jitter, especially when considering many operating systems today use smooth scroll as default.

**Comment by AimanKM** [comment] 2022-04-27 01:26
https://codesandbox.io/s/jovial-ramanujan-754p13?file=/src/App.js

**Comment by AimanKM** [comment] 2022-04-27 01:29
Try this: https://codesandbox.io/s/jovial-ramanujan-754p13?file=/src/App.js

**Comment by andrew-aladev** [comment] 2022-04-27 16:17
[react-select@3.1.0.zip](https://github.com/JedWatson/react-select/files/8573903/react-select%403.1.0.zip)

I've added simple patch for 3.1.0 version, you can easily adapt it for any other version.

> I doubt that's a realistic option, you'd have to consistently rerender at 60fps on top of everything else the browser is doing to avoid jitter, especially when considering many operating systems today use smooth scroll as default.

Sure, absolute menu has move using jumps. I've added a patch for this solution. If user wants smooth movement than it has to avoid absolute mode.

Thank you.

**Comment by srinivasmerugu** [comment] 2022-06-13 11:25
@Methuselah96 Could you please let us know if there is any plan of integrating popper for menu positioning as discussed here very long back for addressing scrolling issue with portal.

**Comment by Methuselah96** [comment] 2022-06-13 11:30
The status remains the same as it was in my previous comments. I am hopeful it will be released by the end of the year.

**Comment by Sakib326** [comment] 2022-07-29 11:53
> Hope this helps someone
> 
> ```
> <div id="scrollContainer" style={{ overflowY: 'auto' }}>
>   <Select
>     menuPortalTarget={document.body} // Or document.getElementById('scrollContainer')
>     styles={{
>       menuPortal: base => ({ ...base, zIndex: 9999 }),
>     }}
>     closeMenuOnScroll={event => {
>       return event.target.id === 'scrollContainer';
>     }}
>   />
> </div>
> ```

thanks . it's helpful

**Comment by srinivasmerugu** [comment] 2022-08-18 13:56
@Methuselah96 Thanks for the #5256 . Could you please let us know in which version of react-select it will accommodate.

**Comment by divinsmathew** [comment] 2022-09-01 20:24
For me, simply adding `menuPortalTarget={document.body}` fixed the issue.

**Comment by stephanvd-thedelta** [comment] 2022-10-10 12:07
as a hack, I've done the following:

```tsx
  const [open, setOpen] = useState(false);
  const portalRef = useRef(document.getElementById('popover-root'));
  const selectRef = useRef<SelectInstance<Item, false>>(null);

  // ...

  // Bug in library - Dropdown doesn't scroll with page if using a portal
  // Remove this hack once the folling issue is closed:
  // https://github.com/JedWatson/react-select/issues/4088
  const hackToFixScrollingPosition = useCallback(() => {
    const controllerEl = selectRef.current?.controlRef;
    const menuEl = selectRef.current?.menuListRef;
    const menuControllingEl = menuEl?.parentElement?.parentElement;
    if (!controllerEl || !menuEl || !menuControllingEl) {
      return;
    }

    const controllerBounding = controllerEl.getBoundingClientRect();
    const menuBounding = menuEl.getBoundingClientRect() as DOMRect;
    const shouldPositionOnTop = window.innerHeight - controllerBounding.bottom < menuBounding.height;

    if (shouldPositionOnTop) {
      menuControllingEl.style.top = controllerBounding.top - menuBounding.height - 5 + 'px';
    } else {
      menuControllingEl.style.top = controllerBounding.top + controllerBounding.height + 5 + 'px';
    }
    menuControllingEl.style.left = controllerBounding.left + 'px';
  }, []);

  useEffect(
    function hackToFixScrollingPositionSubscriber() {
      let el: HTMLElement | null | undefined = selectRef.current?.controlRef;
      const listening: HTMLElement[] = [];
      do {
        if (el) { // ts pls
          el.addEventListener('scroll', hackToFixScrollingPosition);
          listening.push(el);
        }
      } while ((el = el?.parentElement));

      return () => {
        for (const el of listening) {
          el?.removeEventListener('scroll', hackToFixScrollingPosition);
        }
      };
    },
    [hackToFixScrollingPosition],
  );

  useEffect(
    function hackToFixScrollingPositionOnOpen() {
      setTimeout(hackToFixScrollingPosition, 100);
    },
    [hackToFixScrollingPosition, open],
  );

  // ...

  <Select
      ....
      menuPortalTarget={portalRef.current}
      ref={selectRef}
      menuShouldScrollIntoView={false}
      minMenuHeight={50}
      onMenuClose={() => setOpen(false)}
      onMenuOpen={() => setOpen(true)}
  />
```

**Closed** 2022-10-12 23:14 UTC
Labels: issue/bug-confirmed, issue/reviewed, menu-bug

**Comment by Methuselah96** [comment] 2022-10-12 23:24
The feature to auto-update the menu position when using menu portalling (#5256) has been released in [`react-select@5.5.0`](https://github.com/JedWatson/react-select/releases/tag/react-select%405.5.0). Let me know if this addresses the issues experienced here. If there are more bugs to sort related to menu positioning, please open new issues with using CodeSandboxes with the latest version `react-select`. Thanks to everyone for your patience.

**Comment by Dalton-Klein** [comment] 2022-11-02 22:31
> 

I have upgraded to 5.5.0 and haven't noticed any difference in this issue. 

Unless I include these three options, the selects collide with each other when stacked vertically: 

- menuPortalTarget={document.body}

- menuPosition={'fixed'}

- menuShouldBlockScroll={true}


The issue with using these three options, is that it wipes all the styling I have set, and I cannot figure out a way to override the css styling when it is attached to the body.

**Comment by lukebennett88** [comment] 2022-11-02 23:10
@Dalton-Klein, if you're able to make a CodeSandbox repro of the bug, I'd be happy to take a look for you.

**Comment by Etheryte** [comment] 2022-11-04 15:07
I can confirm that the 5.5.0 release [works excellent and is buttery smooth](https://codesandbox.io/s/react-select-v5-sandbox-forked-xcc6z2). Thank you very much for everyone involved for your effort, especially @Methuselah96, this is splendid.

**Comment by vanhaaggen** [comment] 2023-02-23 13:36
I know this has been merged already but maybe this helps somebody. 

I had a selector in a bootstrap modal. None of the above mentioned solutions did work for me.  In my case, setting `menuPortalTarget` to `null` attached the menu-portal element to the `Select` parent element and kept it there, even on scroll. 

I have no idea why this is working but If someone knows the answer, please let me know.

**Comment by IttzyTT** [comment] 2023-07-13 13:51
> Here's what I've been using. It's really hack-y and caused other problems, but it's the best I could do.
> 
> Because the position is fixed, if you need to scroll , the menu is pinned to the fixed position. The trick was to add an event listener that checks where the scroll occurs, and closes the menu if scrolling outside. The major problem this caused was, since it's used on a data table, the entire table rerenders every time you scroll, causing major stuttering. If your use case is more like a side menu, it might work.
> 
> I ended up using a different dropdown, in large part, because of this issue.
> 
> ` <Select isClearable value={value || ''} menuPortalTarget={document.body} menuPosition={'fixed'} // HACK: Specifying class name to force close dropdown. Issue with react-select libray (dropdown fixed position). // This CSS selector will almost certainly cause problems during deployment. closeMenuOnScroll={(e: any) => !e.target.classList.contains('css-4ljt47-MenuList')} options={suggestions} />`

genius, works!

**Comment by ravivarma333** [comment] 2024-01-03 20:47
<img width="708" alt="Screenshot 2024-01-03 at 12 42 49 PM" src="https://github.com/JedWatson/react-select/assets/45998945/fadefbd6-b8f4-4ced-ba52-de966c48c242">

@Methuselah96 I see that when a div has the select tag from react-select and when you try to scroll the div the drop down of the select appears above of the divsion when scroll is extended.

Can you look into this.
