### ISSUE TITLE
onChange is called when user clears input

### ISSUE THREAD

**Issue by motoedie** [JedWatson/react-select#3985] opened 2020-03-25 15:55 UTC
When empty input is active and user presses backspace, onChange is called.

https://codesandbox.io/s/react-codesandboxer-example-qnl7c

**Comment by flexdinesh** [comment] 2020-03-26 13:15
Hey @motoedie! That is the intended behaviour. We listen to all keydown events and propogate `onChange` to the userland with the value.

You can ignore it conditionally like this —
```
handleChange = (e) => {
  if(!e) return;

  // value exists
};
```

Closing the issue now. Feel free to reopen it if you want to discuss it further.

**Closed by flexdinesh** 2020-03-26 13:15 UTC

**Comment by alkeshshahrspl** [comment] 2020-05-21 09:59
hi,

value is already null and keep pressing backspace, it is calling onChange all time.
whenever user presses backspace it is triggering onChange. Value is already null and after pressing backspace it will still remain null so value is not changed so what is the meaning of trigger onChange each time user presses backspace?
