### ISSUE TITLE
using isMulti & closeMenuOnSelect={false} props.  reset input value after selection

### ISSUE THREAD

**Issue by eretica** [JedWatson/react-select#4463] opened 2021-02-24 06:49 UTC
https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/Select.js#L792

# Are you reporting a bug or runtime error?

Im using version 4.1.0 & 3.1.1

- using this props `isMulti={true} & closeMenuOnSelect={false}`
- filter by input value
- select option
- input value reset <= here! issue

I don't want to be reset

# Are you making a feature request?

may be this line is issue 
https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/Select.js#L792

https://codesandbox.io/s/solitary-butterfly-8j6d3?file=/src/App.js

no need input reset when select using isMulti props

**Comment by Rall3n** [comment] 2021-02-24 07:19
Possible duplicate of #3210.

The solutions provided there still apply to the current version.

**Closed** 2021-02-24 15:59 UTC
