### ISSUE TITLE
Include `name` property in `onChange(selected)`

### ISSUE THREAD

**Issue by jfsiii** [JedWatson/react-select#1458] opened 2017-01-02 22:20 UTC
This would make it easier to use a single `onChange` handler for tracking current state.

e.g. The same change handler 

```javascript
const onChange = (selected) => {
  this.setState({ [selected.name]: selected.value })
}
```

Could be used for

```jsx
<Select
    name="form-field-name-one"
    value="one"
    options={optionsForOne}
    onChange={onChange}
  />

<Select
    name="form-field-name-two"
    value="two"
    options={optionsForTwo}
    onChange={onChange}
  />
```

My current workaround is to create a handler which uses a closure to track the name.

```javascript
_createChangeHandler(name) {
  const onChange = (newValue) => this.setState({ [name]: newValue.value });
  return onChange;
}

const onChange = this._createChangeHandler(name);
return (
  <Select
    name={name}
    value={this.state[name]}
    onChange={onChange}
    ...
  />
);
```

but I'd prefer it be available from the function's argument(s).

**Comment by jonathanphz** [comment] 2017-07-26 20:33
It seems weird that there's no option to retrieve the name of the Select. How are people dealing with multiple Selects in forms? Multiple onChange functions...?

**Comment by dandonahoe** [comment] 2018-07-01 22:02
This is the only nagging issue I have with this library. It seems like since the `onChange` handler is passed only a single argument, that a second argument containing the control's name could be added without breaking backwards compatibility. This would drastically simplify use when there are multiple selects on a page without hacky workarounds.

**Comment by dandonahoe** [comment] 2018-07-01 22:06
i hate half-assing comments when I'm asking for things, so here's more concreted example that would make my project a lot cleaner:

```jsx
handleChange = (selectedItem, nameOfComponent) => {
  // do things
}

render() {
  return (
    <React.Fragment>
      <ReactSelect
        name='firstSelect'
        value={something}
        onChange={this.handleChange}
        options={someOptions} />
      <ReactSelect
        name='otherSelectName'
        value={otherSmething}
        onChange={this.handleChange}
        options={otherOptions} />
    </React.Fragment>
  );
}
```

**Comment by rhysstubbs** [comment] 2018-11-27 18:09
The fact this functionality hasn't been implemented is enough for me to switch to a different solution, is there any hope this will change? Will pull-requests be accepted for it?

**Comment by markoj3s** [comment] 2019-01-08 13:42
https://react-select.com/upgrade-guide
Seems like there is now a second argument `actionMeta` for `onChange`. `name` is accessible from there.

**Comment by yim222** [comment] 2019-03-22 09:57
@markoj3s right. 
You can access the name property with second argument of the ev. 

Example (insert your option and check the console ) 

: 
```

<Form.Group class="">
                    <Form.Label for="validationTooltip02">מיועד ל-</Form.Label><br/>
                    <h3>Trying to make select </h3>
                    <Select   isMulti
                      MultiValueRemove
                      options={options} defaultMenuIsOpen = {false} closeMenuOnSelect = {false}
                      placeholder  = "choose"

                      onChange = {
                        (ev, meta )=>{
                                console.log(ev, "ev\n", meta, " = meta"); 


                        } }
                        name = "uniqueName"
                    />
</Form.Group>
```



![image](https://user-images.githubusercontent.com/16339682/54814963-7ea59980-4c99-11e9-8c10-877bb824001f.png)

**Comment by codenamerhubarb** [comment] 2019-06-17 05:39
Looks like the second argument of the onChange event only includes the name if there is one option selected, not when isMulti is enabled and you have more than one item selected or you are creating a new item with a CreatableSelect.

**Comment by ivan-kleshnin** [comment] 2020-03-31 09:40
+1

The same should apply to `onBlur` and `onFocus` which now
1) have entirely different API with `event` argument instead of custom object
2) the `event.target` points to nameless `input` :(

**Comment by Massetho** [comment] 2020-10-27 15:09
+1

Not having an event.target on the onChange option makes this component much less usable in my opinion.

**Comment by Methuselah96** [comment] 2020-11-14 16:36
I've started [a fork](https://github.com/react-select-oss/react-select) of react-select. Feel free to resubmit this issue on the fork and/or submit a PR to resolve this issue on the fork and we can get it merged and released.

**Comment by ebonow** [comment] 2020-12-04 07:15
Greetings @codenamerhubarb 

I was not able to reproduce. It appears in all cases onChange was returning the name in the context parameter regardless of value, no value, isMulti, or creating new option.

Here is my testing [codesandbox](https://codesandbox.io/s/react-select-name-onchange-g4rfe?file=/src/App.js)

<img width="791" alt="Screen Shot 2020-12-03 at 11 08 39 PM" src="https://user-images.githubusercontent.com/1007579/101133109-faa25b00-35bc-11eb-8928-5242f278184e.png">

**Closed** 2020-12-07 00:52 UTC
Labels: issue/enhancement, issue/reviewed
