### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by littlee** [JedWatson/react-select#1971] opened 2017-09-09 15:53 UTC
1.0.0-rc.6 get Unexpected token import error

**Comment by tobilen** [comment] 2017-09-09 16:22
same here

**Comment by acusti** [comment] 2017-09-09 18:03
The `lib/*` files no longer have their `import` statements transformed to `require`s, as of 1aa5134a1c2fd72daedabb45c2a81483c8bfeb96. See:

https://github.com/JedWatson/react-select/commit/1aa5134a1c2fd72daedabb45c2a81483c8bfeb96#diff-5c7f669d548ab8bf495256ff9bfd0acc

**Comment by super-cache-money** [comment] 2017-09-09 19:18
Hmm, that's an interesting move, particularly since currently node.js doesn't support `import` natively. IMO to `require` (lol) people to transpile stuff in the node_modules might be more of an inconvenience than it's worth.

**Comment by DeciderWill** [comment] 2017-09-09 20:39
Same here.

Here are the errors I get when building a docker image with Node 8.4.0.

```
[91mErrors prevented bundling:
[0m[91mWhile minifying app code:
packages/minifyStdJS/plugin/minify-js.js:96:26: Babili minification error
within packages/modules.js:
node_modules/react-select/lib/Select.js, line 1167

Only one default export allowed per module.:

export default Select;

at maybeThrowMinifyErrorBySourceFile
(packages/minifyStdJS/plugin/minify-js.js:96:26)
at files.forEach.file (packages/minifyStdJS/plugin/minify-js.js:135:9)
at Array.forEach (<anonymous>)
at MeteorBabelMinifier.processFilesForBundle
(packages/minifyStdJS/plugin/minify-js.js:118:9)
```

**Comment by acusti** [comment] 2017-09-09 22:10
@super-cache-money I'd guess it's an unintended build config issue, not an intentional change. It'd be one heck of a breaking change for a -rc* version bump.

**Comment by el-rotny** [comment] 2017-09-10 00:25
Was having the same issue. I can confirm that switching back to _1.0.0-rc.5_  fixed this in an isomorphic build.

**Comment by JedWatson** [comment] 2017-09-11 05:08
Fixed in `1.0.0-rc.7`

**Closed by JedWatson** 2017-09-11 05:08 UTC

**Comment by JedWatson** [comment] 2017-09-11 05:11
Sorry everyone, that was an unintended side-effect of the new build. We've fixed it now, should work as expected and please let us know if you see any other regressions with the rc - we'll jump on them asap and then want to get 1.0.0 out the door.

**Comment by scoumbourdis** [comment] 2017-09-11 07:14
Thanks @JedWatson you are awesome! :+1:
