### ISSUE TITLE
Unexpected call to onMenuClose on input blur.

### ISSUE THREAD

**Issue by rcgillet** [JedWatson/react-select#3876] opened 2019-12-06 16:34 UTC
There is a call to `onMenuClose` on every `input` blur, even when the menu has already been closed from another action. 

Steps to reproduce: 
1. Pass in an `onBlur` and `onMenuClose` function to the `Select` component.
2. Open the menu and make a selection. (`onMenuClose` is fired)
3. Hit tab or a similar action that would take the focus off of the input. (Both `onBlur` and `onMenuClose` are fired)

CodeSandbox reproducing the issue: https://codesandbox.io/s/admiring-bardeen-pu0rg

I was looking through the codebase and found that `onMenuClose` is being called regardless of the value of `menuIsOpen`. [Link to code](https://github.com/JedWatson/react-select/blob/9606a92fc236d00d79fa6e7b4b021e74118f8ac2/packages/react-select/src/Select.js#L1112)

Adding a conditional for `menuIsOpen` should fix the issue I believe. I would be happy to submit a PR if you believe that the approach I am proposing makes sense.

**Comment by bladey** [comment] 2020-06-18 05:59
Hi @rcgillet,

Thanks for reporting this issue. It appears this issue is a duplicate of #3335.

There is a PR at to resolve this #3897 which will get merged soon.

If I'm not correct, please let me know.

**Closed by bladey** 2020-06-18 05:59 UTC
Labels: bug/unconfirmed, issue/checked
