### ISSUE TITLE
Flow-type throws error with Selectprops 

### ISSUE THREAD

**Issue by michielmetcake** [JedWatson/react-select#3804] opened 2019-10-07 13:33 UTC
So; I'm using the select component from react-select together with Flow. This will cause these errors. I'm not sure what I'm doing wrong here? I'm using a very minimal example of the Select component. 

I'm using the [Formik](https://jaredpalmer.com/formik/docs/api/formik) library for my form. The prop setFieldValue originates from that library. 

So far I've tried to update all the components I'm using. And I've tried to pass the options as children. 

Could anyone help me out? Or point me into the right direction?

Thanks a lot

> Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/react-select/src/components/Input.js:49:3
> 
> All branches are incompatible:
>  • Either property selectProps is missing in PropsWithStyles [1].
>  • Or property selectProps is missing in object type [2].

> Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/react-select/src/Select.js:446:23
> 
> Cannot assign defaultComponents(...) to this.components because:
>  • property children is missing in props [1] but exists in object type [2] in property Menu.
>  • property innerRef is missing in props [1] but exists in object type [2] in property Menu.

**Used Packages:**
```
"dependencies": {
  "react": "^16.8.3",
  "react-app-polyfill": "^1.0.1",
  "react-dom": "^16.8.3",
}
"devDependencies": {
  "flow-bin": "^0.109.0",
  "flow-typed": "^2.6.1",
  "react-select": "^3.0.8",
   "@babel/preset-flow": "^7.0.0",

}
```
**Minimal example:**
```
/** @flow */
import React from 'react';
import Select from 'react-select';

/** Option type definitions for React-select */
type Option = {
  value: string,
  label: string,
};
type OptionValue = Option | Option[] | null | typeof undefined;

const CustomSelect = ({
  setFieldValue,
}: {
  setFieldValue: (field: string, value: string) => void,
}) => {
  const handleOnChange = (option: OptionValue) => {
    if (option && option.value) setFieldValue('topic', String(option.value));
  };

  const options = [
    {
      label: 'label1',
      value: 'valu1e',
    },
  ];

  return (
    <Select
      className='react-select-container'
      classNamePrefix='react-select'
      value={{ value: 'value' }}
      name='topic'
      onChange={handleOnChange}
      options={options}
      placeholder='placeholder'
    />
  );
};

export { CustomSelect };
```

**Comment by iamdey** [comment] 2019-10-24 16:16
about the the Input error, it is obvious that it comes from selectProps which is unused: https://github.com/JedWatson/react-select/blob/a860de4f9904473886cb66e7bfeea8539ca6a50f/packages/react-select/src/components/Input.js#L49

except to ignore it, that should not be a problem if it is removed from there: https://github.com/JedWatson/react-select/blob/a860de4f9904473886cb66e7bfeea8539ca6a50f/packages/react-select/src/Select.js#L1434


For the Menu, I don't understand why it throws, everything looks ok (but a bit complicated due to memoization).

FYI I wasn't able to get those errors using the sources, only using the package.

**Comment by bj00rn** [comment] 2019-10-31 10:08
looks like the definitions incomaptible with flow > 0.99.0

probably adressed in #3626?

**Comment by bj00rn** [comment] 2019-10-31 10:12
duplicate of #3612

**Comment by bladey** [comment] 2020-06-18 02:22
Hi all,

As @bj00rn mentioned, this appears to be a duplicate of #3612, I'm going to close this issue so we don't have duplicates. I'll mention this issue in the original to keep context.

**Closed by bladey** 2020-06-18 02:22 UTC
Labels: bug/unconfirmed
