### ISSUE TITLE
AsyncSelect doesn't clear underlying Select's value

### ISSUE THREAD

**Issue by javlund** [JedWatson/react-select#5219] opened 2022-06-08 14:09 UTC
This may be related to https://github.com/JedWatson/react-select/issues/5058, but I'm not sure, so I'm making a new issue for it.

In the code example below:

https://codesandbox.io/s/react-select-v5-sandbox-forked-i3u7l0?file=/example.tsx

, notice how the value of the select always stays set even though I clear the underlying state value (press the "Clear value" button). I don't seem to be able to set it to `undefined`.

Looking at my own, similar, code in the React component devtools, it seems that the value of the `AsyncSelect` is correctly cleared, but the `Select` within it is not. So that might be the issue. Or maybe I'm just getting something fundamentally wrong.

PS. Speaking of React devtools, the `AsyncSelect` is described as `Anonymous` within it - consider setting the `displayName` for it.

**Comment by Rall3n** [comment] 2022-06-08 14:27
Hello @javlund,

the problem is you setting the state value to `undefined`.
Setting the value on any `Select` component (or any other `<input>` element in React) to `undefined` transforms the component to an [un-controlled component](https://reactjs.org/docs/uncontrolled-components.html) (because technically the `value` prop does not exist).

Clearing the state with the value `null` keeps it controlled and accomplishes your desired result.

-----
I will close this issue right away as it is not a problem with the library, but a general React issue.

**Closed by Rall3n** 2022-06-08 14:27 UTC
Labels: issue/bug-unconfirmed
