### ISSUE TITLE
onMouseDown and onClick conflict with each other in IE

### ISSUE THREAD

**Issue by StefanBilliet** [JedWatson/react-select#184] opened 2015-05-12 11:46 UTC
Hi

I found a bug in IE 11, when in multi select mode. If you start clicking on items in the multiselect dropdown, eventually more items get added than you selected, unless you select the items fairly slowly.
I can replicate the behaviour in the current example page. In Chrome, the issue doesn't present itself.

It's like the onMouseDown and the onClick in buildMenu() conflict with each other in IE, because if I remove onMouseDown, I don't see it happening anymore.
Thing is though that if only the onClick is present, the menu closes after selecting an item. If only onMouseDown is present, the menu stays open.
https://github.com/StefanBilliet/react-select/commit/45f0f02ea86dbd3db1f0c78f7a1d983947a17b45

**Comment by dcousens** [comment] 2015-08-13 06:26
Still the case?

**Comment by gwyneplaine** [comment] 2019-01-21 05:36
Have been unable to reproduce this in v2.x 
Closing this issue, if for some reason you feel that what I've described above doesn't correctly address your problem, please feel free to create a new issue. Mostly doing this for clarity ad to reduce our issues list down to a sane and relevant number of actionable tasks.

**Closed by gwyneplaine** 2019-01-21 05:36 UTC
Labels: bug	(unconfirmed)
