### ISSUE TITLE
I have multi=false but react-select emits a change event with an array for the value.

### ISSUE THREAD

**Issue by StokeMasterJack** [JedWatson/react-select#1344] opened 2016-11-02 20:27 UTC
I have multi={false}. But sometimes, react-select emits a change event with an empty array for the value.

I am using:
AsyncCreatable
react-select v1.0.0-rc.2
Chrome Version 54.0.2840.71 (64-bit)
Mac OS X

Here is the stack trace from the Chrome console:

Jed emitted an array []
Uncaught Error: IllegalState(…)
	CompanyPicker._this.onChange			@	CompanyPicker.jsx?9896:64
	setValue								@	Select.js?407b:654
	popValue								@	Select.js?407b:689
	handleKeyDown							@	Select.js?407b:509
	ReactErrorUtils.invokeGuardedCallback	@	ReactErrorUtils.js?6b31:70
	executeDispatch							@	EventPluginUtils.js?0958:89
	executeDispatchesInOrder				@	EventPluginUtils.js?0958:112
	executeDispatchesAndRelease				@	EventPluginHub.js?c6b1:44
	executeDispatchesAndReleaseTopLevel		@	EventPluginHub.js?c6b1:55
	forEachAccumulated						@	forEachAccumulated.js?b898:25
	processEventQueue						@	EventPluginHub.js?c6b1:231
	runEventQueueInBatch					@	ReactEventEmitterMixin.js?8a20:18
	handleTopLevel							@	ReactEventEmitterMixin.js?8a20:29
	handleTopLevelImpl						@	ReactEventListener.js?2365:73
	perform									@	Transaction.js?6dff:138
	batchedUpdates							@	ReactDefaultBatchingStrategy.js?ef70:63
	batchedUpdates							@	ReactUpdates.js?ce09:98
	dispatchEvent							@	ReactEventListener.js?2365:150

**Comment by IanVS** [comment] 2018-11-20 19:20
I think this is a duplicate of https://github.com/JedWatson/react-select/issues/2682

**Closed** 2018-11-21 23:09 UTC
