### ISSUE TITLE
onOpenMenu triggers even when menu is already opened

### ISSUE THREAD

**Issue by dannyhuly** [JedWatson/react-select#3373] opened 2019-01-22 10:42 UTC
### Bug report
description:
`onOpenMenu` triggers even when menu is already opened 

expected result:
 `onOpenMenu` should triggers only when menu is opened

test case:
https://codesandbox.io/s/420oq96n4w
* open console
* click Select
* start typing in the input

**Comment by bladey** [comment] 2020-06-12 02:15
Duplicate of #3335, closing this issue as #3335 has expanded information.

**Closed by bladey** 2020-06-12 02:15 UTC
Labels: bug-unconfirmed
