### ISSUE TITLE
Input styles not being removed

### ISSUE THREAD

**Issue by raymon-zhang** [JedWatson/react-select#4673] opened 2021-07-02 03:31 UTC
If the user has applied global styles to the input element, such as 
```
input {
    box-shadow: 0px 0px 0px 5px red;
}
```
then the input element inside of react-select does not override those styles. 
You can see the behavior in this codesandbox: [https://codesandbox.io/s/react-select-v3-sandbox-forked-v06wq?file=/index.js](https://codesandbox.io/s/react-select-v3-sandbox-forked-v06wq?file=/index.js).

**Comment by ebonow** [comment] 2021-07-02 04:28
Greetings @raymon-zhang ,

This is by design and in my opinion a preferable implementation. Here essentially are the two options:

1) Overwrite all global input styles, forcing users to add greater specificity if they want to retain the styling in their inputs in the react-select component (ie: color, font-family, etc...)

2) Add as minimum of styling necessary to make the control work and have the user be responsible for their own global styling within the context of their own application.

I don't believe that every react-select user should be responsible for users who choose to style their own application with global styles but do not want to be responsible for how those styles impact 3rd party libraries.

What I can offer you is a solution to this:
```jsx 
    const styles = {
      input: (css) => ({
        ...css,
        input: {
          boxShadow: "none"
        }
      })
    };
    
    return <Select styles={styles}  {...otherProps} />
```
[Codesandbox demo](https://codesandbox.io/s/react-select-v3-sandbox-forked-sogfi?file=/example.js)

If using classNamePrefix, you could also target the input via `.[prefix]__input input { box-shadow: none }`

Please also note that this will be much easier to do in version 5 as the input will be exposed as `.[prefix]__input` making it easier to specify styling for inputs. 

I will be closing this, but please feel free to ask any question or offer any concerns about this approach.

**Closed by ebonow** 2021-07-02 04:28 UTC
