### ISSUE TITLE
Cannot Select an option on iOS Safari, Chrome Android Nexus 6P can't scroll 

### ISSUE THREAD

**Issue by abhiaiyer91** [JedWatson/react-select#904] opened 2016-04-19 23:06 UTC
Hey there, I am having trouble with touch devices trying to select an option in our Select dropdown. The onChange method does not get called at all? Is there something I'm missing? And for android we cannot scroll. 

```
   <Select
              value={this.state.selectValue}
              options={selectOptions}
              clearable={false}
              onChange={this.setSelectValue}
            />
```

I'm running `1.0.0beta12`

**Comment by abhiaiyer91** [comment] 2016-04-19 23:22
Alright an update for iOS, if you hold down the option then it selects, but quick taps close the dropdown completely.

**Comment by abhiaiyer91** [comment] 2016-04-20 02:07
Upon further investigation, it does not work on iphone 6 but does work on iPhone 6S

**Comment by gor181** [comment] 2016-04-20 05:42
@abhiaiyer91 where are you testing this? The issue is present when you are using Chrome device emulator but works just fine on real devices.

**Comment by abhiaiyer91** [comment] 2016-04-20 17:53
I am testing this on real devices. iOS and real device Nexus 6. My package.json does say its on beta12, but i wonder if browserify has cached beta8, and Im not getting the recent touch updateS?

**Comment by andresfcamacho** [comment] 2016-04-21 20:17
I'm seeing the same thing. If you touch and hold until it highlights then it works, obviously not really workable.

**Comment by andresfcamacho** [comment] 2016-04-23 13:51
For what its worth it seems like if you change `handleTouchStart` in Option.js to call `handleMouseDown`, it seems to work:

```
	handleTouchStart: function handleTouchStart(event) {
		// Set a flag that the view is not being dragged
		this.dragging = false;

		this.handleMouseDown(event);
	},
```

This doesn't seem like the real fix though. There could be something cancelling the touch event preventing `handleTouchEnd` from being called.

**Comment by andresfcamacho** [comment] 2016-04-26 01:59
My suggested fix is a no go because it doesn't allow scrolling.

**Comment by andresfcamacho** [comment] 2016-04-26 16:14
I was able to figureout why this didn't work in our environment. We're in vanilla Rails app that is in the process of migrating most views over to React. Previously we had included in our vendor directory the `fastclick` js file. After removing it I then installed the `react-fastclick` via npm and now everything works as expected. It could be we had an older version of `fastclick`, not sure. 

In the end this combination worked for us:

```
    "react-select": "^1.0.0-beta12",
    "react-fastclick": "^2.1.0",
```

@abhiaiyer91 you may want to check if you have the latest `react-fastclick` installed.

**Comment by dahjelle** [comment] 2016-04-27 13:51
We just ran into this issue as well, and as with @andresfcamacho, it was fixed by using `react-fastclick` instead of `fastclick`. Thanks much!

**Comment by charlesbodman** [comment] 2016-05-20 00:18
Can confirm this is an issue on iOS (Simulator and real devices) .
Works fine chrome device emulation tho.

**Comment by rahulinaction** [comment] 2016-06-13 07:13
Well any headups to solve this with fastclick itself rather than react-fastclick.The addition of react-fastclick results in other issues which fast click solves.

**Comment by adamwan92** [comment] 2016-06-27 14:06
Anyone else got this working with React-fastclick? I installed it via npm and have found no changes yet.

**Comment by bsthomsen** [comment] 2016-09-05 15:35
@andresfcamacho thanks for posting, you saved me for many hours of debugging :) switched fastclick with react-fastclick!

**Comment by aertmann** [comment] 2016-10-25 21:13
Here's a workaround for the problem that let's you keep Fastclick:

`optionRenderer={option => <div className="needsclick">{option.label}</div>}`

pretty annoying conflict :/

**Comment by Jaikant** [comment] 2017-02-19 14:59
react-fastclick solved the problem for me too.

**Comment by AnthonyDunk** [comment] 2018-06-25 00:29
The solution that worked for me on Android was adding the class "needsclick" to the select control.

**Comment by akhilaudable** [comment] 2019-03-11 03:07
We don't use ` React-fastclick` still there is a problem. Even if you open the [demo](https://react-select.com/components) of `react-select`  with touch devices (especially in Safari) you will see the issue.

**Comment by chris-guidry** [comment] 2019-10-02 15:51
@aertmann's option works well for v1. For v2 I had to switch to the prop formatOptionLabel: 
`formatOptionLabel={option => <div className="needsclick">{option.label}</div>}`

**Comment by bladey** [comment] 2020-05-28 04:58
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Closed by bladey** 2020-05-28 04:58 UTC
