### ISSUE TITLE
How to set current value or how to enable edit of the selected tag?

### ISSUE THREAD

**Issue by AlexanderTserkovniy** [JedWatson/react-select#1558] opened 2017-02-16 08:53 UTC
Hi guys,

1) The question is simple how to set current value of the input? Like when I put focus there and see already written text.

2) Or how to enable editing of the existing tag, that I could click and continue typing?

Thanks.

**Comment by jayryemure** [comment] 2017-02-17 17:41
This is critical for my application.  I looked into #2 and couldn't find any options to do this and would greatly appreciate a workaround (couldn't come up with that either).

**Comment by Siyfion** [comment] 2017-02-27 12:26
Is what you both are referring to is the ability to modify an existing selection's text, ie. Say the selected text is "AAAAA" and you want to select "AAAAB" you want to delete the last letter and change it... You can't. You have to delete the whole thing and start again?

If so, then I wholeheartedly agree, this seems like a really silly little bug... @JedWatson any ideas?

**Comment by AlexanderTserkovniy** [comment] 2017-02-27 12:46
@Siyfion yes, correct it is one option and another one is to set current value, thus we could remove element onclick and add set current value with focus, which will end with editing mode.

**Comment by riorulzz** [comment] 2017-03-07 12:57
@JedWatson I also need this for my application. Any ideas how can we implement it ?

**Comment by janusch** [comment] 2017-08-29 14:39
This would be great to implement. Does maybe one of the 137 PRs of this writing solve this?
Is it correctly understood that editing a selected value should only be possible if it is a `Select.Creatable`?

**Comment by Subha** [comment] 2017-09-28 18:40
I have this requirement too. 
Ellipses are displayed on the field for long text but not able to place cursor pointer at the end. Not able to edit it also. To enter value we need to delete it and re-enter. Can we have a fix for this.

**Comment by fzan** [comment] 2017-11-16 16:07
@JedWatson pushing up this, just noticed that we need the same thing it's opened from February

**Comment by jnachtigall** [comment] 2018-01-05 13:08
Looks like this ticket is a dupe of #1868 and the suggested solution is to create your own value and option component which handles the rendering and focus/edit etc. behaviour. I haven't tried myself so would be nice if somebody has a codepen/jsfiddle.

**Comment by julian69** [comment] 2018-01-11 01:30
I've just run into the same issue and haven't been able to find a solution yet.
Does anyone know whether there is a workaround?
I'd really appreciate any help since I'd need to get this feature working asap.
Thanks

**Comment by magdalko** [comment] 2018-01-16 11:04
I see not only me has the same problem! SOLUTION, please come :P

**Comment by AlexanderTserkovniy** [comment] 2018-02-12 09:27
I was not able to resolve it. Had to do some workaround, not even close to the react-select.

**Comment by jmaslin** [comment] 2018-08-23 23:39
Has anyone found a solution for this? The library is great but this feature would _greatly_ improve UX.

**Comment by jwr** [comment] 2018-08-31 22:12
Just encountered this problem: I was hoping to replace an editable-text control that I had with react-select, so that text can still be edited, just with a list of suggestions. But I can't, because react-select does not allow editing...

**Comment by kimbel** [comment] 2019-02-20 11:09
I was not able to resolve it as well.. anyone came up with a solution??

**Comment by burtek** [comment] 2019-02-20 12:28
Two years later... Another +1. @JedWatson ?

**Comment by chetan-zalake** [comment] 2019-02-25 09:34
Another +1. @JedWatson ?
This needs to be added as it is a basic requirement.

**Comment by Rall3n** [comment] 2019-02-25 10:57
With **v2.x** you can overwrite the internal components of the `Select` with the [Components Framework](https://react-select.com/components) to either replace or enhance functionality.

Here is a very basic example of a `CreateableSelect` with editable custom option: [CodeSandbox](https://codesandbox.io/s/9j400309y4).

Easy to implement with the help of the documentation and a look into the core code here on github.

If you are looking for editable option in a simple `Select` component, you should think about using unique identifiers for your options to identify them if you change the label (and maybe values).

**Comment by jonnydodad** [comment] 2019-03-07 21:41
Another +1, a little shocked this isn't a core feature.
@Rall3n thanks for the info but I'm a little confused by the CodeSandbox.. I want to be able to select an item from the dropdown and then edit it. For example, if I want to select option 'AAAAA', delete the last 'A' and type a 'B' so that the input contains 'AAAAB', I don't have to delete the entire item and start over. I can't seem to make that happen with this example...

**Comment by Rall3n** [comment] 2019-03-08 09:30
@jonnydodad Easy (using [my example](https://codesandbox.io/s/9j400309y4) as reference):

Edit `onChange` to not save the value into either `value` or `createdOption`, but into just `value`:
```jsx
onChange = (option, action) => {
    // If you want to keep the option in the menu, make a copy of the option as this is a reference to the element in the options array.
    var newOption = Object.assign({}, option);

    this.setState({ value: newOption });
}
```

Remove the `__isNew__` check from `SingleValue` and always render the input:
```jsx
SingleValue = ({ children, ...props}) => {
    return (<components.SingleValue {...props}>
      <input
        type="text"
        { ... }
      />
    </components.SingleValue>)
};
```

Update `onEditChange` to set state to `value` instead of `customOption`:
```jsx
onEditChange = (e) => {
    /* ... */
    this.setState({ value: newOption })
}
```

And for good measure remove the selection of `this.state.customOption` from the `value` prop of `CreatableSelect`:
```jsx
<CreatableSelect 
    { ... }
    value={this.state.value}
/>
```

**And et voilà**: You can now edit every option you have selected.

**Comment by jonnydodad** [comment] 2019-03-09 18:36
@Rall3n wow awesome thank you so much!

**Comment by inottawa** [comment] 2019-03-11 18:10
@jonnydodad I went with a [different approach](https://codesandbox.io/s/lymqy87k9l?fontsize=14).

I pulled a reference to the internals [via ref](https://react-select.com/advanced#accessing-internals)
`<CreatableSelect
    ref={ref => {
        this.select = ref;
    }}
/>`
I assigned the input value of the ref manually when the component is focused
`handleFocus = element => {
    if (this.state.value) {
      console.log(this.state.value.label);
      this.select.state.inputValue = this.state.value.label;
    }
};`

**Comment by silverwind** [comment] 2019-03-15 10:56
Would be interested in a solution for when `isMulti` is enabled. Hitting backspace with the cursors after a selected value should make that value editable.

**Comment by GIT-Sachin** [comment] 2019-11-01 03:14
@inottawa The approach you suggested is working fine if onFocus is triggered on mouse click. If it is happening because of pressing tab key then the behaviour is similar to what we get by default.

Here is the [Codesandbox](https://codesandbox.io/s/create-select-with-fake-service-xmyhd)

**Comment by SimpleCookie** [comment] 2019-11-15 15:49
I still need this but for the AsyncSelect. Setting select.state.value etc doesn't work ..  and it seems like the AsyncSelect has a select which has a select which has a select .. really weird structure :smile:

**Comment by punkrats** [comment] 2020-01-31 23:59
I was struggling to get `AsyncCreatableSelect` to be editable. I've downgraded to react-select 2.4.4 because 3.x did not seem to work.

In my example, the component is imported not as stated in the docs, because I could fetch `react-select/async-creatable`. And importing `AsyncCreatableSelect` from `'react-select'` seems to yield a regular `Select` component.

Hope this helps.

```javascript

'use strict'

import React from 'react'
import { AsyncCreatable } from 'react-select'

export default class MyComponent extends React.Component {
  constructor(props) {
    super(props)
    this.select = null
    this.state = {
      value: {label: props.value}
    }
    this.setRef = this.setRef.bind(this)
    this.loadOptions = this.loadOptions.bind(this)
    this.onChange = this.onChange.bind(this)
    this.onFocus = this.onFocus.bind(this)
    this.onMenuClose = this.onMenuClose.bind(this)
  }

  // Set reference to the select element.
  // Note the nested `select` objects!
  setRef(element) {
    this.select = element
      ? element.select.select.select
      : null
  }

  loadOptions(value) {
    // Load options remotely...
  }

  onChange(value) {
    this.setState({value: value})
  }

  // Restore input value
  onFocus() {
   if (this.state.value) {
     this.select.handleInputChange({
       currentTarget: {value: this.state.value.label}
     })
   }
  }

  // Blur select element to trigger onFocus on next click
  onMenuClose() {
    this.select.blur()
  }

  render() {
    return (
      <AsyncCreatable
        ref={this.setRef}
        loadOptions={this.loadOptions}

        // Let the select field appear as regular input
        openMenuOnClick={false}
        components={{DropdownIndicator: null, IndicatorSeparator: null}}

        // Hook into events to make the editing work
        onChange={this.onChange}
        onFocus={this.onFocus}
        onMenuClose={this.onMenuClose}

        // Create the new option at the top of the list
        createOptionPosition="first"

        // Set value given in props
        value={this.state.value}
      />
    )
  }
}
```

**Comment by tuval-rotem-rf** [comment] 2020-03-08 10:30
> Would be interested in a solution for when `isMulti` is enabled. Hitting backspace with the cursors after a selected value should make that value editable instead of outright deleting it.

here's my example for **isMulti** new example using @Rall3n as a base
https://codesandbox.io/s/react-select-editable-multi-createable-wp13r

**Comment by cention-sany** [comment] 2020-07-23 12:00
My approach by replacing hidden **SingleValue** and enchanced **Input**.

```javascript
import React, { useCallback, useMemo, useState } from "react";
import { components as cs } from "react-select";
import CreatableSelect from "react-select/creatable";
import { colourOptions } from "./docs/data";

const NewSingleValue = () => null;

const NewInput = ({ value: inputValue, isHidden, ...props }) => {
  const {
    selectProps: { value, getOptionLabel }
  } = props;
  const label = useMemo(() => {
    if (!value) {
      return "";
    }
    return getOptionLabel(value);
  }, [getOptionLabel, value]);
  const v = useMemo(() => {
    if (!inputValue) {
      return label;
    }
    return inputValue;
  }, [inputValue, label]);
  const hidden = useMemo(() => {
    if (v) {
      return false;
    }
    return isHidden;
  }, [isHidden, v]);
  return <cs.Input isHidden={hidden} value={v} {...props} />;
};

const components = {
  ...cs,
  Input: NewInput,
  SingleValue: NewSingleValue
};

const CreatableSingle = props => {
  const [value, setValue] = useState(null);
  const handleInputChange = useCallback((inputValue, actionMeta) => {
    console.group("Input Changed");
    console.log(inputValue);
    console.log(`action: ${actionMeta.action}`);
    console.groupEnd();
  }, []);
  const handleChange = useCallback((value, actionMeta) => {
    console.group("Value Changed");
    console.log(value);
    console.log(`action: ${actionMeta.action}`);
    console.groupEnd();
    setValue(value);
  }, []);
  return (
    <CreatableSelect
      components={components}
      isClearable
      onChange={handleChange}
      onInputChange={handleInputChange}
      options={colourOptions}
      value={value}
    />
  );
};

export default CreatableSingle;
```

https://codesandbox.io/s/unr3u

Should work for AsyncCreatable too.

**Comment by ebonow** [comment] 2020-12-04 16:30
Here is my [take at an editable Select.](https://codesandbox.io/s/react-select-editable-and-selectable-6nfdv)

It's not AsyncCreatable, but should work the same way.

``` JS 
import React, { useState, useRef } from "react";
import Select, { components } from "react-select";

const Input = (props) => <components.Input {...props} isHidden={false} />;

export default function EditableSelect() {
  // This needs to become a controlled component so track state
  const [value, setValue] = useState();
  const [inputValue, setInputValue] = useState("");

  const options = useRef([
    { label: "Editable Options", value: 1 },
    { label: "Black Magic", value: 2 },
    { label: "Very Possible ", value: 3 }
  ]).current;

  const selectRef = useRef();

  const onInputChange = (inputValue, { action }) => {
    // onBlur => setInputValue to last selected value
    if (action === "input-blur") {
      setInputValue(value ? value.label : "");
    }

    // onInputChange => update inputValue
    else if (action === "input-change") {
      setInputValue(inputValue);
    }
  };

  const onChange = (option) => {
    setValue(option);
    setInputValue(option ? option.label : "");
  };

  const onFocus = () => value && selectRef.current.select.inputRef.select();

  return (
    <div style={{ fontFamily: "sans-serif", textAlign: "center" }}>
      <Select
        ref={selectRef}
        options={options}
        isClearable={true}
        value={value}
        inputValue={inputValue}
        onInputChange={onInputChange}
        onChange={onChange}
        onFocus={onFocus}
        controlShouldRenderValue={false}
        components={{
          Input
        }}
      />

      <button onClick={onFocus} disabled={!value} style={{ margin: "1rem 0" }}>
        Hocus Focus!
      </button>
    </div>
  );
}
```

**Comment by ebonow** [comment] 2020-12-04 16:33
@cention-sany just a heads up that there is a prop called `controlShouldRenderValue` that essentially does the same thing by not rendering the single or multi value component.

**Comment by ebonow** [comment] 2020-12-04 16:37
That all said, this thread is very similar to many others and I have created a [discussion here](https://github.com/JedWatson/react-select/discussions/4302) to better discuss the behavior and perhaps what a prop implementation might look like.

I will close this issue and further discussion about this behavior can be had in the provided link.

**Closed by ebonow** 2020-12-04 16:37 UTC
Labels: category/question, issue/reviewed

**Comment by Gian-Marco-27** [comment] 2023-03-20 11:39
> Here is my [take at an editable Select.](https://codesandbox.io/s/react-select-editable-and-selectable-6nfdv)
> 
> It's not AsyncCreatable, but should work the same way.
> 
> ```js
> import React, { useState, useRef } from "react";
> import Select, { components } from "react-select";
> 
> const Input = (props) => <components.Input {...props} isHidden={false} />;
> 
> export default function EditableSelect() {
>   // This needs to become a controlled component so track state
>   const [value, setValue] = useState();
>   const [inputValue, setInputValue] = useState("");
> 
>   const options = useRef([
>     { label: "Editable Options", value: 1 },
>     { label: "Black Magic", value: 2 },
>     { label: "Very Possible ", value: 3 }
>   ]).current;
> 
>   const selectRef = useRef();
> 
>   const onInputChange = (inputValue, { action }) => {
>     // onBlur => setInputValue to last selected value
>     if (action === "input-blur") {
>       setInputValue(value ? value.label : "");
>     }
> 
>     // onInputChange => update inputValue
>     else if (action === "input-change") {
>       setInputValue(inputValue);
>     }
>   };
> 
>   const onChange = (option) => {
>     setValue(option);
>     setInputValue(option ? option.label : "");
>   };
> 
>   const onFocus = () => value && selectRef.current.select.inputRef.select();
> 
>   return (
>     <div style={{ fontFamily: "sans-serif", textAlign: "center" }}>
>       <Select
>         ref={selectRef}
>         options={options}
>         isClearable={true}
>         value={value}
>         inputValue={inputValue}
>         onInputChange={onInputChange}
>         onChange={onChange}
>         onFocus={onFocus}
>         controlShouldRenderValue={false}
>         components={{
>           Input
>         }}
>       />
> 
>       <button onClick={onFocus} disabled={!value} style={{ margin: "1rem 0" }}>
>         Hocus Focus!
>       </button>
>     </div>
>   );
> }
> ```

``` typescript
// onInputChange => update inputValue
if (action === 'input-change') {
  setInputValue(inputValue);
  if (inputValue.trim().length == 0 && value) {
    selectRef.current.commonProps.clearValue();
  }
}
```

**Comment by dkrefta** [comment] 2023-11-08 23:23
@Gian-Marco-27 cool man, that was exactly what I was searching for, thanks!
