### ISSUE TITLE
customize messages for accessibility

### ISSUE THREAD

**Issue by guido-warken** [JedWatson/react-select#3691] opened 2019-07-24 14:42 UTC
### new suggestion of accessibility feature
Hi, i am Guido. 
I'm a brazilian developer, and i'm working into a corporate project.
In our company, we've a framework based on react, and we are using react-select on it.
My task is to improve accessibility in our components, and at this moment i am trying to customize the accessibility messages of the select component, but i did not find any feature witch gives possibility to, for example, change the accessibility messages language.
When i press the down arrow to open the select's dropdown menu, my screen reader reads, for example, the following message:
>   option guido focused, 1 of 4. 4 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
![select with 4 options](https://user-images.githubusercontent.com/13587440/61796430-c54c0180-adfb-11e9-8353-515768d886f6.png)

For development and testing, i'm using the NVDA Screen reader. 
This accessibility message don't appears on the screen, but the screen reader can read it.

### suggestion

It would be a good idea to implement something where you can make accessibility messages more flexible. For example, it would be interesting to make possible the switching of its language, from english to any other.
Thanks!

**Comment by ebonow** [comment] 2020-12-12 06:03
Greetings, 
Thank you for reporting this and your patience. It is on our radar and I believe this is a duplicate of #3352 and additionally will be resolved by https://github.com/JedWatson/react-select/pull/4161

Closing this as a duplicate and addressing with the cited issue and PR. Thank you for reporting this and feel free to follow either the issue or PR for updates.

**Closed by ebonow** 2020-12-12 06:03 UTC
Labels: category/accessibility, issue/enhancement, issue/reviewed
