### ISSUE TITLE
Search functionality does not work like standard system dropdowns

### ISSUE THREAD

**Issue by jonrandy** [JedWatson/react-select#4834] opened 2021-10-04 04:09 UTC
Is it possible to set up the select in such a way that the searching behaviour works like a normal select box? i.e. start to type when focused on the box and it will select the first item matching what you typed - WITHOUT actually showing what you typed, and the 'typed' search effectively clears after a second or so - so you can start a new search.

I like the way react-select looks - I just don't like that it does not 'out of the box' have the expected behaviour of a select element.

I could code it to work like this, but this is standard functionality that I would expect to just work

**Comment by Rall3n** [comment] 2021-10-04 08:11
Hello @jonrandy,

this would be an expected behavior for the default `<select>` element or a [`listbox` pattern](https://www.w3.org/TR/wai-aria-practices/#Listbox).
However, the `Select` component (as well as all of its variations) is designed more like a [`combox box` pattern](https://www.w3.org/TR/wai-aria-practices/#combobox), which does not define the described/expected interaction.

But this does not hinder you to implement it yourself with the customization options provided by the `Select` component.

**Comment by jonrandy** [comment] 2021-10-04 08:15
So, `react-combo` would probably have been a better choice of name since it isn't actually modelled after a `select` box?

**Comment by ebonow** [comment] 2021-10-04 16:18
> So, `react-combo` would probably have been a better choice of name since it isn't actually modelled after a `select` box?

Maybe? 

The `react-combobox` repo is over 7 yrs old so maybe it was already taken and `react-combo` is 5 years old but I would also say that it is less descriptive. Of the 3 names, `react-select` certainly seems the catchiest. ¯\_(ツ)_/¯

Did you have further questions about implementation @jonrandy ? If you do put this together, I would be interested in sharing it with the community so that other users can make use of it.

**Comment by jonrandy** [comment] 2021-10-04 16:21
Not sure I have the time right now, but will certainly let you know if I do
it 👍

**Comment by ebonow** [comment] 2021-10-09 23:24
@jonrandy I decided to take a stab at recreating a native html select behavior by keeping all the options in the list but focusing and setting the option as the input matches the typed input.

Here is a first draft of it.
 
[Codesandbox example: 
](https://codesandbox.io/s/react-select-native-focus-on-typed-option-show-all-options-wn9d2?file=/src/App.js)

```jsx
import { useCallback, useRef, useState } from "react";
import Select, { components, createFilter } from "react-select";
import { compliments } from "../data/options";

const App = () => {
  const selectRef = useRef();

  const [value, setValue] = useState();
  const [inputValue, setInputValue] = useState();

  const filterOptions = useCallback(() => true, []);

  const onChange = useCallback((option) => setValue(option), []);

  const onInputChange = useCallback((inputValue, { action }) => {
    //onBlur => clear inputValue so singleValue can render
    if (action === "input-blur" || action === "menu-close") {
      setInputValue("");
    }

    if (action === "input-change") {
      setInputValue(inputValue);

      // Use built-in filtering to find first matching option
      const firstMatchFilter = createFilter({ matchFrom: "start" });
      const firstMatch = compliments.find((opt) =>
        firstMatchFilter({ ...opt, data: {} }, inputValue)
      );

      // If a match is found, update the internal ref to set the focusedOption and scroll to it
      if (firstMatch) {
        setValue(firstMatch);
        selectRef.current.scrollToFocusedOptionOnUpdate = true;
        selectRef.current.setState({ focusedOption: firstMatch });
      }
    }
  }, []);

  return (
    <>
      <div>
        Recreating HTML Select by setting value and scrolling while typing
      </div>
      <br />
      <Select
        filterOption={filterOptions}
        placeholder="How are you feeling today?"
        options={compliments}
        onChange={onChange}
        onInputChange={onInputChange}
        inputValue={inputValue}
        inputId="yo"
        value={value}
        ref={selectRef}
      />
    </>
  );
};

export default App;

```

This should be a good first draft to get going. I would love to see much easier functionality regarding the ability to set focused options without all of the internal method hackery, but I suppose that's a discussion for another day. 

Given that this behavior does seem to at least be possible without any other changes to the library and given that it's unlikely that the name of this library will change anytime soon, I think it should be safe to close this issue, but feel free to still reply or contribute here and at worst case this issue can always be reopened.

**Closed** 2021-10-09 23:24 UTC
Labels: awaiting-author-response

**Comment by cpmsmith** [comment] 2022-02-04 22:26
This may have changed since last discussed, but at least as of now, The WAI-ARIA best practices do mention this style of keyboard interaction on non-editable comboboxes, though it's optional:

> - Printable Characters:
>   - If the combobox is not editable, optionally moves focus to a value that starts with the typed characters.
https://www.w3.org/TR/wai-aria-practices/#combobox-keyboard-interaction
