### ISSUE TITLE
How to specify labelkey and valuekey in version 2.1.1

### ISSUE THREAD

**Issue by akprgm** [JedWatson/react-select#3146] opened 2018-10-25 11:37 UTC
I updated package to 2.1.1 from 1.*, after that lablekey and valuekey stopped working.

**Comment by cutterbl** [comment] 2018-10-25 12:06
You forgot to actually ask your question (which should really go to StackOverflow in this scenario), but:

```
import React, {Component} from 'react';
import Select from 'react-select';

class MySelect extends Component {
  getOptionValue = (option) => option.id;

  getOptionLabel = (option) => option.name;

  render() {
    const { options, placeholder } = this.props;
    return (
      <Select
        getOptionValue={this.getOptionValue}
        getOptionLabel={this.getOptionLabel}
        options={options}
        placeholder={placeholder}
      />
    );
  }
}
```

**Comment by cutterbl** [comment] 2018-10-26 18:39
Here's a [codesandbox example](https://codesandbox.io/s/zx45kql9q4).

**Comment by AntonOellerer** [comment] 2018-10-29 17:03
Hey, I tried this but for me it does not work, description as follows:
```jsx
<Select
  options={this.state.organisations}
  getOptionLabel={opt => opt.name}
  getOptionValue={opt => opt.organisationId}
  onChange={this.handleOrganisationChange}
  />
```
This does not work for me, the data is loaded into the select, I can print it in the `onChange` but the rows are just whitespace.
When I modify the dataset after receiving it like this, everything works as is should:
```javascript
var i;
for(i = 0; i < response.data.content.length; i++) {
  organisations[i].label = organisations[i]['name'];
  organisations[i].value = organisations[i]['organisationId'];
}
```
Additional info:
* I am loading the data from a server
* The first few names are just "" due to them being alphabetically on the top and whitespace being allowed
* I tried setting a `organisationsLoaded` flag and only opening `Select` when the data finished loading, but it changed nothing
* If I have the two solutions implemented at the same time, it works, so from what I am guessing there is something wrong with the `getOptionValue` and the `getOptionLabel`

Did I do something wrong or might there be a problem in the library?

I hope what I wrote is understandable, thank you for the great work 
Regards
Anton

**Comment by cutterbl** [comment] 2018-10-29 18:17
In your example, if `this.state.organizations` is an array of options `{name: 'foo', organizationId: 6}`, and you have your select setup

```
<Select options={this.state.organizations}
              getOptionLabel={(opt) => opt.name}
              getOptionValue={(opt) => opt.organizationId} />
```
Then it should work fine. If you're using the AsyncSelect with the `loadOptions` prop for doing your external request, it changes only slightly

```
import React, { Component } from 'react';
import AsyncSelect from 'react-select/libs/Async';

export default MySelect extends Component {
  getOptions = (inputValue) => {
    return fetch(`${myurl}?myparam=${inputValue}`)
      .then(response => {
        // do you have to `parse`? I don't remember...
        if (response && response.data && response.data.content) {
          return response.data.content; // this is the options array?
        }
        return [];
      })
      .catch(error => {
        // whoops! what now?
      });
  };

  render() {
    return (
      <AsyncSelect defaultOptions={true}
        loadOptions={this.getOptions}
        getOptionLabel={(opt) => opt.name}
        getOptionValue={(opt) => opt.organizationId} />
    );
  }
}
```

**Comment by AntonPuko** [comment] 2018-10-29 19:19
@cutterbl Hi, is in your codesandbox, `getOptionValue` actually doing something?

If I understand correctly what this should do, it changes the value which should be returned from `onChange` callback.

If we I make the select controllable and logging the value, it still returns the full object instead of id.
https://codesandbox.io/s/l7pzz83k8q

is this a lib bug, or I just don't understand something?

**Comment by cutterbl** [comment] 2018-10-29 19:22
No, getOptionValue and getOptionLabel are used to map your options array object's keys to a 'value' and a 'label'. Rarely will a client-side dev have access to adjust the remote api to control these objects, so this allows you to say "this object key is the 'value', and this object key is the 'label'. `onChange` always returns your selected object (that's the way it works).

**Comment by AntonPuko** [comment] 2018-10-29 19:48
thanks. thats pretty controversial though that onChange returns an option, not value :/

**Comment by cutterbl** [comment] 2018-10-29 20:53
It is. If you add the `id` prop, it creates a hidden input with that `id`, whose value will get set to the `value` that you mapped through `getOptionValue`.

**Comment by AntonPuko** [comment] 2018-10-30 09:06
hm... interesting, I potentially can build a hacky trick around it to achieve what I need. But i don't see any hidden inputs there:
![image](https://user-images.githubusercontent.com/8849922/47707142-bb61ed00-dc33-11e8-9441-f34a012feaf7.png)

**Comment by cutterbl** [comment] 2018-10-30 11:13
Sorry, had it kinda backwards. It's when you put a `name` prop on the Select.
![screen shot 2018-10-30 at 6 12 43 am](https://user-images.githubusercontent.com/666987/47714431-dec47200-dc0a-11e8-98a1-36a9e9bcdf84.png)

**Comment by AntonOellerer** [comment] 2018-10-30 14:17
> Thanks, though I'm just a user who answers questions I've already figured out on my own. The other guys do the heavy lifting :)
> 
> In your example, if `this.state.organizations` is an array of options `{name: 'foo', organizationId: 6}`, and you have your select setup
> 
> ```
> <Select options={this.state.organizations}
>               getOptionLabel={(opt) => opt.name}
>               getOptionValue={(opt) => opt.organizationId} />
> ```
> 
> Then it should work fine. If you're using the AsyncSelect with the `loadOptions` prop for doing your external request, it changes only slightly
> 
> ```
> import React, { Component } from 'react';
> import AsyncSelect from 'react-select/libs/Async';
> 
> export default MySelect extends Component {
>   getOptions = (inputValue) => {
>     return fetch(`${myurl}?myparam=${inputValue}`)
>       .then(response => {
>         // do you have to `parse`? I don't remember...
>         if (response && response.data && response.data.content) {
>           return response.data.content; // this is the options array?
>         }
>         return [];
>       })
>       .catch(error => {
>         // whoops! what now?
>       });
>   };
> 
>   render() {
>     return (
>       <AsyncSelect defaultOptions={true}
>         loadOptions={this.getOptions}
>         getOptionLabel={(opt) => opt.name}
>         getOptionValue={(opt) => opt.organizationId} />
>     );
>   }
> }
> ```

The non async thing is what I tried and it did not work, but I will take another look at it when I'm back at work, thank you

**Comment by AntonOellerer** [comment] 2018-11-05 09:04
Hey, so i tried it again the way you suggested, and the problem still persist.
If I log the info about the selected organisation in an `onChange` method, I can see that the organisation got selected, but the list of the organisations is just white and the blue row does not move.
![captura de pantalla de 2018-11-05 10-03-29](https://user-images.githubusercontent.com/13524304/47988248-125b3c80-e0e2-11e8-86d4-fc1301e80816.png)

**Comment by cutterbl** [comment] 2018-11-05 14:10
Honestly can't say, without seeing your code and a sample of your loadOptions return.

**Comment by gwyneplaine** [comment] 2018-12-28 03:20
Thanks @cutterbl  for jumping on this, closing this issue, @AntonOellerer if your problem still persists, please create a new issue with a codesandbox reproduction so that we can more easily triage the problem.

**Closed by gwyneplaine** 2018-12-28 03:20 UTC

**Comment by czsyjss** [comment] 2019-08-30 14:11
Please check if you're using the latest version of react-select
The issue may be caused by react-select v1


> Hey, so i tried it again the way you suggested, and the problem still persist.
> If I log the info about the selected organisation in an `onChange` method, I can see that the organisation got selected, but the list of the organisations is just white and the blue row does not move.
> ![captura de pantalla de 2018-11-05 10-03-29](https://user-images.githubusercontent.com/13524304/47988248-125b3c80-e0e2-11e8-86d4-fc1301e80816.png)
