### ISSUE TITLE
Server rendering support

### ISSUE THREAD

**Issue by davegomez** [JedWatson/react-select#1726] opened 2017-05-16 15:13 UTC
I'm using the library in a [next.js](https://github.com/zeit/next.js/) project for server rendering and I'm getting some warnings when using React Select.

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This
generally means that you are using server rendering and the markup generated on the server was 
not what the client was expecting. React injected new markup to compensate which works but you 
have lost many of the benefits of server rendering. Instead, figure out why the markup being 
generated is different on the client or server:
 (client) " id="react-select-2--value" data-reacti
 (server) " id="react-select-24--value" data-react
```

Since I don't know the library code can't figure out how difficult this would be or if is possible at all, but it would be great to have support for this kind server rendered applications.

**Comment by schnerd** [comment] 2017-05-16 17:15
Dupe of See #1297, #1120, #1325

@davegomez consider closing?

**Closed** 2017-05-16 17:20 UTC
