### ISSUE TITLE
Microsoft Edge / IE11 Focused Fields

### ISSUE THREAD

**Issue by hnordt** [JedWatson/react-select#649] opened 2015-12-04 16:45 UTC
Hello.

I'm using React Select `v1.0.0-beta6`.

In IE11 and:

![captura_de_tela_120415_024412_pm](https://cloud.githubusercontent.com/assets/1625399/11595220/7c95e104-9a95-11e5-8d35-f72be5031e0b.jpg)

When I selected a value, looks like field always stay focused:

![captura_de_tela_120415_024505_pm](https://cloud.githubusercontent.com/assets/1625399/11595247/9c8085e6-9a95-11e5-95ce-d489db48bc44.jpg)

The problem is that in Microsoft Edge / IE11 the onBlur event doesnt dispatches.

**Comment by cloudkite** [comment] 2015-12-13 22:12
@hnordt most likely related to https://github.com/JedWatson/react-select/pull/661

**Comment by JedWatson** [comment] 2015-12-14 11:12
I really need to get a Windows machine :grimacing:

Can anyone confirm what's going on between this issue and #661?

**Comment by gaastonsr** [comment] 2015-12-14 16:54
I just verified and #661 fixes this.

The problem is when the blur handler is called on IE it fails because isEqualNode expects a DOM node and it receives an undefined/null object. Which in modern browsers instead of fail it returns false.

**Comment by JedWatson** [comment] 2015-12-15 12:12
Fixed by #661

**Closed by JedWatson** 2015-12-15 12:12 UTC
