### ISSUE TITLE
The NumericSelect.js demo file is broken when selecting the multi-select checkbox

### ISSUE THREAD

**Issue by elkarouh** [JedWatson/react-select#1810] opened 2017-06-22 08:53 UTC
### Thanks for using react-select!

If you are reporting an error please include a test case that demonstrates the issue you're reporting!
This is very helpful to maintainers in order to help us see the issue you're seeing.

Here is a Plunker you can fork that has react-select loaded and supports JSX syntax:
https://plnkr.co/edit/HTmtER9AMNcPoWhXV707?p=preview

You may also find the [online Babel tool](https://babeljs.io/repl/) quite helpful if you wish to use ES6/ES7 syntax not yet supported by the browser you are using.

**Comment by agirton** [comment] 2017-06-22 17:01
Hi @elkarouh thank you for reporting. I can confirm this is in fact broken. Would you like to submit a PR to fix it? :smile:

**Comment by elkarouh** [comment] 2017-06-23 06:01
Hi,

I am in the learning phase. I don't know how i would fix it. I don't even
know what a PR is ! Sorry not being able to help.

**Comment by agirton** [comment] 2017-06-23 17:03
Oh ok, no problem! Would you like some guidance on where to look to fix it?

**Comment by ericliu121187** [comment] 2017-06-23 18:29
Hi @agirton I am looking to contribute to open-source and wouldn't minding taking a look.

It seems like I need to fix something in [NumericSelect.js](https://github.com/JedWatson/react-select/blob/master/examples/src/components/NumericSelect.js).

Do you mind if I submit a PR?

**Comment by agirton** [comment] 2017-06-23 19:01
Hi @ericliu121187 that would be great! It's possible there is an underlying issue with the combination the example uses: simpleValue, multi select and numbers. I will remove the help wanted label since you would like to take this on.

**Comment by ericliu121187** [comment] 2017-06-25 23:53
Yup! In `NumericSelect.js`, I updated line 42 to:

```javascript
onChange(value) {
  this.setState({
    value: value.split(',').map(Number)
  });
console.log('Numeric Select value changed to', value);
},
```

Some questions:

1. I don't have permission to push to `origin`. How should I proceed?
1. Is there a particular branch naming convention and PR template that you would prefer?
1. It seems like there is no test for this file, right? Should I make one?
1. Also, `example/dist/app.js` keeps getting updated as well. Should that folder be included in the `.gitignore`?
1. The build does not work with node v.8. I'm not exactly sure what is the most recent non-breaking version the build supports, but it might be worthwhile to mention in the README.md.

**Comment by audiolion** [comment] 2017-06-27 15:03
@ericliu121187 see https://github.com/JedWatson/react-select/blob/master/CONTRIBUTING.md

**Comment by agirton** [comment] 2017-06-27 20:41
Hi @ericliu121187 if the NumericSelect has this issue. It's very possible that there is an underlying issue. 

It looks there is a PR with a fix for this #1600. Also found a duplicate issue #1476. So going to close out this in favor of that ticket.

My apologies for not finding this sooner and wasting your time 😞 .

**Closed by agirton** 2017-06-27 20:41 UTC
Labels: bug blocker

**Comment by ericliu121187** [comment] 2017-06-27 20:54
@agirton There doesn't seem to be any underlying issue. It's just that `simpleValue` returns a string and select expects an array when `multiValue` is selected.

No problem! Is there another issue I can help with?

@audiolion Ah, thanks!

**Comment by agirton** [comment] 2017-06-27 21:01
@ericliu121187 we have quite a long list of issues 😄 . At this time nothing stands out to me as good intro tickets. But feel free to go through the list and see if there are any issues that might be easy to take on that don't already have a PR open.
