### ISSUE TITLE
async options lose index when input is removed from list of inputs

### ISSUE THREAD

**Issue by alvamanu** [JedWatson/react-select#5027] opened 2022-01-27 19:45 UTC
On a list of react select asyncs of three, for example, you have three different values selected. Let's say for index 0 you have Orange, for index 1 you have Purple and for index 2 you have Yellow. if you remove index 1, index 2 SHOULD take its place with its own value, In this case Yellow. However, Index 1 keeps the value (Purple) of the deleted input instead.

https://codesandbox.io/s/codesandboxer-example-forked-sxewf?file=/example.tsx

There must be a way we could give options an index. The issue is loadOptions is a function.

**Comment by Rall3n** [comment] 2022-01-27 20:32
Hello @alvamanu,

this is not a problem with `react-select` or its components.
The problem is you using indexes as keys. React thinks the component on index `1` never changed because the key never changed.

Keys help React identify which items have been added, removed or changed. Indexes are not recommended as keys because they are not unique enough. They can't properly convey that something changed.

I recommend reading up on [Lists and keys in React](https://reactjs.org/docs/lists-and-keys.html).

-----
I'll close this issue as it being not an issue with the library.

**Closed by Rall3n** 2022-01-27 20:32 UTC
Labels: issue/bug-unconfirmed

**Comment by alvamanu** [comment] 2022-01-27 20:35
Yeah, Already tried keys with uuid. Thanks anyway
