### ISSUE TITLE
Should Creatable be mutating its options prop?

### ISSUE THREAD

**Issue by ericchernuka** [JedWatson/react-select#1793] opened 2017-06-16 17:51 UTC
Mostly a question on the rationale for Creatable mutating the options prop when a new tag is added, but a `onNewOptionClick` is not defined.  Currently on the examples site the options from state are directly mutated which seems like a bad idea.

The code below from Creatable (https://github.com/JedWatson/react-select/blob/master/src/Creatable.js#L95) shows the mutation:
```
if (isOptionUnique) {
	if (onNewOptionClick) {
		onNewOptionClick(option);
	} else {
		options.unshift(option);

		this.select.selectValue(option);
	}
}
```

Was this intentional or was it for those using things like MobX?

**Comment by agirton** [comment] 2017-06-19 05:14
Hi @ericchernuka this is a duplicate of #1477 you can follow the discussion there.

**Closed by agirton** 2017-06-19 05:14 UTC
