### ISSUE TITLE
Warning: Prop `className` did not match. Server: "css-7pg0cj-a11yText" Client: "css-1f43avz-a11yText-A11yText"

### ISSUE THREAD

**Issue by agawley** [JedWatson/react-select#4706] opened 2021-08-02 18:06 UTC
Hi folks

I am getting this error on any page that has a react-select element on it that is rendered server-side. Repro repository is here: https://github.com/agawley/loadable-repro

Any thoughts on how to get SSR and client side to match up in this case?

Thanks.

**Comment by sdenardi** [comment] 2021-09-10 01:56
Also started getting this warning recently.

**Comment by Methuselah96** [comment] 2021-09-10 16:01
Thanks, just to keep the issue centralized I'm going to close this in favor of https://github.com/JedWatson/react-select/issues/3590 since it seems likely it's the same underlying issue.

**Comment by Methuselah96** [comment] 2021-09-11 21:35
@agawley @sdenardi What browser are you seeing this warning on? Is it Safari and only Safari?

**Comment by sdenardi** [comment] 2021-09-13 13:11
I'm seeing this on the latest version of Chrome on MacOS.

**Comment by Methuselah96** [comment] 2021-09-13 13:22
@sdenardi Sounds like you have a different issue than most people. The known bug only exists on Safari.

1. Can you try out https://codesandbox.io/s/react-ssr-bug-hfp29?file=/src/components/App.jsx and see if you get a console error?
2. Can you create a CodeSandbox that reproduces the issue on Chrome?

**Comment by Methuselah96** [comment] 2021-09-13 13:23
@agawley Your warning might be due to something different as well. Do you only get the warning on Safari or do you get the warning on other browsers as well?

**Comment by sdenardi** [comment] 2021-09-21 04:54
> @sdenardi Sounds like you have a different issue than most people. The known bug only exists on Safari.
> 
> 1. Can you try out https://codesandbox.io/s/react-ssr-bug-hfp29?file=/src/components/App.jsx and see if you get a console error?
> 2. Can you create a CodeSandbox that reproduces the issue on Chrome?

@Methuselah96 Thank you for the reply and for the CodeSandbox. We were able to identify that the issue lies with our build setup. Our Webpack configuration uses multiple entries, and in development we disable `optimization` that would typically create a common `vendor` file.

I can confirm that this issue disappears when we use a `vendor` file. I imagine the problem lies with the fact that we were `importing` `react-select` (and `emotion`) multiple times, but I can't confirm.

**Comment by agawley** [comment] 2021-09-27 08:37
> @agawley Your warning might be due to something different as well. Do you only get the warning on Safari or do you get the warning on other browsers as well?

I get it on Chrome and Safari.

**Comment by Methuselah96** [comment] 2021-09-27 13:53
Got it, it would be great if you could find a way to reproduce it either in a CodeSandbox or public repo.

**Comment by agawley** [comment] 2021-09-28 08:40
How's this:

`git clone https://github.com/agawley/loadable-repro
npm install
npm run offline`

**Comment by Methuselah96** [comment] 2021-09-28 13:35
🤦 Yes, indeed, I even already had it cloned on my computer, just forgot which thread I was in. Thanks for the repro, I'll take a look when I get a chance.

**Comment by agawley** [comment] 2021-09-28 13:41
`git pull` before you do as I simplified it a bit. Thanks!

**Comment by elrumordelaluz** [comment] 2022-05-16 10:28
I started to note this issue upgrading to `react@18` on a NextJS project, is this possible?

**Comment by gunnartorfis** [comment] 2022-05-31 20:33
@elrumordelaluz  Happening for me on a Remix project at React 17.

**Comment by NedelinaN** [comment] 2022-10-06 10:08
I get this warning on the latest version of Chrome on MacOS at react 18.2

**Comment by martinmckenna** [comment] 2022-11-06 23:33
any update here?

**Comment by EvgeniyBudaev** [comment] 2022-12-11 16:05
**Fix in Remix.js**

```python
import { useHydrated } from 'remix-utils'; 
const isHydrated = useHydrated();  
isHydrated ? <Select /> : null;  
```


**Fix in Next.js and React.js**

```python
import { useEffect, useState } from "react";

export const useMounted = (): { hasMounted: boolean } => {
  const [hasMounted, setHasMounted] = useState(false);
  useEffect(() => {
    setHasMounted(true);
  }, []);
  return { hasMounted };
};

const { hasMounted } = useMounted();

hasMounted ? <Select /> : null;
```

**Comment by phifa** [comment] 2022-12-22 11:30
@EvgeniyBudaev the thing is, this causes a layout shift. Is it not possible to server side render react-select?

**Comment by Rall3n** [comment] 2022-12-23 02:31
Issue is caused by mismatched environments between client and server.

Repro repo from @agawley had frontend built in development mode, but server ran in production.

One major indicator for this is the added label (e.g. `...-A11yText`) at the end of the client classes. This is part of the `autoLabel` feature in `@emotion` which adds component names at the end of classes. By default these are only added in **development** mode.

**Always make sure that server and client run builds in the same environment.**

**Comment by agawley** [comment] 2022-12-23 20:12
Thank you for taking this down. Appreciated.

**Closed** 2022-12-23 20:13 UTC
Labels: issue/bug-unconfirmed

**Comment by giovannefc** [comment] 2023-03-25 13:11
> **Fix in Remix.js**
> 
> ```python
> import { useHydrated } from 'remix-utils'; 
> const isHydrated = useHydrated();  
> isHydrated ? <Select /> : null;  
> ```
> 
> **Fix in Next.js and React.js**
> 
> ```python
> import { useEffect, useState } from "react";
> 
> export const useMounted = (): { hasMounted: boolean } => {
>   const [hasMounted, setHasMounted] = useState(false);
>   useEffect(() => {
>     setHasMounted(true);
>   }, []);
>   return { hasMounted };
> };
> 
> const { hasMounted } = useMounted();
> 
> hasMounted ? <Select /> : null;
> ```

That's worked! Thank you.
