### ISSUE TITLE
optgroups

### ISSUE THREAD

**Issue by kopancek** [JedWatson/react-select#59] opened 2015-02-06 14:50 UTC
Is there a way of having option groups, like the standard [optgroup](http://www.w3schools.com/tags/tag_optgroup.asp) element in html select?

**Comment by piecyk** [comment] 2015-03-25 17:37
I want to help with this future... i was thinking going with simple structure

```js
var options = [{
            label: "Group 1",
            children: [{
                value: "one",
                lable: "One"
            }, {
                value: "two",
                lable: "Two"
            }];
```
is someone started to work on that?

**Comment by acthp** [comment] 2015-03-31 03:55
I also need this, immediately. Is there work in progress, or should I fork?

**Comment by Venkatrao727** [comment] 2015-04-02 05:23
+1

**Comment by TSMMark** [comment] 2015-04-02 16:19
+1

Anyone working on this?

**Comment by whather** [comment] 2015-04-15 18:25
I also would love this. Planning on switching from Selectize.js (which has optgroup support) to this, but would need this functionality first.

**Comment by rick-li** [comment] 2015-04-27 13:36
+1

**Comment by guillaumepiot** [comment] 2015-05-04 01:22
+1

**Comment by dcousens** [comment] 2015-05-07 04:50
We're accepting PRs,  so don't feel bad if you beat @jossmac to it.  It currently isn't on the hit list.

**Comment by jossmac** [comment] 2015-05-07 05:01
I'm working almost exclusively on http://elemental-ui.com for the foreseeable future, so I won't be of much help I'm afraid. Incidentally, I've implemented a dropdown over there that may be of interest using the following pattern:
```
var dropdownOptions = [
  { type: 'item', value: 'action', label: 'Action' },
  { type: 'item', value: 'another-action', label: 'Another action' },
  { type: 'item', value: 'something-else-here', label: 'Something else here' },
  { type: 'divider' },
  { type: 'header', label: 'Dropdown header' },
  { type: 'item', value: 'separated-link', label: 'Separated action' },
];
```
More here: https://github.com/elementalui/elemental/blob/master/src/components/Dropdown.js

**Comment by nextminds** [comment] 2015-05-07 14:25
+1

**Comment by zenjyn** [comment] 2015-06-15 19:01
@JedWatson I'm currently working on this for a project. How would you like this implemented? The interface we need is a variation on the selectize structure, but I can handle that in a wrapper class if you prefer something different:

options: [
	{optgroup: 'Things', value: "thing1", label: "Thing 1" },
	{optgroup: 'Things', value: "thing2", label: "Thing 2" },
	{optgroup: 'Things', value: "thing3", label: "Thing 3" },
	{optgroup: 'Stuffs', value: "stuff1", label: "Stuff 1" },
	{optgroup: 'Piles', value: "pile1", label: "Pile 1" },
	{value: "pile1", label: "Pile 1" }
],
optgroups: [
	{position: 1, label: 'Things'},
	{position: 2: label: 'Stuffs'}
],

Options with an optgroup not in the optgroup set are ignored. Options without an optgroup are listed last.

**Comment by piecyk** [comment] 2015-06-15 19:29
@zenjyn :+1: great if you working on public branch i can help with something ( would love to see this merged... and `kill select2` at my project   

what do you think about something like this ? then you can sort the whole `options` array by label (if we have `values` the render it as `optgroup` ) 
```
options: [
  {
    label: "Thing 1a",
    //value: "allThings1a" then in future we can also add selecting the whole group
    values: [
      {
        value: "thing1a", label: "Thing 1a"
      },
      {
        value: "thing2a", label: "Thing 2a" 
      }
    ]
  },
  {
    label: "Thing 2b",
    values: [
      {
        value: "thing1b", label: "Thing 1b"
      },
      {
        value: "thing2b", label: "Thing 2b" 
      }
    ]
  },
  {
    label: "Thing 3c",
    value: "thing3c"    
  }
];
```

**Comment by zenjyn** [comment] 2015-06-16 15:39
@piecyk I started with something like that on our end but determined that being able to add, remove, reorder the optgroups in their own array was slightly more flexible for our purposes. I'm still open to something more like your nested structure for the PR, however.

As far as group selecting goes, I wasn't planning on getting into that just yet, but we could make a group select flag then just enable a toggleGroup callback to the onClick event for optgroup divs. Thoughts?

**Comment by grydstedt** [comment] 2015-09-10 01:58
+1

**Comment by banderson** [comment] 2015-09-23 20:37
@zenjyn @piecyk any progress on a public branch? I'd be willing to help out too, I need this for a project at work. 

/cc @colbyr

**Comment by zenjyn** [comment] 2015-09-24 00:00
@banderson the optgroup issue for my project was pushed to the backlog almost immediately after I posted on here. I probably won't get to it unless it's still unimplemented by the time the task comes up again. For my project I believe it's on the roadmap 6 months out or so.

**Comment by agrass** [comment] 2015-10-22 21:04
+1

**Comment by tineo** [comment] 2015-10-23 17:42
+1

**Comment by lanceschi** [comment] 2015-11-03 13:50
:+1:

**Comment by thataustin** [comment] 2015-12-09 02:29
Trying to kick this thing up again... 

@piecyk - I like your proposed API, but I would rename `values` to `children`.  I think it's a bit more obvious what the purpose is, and a bit easier to read (ie, harder to misread).  Anyone else fine with that API?  If we get some more feedback on that API, it will be easier to start in on it.

**Comment by piecyk** [comment] 2015-12-09 09:36
@thataustin i agree the `children` is a better name... maybe @JedWatson can share his point of view on this... if this is on road map... there are so many issues and pull request now it's getting hard to follow :+1:  

for now we can make simple crazy and naive wrapper, but should work as expected ;) 

```js
const MyOptions = [
  {
    text: "Group 1",
    children: [{
      id: "one1",
      text: "One1"
    }, {
      id: "two2",
      text: "Two2"
    }]
  },{
    text: "Group 2",
    children: [{
      id: "one2",
      text: "One2"
    }, {
      id: "two2",
      text: "Two22"
    }]
  }
];

function option(value, label, render, disabled = false) {
  return {value, label, render, disabled};
}
const transformOptions = options => _.reduce(options, (res, el) => {
  const parent = option(el.text, el.text, (<strong>{el.text}</strong>), true);
  const children = _.map(el.children, child => _.assign(
    {}, option(child.id, child.text, (<span style={{paddingLeft: 10}}>{child.text}</span>)), {parent: el.text}
  ));

  return res.concat(parent).concat(children);
}, []);

const SelectGroups = React.createClass({
  getInitialState() {
    return {
      value: this.props.value,
      options: transformOptions(this.props.options)
    };
  },
  optionRenderer(option) {
    return option.render;
  },
  onChange(value) {
    this.setState({value});
    this.props.onChange(value);
  },
  filterOptions(options, term, currentValues) {
    if (term === this.prevTerm) {
      return this.prevOptions;
    } else {
      const almostReadyOptions = this.props.filterOptions ? this.props.filterOptions(options, term, currentValues)
      // very naive filter, maybe ref form react-select and re-use the filterOptions ;)
            : _.filter(options, o => o.parent ? _.includes(o.label.toLowerCase(), term.toLowerCase()) : true);
      const optionsGroupByParent = _.groupBy(almostReadyOptions, 'parent');
      // filter empty parents
      const readyOptions = _.filter(almostReadyOptions,
                                    option => option.parent ? option : _.size(optionsGroupByParent[option.value]) > 0);
      this.prevTerm = term;
      this.prevOptions = readyOptions;
      return readyOptions;
    }
  },
  render() {
    return (
      <Select
        {...this.props}
        value={this.state.value}
        onChange={this.onChange}
        optionRenderer={this.optionRenderer}
        options={this.state.options}
        filterOptions={this.filterOptions}
      />
    );
  }
});

// use it 
//<SelectGroups
//  options={MyOptions}
//  onChange={val => console.log(val)}
///>
```

**Comment by mqklin** [comment] 2015-12-26 06:09
Guys, i have a workaround:

    //react-select-groups.scss
    .Select-menu-outer {
      .Select-option {
        padding-left: 2em;
      }
      .Select-option.is-disabled {
        cursor: default;
        padding-left: 1em;
        font-weight: bold;
      }
    }

Then you have to just push disabled values into `options` with labels that are group names:

    //my-component.js
    ...
    let options = [];
    options.push({
      label: "Пользователи",
      value: "someUniqueValue",
      disabled: true
    });
    users.map((user) => {
      options.push({
        label: user.name,
        value: user.id,
      });
    });
    ...


Result:
![123](https://cloud.githubusercontent.com/assets/9456433/12005312/b9b8abac-abc0-11e5-9954-0bab32f087bc.png)

**Comment by thataustin** [comment] 2015-12-26 22:02
@mqklin - Just to make sure I understand correctly...

If I want to use both a grouped select box (like the one you show) and a non-grouped select box (the standard react-select box) on the same page, they would both have options that are indented by `2em`s.  

Is that right?  Or does your css only target grouped options somehow?

**Comment by mqklin** [comment] 2015-12-26 23:34
@thataustin, you can wrap your grouped select box in a special class :

    .myselectbox--grouped {
     .Select-menu-outer {/*my previous code*/}
    }

    <Select className="myselectbox--grouped"/>
    //or <div className="myselectbox--grouped"><Select/><div/>

**Comment by vgoklani** [comment] 2016-01-27 19:01
+1

**Comment by TrevorBurnham** [comment] 2016-03-08 19:45
HubSpot has created a fork with this functionality. We're calling it [React Select Plus](https://github.com/HubSpot/react-select-plus/). Please [give it a try](http://github.hubspot.com/react-select-plus/) and let us know what you think!

**Comment by TSMMark** [comment] 2016-03-08 20:05
@TrevorBurnham <3

**Comment by asazernik** [comment] 2016-03-09 00:38
@TrevorBurnham Be still my beating heart!

**Comment by derekperkins** [comment] 2016-05-06 21:41
@TrevorBurnham Are you going to push that back upstream here?

**Comment by TrevorBurnham** [comment] 2016-05-06 22:33
@derekperkins It's not up to me. I'd certainly be happy to see it merged in.

**Comment by tBaxter** [comment] 2016-07-06 18:29
+1

**Comment by mason505** [comment] 2016-07-13 16:42
+1

**Comment by tslater** [comment] 2016-07-26 14:29
+1

**Comment by srisonti** [comment] 2016-07-28 18:34
+1

**Comment by imperat0r** [comment] 2016-07-29 08:24
+1

**Comment by dingnigefei** [comment] 2016-08-01 07:42
+1

**Comment by gus4no** [comment] 2016-08-05 18:18
+1

**Comment by bion** [comment] 2016-08-17 21:29
+1

**Comment by tqthe** [comment] 2016-08-23 09:43
Any plan for this feature?

**Comment by maswin** [comment] 2016-08-31 17:51
+1

**Comment by themetis** [comment] 2016-10-03 16:13
+1

**Comment by jurgob** [comment] 2016-10-16 12:46
+1

**Comment by manugb** [comment] 2016-10-19 14:45
@JedWatson I think https://github.com/HubSpot/react-select-plus should be merged and @TrevorBurnham could be added as a mantainer of this funcionality

**Comment by yarnball** [comment] 2016-10-27 14:05
This would be an incredibly handy feature if it could look something like this-


![2016-10-28 at 1 04 10 am](https://cloud.githubusercontent.com/assets/13043067/19770210/2b77a812-9caa-11e6-832a-ae6b723e6f0d.jpg)

I found that on this repo here: https://github.com/mvader/react-categorized-tag-input

The main issue with it is: It doesn't "HIDE" a tag once you've added it. Otherwise it's a **game changer**

**Comment by peter-dangelo** [comment] 2016-11-29 14:01
+1

**Comment by rabaut** [comment] 2016-12-13 22:27
+1

**Comment by alexjesp** [comment] 2017-01-10 16:05
+1

**Comment by lomholdt** [comment] 2017-01-18 10:09
+1

**Comment by stivaugoin** [comment] 2017-01-18 20:56
+1

**Comment by ehartford** [comment] 2017-01-27 10:04
I came here from react-chosen, which says it's deprecated and use react-select... but it has groups and react-select doesn't.  no feature parity

**Comment by t1mmen** [comment] 2017-02-03 18:12
@JedWatson @bvaughn or anyone else who is a core contributor/is able to implement & release this feature: I'm offering CAD$100 to whoever gets this done (expires 4 weeks from now)

**Comment by bvaughn** [comment] 2017-02-03 19:23
Hey @t1mmen,

For what it's worth, the [react-virtualized-select](https://github.com/bvaughn/react-virtualized-select/) HOC already supports option groups, albeit with a different input-format than the ones shown above.

Check out the "_Dynamic Height Options_" example [here](https://bvaughn.github.io/react-virtualized-select/) (source [here](https://github.com/bvaughn/react-virtualized-select/blob/9f4a9e60989cfe2e40cac451239cdfb70dd001b5/source/VirtualizedSelect/VirtualizedSelect.example.js#L248-L282), underlying data source [here](https://github.com/bvaughn/react-virtualized-select/blob/master/source/demo/data/names.js)).

You could pretty easily map from the formats above to the format used in my example though, eg
```js
var options = [
  {optgroup: 'Things', value: "thing1", label: "Thing 1" },
  {optgroup: 'Things', value: "thing2", label: "Thing 2" },
  {optgroup: 'Things', value: "thing3", label: "Thing 3" },
  {optgroup: 'Stuffs', value: "stuff1", label: "Stuff 1" },
  {optgroup: 'Piles', value: "pile1", label: "Pile 1" }
];

let currentOptGroup;
options = options.reduce((options, option) => {
  if (option.optgroup !== currentOptGroup) {
    currentOptGroup = option.optgroup;
    options.push({
      value: option.optgroup,
      type: 'header'
    });
  }

  options.push({
    value: option.value,
    type: 'option'
  });

  return options;
}, []);
```

**Comment by piecyk** [comment] 2017-02-04 19:37
Guys, basic you just need to implement 2 function  to get `optgroups` (as many examples was done in previous comments)
 * `optionRenderer`
 * `filterOptions`

I encountered one issue, auto scroll to focused element on open. In my code group header are disabled options, so it will scroll to first option of the group and hide the header, 

so for groups i extend Select and pass filterOptions, optionRenderer (i know... not so nice, but :dancer:) if some has better idea ping me :+1: 
```js
// disable scroll when focused element is in menu height, to don't hide first disable option group label
class Select extends ReactSelect.Select {
  componentDidUpdate(prevProps, prevState) {
    if (this.menu && this.focused && this.state.isOpen) {
      const menuNode = ReactDOM.findDOMNode(this.menu);
      const focusedOptionNode = ReactDOM.findDOMNode(this.focused);
      if (focusedOptionNode.offsetTop + focusedOptionNode.offsetHeight < menuNode.offsetHeight) {
        this.hasScrolledToOption = true;
      }
    }
    return super.componentDidUpdate(prevProps, prevState);
  }
}
```
 
Maybe it will be good idea add group demo to examples @JedWatson ? I can do some PR 
and close this issue then.

**Comment by t1mmen** [comment] 2017-02-08 22:09
@bvaughn Thanks for that! I also know https://github.com/HubSpot/react-select-plus support optgroups.

My bounty is for getting this into the official release of `react-select` so I can rely on the official release instead of worrying about forks getting outdated, etc :)

**Comment by bvaughn** [comment] 2017-02-08 22:14
Fair enough! Although worth pointing out that- unlike [HubSpot/react-select-plus](https://github.com/HubSpot/react-select-plus)- [bvaughn/react-virtualized-select](https://github.com/bvaughn/react-virtualized-select/) is not a _fork_ but a decorator and so is less likely to get outdated. Then again it also pulls in an additional dependency on [bvaughn/react-virtualized](https://github.com/bvaughn/react-virtualized) which helps performance but at the cost of bundle size so...trade-offs.

Getting this functionality into react-select core would probably be convenient. Not sure how difficult to implemented it. Unfortunately I won't have the time...but maybe someone else will. 😄

**Comment by ehartford** [comment] 2017-02-08 23:29
I'll add 100 USD to the bounty

**Comment by JedWatson** [comment] 2017-02-10 01:22
Thanks for the bounty offers @t1mmen and @ehartford! this is the first time anybody has actually offered a financial contribution to _any_ of the open source projects I'm a maintainer of.

I'm happy to pick this up and put some focus on getting proper outgroup support into the official react-select release mainly because I think it's a good thing to encourage 👍 

Will look into how it could be implemented and report back soon - I've been setting some time aside to focus on React Select in the next few days/weeks anyway. Going to start by reviewing the prior art of @piecyk and @TrevorBurnham.

**Comment by t1mmen** [comment] 2017-02-10 19:20
Thank you @JedWatson, I'm excited about being able to return to `react-select` soon :) 

Since you'll be tacking this personally, I'd be happy to transfer my share of the bounty now, just let me know how you'd prefer to take payment (email in profile, or DM @t1mmen on Twitter)

This is in no way a condition for my bounty, but _if_ this fits with your vision, I'd really love if this implementation supported nested optgroups and/or ability to select the group label.

Use case would be something like this:
```
- Tag group
  - Tag 1
  - Tag 2
  - Tag 3
```

Selecting the Tag group would be an efficient way of adding all subtags.

**Comment by raapperez** [comment] 2017-02-20 13:22
Is there any news about this?

**Comment by t1mmen** [comment] 2017-03-02 17:43
@JedWatson Heads up: It's getting real close to the 4 week deadline on my bounty :)

**Comment by khenlevy** [comment] 2017-03-15 08:57
+1

**Comment by BossGrand** [comment] 2017-03-23 18:55
+1

**Comment by junibrosas** [comment] 2017-03-24 09:01
+1

**Comment by gate8team** [comment] 2017-03-27 22:14
+1

**Comment by jakeseaton** [comment] 2017-03-28 14:22
+1

**Comment by TSMMark** [comment] 2017-03-28 15:19
If only GitHub had a reaction feature so I didn't have to get a thousand `+1` comment notifications every day.....

**Comment by alaingilbert** [comment] 2017-03-28 19:37
Or at least if they had a `subscribe` feature, that would help. So people could subscribe to the thread without having to comment `+1`...

**Comment by geminiyellow** [comment] 2017-04-10 08:19
still working forward?

**Comment by vujita** [comment] 2017-06-11 16:58
+1

**Comment by Geczy** [comment] 2017-06-26 20:12
seems like a dead request...

**Comment by fabioespinosa** [comment] 2017-06-26 21:32
Any updates @JedWatson ? would really really love to see this come true!

**Comment by o1dnik** [comment] 2017-07-03 08:57
@mqklin I had same (similar) solution, but the problem is with focus on first non-disabled element which moves the dropdown 1 item down and hides the first groupname. Do you have same issue ?

**Comment by o1dnik** [comment] 2017-07-03 08:59
For those who's interested, total count of `+1`'s is 33 (plus this one =34) at the moment :) @JedWatson Any plans on implementation ? Should someone fork and pr ?

**Comment by calvinwyoung** [comment] 2017-07-19 21:02
Make that a total of 35 `+1` comments now :)

+1

**Comment by FrankRenyu** [comment] 2017-07-27 22:53
If we only wan to implement "optgroup" on top of "option", we can do something like this. It works for me.


    return <option>{props.data}</option>;
    };
     var options = [];
     $.each(this.props.options, function(key, item) {
           options.push(<optgroup label={key}>{item.map((data) => <Item data={data}/>)}</optgroup>);
     });

**Comment by o1dnik** [comment] 2017-07-28 09:35
@FrankRenyu it does not solve the problem with scrolling-off from the top as far as I understand ?

**Comment by sundriver** [comment] 2017-08-29 06:06
+1

**Comment by jainamit333** [comment] 2017-09-01 10:07
+1

**Comment by drakoniprincessa** [comment] 2017-09-12 10:09
+1

**Comment by dannyvassallo** [comment] 2017-09-12 15:05
+1

**Comment by Geczy** [comment] 2017-09-12 15:20
*unsubscribes*

**Comment by minlare** [comment] 2017-09-26 07:46
+1

**Comment by zhilinstas** [comment] 2017-10-06 18:50
+1

**Comment by arumpuspa** [comment] 2017-10-10 06:31
+1

**Comment by graphical-iain** [comment] 2017-10-10 15:56
+1

**Comment by lucasff** [comment] 2017-10-12 13:12
please stop (spam-)posting +1, just react with the thumbs up!

**Comment by chhuang** [comment] 2017-10-25 10:02
+$50

**Comment by renanborgez** [comment] 2017-10-30 17:04
+1

**Comment by jmoguelruiz** [comment] 2018-01-14 06:49
+1

**Comment by NicholasKuchiniski** [comment] 2018-01-22 03:01
+1

**Comment by JedWatson** [comment] 2018-01-25 12:00
I am really happy to say that groups are implemented in my new `v2` branch 🎉 

Everyone who has +1'd this will be happy to know this was one of the first things we implemented in the new version, and I'm quite happy with how they turned out.

v2 is currently in alpha: see #2208 and the PR #2289

If you want an early preview, it's available here: https://deploy-preview-2289--react-select.netlify.com

Expect it to hit final release sometime towards the end of February.

Now, with great relief, I'm going to close this issue 🙂

**Closed by JedWatson** 2018-01-25 12:00 UTC
Labels: feature

**Comment by guillaume86** [comment] 2018-01-25 13:20
@JedWatson brilliant thanks!

Is there a lot of API changes in v2? Do you expect easy migrations or will it be a bit involved?

**Comment by JedWatson** [comment] 2018-01-25 13:37
I'm not sure yet - I need to finalise the new API before I can know, and then I'll publish an upgrade guide.

Depends on how much you've customised it. I'm removing a lot of the edge-case props in favour of a more powerful architecture, but I'll try to make the upgrade as simple as possible.

**Comment by jossmac** [comment] 2018-01-25 22:54
Yay! An end to the daily `+1` emails 🎉

**Comment by s-dezign** [comment] 2018-03-05 21:01
v2 is really great. One question ... How to get group label/object for selected option? for example in onChange method. 

Thanks

**Comment by JedWatson** [comment] 2018-03-06 12:26
Answer in #2417
