### ISSUE TITLE
Menu pushes down the whole site instead of popping on top

### ISSUE THREAD

**Issue by alvamanu** [JedWatson/react-select#4051] opened 2020-05-17 18:01 UTC
I'm thinking this is a bug. I'm working around this issue by adding 0 to minMenuHeight. The menu popup should open to the top if there is no more space below it, like the behavior of any common select field.

The documentation states "Minimum height of the menu before flipping" for the description of minMenuHeight prop, but it doesn't flip.

**Comment by ebonow** [comment] 2021-01-17 06:30
Greetings @alvamanu , apologies for the tremendously late reply. 

I was hoping you could provide a codesandbox example of the behavior you are describing to make sure I am understanding correctly. It should be made a bit more clear that the "available space" is calculated from the menu's current position to the bottom of the window which may or may not clear things up for you. In any case, hoping you can provide an example so I can better understand and triage the issue.

**Comment by ebonow** [comment] 2021-02-01 08:41
In an effort to better maintain react-select and reported issues, I will be closing this so that we can continue to focus on reproducible issues. If you are able to provide a codesandbox or some steps to better diagnose the issues, we would happily re-open with the assumption that this is not a duplicate of any other reported issue involving menu placement and positioning.

**Closed by ebonow** 2021-02-01 08:41 UTC
Labels: awaiting-author-response

**Comment by Methuselah96** [comment] 2021-02-01 13:24
As a note, this sounds like similar behavior to https://github.com/JedWatson/react-select/issues/4088#issuecomment-766183541.
