### ISSUE TITLE
Style types malformed after installing packages

### ISSUE THREAD

**Issue by Staefloded** [JedWatson/react-select#5825] opened 2023-12-11 07:12 UTC
<img width="965" alt="Screenshot 2023-12-11 at 08 08 54" src="https://github.com/JedWatson/react-select/assets/31619471/94519566-5d09-42d7-be4c-dc3f42d7e35b">

This is the error I am getting after passing styles to the style prop

**Comment by otaviollneto** [comment] 2023-12-11 13:33
Same

**Comment by Methuselah96** [comment] 2023-12-11 14:00
This seems similar to https://github.com/frenic/csstype/issues/189, can you see what version of `csstype` is getting installed in your package lock file?

**Comment by frle10** [comment] 2023-12-11 14:06
I'm experiencing the same thing.

**Comment by valacosta19** [comment] 2023-12-11 15:26
Same issue

**Comment by Staefloded** [comment] 2023-12-11 15:33
> This seems potentially related to [frenic/csstype#189](https://github.com/frenic/csstype/issues/189), can you see what version(s) of `csstype` are getting installed in your package lock file?

`  dependencies:
    "@babel/runtime" "^7.12.0"
    "@emotion/cache" "^11.4.0"
    "@emotion/react" "^11.8.1"
    "@floating-ui/dom" "^1.0.1"
    "@types/react-transition-group" "^4.4.0"
    memoize-one "^6.0.0"
    prop-types "^15.6.0"
    react-transition-group "^4.3.0"
    use-isomorphic-layout-effect "^1.1.2"`
    
  These are the dependencies and their version

**Comment by sebherrerabe** [comment] 2023-12-11 15:36
Similar issue here :( 
![image](https://github.com/JedWatson/react-select/assets/96073676/b57936c4-d585-4d93-a2ef-43a0841396b4)

**Comment by Methuselah96** [comment] 2023-12-11 15:38
> ` dependencies: "@babel/runtime" "^7.12.0" "@emotion/cache" "^11.4.0" "@emotion/react" "^11.8.1" "@floating-ui/dom" "^1.0.1" "@types/react-transition-group" "^4.4.0" memoize-one "^6.0.0" prop-types "^15.6.0" react-transition-group "^4.3.0" use-isomorphic-layout-effect "^1.1.2"`
> 
> These are the dependencies and their version

Can you find the `csstype` entry in your lock file?

**Comment by sebherrerabe** [comment] 2023-12-11 15:44
> > ` dependencies: "@babel/runtime" "^7.12.0" "@emotion/cache" "^11.4.0" "@emotion/react" "^11.8.1" "@floating-ui/dom" "^1.0.1" "@types/react-transition-group" "^4.4.0" memoize-one "^6.0.0" prop-types "^15.6.0" react-transition-group "^4.3.0" use-isomorphic-layout-effect "^1.1.2"`
> > These are the dependencies and their version
> 
> Can you find the `csstype` entry in your lock file and paste its contents here?

Here's mine
`},
		"node_modules/csstype": {
			"version": "3.1.2",
			"resolved": "https://registry.npmjs.org/csstype/-/csstype-3.1.2.tgz",
			"integrity": "sha512-I7K1Uu0MBPzaFKg4nI5Q7Vs2t+3gWWW648spaF+Rg7pI9ds18Ugn+lvg4SHczUdKlHI5LWBXyqfS8+DufyBsgQ=="
		},`

**Comment by DMaxence** [comment] 2023-12-11 15:45
@Methuselah96 Does not work with `version "3.1.3"` either

**Comment by sebherrerabe** [comment] 2023-12-11 15:55
> > > ` dependencies: "@babel/runtime" "^7.12.0" "@emotion/cache" "^11.4.0" "@emotion/react" "^11.8.1" "@floating-ui/dom" "^1.0.1" "@types/react-transition-group" "^4.4.0" memoize-one "^6.0.0" prop-types "^15.6.0" react-transition-group "^4.3.0" use-isomorphic-layout-effect "^1.1.2"`
> > > These are the dependencies and their version
> > 
> > 
> > Can you find the `csstype` entry in your lock file and paste its contents here?
> 
> Here's mine
> 
> ```json
> },
> "node_modules/csstype": {
> "version": "3.1.2",
> "resolved": "https://registry.npmjs.org/csstype/-/csstype-3.1.2.tgz",
> "integrity": "sha512-I7K1Uu0MBPzaFKg4nI5Q7Vs2t+3gWWW648spaF+Rg7pI9ds18Ugn+lvg4SHczUdKlHI5LWBXyqfS8+DufyBsgQ=="
> },
> ```

Hey, I just realised that this is the version I get installed locally, and I encounter no errors with it. Apparently, my problem arises when running my pipeline where I store my repository (Bit bucket). I'll try to check which version is being installed there.

My first thought is that the problem is associated with version 3.1.3.

**Comment by Staefloded** [comment] 2023-12-11 16:11
> > > > ` dependencies: "@babel/runtime" "^7.12.0" "@emotion/cache" "^11.4.0" "@emotion/react" "^11.8.1" "@floating-ui/dom" "^1.0.1" "@types/react-transition-group" "^4.4.0" memoize-one "^6.0.0" prop-types "^15.6.0" react-transition-group "^4.3.0" use-isomorphic-layout-effect "^1.1.2"`
> > > > These are the dependencies and their version
> > > 
> > > 
> > > Can you find the `csstype` entry in your lock file and paste its contents here?
> > 
> > 
> > Here's mine
> > ```json
> > },
> > "node_modules/csstype": {
> > "version": "3.1.2",
> > "resolved": "https://registry.npmjs.org/csstype/-/csstype-3.1.2.tgz",
> > "integrity": "sha512-I7K1Uu0MBPzaFKg4nI5Q7Vs2t+3gWWW648spaF+Rg7pI9ds18Ugn+lvg4SHczUdKlHI5LWBXyqfS8+DufyBsgQ=="
> > },
> > ```
> 
> @Methuselah96 , I just realised that this is the version I get installed locally, and I encounter no errors with it. Apparently, my problem arises when running my pipeline where I store my repository (Bit bucket). I'll try to check which version is being installed there.
> 
> My first thought is that the problem is associated with version 3.1.3.

mine fails locally and also in my gitlab pipeline

**Comment by Methuselah96** [comment] 2023-12-11 16:51
Yes, the issue is with csstype@3.1.3. You'll have to manually make sure that csstype is resolving to csstype@3.1.2, either by manually editing the lock file, or using something like [npm overrides](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) or [Yarn resolutions](https://yarnpkg.com/configuration/manifest#resolutions).

**Comment by ODreelist** [comment] 2024-02-29 19:04
Still having this issue as a result of a recent @types/react package update. @types/react@18.2.61 now depends on csstype: 3.1.3.

Workaround: 

`import ReactSelect, { CSSObjectWithLabel, ControlProps, GroupBase } from "react-select";

type OptionType = { label: string; value: string };

type StylesType = Record<
  string,
  (
    base: (props?: Record<string, CSSObjectWithLabel>) => CSSObjectWithLabel,
    state: ControlProps<OptionType, boolean, GroupBase<OptionType>>,
  ) => CSSObjectWithLabel
>;

const selectStyles: StylesType = {
  control: () => ({
    width: "100%",
  }),
  container: (baseStyles, state) => ({
    ...(state.isDisabled && { pointerEvents: "none" }),
    ... baseStyles,
    width: "100%",
  }),
};

<ReactSelect styles={selectStyles} />;`

**Comment by tom-engineering** [comment] 2024-03-09 12:16
For anyone searching who has a project that also has a direct dependency on `@emotion/react`, this was resolved for me with `@emotion/serialize@1.1.3` which you can obtain by installing or re-installing `@emotion/react@11.11.3` or above: https://github.com/emotion-js/emotion/pull/3143

**Comment by MattIPv4** [comment] 2024-05-14 01:32
👀 If you're just reliant on `react-select` and don't have a direct dependency on `@emotion/react`/`@emotion/serialize`/`csstype`, you can likely resolve this by running `npm update @emotion/react` to bump the installed sub-dependency (`react-select` does not pin it to a specific version). You can confirm you have the fixed `@emotion/react`/`@emotion/serialize` version with `npm ls @emotion/serialize`.

**Closed** 2024-05-14 07:58 UTC
Labels: issue/bug-unconfirmed

**Comment by Aeon** [comment] 2025-11-19 18:57
@Staefloded just hit this in 2025 - maybe `react-select` needs to pin to @emotion/serialize@3.1.3 or higher - otherwise people with older installs may hit this?
