### ISSUE TITLE
Unexpected token: name(instanceId) in 1.0.0-rc.6

### ISSUE THREAD

**Issue by zjy01** [JedWatson/react-select#1977] opened 2017-09-11 03:50 UTC
### System
window and linux catch error

### Version
1.0.0-rc.6

### Error
```
ERROR in app.d61ff.js from UglifyJs
Unexpected token: name (instanceId) [app.d61ff.js:24368,4]
```

**Comment by agirton** [comment] 2017-09-11 04:01
Hi @zjy01 please look for existing issues before a new one. Closing as this is a duplicate of #1971

**Closed by agirton** 2017-09-11 04:01 UTC
