### ISSUE TITLE
Placeholder value overlapped by clear/select icons

### ISSUE THREAD

**Issue by kevinhos** [JedWatson/react-select#1916] opened 2017-08-08 21:52 UTC
It looks like very long select values will be overlapped by the clear and select icons when selected.

![screen shot 2017-08-08 at 4 48 43 pm](https://user-images.githubusercontent.com/18267875/29096307-f0dc330e-7c59-11e7-9395-1d19fbaee334.png)

**Comment by jochenberger** [comment] 2017-08-21 11:52
dupe of #1554

**Comment by JedWatson** [comment] 2017-09-12 17:31
Fixed by #1866

**Closed by JedWatson** 2017-09-12 17:32 UTC
