### ISSUE TITLE
Always check isMounted() with asyncOptions callback

### ISSUE THREAD

**Issue by drewhamlett** [JedWatson/react-select#115] opened 2015-04-01 20:53 UTC
I was getting `Can only update a mounted or mounting component.` a lot in my code and I always check for isMounted.  I traced it down to the callback for react-select.

``` js
       if (this.isMounted()) {
          return callback(null, {
            options: results,
            complete: false
          });
        }
```

This should be noted in docs I believe.  Opinions?

**Comment by JedWatson** [comment] 2015-04-05 12:48
Can you provide some more context about where you're seeing it? I'm happy to add docs for it, just not sure where you're supplying the callback...

**Comment by dcousens** [comment] 2015-05-07 03:48
@JedWatson I think the issue is that we are not checking if we are still mounted in https://github.com/JedWatson/react-select/blob/master/src/Select.js#L448-L473, and it is a question as to whether this should be left up to the user or is it our responsibility.

I'm opting towards the former,  but I don't see the latter as a terrible choice,  if you are trying to be a friendly library.

**Comment by Pomax** [comment] 2016-02-02 20:50
I'm constantly running into this while doing mocha/phantom unit testing, where custom events are generated, handing by a component that uses (one or more) `<Select>` in its render function, and then gets dismounted in the unit test code while the `<Select>` element is still doing... things... that cause it to call its own `setState()` despite the owning component having already been dismounted again in preparation for moving on to the next unit test.

Having the Select component do some `isMounted()` guarding before letting `setState()` through would certainly make the test logs a lot calmer.

**Comment by agirton** [comment] 2017-05-20 18:14
Closing as `isMounted` is no longer used.

**Closed by agirton** 2017-05-20 18:14 UTC
Labels: question, todo
