### ISSUE TITLE
Edit in CodeSandbox is not working

### ISSUE THREAD

**Issue by ogiexela** [JedWatson/react-select#4649] opened 2021-06-23 16:08 UTC
Clicking "edit in codesanbox" button on any examples does nothing.

**Comment by ebonow** [comment] 2021-06-23 16:22
Duplicate of https://github.com/JedWatson/react-select/issues/4358

You should be able to add missing dependencies once codesandbox opens

**Comment by ebonow** [comment] 2021-06-23 17:45
Apologies. I conflated this issue with an existing issue. It appears that we are having issues opening CodeSandbox links with the newly generated docs.

**Comment by sadrzadehsina** [comment] 2021-06-28 16:15
Is this fixed? I can't open examples in codesandbox.

**Comment by ebonow** [comment] 2021-06-28 16:35
Sorry, unfortunately, they are not fixed yet. We are looking at the issue but believe to have a resolution to it soon.

**Comment by viriyadhika** [comment] 2021-07-14 15:42
When I downloaded the code and run it with my PC it shows that examplePath points to docs/examples/BasicSingle.tsx
![image](https://user-images.githubusercontent.com/50723579/125650181-3f642596-b6e6-455b-9f97-3fd08b9d9fbd.png)
It correctly redirects to the code sandbox


However in the website itself upon inspecting, it shows that examplePath points to docs/examples/BasicSingle.js
![image](https://user-images.githubusercontent.com/50723579/125650736-7d97f6d2-f954-49fd-b63b-b5e7aacfe666.png)

Next release should fix the bug

**Comment by ebonow** [comment] 2021-10-10 20:37
Fixed.

**Closed by ebonow** 2021-10-10 20:37 UTC
Labels: issue/bug-confirmed
