### ISSUE TITLE
In React Select dropdown is not closing some times

### ISSUE THREAD

**Issue by srikanth0448** [JedWatson/react-select#4678] opened 2021-07-06 09:55 UTC
In React Select dropdown is not closing some times, when move to next field without select dropdown. Thanks in advance.

![image](https://user-images.githubusercontent.com/34440998/124581121-6fe54f80-de6e-11eb-9031-48ba8eb0f082.png)

**Comment by Rall3n** [comment] 2021-07-06 13:42
Hello @srikanth0448,

could you provide more information about your usage of the `Select` component?
What version are you using?
How are you using the component and what customization have you applied?

If possible, could you also provide a reproducible example using [this `CodeSandbox`](https://codesandbox.io/s/react-select-v4-sandbox-rxvsh)?

**Comment by srikanth0448** [comment] 2021-07-07 06:27
First I click on select dropdown without select any option I moving to another field, in first time dropdown is closing.  But in second time repeat the same thing that dropdown not closing. I am attaching the video please have a look.

https://user-images.githubusercontent.com/34440998/124710048-d96e6800-df19-11eb-8c6c-16a70c6d336b.mp4

**Comment by Rall3n** [comment] 2021-07-07 07:29
@srikanth0448 I cannot reproduce this problem with just an `<input>` element and the `Select` component. Unfortunately, your screen capture doesn't help in finding a solution either.

Could you please either provide a snippet of code of your implementation or a reproducible example using [CodeSandbox](https://codesandbox.io/s/react-select-v4-sandbox-rxvsh).

**Comment by ebonow** [comment] 2021-10-05 00:23
Greetings @srikanth0448 ,

I am unable to reproduce this error. Perhaps you are running into the same issue as here https://github.com/JedWatson/react-select/issues/4831 as a result of creating a ValueContainer without an Input, but we are unable to assist without further details or code samples.

I'll be closing this issue, but feel free to reply if you still have questions.

**Closed by ebonow** 2021-10-05 00:23 UTC
Labels: issue/bug-unconfirmed, awaiting-author-response
