### ISSUE TITLE
Inconsistent behaviour on remove last item (vs remove all items)

### ISSUE THREAD

**Issue by joe-oli** [JedWatson/react-select#4247] opened 2020-10-12 05:58 UTC
# Are you asking a question?
No.

# Are you reporting a bug or runtime error?
An error in your example, a runtime error, and a bug.

An error in your example in this page:
https://react-select.com/creatable

Specifically **Multi-select text input** and the method **handleKeyDown**;

```
  handleKeyDown = (event: SyntheticKeyboardEvent<HTMLElement>) => {
    const { inputValue, value } = this.state;
    if (!inputValue) return;
    switch (event.key) {
      case 'Enter':
      case 'Tab':
		//... etc... 
        this.setState({
          inputValue: '',
          value: [...value, createOption(inputValue)],
        });
        event.preventDefault();
    }
  };
```
  
The line 
	`value: [...value, createOption(inputValue)],`
assumes ...value is always an array; this is NOT true; 
value becomes null when you remove the last item, by clicking on the individual item;

Herein lies the bug: **Inconsistent behaviour when removing the last item.**
When removing an individual last item (click on small-x), value = null;
When removing all items (click on big-x), value = [];

# Are you making a feature request?
No. it is a bug fix. 
Please make the behavior consistent on item removal, so that even your own example works.

**Comment by Rall3n** [comment] 2020-10-12 09:33
Duplicate of two issues:
* #3632 (also #4021) Inconsistent behaviour when removing last item
* #4190 Broken Multi-select text input example

**Comment by dakur** [comment] 2020-10-21 12:26
Related #4252

**Comment by ebonow** [comment] 2020-12-13 04:26
Documentation Issue is a duplicate of https://github.com/JedWatson/react-select/issues/4190

**Comment by ebonow** [comment] 2021-01-14 06:14
Closing this as the example and behavior have been fixed. 

Related: https://github.com/JedWatson/react-select/pull/4373

**Closed by ebonow** 2021-01-14 06:14 UTC

**Comment by joe-oli** [comment] 2021-01-14 11:34
So what is the simple answer? is removing all-items and removing last-item now setting the value to 
1) null, or 
2) [] ?
All the related issues have got me so confused.

**Comment by dakur** [comment] 2021-01-14 12:11
I don't know in which issue I have read it, but the answer – as I understood it – is `null` for now, but may be rethought to `[]` in future.

**Comment by dakur** [comment] 2021-01-14 12:14
> 
> 
> @joe-oli I don't know in which issue I have read it, but the answer – as I understood it – is `null` for now, but may be rethought to `[]` in future.

Ha, it's here: https://github.com/JedWatson/react-select/issues/4293#issuecomment-759601523

> - Clearing the value from isMulit Select will return the value null to be consistent with current implementation.
>   - It should be noted that it was discussed that this approach for returning null for multi Select can be confusing and will likely be reverted back to [] in v4.0

**Comment by ebonow** [comment] 2021-01-14 15:14
> So what is the simple answer? is removing all-items and removing last-item now setting the value to
> 
> 1. null, or
> 2. [] ?
> 
> All the related issues have got me so confused.

@joe-oli, 

`null` per the spec for v3 as described under **Normalized Values**
https://github.com/JedWatson/react-select/releases/tag/react-select%403.0.3

In a recent call with Jed, Nathan, and Thomas, the argument was made that `null` seems a bit confusing and while rolling the spec change back only one major release later seems to admit we got it wrong, ultimately the goal is to get it right.

Therefore in v3.2, the fix was made for consistency to return null when removing the last value to avoid breaking changes, 

In v4, this will likely be reversed such that a multi with no value returns empty array instead.

Hope this is clears things up. Did you have any other questions or concerns regarding this approach?

**Comment by joe-oli** [comment] 2021-01-15 01:53
> Did you have any other questions or concerns regarding this approach

Thank you, no more questions now that it is clear what to expect.
