### ISSUE TITLE
4.x doesn't work with Webpack 5 out of the box

### ISSUE THREAD

**Issue by Slapbox** [JedWatson/react-select#4419] opened 2021-02-04 00:52 UTC
### Bug

This issue affects the newest version of React-Select and could be remedied by upgrading `@babel/runtime`

https://github.com/babel/babel/issues/12058

Until then people can try using package.json's `resolutions` field. (Trying that now, but `yarn` is out of whack so we've got to reinstall everything. Will report back if any issues.)

**Comment by Methuselah96** [comment] 2021-02-04 00:56
Duplicate of https://github.com/JedWatson/react-select/issues/4253.

As noted there:

> Note that this issue shouldn't be blocking anyone because the current range for `@babel/runtime` (i.e., `^7.4.4`) allows for the version with the fix `7.12.0`, but it would still be nice bump the dependency anyway.

**Closed by Methuselah96** 2021-02-04 00:56 UTC
