### ISSUE TITLE
 Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive.

### ISSUE THREAD

**Issue by Alexandr-fly-code** [JedWatson/react-select#3848] opened 2019-11-06 09:12 UTC
"[Violation] 'setTimeout' handler took <N>ms"
"[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive.
How to fix it?

**Comment by PythooonUser** [comment] 2020-04-09 14:35
This is probably a duplicate of https://github.com/JedWatson/react-select/issues/2729.

**Comment by bladey** [comment] 2020-06-03 02:01
Hello -

In an effort to sustain the `react-select` project going forward, we're closing issues that appear to be duplicates or are now redundant.

As @PythooonUser has stated, this appears to be a duplicate of #2729.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you, and we'll re-open it if necessary.

**Closed by bladey** 2020-06-03 02:01 UTC
