### ISSUE TITLE
Portaled Menu Element horizontally shifting when using browser zoom

### ISSUE THREAD

**Issue by EvertLundBind** [JedWatson/react-select#4375] opened 2021-01-14 10:48 UTC
**Steps to reproduce:**

1) Standard implementation with portaling as per spec (https://react-select.com/advanced#portaling)
2) Use browser zoom while menu element is visible

**Expected results:**

Portaled menu element will maintain its relative position

**Actual results:**

Portaled menu element shifts left to right depending on the browser zoom level

Screenshot of https://react-select.com/advanced#portaling displaying the issue:
![W2ZyWD0](https://user-images.githubusercontent.com/76153623/104581031-b055d480-5666-11eb-87e2-f5deb535acc5.png)

Tested on:
Chrome 87.0.4280.88

**Comment by ebonow** [comment] 2021-01-14 23:05
Confirmed that this behavior exists but not sure what if anything can be done. It appears that there is no standard in place to identify if a viewport has been "zoomed"
https://css-tricks.com/can-javascript-detect-the-browsers-zoom-level/

It should also be noted that the menu "snaps" back into its expected position when the menu/option is hovered. This leads me to believe that it may be related to some other behavior that prevents the menu from staying positioned as expected:
https://github.com/JedWatson/react-select/issues/4336
https://github.com/JedWatson/react-select/issues/3533
https://github.com/JedWatson/react-select/issues/4159

They all share similar behavior in that the scroll position is offset from what is expected but then snaps into place once the menu is hovered.

I think it may be worth consolidating these into a single use-case to better identify the root.

**Comment by ebonow** [comment] 2021-01-17 06:13
I reviewed #3533 a bit more and this seems to be a duplicate as the browser behavior is also noted in there. I will be closing this to consolidate the efforts to that issue.

**Closed by ebonow** 2021-01-17 06:13 UTC
Labels: issue/needs-review
