### ISSUE TITLE
Disable auto select of first option 

### ISSUE THREAD

**Issue by LuizGMiranda** [JedWatson/react-select#4042] opened 2020-05-08 15:01 UTC
Hi,

I'm want to disable the auto select of the first option, how to this? Version 3.1.0

Thanks!

**Comment by manualva7** [comment] 2020-05-08 23:33
If your intention is to put a placeholder, there is an option for that.

Please provide more information.

**Comment by LuizGMiranda** [comment] 2020-05-10 18:03
Whenever I search for something and hit enter, it is selected or the first item. However I want to leave what I put without automatic item selection.

**Comment by manualva7** [comment] 2020-05-11 18:17
You might want to look into creatable. https://react-select.com/home#creatable

**Comment by bladey** [comment] 2020-06-10 05:41
This will be resolved when #4080 is merged.

**Comment by ebonow** [comment] 2020-12-20 05:18
Greetings, this appears to be a duplicate of https://github.com/JedWatson/react-select/issues/2848. 

I will close this issue, but please feel free to subscribe to the mentioned issue to receive any updates regarding any updates in this PR being released.

**Closed by ebonow** 2020-12-20 05:18 UTC
Labels: issue/enhancement, issue/has-pr, issue/reviewed
