### ISSUE TITLE
Warnings: componentWillReceiveProps in strict mode, Legacy context API, findDOMNode is deprecated

### ISSUE THREAD

**Issue by bladey** [JedWatson/react-select#4094] opened 2020-06-18 06:17 UTC
_This issue is a round-up of multiple past issues documenting the same bug. Feel free to check out the linked issues below for more information. This issue is the source of truth going forward to investigate the issue, report findings, and implement a bug fix._

**Issue:**

<img width="715" alt="W35yYs" src="https://user-images.githubusercontent.com/737821/84984363-ffde2b80-b17d-11ea-8842-9cc8a2f0eb5c.png">

```
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.
```

```
Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.
```

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of NodeResolver which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
```

**Issues:**

https://github.com/JedWatson/react-select/issues/3751
https://github.com/JedWatson/react-select/issues/3720
https://github.com/JedWatson/react-select/issues/3915
https://github.com/JedWatson/react-select/issues/3745
https://github.com/JedWatson/react-select/issues/4068
https://github.com/JedWatson/react-select/issues/3703

If anyone would like to share any further information, please do so.

**Comment by giangr21** [comment] 2020-06-18 13:39
Same issue here

**Comment by Sine99** [comment] 2020-06-19 14:57
same issue

**Comment by manvydasu** [comment] 2020-06-19 16:38
So basically someone would have to create a PR and replace legacy component lifecycle methods with newer version: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#migrating-from-legacy-lifecycles

**Comment by stak99** [comment] 2020-06-28 03:06
same issue

**Comment by corysimmons** [comment] 2020-06-29 14:49
For anyone else going insane over this, you can disable those warnings (and other, actually helpful ones) by commenting out `<React.StrictMode>` in `index.js`. Just remember to uncomment it a few times a day to get the helpful warnings.

**Comment by martijnhalekor** [comment] 2020-07-15 09:51
Same issue here.

**Comment by roberto-souza** [comment] 2020-07-20 18:15
Hello! The problem is not solved yet? :(

**Comment by OlegPuzankin** [comment] 2020-07-24 19:32
Can anyone say  - are these warnings critical and can we expect the developers to fix that in the future?

**Comment by corysimmons** [comment] 2020-07-24 20:20
@OlegPuzankin They aren't critical in React 16.x.x, in React 17+ I suspect all the deprecated `UNSAFE_xyz` methods will be removed so any libraries depending on those methods will stop working.

Yes, the maintainer is aware of it and has it on their todo list.

**Comment by PritishSawant** [comment] 2020-10-24 10:11
React v17 has been released. Someone please fix this issue

**Comment by ljharb** [comment] 2020-10-24 15:57
The UNSAFE removal has been deferred to React 18.

**Comment by Methuselah96** [comment] 2020-11-14 16:36
I've started [a fork](https://github.com/react-select-oss/react-select) of react-select. Feel free to resubmit this issue on the fork and/or submit a PR to resolve this issue on the fork and we can get it merged and released.

**Comment by corysimmons** [comment] 2020-11-25 18:09
@Methuselah96 Is that a drop-in replacement that won't spam the `UNSAFE` warnings?

**Comment by Methuselah96** [comment] 2020-11-25 20:32
@corysimmons I haven't finished the changes necessary to remove the `UNSAFE` warnings in the fork.

I didn't make a PR for this project, because at the time, it had been several months since any PR had been merged and half a year since a new version had been released. I planned on creating a PR once I had finished all the changes necessary.

**Comment by bwilson** [comment] 2020-11-25 20:40
Thanks for your efforts!

**Comment by flora8984461** [comment] 2020-12-02 22:11
Have the same issue here.

**Comment by Dezzymei** [comment] 2021-01-18 17:44
I am still getting this issue. I thought this was working with react 17?

**Closed** 2021-01-22 05:20 UTC
Labels: issue/bug-confirmed, issue/reviewed

**Comment by corysimmons** [comment] 2021-01-22 14:27
@Methuselah96 Thank you, Hero!

**Comment by Ochaun** [comment] 2021-02-25 18:36
Still getting this issue on 4.1.0 for the Animated Select.

**Comment by ebonow** [comment] 2021-02-25 18:38
@Ochaun this is being tracked in https://github.com/JedWatson/react-select/issues/4456
