### ISSUE TITLE
How to prevent the menu from opening on click?

### ISSUE THREAD

**Issue by rooskienz** [JedWatson/react-select#1131] opened 2016-08-01 03:02 UTC
Hi,

When I click on the input the menu opens but I only want it to open when user starts typing and there are matching options. How do I do that?

Cheers!

**Comment by gojohnnygo** [comment] 2016-08-03 04:38
@rooskienz - Calling [focus()](https://github.com/JedWatson/react-select#methods) has the pleasant side effect of closing the menu. Calling that onClick may do the trick. 

```
// pseudo code
<span onClick=this.Select.focus()>
  <Select
    ref={(ref) => this.Select = ref}
  />
</span>
```

**Comment by morgs32** [comment] 2016-12-25 04:01
This is throwing an error for me. Calling focus on undefined.

**Comment by gojohnnygo** [comment] 2016-12-26 19:15
@morgs32 sounds like you don't have a ref to the react-select component.

**Comment by elghali** [comment] 2017-09-19 09:03
@morgs32 
`SelectFocus = () => {
this.Select.focus()
}...
...
<span onClick=this.SelectFocus()>
  <Select
    ref={(ref) => this.Select = ref}
  />
</span>`
but still, the problem remains

**Comment by morgs32** [comment] 2017-09-25 15:31
@elghali Yea I don't know why @gojohnnygo thinks that'll work.
I had to fork this and make the changes myself:
https://github.com/morgs32/react-select/commit/554fea70c5af102cab116c48fc09be1758384cad#diff-04191649796841200b33375bdff7c78f

Looking at the code, it seems that when Select is focused, it is sure to have an open menu.

**Comment by elghali** [comment] 2017-11-02 11:12
I wrapped the `Select` comp within a `span` which doesn't allow it to open and it works, but the problem is that now even when the arrow is clicked it won't open either,
```  
     dontOpenOnClick = () => {
    this.conditionSelector.select.closeMenu();
  }
   <span onFocus={this.dontOpenOnClick}>
                <Select.Creatable
                  ref={(node) => this.conditionSelector = node}
                />
   </span>

**Comment by boonya** [comment] 2019-06-19 11:38
There is special option `openMenuOnClick={false}`

**Comment by bladey** [comment] 2020-05-28 04:47
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Closed by bladey** 2020-05-28 04:47 UTC
