### ISSUE TITLE
Consider making simpleValue return array of values instead of delimited string

### ISSUE THREAD

**Issue by Aaronius** [JedWatson/react-select#1275] opened 2016-10-03 22:26 UTC
As described in the docs, the `onChange` event provides an array of selected options or a comma-separated string of values (eg "1,2,3") if `simpleValue` is true.

I would like to propose changing the API (yeah, it would be a breaking change) so that if `simpleValue` is set, `onChange` would produce an array of values rather than a comma-separated string of values.

Admittedly, I propose this not fully understanding the value of receiving a comma-delimited string of values. In all circumstances I have encountered, I want an array of values. When storing the currently selected values in our app state, we always have to either (1) split on the delimiter when using `simpleValue` or (2) pluck all values from the options objects when not using `simpleValue`.

Using `simpleValue` also has the side-effect of coercing values that are not string-based into strings since they have to be [joined using the delimiter](https://github.com/JedWatson/react-select/blob/17d76a4161096cb88fb04a6e9e6529580e67b305/src/Select.js#L582). You can see where this can cause problems just by looking at the [demo site](http://jedwatson.github.io/react-select/). On the Numeric Values demo, check "Multi-Select" then try to select an option. It doesn't work due to coercion of numeric values into strings. If a consumer receives `10,12`, is `10` really a string or a number? Consumers may only know by reconciling it with the original options sent into the Select. And that makes me sad. We run into the same situation with boolean values (a feature which has been merged but not published).

**Comment by nickhsu** [comment] 2016-10-19 02:36
+1 

I was in the same situation like u. Finally, I did lots of dirty work to parse the data from the server and normalize it before saving to the server.

**Comment by pandabrand** [comment] 2016-10-30 04:18
+1  
This would be a great option. I just had to adjust for this.

**Comment by krtcom** [comment] 2016-12-19 18:11
+1
yes please...

**Comment by jochenberger** [comment] 2017-02-13 11:39
dupe of #498

**Comment by bladey** [comment] 2020-05-27 06:18
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.

**Closed by bladey** 2020-05-27 06:18 UTC
