### ISSUE TITLE
select field can be opened only by dbl-click

### ISSUE THREAD

**Issue by Charlie91** [JedWatson/react-select#1982] opened 2017-09-11 15:48 UTC
i have found a possible bug in ^1.0.0-rc.7 version. It is all okay in ^1.0.0-rc.5.
Select can be opened only by dbl-click, and by first-click it's only receive a focus.

**Comment by Charlie91** [comment] 2017-09-11 15:49
i tested it on the documentation's first example

**Comment by livemixlove** [comment] 2017-09-11 19:21
I reverted to 1.0.0-rc.5 to fix it for now.

**Comment by nicubarbaros** [comment] 2017-09-12 08:32
yep same for me, I think I will revert to rc.5 as well.

**Comment by jochenberger** [comment] 2017-09-12 09:10
dupe of #1980

**Comment by JedWatson** [comment] 2017-09-13 07:20
also dupe of #1994, let's track it there

**Closed by JedWatson** 2017-09-13 07:20 UTC
