### ISSUE TITLE
First item of the menu is selected by hitting enter by default even if the input value in the container does not match it

### ISSUE THREAD

**Issue by fydsa** [JedWatson/react-select#4202] opened 2020-09-09 12:28 UTC
Hi everybody,

I am using AsyncSelect, and I type sth in the container and then some options appear in the menu,  but the problem is that even in the case that what I've typed in the container does not match any of the options, hitting enter cause selecting the first item of the options. Can anyone help me to find a way to prevent this behavior? I really appreciate any help. 

Many thanks in advance.

**Comment by ebonow** [comment] 2020-09-09 19:59
Greetings @fydsa ,

I would love to help, but am not certain I understand how you are seeing this behavior.

[This example](https://codesandbox.io/s/s581m?module=/example) might provide some clues as to why you are seeing this behavior. Two important things to look at are checking that you are managing the filtering and then calling the callback when the input returns. 

If this doesn't help, then perhaps you could include an example to help me better understand why it isn't working as expected.


-

**Comment by fydsa** [comment] 2020-09-09 21:04
> Greetings @fydsa ,
> 
> I would love to help, but am not certain I understand how you are seeing this behavior.
> 
> [This example](https://codesandbox.io/s/s581m?module=/example) might provide some clues as to why you are seeing this behavior. Two important things to look at are checking that you are managing the filtering and then calling the callback when the input returns.
> 
> If this doesn't help, then perhaps you could include an example to help me better understand why it isn't working as expected.

Thanks for your reply. Well, actually, the problem is that I hitting enter in the container cause selecting the first item of the option list even if nothing is typed in the container input field. Or for instance, in the example you provided, I type "q" in input field and no option is matched with it, and then I out focus the input field and the menu is closed and the first item of the list which in this case is "ocean" is appeared in the input container as the selected value. I am looking for a way to prevent this behavior.

Thank you a again

**Comment by ebonow** [comment] 2021-02-10 01:41
Sorry for the late reply to this. 

So I understand better, when you say that the input does not match any of the options, you specifically mean when there is no input correct? 

There is issue https://github.com/JedWatson/react-select/issues/2848 which already has an open PR. Would this be what you are referring to or am I misunderstanding?

**Comment by ebonow** [comment] 2021-02-22 15:40
Based on available information, closing this as a duplicate of #2848 . Can revisit or re-open if more information is provided later.

**Closed by ebonow** 2021-02-22 15:40 UTC
Labels: awaiting-author-response
