### ISSUE TITLE
Feature request: Optionally place drop-down and clear icons on left side

### ISSUE THREAD

**Issue by rpiaggio** [JedWatson/react-select#1608] opened 2017-03-19 19:50 UTC
Thank you!

**Comment by dekelb** [comment] 2017-03-21 14:16
This is a duplicate of #1190

**Comment by dekelb** [comment] 2017-03-21 18:26
@rpiaggio If you notice, the #1613 is 2 hours old :) I just opened that pr.

Regarding your request - if you check the code in my pr you can take the css from there and use it.

**Comment by bladey** [comment] 2020-05-27 06:21
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.

**Closed by bladey** 2020-05-27 06:21 UTC
