### ISSUE TITLE
Impossible to use with too many options

### ISSUE THREAD

**Issue by Wiz1991** [JedWatson/react-select#4470] opened 2021-02-28 11:31 UTC
When dealing with 100+ options the hovering effect creates tremendous lag. Scrolling becomes impossible. Now if you just hold your mouse over the scroll bar and scroll with either scroll wheel or the bar there is no lag whatsoever. I am guessing the MenuList is being rerendered on hover. I am not sure. But whatever its doing, its bad. I think that the hover effect should be stoppped while scrolling or moving the mouse too much. Once the mouse has stopped then and only then show the hover effect. Otherwise this library is impossible to use. 

Note: I have seen some fixes around here but they are not quite well implemented. One in particular works but has issues with height and some issues with searching. As well as that in grouped list there is some kind of overlap where the group title overlaps with every option.

**Comment by ebonow** [comment] 2021-02-28 18:00
Greetings @Wiz1991,

Closing this as a duplicate of the #3128.

Since this already exists as an open issue, you might want to try opening a Q&A discussion along with a codesandbox of your implementation. There might be more people willing to look at a specific example there and suggest some solutions on your particular use-case.

**Closed by ebonow** 2021-02-28 18:00 UTC
