### ISSUE TITLE
menuShouldBlockScroll also blocks menu scrolling.

### ISSUE THREAD

**Issue by 2Steaks** [JedWatson/react-select#3929] opened 2020-02-11 11:46 UTC
Hi, I'm using **menuPortalTarget** to render outside of containers with overflow hidden such as table rows. In order for the menu position to be correct I have to set **menuPosition** to fixed. This works great except when you scroll the page and the menu position is not recalculated. To fix this I then use **menuShouldBlockScroll** which in combination with the other props achieves the desired result except for the fact that **menuShouldBlockScroll** also blocks the menu (has max-height with scroll auto) contents from being scrollable.

Would it be possible to prevent scrolling for all elements except for `.react-select__menu-list` ?

**Comment by flexdinesh** [comment] 2020-02-21 12:52
Hey @2Steaks would you be replicate the issue in a codesandbox? It'd be easier to comprehend the issue with an example.

**Comment by 2Steaks** [comment] 2020-02-28 13:33
Good shout, here you go: https://codesandbox.io/s/festive-dirac-izf5y

**Comment by epotockiy** [comment] 2020-03-27 07:59
Confirmed the same issue for me, @flexdinesh do you check this bug in sandbox?
I made investigation and figured out, that this were broken after release of 3.0.5 version
I checked commits, and find this [commit](https://github.com/JedWatson/react-select/commit/691a01171969da89e20097f9d603651bb18a8510)
When i reverted this changes locally, scroll start working again
I don't know reason of this changes, but i think that this should be reverted or updated

**Comment by stnwk** [comment] 2020-03-30 13:39
Hi @JedWatson can you give any more insights into this? This is a big bummer :(

**Comment by flexdinesh** [comment] 2020-03-31 03:00
Hey @2Steaks thanks for the codesandbox I can see it now. I'll get to it sometime soon. I'll update here once we make progress.

**Comment by srinivasmerugu** [comment] 2020-04-17 12:15
> Hey @2Steaks thanks for the codesandbox I can see it now. I'll get to it sometime soon. I'll update here once we make progress.

Hi @2Steaks Please let us know once it is pushed.

**Comment by engPabloMartinez** [comment] 2020-05-20 21:25
Hey team, any news around a fix for this? maybe a temporary one? is going back to 3.0.4 the only workaround for now?

**Comment by 2Steaks** [comment] 2020-05-21 11:19
@flexdinesh reverting this code seems to fix the issue.

https://github.com/JedWatson/react-select/commit/691a01171969da89e20097f9d603651bb18a8510#diff-16745c8f19a824159168a93abf7bb78b

**Comment by srinivasmerugu** [comment] 2020-05-26 13:12
@flexdinesh Even we are waiting for this fix as we are using 3.1.0 features as well and do not want to go back to 3.04 version. Please let us know once you revert the 691a011#diff-16745c8f19a824159168a93abf7bb78b or give any other solution .
 
Thank you !

**Comment by bladey** [comment] 2020-06-15 04:48
Hello -

Thanks for reporting this issue.

This bug has been reported multiple times as per issue #4088.

A new master issue #4088 has since been created to keep track this this bug.

This new issue will exist as the source of truth going forward to investigate the issue, report findings, and implement a bug fix.

We'll take into account all the details above while investigating.

If you feel this issue has been wrongly closed as it isn't related to the new master issue #4088, please let us know and we'll take another look.

Thank you!

**Closed by bladey** 2020-06-15 04:48 UTC
Labels: issue/bug-confirmed

**Comment by Eddie-CooRo** [comment] 2021-02-09 06:44
@bladey
I think this issue is not related to #4088
#4088 is about the menu not following the scroll when the `menuShouldBlockScroll` is *false*. This issue is about the menu scroll also getting blocked when the `menuShouldBlockScroll` is *true*

**Comment by Methuselah96** [comment] 2021-02-09 14:13
@Eddie-CooRo Is this still an issue for you? It would be great if you could create a CodeSandbox that reproduces the issue.

**Comment by Eddie-CooRo** [comment] 2021-02-09 14:29
Ugh... I was following this issue and #4088 for over one-two months already :sweat_smile:  
Didn't notice there is a fix already published for it :heart_eyes: 

For book-keeping purposes, this issue is "solved" in v4 :heart_eyes: :v:  
Thanks, @Methuselah96 :v:

**Comment by iksent** [comment] 2021-07-12 12:26
I am experiencing this issue at v4.3.0 :(

**Comment by ranno-lauri** [comment] 2021-07-30 08:16
> I am experiencing this issue at v4.3.0 :(
> 
> The next config sometimes blocks menu scrolling:
> 
> ```
> menuPortalTarget: document.body,
> menuPosition: 'fixed',
> menuShouldBlockScroll: true,
> menuShouldScrollIntoView: true,
> ```
> 
> UPD: I were using custom component for MenuList without components.MenuList - that was the reason.

For me it was not passing and spreading the base props for custom menuList styling
