### ISSUE TITLE
[V2] IE 11 cursor bug

### ISSUE THREAD

**Issue by lucletruc** [JedWatson/react-select#2886] opened 2018-08-02 09:59 UTC
I know.. ie 11.
For some reason it places a cursor next to the select when it is not searchable or a creatable.
If the multi prop is on, the cursor is displayed with an offset to left inside of the last selected element.

Visual:
![ie11](https://user-images.githubusercontent.com/8947166/43577221-8de3e834-964b-11e8-8227-91f7229c2535.gif)

Is this fixable?

**Comment by kaiohon** [comment] 2018-08-02 12:02
Caused by "left: -100" in DummyInput.js

**Comment by kaiohon** [comment] 2018-08-02 14:56
Adding textIndent: '-99999999em', solves the issue, btw.

**Comment by gwyneplaine** [comment] 2018-08-03 00:53
thanks for this @lucletruc, we'll have a look at resolving this in the following release

**Comment by digzit** [comment] 2018-08-15 13:12
![capture d ecran 2018-08-15 a 09 11 33](https://user-images.githubusercontent.com/1471374/44149776-3fd5b3e6-a06b-11e8-9f4a-1d4173069600.png)

its work for me with this fix

**Comment by Tenkir** [comment] 2018-10-19 19:59
Why not just use `-ms-user-select:none`? Seems like a more direct solution.

**Comment by bladey** [comment] 2020-05-28 01:46
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Closed by bladey** 2020-05-28 01:46 UTC
