### ISSUE TITLE
optgroup support?

### ISSUE THREAD

**Issue by abhinavsingi** [JedWatson/react-select#445] opened 2015-09-14 09:04 UTC
There's no optgroup support in reac-select as of now. Is it on a roadmap?

**Comment by SoonDead** [comment] 2015-09-23 14:13
+1

This would be very good.

**Comment by brianreavis** [comment] 2015-09-24 19:53
Please search for similar issues before creating them (duplicate of https://github.com/JedWatson/react-select/issues/59)

**Closed by brianreavis** 2015-09-24 19:53 UTC
