### ISSUE TITLE
If matchPos is set, ignoreCase is ignored

### ISSUE THREAD

**Issue by at0g** [JedWatson/react-select#264] opened 2015-06-22 07:09 UTC

**Comment by bruderstein** [comment] 2015-07-31 15:35
I can't reproduce this.  Note that the default "matchProp" is "any", hence it will search the values too, so if you've got options as in the example:
```
options = [ { value: 'one', label: 'One' }, 
		{ value: 'two', label: 'Two' },
		{ value: 'three', label: 'Three' }
];
``` 
and type `o`, you'll get the first value even with `ignoreCase={true}`, as it matches the value.
Set the `matchProp="label"` to only check the label.

**Comment by bruderstein** [comment] 2015-08-10 21:40
Going to close this as we've had no feedback, and I can't reproduce it. If you're still having the issue, feel free to comment and we'll reopen it.

**Closed by bruderstein** 2015-08-10 21:40 UTC

**Comment by at0g** [comment] 2015-08-11 11:11
My apologies for the slow reply. The issue that I experienced back in June involved setting `{matchPos: 'start', ignoreCase: true}`. Perhaps something has changed since then, I'll reopen the issue if I can reproduce it.

In your first comment you mention the `matchProp` property. I presume when trying to replicate you were in fact using `matchPos`?

**Comment by bruderstein** [comment] 2015-08-11 13:44
I just meant that due to the example having `Two` as the label, and `two` as the value, that even when `ignoreCase={false}`, it will still find the value when entering `tw`, as `matchProp` has a default of `any`, hence it will match the value too.

`ignoreCase` also defaults to `true`, so this would be very strange if this didn't work! :smile:

**Comment by MbF-Vijayaragavan** [comment] 2018-08-23 09:29
in react-select 2.0.0 there is no props to filter
