### ISSUE TITLE
"Enter" don't fully work in "creatable" example

### ISSUE THREAD

**Issue by erikkrantzkb** [JedWatson/react-select#4191] opened 2020-09-02 05:24 UTC
I am experience a bug in the "Multi-select text input" example on https://react-select.com/creatable.

In the "Multi-select text input"-input I do the following:
1. Type "something"
2. Press ENTER to create a gray box with the word "something" in
3. Click on the "x" in the gray box or press BACKSPACE to remove the gray box
4. Type "something" again
5. Press ENTER <- This do nothing!!

Note: If I click on the big X on the right side of the whole input instead of step 3, step 5 works.

**Comment by ebonow** [comment] 2020-09-02 15:36
Duplicate of #4122 

There is a MR pending that should resolve this.

**Closed** 2020-10-01 06:36 UTC
