### ISSUE TITLE
Menu disappears when scrollbar is touched (when not searchable)

### ISSUE THREAD

**Issue by pjm17971** [JedWatson/react-select#471] opened 2015-09-22 23:02 UTC
The fix for #397 doesn't seem to work for the case where the selector is not searchable (searchable=false). The menu vanishes when the scrollbar is touched.

![chooser-bug](https://cloud.githubusercontent.com/assets/1288813/10034115/ecfd6156-6142-11e5-8ceb-7d290e3e4541.gif)

**Comment by burtyish** [comment] 2015-09-24 08:04
👍

**Comment by burtyish** [comment] 2015-09-24 08:32
When the menu is not searchable, this code in `handleMouseDown` causes the menu to close:
```
// for the non-searchable select, close the dropdown when button is clicked
if (this.state.isOpen && !this.props.searchable) {
	this.setState({
		isOpen: false
	}, this._unbindCloseMenuIfClickedOutside);
	return;
}
```
https://github.com/JedWatson/react-select/blob/master/src/Select.js#L367-L372

The code is supposed to close an open non-searchable menu when the `Select-control` is clicked (see #211). The problem is that `handleMouseDown` is used for both the `Select-control` *and* the menu. So clicking on the scrollbar triggers this code in the handler, closing the menu.

**Closed** 2015-10-02 08:16 UTC
