### ISSUE TITLE
componentWillReceiveProps has been renamed, and is not recommended for use.

### ISSUE THREAD

**Issue by vibhorme** [JedWatson/react-select#3770] opened 2019-09-21 06:05 UTC
While using the react-select v2 Async Select component there is a warning being rendered in the devtools regarding the use of componentWillRecieveProps, which has been updated and renamed in the new Updates in ReactJs.

The warning is 

**Warning:** componentWillReceiveProps has been renamed, and is not recommended for use.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Can we update the files of the async and select folder present in the node_modules because it needs to be updated as per the new code structure in ReactJs

**Comment by mpopv** [comment] 2019-09-23 14:51
Duplicate of #3720

**Comment by ranneyd** [comment] 2019-09-25 17:11
https://github.com/JedWatson/react-select/issues/3720#issuecomment-535120385

You can use this while this lib gets sorted out

**Comment by ranneyd** [comment] 2019-10-02 21:51
Latest version of lib is fixed fyi

**Comment by mitchellhamilton** [comment] 2019-10-03 00:37
Thanks for the issue, closing since this is now fixed!

**Closed by mitchellhamilton** 2019-10-03 00:37 UTC
