### ISSUE TITLE
Edit the selcted value

### ISSUE THREAD

**Issue by magdalko** [JedWatson/react-select#2296] opened 2018-01-16 10:46 UTC
Hi,

What I would like to do is to edit the selected value. I am passing the value as a state to the value attribute. And it shows the text, but when I try to edit it, I cant because the cursor is in the beginning. So I am forced to type the name form the beginning even though the thing i am searching for is containing the part of the selected value (ex. Selected: exampleName1; want to search: example2; I would just use the backspace and edit the text but can't). Is there any work around for this issue? :) 

Thanks for help!

**Comment by yuri-sakharov** [comment] 2018-01-17 03:14
Hi, 
It looks like related to https://github.com/JedWatson/react-select/issues/2277

**Comment by speedo-sp7** [comment] 2018-07-30 09:14
Same issue here

**Comment by mohsinhere** [comment] 2018-11-28 22:31
Still appears to be an issue...

**Comment by mohsinhere** [comment] 2018-11-28 22:32
> Hi,
> 
> What I would like to do is to edit the selected value. I am passing the value as a state to the value attribute. And it shows the text, but when I try to edit it, I cant because the cursor is in the beginning. So I am forced to type the name form the beginning even though the thing i am searching for is containing the part of the selected value (ex. Selected: exampleName1; want to search: example2; I would just use the backspace and edit the text but can't). Is there any work around for this issue? :)
> 
> Thanks for help!

Did you find any work around for this?

Thanks!

**Comment by ebonow** [comment] 2020-12-02 19:18
Greetings all, I have addressed this in several other places and [started a discussion](https://github.com/JedWatson/react-select/discussions/4302) about making this potentially easier but the approach is fairly straight forward to roll your own.

1. Create a custom Input to ensure isHidden is always false
``` JS
const Input = props => <components.Input {...props, isHidden: false } />
```

2. Make the input controlled so we can override the inputValue when an option is selected or the input is blurred.
``` JS
  const [value, setValue] = useState();
  const [inputValue, setInputValue] = useState("");

  const onInputChange = (inputValue, { action }) => {
    // onBlur => setInputValue to last selected value
    if (action === "input-blur") {
      setInputValue(value ? value.label : "");
    }

    // onInputChange => update inputValue
    else if (action === "input-change") {
      setInputValue(inputValue);
    }
  };

  const onChange = (option) => {
    setValue(option);
    setInputValue(option ? option.label : "");
  };
```

3. Hide the rendered value component with the prop `controlShouldRenderValue`

Putting this all together looks like this...
``` JS
const Input = props => <components.Input {...props, isHidden: false } />

const [value, setValue] = useState();
const [inputValue, setInputValue] = useState("");

const onInputChange = (inputValue, { action }) => {
    // onBlur => setInputValue to last selected value
    if (action === "input-blur") {
      setInputValue(value ? value.label : "");
    }

    // onInputChange => update inputValue
    else if (action === "input-change") {
      setInputValue(inputValue);
    }
};

const onChange = (option) => {
    setValue(option);
    setInputValue(option ? option.label : "");
};

return (<Select
  value={value}
  inputValue={inputValue}
  onInputChange={onInputChange}
  onChange={onChange}
  controlShouldRenderValue={false}
  components={{ Input }}
  ...
/>)
```
[Here is the corresponding sandbox](https://codesandbox.io/s/react-select-editable-and-selectable-6nfdv?file=/src/App.js) which allows the user to freely type and edit into the input as would be expected behavior of an input.

That said, there is a dedicated discussion to share more thoughts if this were to be an internal prop to manage this, but in lieu of that, it is possible to accomplish this nonetheless.

As such, I will be closing this issue as more discussion about this can be had in the discussions channel with the provided link above.

**Closed by ebonow** 2020-12-02 19:18 UTC
Labels: category/question, issue/enhancement, issue/reviewed
