### ISSUE TITLE
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by yrshaikh** [JedWatson/react-select#1973] opened 2017-09-10 10:02 UTC
I am trying to setup react-select in my project which using react with jsx. I get this error on adding this line after npm install react-select.

import Select from 'react-select';

SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

**Comment by miketierney** [comment] 2017-09-10 16:26
I suspect that this and #1974 are related.

I'm also seeing this error - reverting to 1.0.0-rc.5 fixes the issue, so it's something that was introduced in the latest release.

**Comment by agirton** [comment] 2017-09-11 02:52
Closing as a duplicate of #1971

**Closed by agirton** 2017-09-11 02:52 UTC
