### ISSUE TITLE
Invariant Violation: addComponentAsRefTo() when using react-addons

### ISSUE THREAD

**Issue by dperetti** [JedWatson/react-select#112] opened 2015-03-28 15:38 UTC
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.

I get this error message when trying to use react-addons. Weird.

**Comment by dcousens** [comment] 2015-05-07 04:34
I believe this was fixed in #88.  @dperetti can you please confirm?

**Comment by raghur** [comment] 2015-05-13 06:06
same here.

**Comment by dcousens** [comment] 2015-05-18 06:58
@raghur you can confirm this still occurs?
Can you please provide reproduction steps?

**Comment by raghur** [comment] 2015-05-18 11:43
@dcousens I tested on a fresh workspace trying to get a minimal example and I cannot reproduce it with the latest react. Most likely we were probably still running an older version.

The only other thing I can think of that is different is that in my actual project all files have `require('react')` and in only one I had `require('react/addons')`.

**Comment by dcousens** [comment] 2015-08-13 06:28
Thanks for the update @raghur

**Closed** 2015-08-13 06:28 UTC
Labels: bug	(unconfirmed)
