### ISSUE TITLE
Docs page broken

### ISSUE THREAD

**Issue by junaid7lone** [JedWatson/react-select#1611] opened 2017-03-21 04:02 UTC
![selection_065](https://cloud.githubusercontent.com/assets/572126/24132149/4ba0ba4e-0e19-11e7-8f9e-9f93c1a54425.png)

**Comment by dtipson** [comment] 2017-03-27 15:17
Duplicate of https://github.com/JedWatson/react-select/issues/1619

**Comment by JedWatson** [comment] 2017-03-29 23:51
Fixed by #1621

**Closed by JedWatson** 2017-03-29 23:51 UTC
