### ISSUE TITLE
Getting unexpected border inside input field

### ISSUE THREAD

**Issue by studiolama** [JedWatson/react-select#5693] opened 2023-07-05 11:35 UTC
I am unable remove this border from input field

<img width="448" alt="Screenshot 2023-07-05 at 4 40 13 PM" src="https://github.com/JedWatson/react-select/assets/120262075/53e8b6cb-6605-4625-8ff0-1f80e14e15fc">

I tried giving border: 0 inside input custom styles but still this is always showing
Any solution to remove this and also in menu dropdown there is no scrollbar coming.

| Platform/Library | Version |
|--------|--------|
| Mac OS | 13.4.1 (22F82) |
| Next.js | 13.4.4 |
| React-select | ^5.7.3 |
| Chrome Browser | Version 114.0.5735.198 (Official Build) (arm64) |

**Comment by ckalas** [comment] 2023-07-21 13:12
experiencing this too. i have a feeling for me its coming from tailwind-forms but haven't worked out why exactly yet

**Comment by Rall3n** [comment] 2023-07-21 13:29
Hello @studiolama an @ckalas,

this issue was already raised in #5062 and #4794.
The cause of this problem is third-party styling libraries adding basic styles to form elements (e.g. `@tailwindcss/forms`).

Either exclude those libraries from your build process or adjust styling generally or for `react-select` specifically using the provided [styling framework](https://react-select.com/styles).

-----
I will close this issue as being a duplicate and not a problem coming from `react-select`.

**Closed by Rall3n** 2023-07-21 13:29 UTC
Labels: issue/bug-unconfirmed
