### ISSUE TITLE
"Select Props" documentation duplication

### ISSUE THREAD

**Issue by benhummon** [JedWatson/react-select#5108] opened 2022-03-15 16:35 UTC
On https://react-select.com/props#select-props most of the props are listed twice. In particular,

- `form`
- `aria-errormessage`
- ...
- `tabIndex`
- `tabSelectsValue`

are listed and then listed a second time.

**Comment by Methuselah96** [comment] 2022-03-15 16:40
Duplicate of https://github.com/JedWatson/react-select/issues/4889.

**Closed by Methuselah96** 2022-03-15 16:40 UTC
Labels: issue/bug-unconfirmed
