### ISSUE TITLE
ignoreCase = true (default behavior) lowercases all user input

### ISSUE THREAD

**Issue by caguthrie** [JedWatson/react-select#1352] opened 2016-11-03 18:54 UTC
This code in ```Async.js``` causes all user input to be ```toLowerCase```'d:

```
if (ignoreCase) {
  inputValue = inputValue.toLowerCase();
}
```

Why does this exist?  If A user types an uppercase character and a lowercase character is printed, that would be confusing for the user.  I'm happy to submit a PR removing this conditional unless there is a workaround I'm not aware of or if there is a valid reason for this code.

**Comment by erfangc** [comment] 2016-11-03 18:56
+1

**Comment by ee08b397** [comment] 2016-11-03 19:10
why

**Comment by scags9876** [comment] 2016-11-04 23:18
Is this a duplicate of https://github.com/JedWatson/react-select/issues/1106 ?

**Comment by saviomuc** [comment] 2016-11-11 16:03
@JedWatson Any chance we can get this fixed? There are already some PRs like this one https://github.com/JedWatson/react-select/pull/1329. Honestly I'd prefer to just have ignoreCase not lowercasing the input at all. Happy to provide a PR if you agree.

**Comment by alexanderteno** [comment] 2017-02-02 22:54
Bump: I'm suffering from this on an Async call, seems if I backup and retype the input it doesn't swap capitalization on a per letter basis. It's very strange. Anyone know a workaround or some sort of soft fix?

**Comment by BossGrand** [comment] 2017-04-07 19:32
Is there any work or thought being done on this? Is there a workaround?

**Comment by BorodinDK** [comment] 2017-04-14 18:23
+1

**Comment by ericnewcomer** [comment] 2017-05-24 02:41
FWIW I'm still seeing this behavior when ignoreCase={true}. I think the fixes proposed previously to not manipulate the user input during async evaluation seems like the right one. For some reason that PR was never merged. Is a new PR welcomed to address this?

**Comment by agirton** [comment] 2017-05-24 03:49
Hey @ericnewcomer depending on the outcome of #1329, we may need a new PR to just remove all mutation of the `inputValue`

**Comment by ericnewcomer** [comment] 2017-05-24 03:55
Also, I did confirm that commenting out that single line does seem to do the trick. I'm really unsure why we would want to maintain that behavior in any case. We can muck with a copy of the input all we want (removing diacritics, etc), but we ought not overwrite what the user is typing.

**Comment by sponrad** [comment] 2017-06-14 18:18
> remove all mutation of the inputValue

That gets my vote for this. Simple fix.

**Comment by not-an-aardvark** [comment] 2017-07-05 20:35
I created a new PR at https://github.com/JedWatson/react-select/pull/1858.

**Closed** 2017-07-06 03:50 UTC
