### ISSUE TITLE
Feature Request (v2): Wait until focus before calling loadOptions

### ISSUE THREAD

**Issue by ernestopye** [JedWatson/react-select#2660] opened 2018-05-30 14:58 UTC
Apologies if this is already supported, but I wasn't able to figure this out. Went through select's code too. I have a workaround in place, but I don't love it. You can read about it here: [StackOverflow](https://stackoverflow.com/questions/48564764/load-options-on-the-first-open-of-the-async-drop-down-menu/50607594#50607594)

**Note:** The accepted answer has a solution for 1.x with a code sample. This is exactly what I'm trying to accomplish.

**Use case:** 
We are using react-select in an admin area, where there may be lots of them within the same page (10+). We want the values to be loaded on demand. We also need to display options even if a user just clicks on the dropdown (which is normally handled by defaultOptions).

**The problem:**
Currently, if you set `defaultOptions` to true, and include `loadOptions`, the latter will be called on mount. This is normally good UX, as you'll let the browser handle loading these before the field is even in focus, so that the values are in there right away. However, in our use case, because we have so many of these, we would end up making far too many requests to the server. What's worse for us, is that most of the time users won't even be clicking on these at all, so we really don't need the values to be loaded unless the user is actually focusing the select field.

**The feature:**
I'm not sure what would be the best way to approach this. But basically it would be some kind of flag that would defer calling loadOptions until the select field is focused. Perhaps `deferLoadOptionsUntilFocus`?

It would be really nice if this was supported out of the box, to avoid having to write extra for this each time, but there very well may be a reason for this design choice. Anyway, thanks for react-select, it's just fantastic, and let me know if I can provide any more details or help with the actual changes if you're interested in implementing this.

Thank you!

**Comment by arorayash** [comment] 2018-11-28 03:31
Any updates on this? I'm currently facing the same issue. We have multiple Async Selects and storing the option results for all is not feasible.

**Comment by mike391** [comment] 2019-01-14 16:50
As a workaround, you can make a wrapper component that contains an async react-select field.  In the wrapper, add these props to your `async select`:
`defaultOptions = {this.state.defaultOptions}, 
onFocus = {this._handleFocus}`

Define a _handleFocus function in the wrapper like so:

`_handleFocus = ()=>{
        this.state.initialOptionLoad &&
            this.setState({ defaultOptions: [your full options list], initialOptionLoad: false })
}`

Where `[your full option list]` should be replaced with your full set of options that you want to load in.

This will cause your react-select component to rerender with the proper default options when first focused.

You can also trigger the same operation by using `onMenuOpen` as well. Not sure if there are any side effects as of yet.

**Comment by brunoracosta** [comment] 2019-12-11 20:24
Any updates on this?

**Comment by OskarPersson** [comment] 2020-01-06 17:07
Duplicate of #1525?

**Comment by bladey** [comment] 2020-06-17 03:16
Hi all, I'm closing this issue in favor of #1525, we'll use the information detailed here when investigating the issue.

**Closed by bladey** 2020-06-17 03:16 UTC
Labels: cat/enhancement

**Comment by shpsyte** [comment] 2020-09-29 21:46
Any update?

**Comment by yoieh** [comment] 2022-02-15 15:55
> Hi all, I'm closing this issue in favor of #1525, we'll use the information detailed here when investigating the issue.

You closed this issue in favor if #1525 then you closed #1525 do to more information in this one.... Why i sent this reopen?

**Comment by Alejandroid17** [comment] 2023-03-16 14:15
Any update?
