### ISSUE TITLE
Misleading TypeScript documentation

### ISSUE THREAD

**Issue by emilie-t-ledn** [JedWatson/react-select#5214] opened 2022-06-02 14:28 UTC
I'm not the most familiar with TypeScript, but it seems that the section regarding "Wrapping the Select component
" https://react-select.com/typescript in this page is wrong, as I spend lots of hours trying to fix TS errors while using the generic, only to found out that removing them fixed the issues.

More information can be seen at the end of this thread when a solution suggested to me was to remove the generics
https://github.com/JedWatson/react-select/issues/3851#issuecomment-1143792522

Some more information or example might be needed in this page.

Thanks

**Comment by Methuselah96** [comment] 2022-06-02 17:11
Since neither your styles nor your custom `ControlComponent` rely on the option type, you should be able to just remove the generics for `StylesConfig` and `ControlProps` and it should just work.

**Comment by emilie-t-ledn** [comment] 2022-06-03 13:32
Do you have a working, do you mean I should be able to keep the generic on the Select wrapper and removed them everywhere else?

**Comment by Methuselah96** [comment] 2022-06-06 14:04
[Yes](https://codesandbox.io/s/codesandboxer-example-forked-lui10t?file=/example.tsx).

**Comment by michaelmccomiskey** [comment] 2022-11-14 16:12
@Methuselah96 I am having an issue when providing a type for the Option generic. The reason I am providing this type is to be able to access the `props.data` for the MultiValue component to provide a custom Tag. Without a type, `data` is `unknown`. 

I was able to successfully provide a type for this but then this introduced another typescript issue with the `styles` prop where the StylesConfig types do not match. 

Here is a codesandbox with the issue reproduced. 
https://codesandbox.io/s/silly-frost-5o3mph?file=/src/App.tsx

It seems moving the styles into the component and passing down the generics solves the issue. This is not preferred as it would be nice to put the styles in their own file. 

Please let me know if I am doing something wrong in the example or there is an issue with `react-select` types.

**Comment by michaelmccomiskey** [comment] 2022-11-15 16:13
Awesome! Thank you so much. I was thinking of going the `createStyles` route. That seems to work great. 

Perhaps we should close this issue?

**Closed** 2022-11-15 16:14 UTC
Labels: issue/bug-unconfirmed, awaiting-author-response
