### ISSUE TITLE
Creatable: when `promptTextCreator` returns only the entered text, changes don't fire on first Enter key press

### ISSUE THREAD

**Issue by tmikoss** [JedWatson/react-select#2125] opened 2017-11-01 05:35 UTC
When `promptTextCreator` of `Creatable` returns only the user-entered label, you can't select the newly entered value on first Enter keypress, only the second one will trigger changes.

From what I managed to debug, this is due to the new entry being pushed into `options` prop somewhere along the way, and then failing the uniqueness check.

Minimal reproduction: https://github.com/tmikoss/react-select-creatable-bug-repro/blob/master/src/index.js (repo root is runnable, built by `create-react-app`).

**Comment by alexanderzobnin** [comment] 2017-11-02 15:41
Faced the same issue.

**Comment by pidov** [comment] 2017-11-09 10:29
+1 on this one

**Comment by Khvalin** [comment] 2017-11-09 15:55
yeah, the issue is a pretty annoying one

**Comment by JedWatson** [comment] 2017-11-19 22:22
Fixed by #2140

**Closed by JedWatson** 2017-11-19 22:22 UTC
