### ISSUE TITLE
Dropdown doesn't close when I click outside the dropdown

### ISSUE THREAD

**Issue by ghost** [JedWatson/react-select#2239] opened 2017-12-20 13:29 UTC
Hi when I show the dropdown menu and then click outside the region of dropdown it doesn't close.
Why?

Here is how I create it
```

 <Select name="fieldcombo"
               value={this.state.comboFieldValue}
               onChange={this.handleFieldComboChange.bind(this)}
               simpleValue
               openOnClick={false}                    
               clearable={true}
               options={selectData}
                />
```

**Comment by jvega** [comment] 2017-12-20 23:26
I have the same issue apparently the version compiled doesn't match with source code @JedWatson 

![source-compiled](https://user-images.githubusercontent.com/926380/34233412-918bfc42-e5bb-11e7-9513-7f1b39069bc6.png)

**Comment by jonathanwmaddison** [comment] 2018-01-02 16:01
I am also having this issue.

**Comment by davidhesson** [comment] 2018-01-03 01:53
It works fine on the website/demo page, but I'm stuck on this too

**Comment by davidhesson** [comment] 2018-01-03 01:58
@jvega it seems more related to the fact that the drop down input doesn't gain focus (at least for me) when I click the arrow to reveal the drop down contents. If I click outside of the dropdown and it doesn't have focus, it doesn't auto hide the drop down contents.

On the demo page, if you click the drop down arrow, the selects gain focus automatically, but I don't see anything in the example code causing that to happen manually, so it seems like it's a library feature that isn't working.

**Comment by angelcustodio** [comment] 2018-01-10 11:30
Same here.
Also, it works properly on a tablet/smartphone. Weird.

**Comment by jvega** [comment] 2018-01-10 13:54
if you check the screenshots that I attach above, the compiled version that was distributed trough NPM (21 days ago) it doesn't match with source version, the `event.stopPropagation()` is outside the if when the dropdown is open

1.2.0 version fix this bug

**Comment by ConAntonakos** [comment] 2018-01-10 22:29
Thanks for reporting this. I can confirm after upgrading from 1.1.0 to 1.2.0 that the outside click bug has been resolved.

**Comment by angelcustodio** [comment] 2018-01-15 16:40
I've update the package in my project to the 1.2.1 version and it's still not working :/

**Comment by vitorhorta** [comment] 2018-01-15 17:09
Same here, not working on 1.2.1

**Comment by jdbdnz** [comment] 2018-05-24 21:35
I had this issue when I applied a `display: none` style to the `div[role="combobox"]`. Removing that style fixed the issue. But it reintroduced the issue where that div was messing up the display of other elements. That I fixed with a `position: absolute` and `height: 0`.

**Comment by NiceGuyNimni** [comment] 2019-02-25 14:10
Could it be that this change caused an issue where in multi select, once I click an option it always closes the drop down even if I set the prop 'closeOnSelect' to false?

My props are:
multi=true,
closeOnSelect=false

**Comment by arihantR** [comment] 2020-02-10 15:00
I faced the same issue, not able to close the multi select dropdown when I click outside it. It works fine for normal dropdown. Any solution. I have the latest version of react-select installed.

**Comment by deniswvieira** [comment] 2020-03-11 10:23
Same problem with "react-select": "3.0.8"

**Comment by bladey** [comment] 2020-06-17 03:02
Hi @deniswvieira and @juliocarneiro, I'm unable to replicate this with a multi select dropbox, could you please provide a CodeSandbox with the same options you're using so I can look into this further, and also let me know which browser version you're having trouble with.

I've created one here for my testing - https://codesandbox.io/s/react-select-v3-sandbox-nl4yg

**Comment by bladey** [comment] 2020-06-29 04:44
This issue will now be closed due to inactivity. If anyone can reproduce this bug and provide a Codesandbox example, please let me know and the issue will be re-opened.

**Closed by bladey** 2020-06-29 04:44 UTC
Labels: awaiting-author-response, issue/bug-unconfirmed

**Comment by kulkarnipradnyas** [comment] 2020-07-30 13:54
IndicatorSeparator: () => null,
          DropdownIndicator: DownArrowIndicator,
          LoadingIndicator: () => null,
          ValueContainer: () => null,
          Option: ColumnOption

If such configuration provided, as valueconatiner is null, it will not close your optionbox on outside click.If anyone have solution.Please provide.

**Comment by binoyskumar92** [comment] 2021-01-12 21:28
If value container is not displayed then this issue happens. I suppose that it uses some kind of css or some property from the value container for the close operation when clicked outside.

**Comment by ebonow** [comment] 2021-01-12 23:19
@binoyskumar92 correct.

The react-select component relies on the Input remaining focused. When then Input is blurred, then the state is changed and window closed (if not controlled).Since the Input is inside the ValueContainer, this mechanism essentially breaks. 

However, as long as there is another component within the Control that can maintain focus, you can conceivably workaround this. Here is a similar issue working with a custom Control (with no ValueContainer) https://github.com/JedWatson/react-select/issues/4279. If you scroll down a bit to [here](https://github.com/JedWatson/react-select/issues/4279#issuecomment-740081627),  I created a solution demonstrating how to open/close the menu

demo: [codesandbox](https://codesandbox.io/s/react-select-focus-testing-270xv?file=/src/App.js)

Let me know if you have any other questions.

**Comment by tania-balto** [comment] 2021-05-26 19:10
This issue should not be closed, it's still relevant. If ValueContainer is set then the dropdown won't close.

**Comment by ebonow** [comment] 2021-06-10 16:55
Greetings @tania-balto 

> If ValueContainer is set then the dropdown won't close.

Can you elaborate or better yet include a codesandbox demonstrating the incorrect behavior?

**Comment by here-kulkarni** [comment] 2021-06-11 05:03
@tania-balto I found a workaround, wrap your component <divid='someid"><select...></div> and then https://www.codegrepper.com/code-examples/javascript/add+event+when+click+outside+div try this on someid.

**Comment by tania-balto** [comment] 2021-06-15 18:18
Greetings, @ebonow. Sorry for the curt response. In my case, I used this code to update the value container to display "{x} selected" if more than one item is selected, and show the item itself if only one is selected, which hopefully helps anyone in the future. 

```js
const ValueContainer = ({ children, ...props }) => {
  const { length } = props.getValue();
  const selectOptionsAndInput = React.Children.map(children, (child) => {
    if (child && [components.SingleValue].indexOf(child.type) === -1) {
      return child;
    }
    return null;
  });

  const searchInput = last(selectOptionsAndInput);

  if (length > 1) {
    return (
      <components.ValueContainer {...props}>
        <div className="option-label">{`${length} selected`}</div>
        {searchInput}
      </components.ValueContainer>
    );
  }

  return <components.ValueContainer {...props}>{selectOptionsAndInput}</components.ValueContainer>;
};
```

The dropdown wouldn't close if I clicked outside, but it was because I tried currying and passing a value in at the `components={{ ValueContainer }}` level. (I was doing ``components={{ ValueContainer(someVal) }}`). So as long as you don't do that and define ValueContainer outside of the component, it should work without an issue. Hopefully this helps someone else who comes along this.

**Comment by ebonow** [comment] 2021-06-15 21:34
@tania-balto ,

I'm glad you were able to get this resolved. This isn't an uncommon issue and recently this section was added to the documentation to better help identify this frustrating behavior.
https://react-select.com/components#defining-components

Regarding your solution, have you tried overriding the `MultiValue` instead of the `ValueContainer`? There is an `index` prop that is passed into the MultiValue component which might be helpful and likely would be a cleaner solution.

[codesandox demo
](https://codesandbox.io/s/react-select-multivalue-index-fpg87)

```jsx
const MultiValue = ({ props }) => {
  if (props.index > 0) return null;
  
  const { length } = props.getValue();
  return (length > 1) 
      ? <div className="option-label">{`${length} selected`}</div>
      :  <components.MultiValue {...props} />
}
```

The component prop does not seem to appear in the documentation anymore so I'll look into what happened there but likely something lost in translation from Flow to TypeScript.

**Comment by tania-balto** [comment] 2021-06-15 21:40
Thanks for the follow up, I'll try that out. I think I tried that approach earlier but it probably wasn't working due to the issue I resolved, so I'll try again.

**Comment by andrewpashko** [comment] 2021-11-26 16:27
I got this issue but in another case 
I'm creating list of options that consist of groups 
And this groups acts like accordeons you can expand and condense them 
and when you click on group it's not possible to close dropdown
<img width="411" alt="Знімок екрана 2021-11-26 о 18 26 55" src="https://user-images.githubusercontent.com/23315851/143609516-903e71fe-52fa-4fb0-94bf-5f17149dde05.png">

**Comment by ebonow** [comment] 2021-11-28 16:58
@andrewpashko would you kindly create a new discussion under q&a preferably with a codesandbox link so that someone can help you with your particular implementation.
