### ISSUE TITLE
onChange not firing

### ISSUE THREAD

**Issue by erolsmsr58** [JedWatson/react-select#2038] opened 2017-10-05 16:41 UTC
I have implemented the component, but the onChange is not firing no matter what I do.

My code looks like this:

`
<Select
      name='select-user'
      value={this.state.selectedUser}
      options={this.selectUserOptions}
      onChange={() => { alert('change!') }}
      placeholder='Selecteer een gebruiker'
      className='dark-select' />
`

I put the alert directly in the onChange property to make sure it isn't a scoping issue with the logChange method. But even this alert doesn't show.

I've used this component before and I'm familiar with it, which surprises me even more as this component has always functioned properly.

Any idea why the onChange doesn't fire, even if I call the alert directly inside the onChange?

**Comment by agirton** [comment] 2017-10-06 03:14
Hi @pro-soft-git it's hard to say why this is not firing in your application. If you feel this is a bug in the package please provide a reproducible case.

**Comment by pro-soft-git** [comment] 2017-10-10 10:00
Hi @agirton, I tried reproducing it and it works perfectly. It only doesn't work in a specific application, so I have to figure out what's causing this. I will report it here if it's something that can be fixed in react-select to prevent this in the future.

For now, you can ignore this, but could you keep this ticket open until I figure out what the issue is on my end (it may be a react-select issue after all)?

Thanks.

**Comment by edude03** [comment] 2017-12-02 05:51
I'm using React 16 and I'm noticing onChange isn't firing for me either

**Comment by Arthelon** [comment] 2017-12-04 09:44
Any updates on this issue? I'm encountering this issue on React v15.6.1

**Comment by pro-soft-git** [comment] 2017-12-04 10:24
Try using it with React and React-Dom version ^16.0.0-beta.5. On this version of v16, it does work for me.

**Comment by bladey** [comment] 2020-05-27 06:33
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.

**Closed by bladey** 2020-05-27 06:33 UTC
Labels: bug-unconfirmed, question
