### ISSUE TITLE
Can't close result list on mobile phone

### ISSUE THREAD

**Issue by jonashaag** [JedWatson/react-select#1490] opened 2017-01-17 15:35 UTC
Problem: You can't click the chevron to close the search result list on mobile phones (iPhone, Android). Desktop works. Opening the list works.

1.0-rc2

**Comment by JedWatson** [comment] 2017-10-27 05:12
I believe this has been fixed in a more recent PR, can't reproduce on my iPhone

**Closed by JedWatson** 2017-10-27 05:12 UTC
