### ISSUE TITLE
Custom search inside options

### ISSUE THREAD

**Issue by Spaider15** [JedWatson/react-select#5234] opened 2022-06-20 08:11 UTC
Hi everyone, i need to add custom search inside dropdown menu, but can't focus input, here an example: 
https://codesandbox.io/s/codesandboxer-example-forked-evg7wj?file=/example.tsx
open menu and try to focus input inside menu

**Comment by tnyidol** [comment] 2022-08-25 18:15
@Spaider15 , were you able to get solution for this issue? As i have recently faced this issue.

**Comment by Rall3n** [comment] 2022-09-15 06:18
Hello @Spaider15,

based on the gist of this issue I would categorize it as a duplicate of #3111 and would close it as such.
[This comment](https://github.com/JedWatson/react-select/issues/3111#issuecomment-470911304) provides an implementation which still works with the current version.

**Closed by Rall3n** 2022-09-15 06:18 UTC
Labels: issue/bug-unconfirmed

**Comment by Spaider15** [comment] 2022-09-15 06:19
> @Spaider15 , were you able to get solution for this issue? As i have recently faced this issue.

nope
