### ISSUE TITLE
Border around cursor when using Createable

### ISSUE THREAD

**Issue by amolpatel** [JedWatson/react-select#5062] opened 2022-02-17 18:54 UTC
Hi all,

I'm using `Createable` and running into a weird CSS bug. I'm noticing a border around the cursor. We are using tailwind in our project but I'm not sure how that would impact this component.

![CleanShot 2022-02-17 at 13 52 34@2x](https://user-images.githubusercontent.com/6493663/154550737-cf4b9a42-15eb-471b-8251-ebfa8f1b4cd7.png)

Usage:

```javascript
<CreatableSelect
    isClearable
    placeholder="Select or manually enter..."
    onChange={(newValue: any, actionMeta: ActionMeta<any>) => {
      if (newValue) {
        onChange(newValue.value);
        return;
      }
      onChange(null);
      return;
    }}
    defaultValue={defaultValue}
    options={options}
  />
```

Any help would be appreciated!

**Comment by Rall3n** [comment] 2022-02-18 06:42
Hello @amolpatel,

this problem was already mentioned in issue #4794 with a solution available.

I will close this issue as being a duplicate of the other.

**Closed** 2022-02-18 06:42 UTC
Labels: issue/bug-unconfirmed
