### ISSUE TITLE
Value is assumed to be string

### ISSUE THREAD

**Issue by sudodoki** [JedWatson/react-select#61] opened 2015-02-11 02:06 UTC
https://github.com/JedWatson/react-select/blob/master/lib/Select.js#L367 this code might break if values is number instead of string.
Thanks for the component.

**Comment by julen** [comment] 2015-02-14 08:57
This is a dupe of #25.

**Comment by dcousens** [comment] 2015-05-07 03:35
@JedWatson unless you have a change of heart on this/#25.  Closing.

**Closed by dcousens** 2015-05-07 03:35 UTC

**Comment by dcousens** [comment] 2015-05-07 04:18
Duplicate.
