### ISSUE TITLE
Creatable multi select  "Create"  word added with new option randomly, while pasting and adding the new option.

### ISSUE THREAD

**Issue by reidharry** [JedWatson/react-select#4122] opened 2020-07-13 09:04 UTC
# Are you asking a question?

No, reporting a bug

# Are you reporting a bug or runtime error?

Bug. When adding a new option by pasting the content in the Creatable multi-select   "Create" option also added with a new option randomly. I have checked in the [demo](https://react-select.com/creatable) also bug was reproduced,  Steps to reproduce given below along with bug video also attached for your reference. 

## Bug video

![Creatable - React Select (1)](https://user-images.githubusercontent.com/16623277/87285724-78ce6a00-c515-11ea-832f-6d0d86693153.gif)

## Steps to reproduce
1. Paste some words in the select box, and click "Create new" option which shows up.
2. Then, remove the added word, again paste the same word and click  "Create new" option,  that case "Create" word also added with option

**Comment by hmtri1011** [comment] 2020-07-13 09:40
Same here, seem like it is a bug, in my case I have customized `formatCreateLabel` and `onCreateOption`
![image](https://user-images.githubusercontent.com/16288424/87289446-d7e8aa80-c526-11ea-83c2-e19ff17e0ca5.png)

Sometimes, my custom `onCreateOption` function does not execute and after that my custom `formatCreateLabel` appeared as a creatable value

**Comment by ebonow** [comment] 2020-07-16 03:23
Can confirm that this is a bug. It appears that the second time around, the option is being "selected" instead of "created"


<img width="1040" alt="Screen Shot 2020-07-15 at 10 17 01 PM" src="https://user-images.githubusercontent.com/1007579/87622663-378eb380-c6e9-11ea-8326-20ebc67ed568.png">

**Comment by reidharry** [comment] 2020-07-16 05:50
@ebonow

thnx, for helping us, Yes that's a bug

**Comment by ebonow** [comment] 2020-07-16 18:29
Looks like this might be related and if so there appears to be a MR that could resolve this.

https://github.com/JedWatson/react-select/issues/3988

**Comment by luknl** [comment] 2020-08-24 22:31
In my case, I was having this error randomly, without having to follow your steps, simply trying to add a new chip.
I fixed it by setting `allowCreateWhileLoading` to false.

Can someone reproduce this one as well? And should I create another issue for this or are they related?
Thanks!

**Comment by vjpr** [comment] 2020-09-23 13:03
I have seen this happening to with `allowCreateWhileLoading`. It prevents the 'create-option' being used, and instead causes a `select-option` event. It also prevents `onCreateOption` being called.

**Comment by ebonow** [comment] 2021-02-11 08:52
Greetings everyone, I am happy to report that it appears that this issue was resolved by PR https://github.com/JedWatson/react-select/pull/4154 which was released in version 3.2

**Closed by ebonow** 2021-02-11 08:52 UTC
Labels: issue/bug-confirmed, issue/reviewed
