### ISSUE TITLE
No custom value rendering when `multi` is false

### ISSUE THREAD

**Issue by 0xCMP** [JedWatson/react-select#329] opened 2015-07-22 20:58 UTC
Right now the way it works only if the `multi` prop is set to true will Select use the `valueRenderer` prop. I'm trying to render my custom value the same way as my custom option but they can not be multi selected. 

```
if (this.props.multi) {
  this.state.values.forEach(function(val) {
    value.push(<Value
      key={val.value}
      option={val}
      renderer={this.props.valueRenderer}
      optionLabelClick={!!this.props.onOptionLabelClick}
      onOptionLabelClick={this.handleOptionLabelClick.bind(this, val)}
      onRemove={this.removeValue.bind(this, val)}
      disabled={this.props.disabled} />);
  }, this);
}

if (!this.state.inputValue && (!this.props.multi || !value.length)) {
  value.push(<div className="Select-placeholder" key="placeholder">{this.state.placeholder}</div>);
}
```

I just want to roughly change the second `if` to 

```
if(this.props.valueRenderer){
  var val = this.state.values[0];
  value.push(<Value
      key={val.value}
      option={val}
      renderer={this.props.valueRenderer}
      optionLabelClick={!!this.props.onOptionLabelClick}
      onOptionLabelClick={this.handleOptionLabelClick.bind(this, val)}
      onRemove={this.removeValue.bind(this, val)}
      disabled={this.props.disabled} />);
} else if (!this.state.inputValue && (!this.props.multi || !value.length)) {
  value.push(<div className="Select-placeholder" key="placeholder">{this.state.placeholder}</div>);
}
```

**Comment by brianreavis** [comment] 2015-07-22 20:59
Duplicate of https://github.com/JedWatson/react-select/issues/296

**Closed by brianreavis** 2015-07-22 20:59 UTC
