### ISSUE TITLE
CreatableSelect doesn't create new options if used with filterOption prop

### ISSUE THREAD

**Issue by Anuj16** [JedWatson/react-select#2945] opened 2018-08-17 14:15 UTC
Hello All,

Thanks a lot for this amazing library.

I am having an issue while using "CreatableSelect" with **filterOption** prop, which has 'matchFrom' value as 'start'. The issue is that I am not able to create new options.

My Component usage looks like the following:-

`const filterConfig = {
    matchFrom: 'start'
 };
<CreatableSelect
                isMulti
                isClearable={false}
                openMenuOnClick={false}
                value={value}
                options={options}
                filterOption={createFilter(filterConfig)}
                className={className}
                classNamePrefix={classNamePrefix}
                onChange={onChange} />` 

If I remove the **filterOption** prop, it works absolutely fine. Am I missing something here? Any help is greatly appreciated.

Thanks in advance.

**Comment by chrysb** [comment] 2019-04-01 17:11
I have encountered this issue as well — it's not clear whether it's a bug or working as intended.

I also tried to force `isValidNewOption={() => {return true}}` but that didn't work.

Did you ever find a way around this, Anuj?

**Comment by Rall3n** [comment] 2019-04-02 23:04
You have to wrap the function created by `createFilter` into another function which checks if the option is the `Create ...` option.

```jsx

const customFilter = createFilter({ matchFrom: 'start' });

/* ... */

<CreatableSelect
    { ... }
    filterOptions={(option, rawInput) => {
        // Data says its new so we return true.
        if (option.data.__isNew__) return true;
        
        // Filter using the filter function
        return customFilter(option, rawInput);
    }}
/>
```
[CodeSandbox](https://codesandbox.io/embed/505ppxw7jx)

**Comment by Anuj16** [comment] 2019-04-03 12:39
@Rall3n Yes you are right. I also did exact same way.

**Comment by Rall3n** [comment] 2019-04-12 14:19
@Anuj16 Please don´t forget to close this issue if the problem you mentioned here is solved.

**Comment by Anuj16** [comment] 2020-04-10 10:22
@Rall3n I had raised a pull request to fix this in repository properly instead of having a workaround. That's why kept this issue open.

**Closed** 2020-04-10 10:24 UTC
