### ISSUE TITLE
onChange returns the selected value, not the complete event

### ISSUE THREAD

**Issue by OsamaShabrez** [JedWatson/react-select#1631] opened 2017-03-28 16:22 UTC
onChange simply returns the new value and label and not the whole event.

I understand we can use the hidden input field to fire an onChange but this does not happen automatically and while we can manually fire an onChange for hidden input field, we can also wrap an event around the Select. Here is how I am doing it following [#520:](https://github.com/JedWatson/react-select/issues/520#issuecomment-282594463)

``` javascript
<Select
  name="form-field-name"
  value={val}
  options={options}
  onChange={(val)=> {onChangeFunc({target: { name:'revision_id', value: val.value }})}}
/>
```

Creating an object myself and passing it to my onChange handler. Is this the right way to do it or you can suggest a better way around it?

**Comment by jonathanchrisp** [comment] 2017-04-13 00:11
I've found that can cause issues with `redux-form` field component, it would be great to get the original event passed as the second argument on the onChange callback.

**Comment by OsamaShabrez** [comment] 2017-04-14 12:49
Currently there is no way to get the original event, at least I didn't found one and there no mention of original event in docs.

**Comment by browne0** [comment] 2017-06-07 15:55
Would love to see this feature implemented, you can do so much from getting the original event!

**Comment by kellenmace** [comment] 2017-06-21 13:15
Another workaround: you can use `this` to access the name of the select (or any of its other attributes). Example:
```
class SomeComponent extends React.Component {

  onChangeFunc(optionSelected) {
    const name = this.name;
    const value = optionSelected.value;
    const label = optionSelected.label;
  }

  render() {
    return(
      <Select
        name="form-field-name"
        value={val}
        options={options}
        onChange={this.onChangeFunc}
      />
    )
  }

}
```

**Comment by fonsleenaars** [comment] 2017-10-02 12:40
I've run into this issue, passing a value to an onChange handler passed from one of `redux-form`'s field component, as @jonathanchrisp mentioned, causes the string to be spread operated by this line: https://github.com/erikras/redux-form/blob/master/src/ConnectedField.js#L103

For now the only solution I could think of was writing a single edge case if statement in the container for this component. I feel like it's kind of a standard using events in onX handlers, so I'm all in favor for introducing that standard here.

To maintain compatibility with people using the onChange handler as is, a simple wrapper could be introduced, and exposed through the props?

**Comment by carlos0202** [comment] 2018-02-02 18:30
Any update on this issue?

This library really needs to conform to the expected behavior of input elements. That is, send the original event instead of an object containing label and value.

**Comment by gvincentlh** [comment] 2018-06-06 22:18
Any chance of *ever* getting resolution on this issue?

**Comment by ashnur** [comment] 2018-06-11 09:41
@gvincentlh this is just a guess, but I think this function should be changed so that it saves the event https://github.com/JedWatson/react-select/blob/master/src/Select.js#L452-L461

Then the event could be passed optionally instead of the value (there is a simpleValue option already, this could be similar I think)

**Comment by ashnur** [comment] 2018-06-12 14:55
@JedWatson do you have an opinion on this that you care to share here?

**Comment by kushalmahajan** [comment] 2018-07-12 07:57
I didn't realise this until now and I feel I wasted my time a bit using in my project. This is so common that don't expect it to be not here.

**Comment by kumarharsh** [comment] 2018-07-12 13:40
well, @github really needs to fix their autocomplete 😂

a good alternative which I've been following is [downshift](http://github.com/paypal/downshift), but it's more barebones rather than a plug-and-play kind of approach.

**Comment by cyrilf** [comment] 2018-08-30 15:52
This is what I came up with: https://gist.github.com/cyrilf/109fc97a22cd080abcc5068a30976696
Not perfect and a bit hacky, but it solved my use-case where I really needed an `event`

Hope it helps :v:

**Comment by danyonsatterlee** [comment] 2018-09-05 19:01
Has anyone taken a look at Material UI's example for React Select and their onChange function? They recommend using React Select for an auto-complete example. It helped me solve the issue of an on change event. This is their sandbox https://codesandbox.io/s/5kvmpwpo9k . For easy reference this is their onChange example and their Select component. I hope it gets someone else started on a solution that works in their project. 
``` 
handleChange = name => value => {
   this.setState({
      [name]: value,
    });
  };

  <Select
       classes={classes}
       styles={selectStyles}
       options={suggestions}
       components={components}
       value={this.state.single}
       onChange={this.handleChange('single')}
       placeholder="Search a country (start with a)"
       />
```

I wasn't familiar with multiple arrows in a function. This is a curried function and this had a nice explanation https://stackoverflow.com/questions/32782922/what-do-multiple-arrow-functions-mean-in-javascript

**Comment by bflorat** [comment] 2018-09-20 13:10
I made it work by encapsulting the onChange function with another function that pass the Select id : 
```
 onOptionChange = (name,selectedOption) => {
         //do something with name and selectedOption
    };
 <Select options=...
              name={info.id}
               value=...
               onChange={e => this.onOptionChange(info.id,e)}
   />}
```

**Comment by ashnur** [comment] 2018-09-20 16:35
Nice hack. Why not just use vanillajs then?

**Comment by bflorat** [comment] 2018-09-20 21:02
It's the method documented by the react.js team  : https://reactjs.org/docs/handling-events.html#passing-arguments-to-event-handlers

**Comment by ashnur** [comment] 2018-09-20 21:15
no, I mean, the variable that seems to be a string, selectName, is actually an object with an .id property.. sure, I could just pass the whole state there, but that doesn't mean I get my original event object unless I somehow recreate a live reference to some dom element, which you seem to be doing here

**Comment by Davidmycodeguy** [comment] 2018-12-13 09:05
Wow This is not implemented? Accept the PR.

**Comment by Mileshosky** [comment] 2018-12-19 17:31
Encapsulation and normalization is great, but please expose the default browser implementation for those that need it.  Should be a minimum when building components around browser UI elements.

**Comment by markoj3s** [comment] 2019-01-08 13:42
https://react-select.com/upgrade-guide
Seems like there is now a second argument `actionMeta` for `onChange`. `name` is accessible from there.

**Comment by oshell** [comment] 2019-01-23 12:45
> https://react-select.com/upgrade-guide
> Seems like there is now a second argument `actionMeta` for `onChange`. `name` is accessible from there.

this should be documented. is it yet? Should be in the minimal example on the readme

**Comment by ashnur** [comment] 2019-01-23 15:01
> > https://react-select.com/upgrade-guide
> > Seems like there is now a second argument `actionMeta` for `onChange`. `name` is accessible from there.
> 
> this should be documented. is it yet? Should be in the minimal example on the readme

I don't see how this solves anything related to this issue.

**Comment by bobort** [comment] 2019-01-28 21:05
It seems to make the whole issue even worse, @ashnur .  If the implementation is ever corrected, now developers who used that second argument will have to refactor their code even more.  I expected so much more from this project.  I'm just now diving into ReactJS, and I thought I was missing some major concept.  Nope.  The developers of this particular package just didn't follow standard procedures.

**Comment by ashnur** [comment] 2019-01-28 22:22
@bobort have you tried https://github.com/paypal/downshift ? :)

**Comment by kushalmahajan** [comment] 2019-01-29 16:04
Well, the person replying to every comment could have stopped all this by just giving an example that it's okay to return the value "only" instead of even, as a result of handleChange. 

If we want to get `event`, we can easily do so by wrapping the select in a div and let the event bubble. Therefore parents' div can have a handleChange instead and use `event.currentTarget` to retrieve the value.

I remember even I commented on it a while back but he seems to reply in same fashion.  Are you really a representative of this library?

**Comment by ashnur** [comment] 2019-01-30 12:31
> If we want to get `event`, we can easily do so by wrapping the select in a div and let the event bubble. Therefore parents' div can have a handleChange instead and use `event.currentTarget.value` to retrieve the value.

I am not sure who are you talking to but the "we" in this case doesn't apply to me. I don't want to add additional markup to deal with inadequate APIs. Throwing code at problems only leads to problems down the road.

**Comment by ashnur** [comment] 2019-01-30 14:04
> So, what was the design process for not passing the event but only the value. I'm curious?
> In case if some one want to capture the `[e.target.name]` how is he supposed to handle that if not wrapping up with parent div.

Dear @kushalmahajan I have the same exact questions :)

> Also, what problems do you think this simple wrap will contain. Let's say I build a React component like this. Why it would be a problem if library authors haven't provided that option? Thoughts!

It's not about problems. I mean, problems can be stated with additional markup, especially if someone wants the code to follow specific semantics. But the bigger question is, why would a library push its users to such hacks?

**Comment by oshell** [comment] 2019-01-31 23:35
> > > https://react-select.com/upgrade-guide
> > > Seems like there is now a second argument `actionMeta` for `onChange`. `name` is accessible from there.
> > 
> > 
> > this should be documented. is it yet? Should be in the minimal example on the readme
> 
> I don't see how this solves anything related to this issue.

https://react-select.com/advanced#action-meta

The documentation is even wrong. It states that action is a string, but it is an object with the properties action, option and name. It solves the issue with getting the name of the target at least.

However, I understand your frustration. This behavior is not intuitive and even worse, not documented correctly. There are other things wrong with this library. For instance, when you define the options as value-label pairs, I would expect it would be enough to pass the value as prop to have a controlled input. But the event only gives me the value, then I have to built the object with the value-label pair again and pass it to the element. This results in a lot of boilerplate, which makes this lib basically a pain in the ass. It is a shame that there is so much work put into this and then it does not even handle the most basic stuff by just following the html standards.

**Comment by ashnur** [comment] 2019-02-01 09:16
> It is a shame that there is so much work put into this and then it does not even handle the most basic stuff by just following the html standards.

I wouldn't go so far as to blame people. :) Let's be honest, this is still something used for all kinds of meaningful purposes, no matter its drawbacks. There is not reason to try to question the people who I am sure had their reasons for choosing the abstractions they chose.

**Comment by Rall3n** [comment] 2019-02-07 07:20
> There is no reason to try to question the people who I am sure had good reasons for choosing the abstractions they chose.

They have a good reason to prefer this pattern. The call to the function bound to the `onChange` prop is not a result of a `change` event, but it is the result of a `keydown`, `click` or `touch`. The event has no `input` element as the target, therefore no name, no value.

This pattern at least provides you with the selected option as the value and (thanks to a previous update) the name of the select (provided by the `name` prop) in the action meta as a second argument.

**Comment by osifo** [comment] 2019-02-09 18:13
Wow! I would have expected that by now some work-around would have been available for this though.
Hopefully soon.

**Comment by mathieutu** [comment] 2019-07-31 18:16
Actually this was already a previous issue, that was marked as closed in v2, but it's not resolved at all:
https://github.com/JedWatson/react-select/issues/272

**Comment by JedWatson** [comment] 2019-11-20 12:38
Sorry for not providing an official response to this earlier, I'm jumping in because it was asked on Twitter and that drew my attention to this issue (for some reason I thought we'd answered this before)

As @Rall3n said, the reason for the design of the current `onChange` arguments is that there is no reliable event we can pass. As there is no browser-native `change` event we can pass, you _probably_ don't want to receive the underlying browser event that triggered the change (`click`, `touch`, `keypress`, etc) because that wouldn't be consistent with other form components and interacting with the event wouldn't necessarily have the expected effect (e.g if you were to `preventDefault` on it)

In fact from memory, for various conditions we don't even always have an event (or there may not just be one, because of internal debouncing).

It seems better to consistently provide a predictable API, which can be relied upon in all conditions, rather than faking an API which can't be properly implemented. And given that, it also made sense not to even make the API look like something it's not (by mimicing `event.currentTarget` etc).

The `onChange` API provides two things: the updated value, and the event meta that describes how the change happened, as well as other useful data like the name property. As far as I know this is everything we _can_ reliably provide.

The only reason I can think of to fake the native `event` API shape is if you're passing a generic handler to multiple form components that include Select and native inputs... which can be solved by extending the Select component, if that's what you need:

```js
import ReactSelect from 'react-select';
export const Select = ({ onChange, name, ...props }) => {
  const patchedOnChange = (value) => {
    onChange({ currentTarget: { value, name }});
  }
  return <ReactSelect onChange={patchedOnChange} name={name} {...props} />
}
```

Hope this clears up the reasoning and workaround.

**Closed by JedWatson** 2019-11-20 12:38 UTC

**Comment by ashnur** [comment] 2019-11-20 13:31
> there is no reliable event we can pass

From the React docs:
>>> Note:
>>> If you want to access the event properties in an asynchronous way, you should call event.persist() 
>>> on the event, which will remove the synthetic event from the pool and allow references to the event 
>>> to be retained by user code.

> there is no browser-native change event we can pass

The HTML element called `select` does have such an event, being a HTML element. You could use the original or could create a new one. 

If you call this a select library, that is to be used in place of that select, it is highly dishonest to say that there isn't such an event. We all used it for quite a long time, it exists. It's your  implementation details that are leaking through and blocking a proper API. And I find it obnoxious that you suggest further propagating said leak of internals by way of one of, non-standard workarounds.

**Comment by JedWatson** [comment] 2019-11-20 16:39
@ashnur I'm going to address your comment for the benefit of anyone else who is seeking to understand the reasoning here, but I also want to make it clear that your language and tone is not welcome or acceptable.

First of all, this isn't about retaining the synthetic event, I know how to do that - it's about getting an event in the first place.

> The HTML element called select does have such an event, being a HTML element. You could use the original or could create a new one.

It's not possible to create a `select` component and capture an `onChange` event by changing its `value`. The event requires user interaction to fire. Faking the interaction would be significantly less predictable than choosing not to try and conform to an API that we can't correctly implement.

> If you call this a select library, that is to be used in place of that select, it is highly dishonest to say that there isn't such an event. 

There. Isn't. Such. An. Event. There is for native `select` components, and if they do what you need, I wouldn't recommend using this library.

> I find it obnoxious that you suggest further propagating said leak of internals by way of one of, non-standard workarounds.

`react-select` is one giant non-standard workaround. It fills a gap left by the HTML spec, because native select controls are insufficient for a range of use cases; that hasn't changed in two decades, and this is far from the first library to deal with it (prior art includes Selectize and Select2 for jQuery, you can go further back to YUI and other frameworks if you like)

> It's your implementation details that are leaking through and blocking a proper API

There's no such thing as a "proper API". This project is not pretending to be a native form control. If anything, the API has been designed to _prevent_ implementation details (such as unpredictable source events) from leaking through.

---

Anyway, I'm done with this issue, hope the explanation and workaround helps people who come across this in the future, but I don't maintain this project to be called dishonest or obnoxious.

**Comment by ashnur** [comment] 2019-11-20 17:44
@JedWatson 
- thank for clarifying, even if it took you 2.5 years. 
- for the record: I called your actions what they are, I haven't called you anything. If you can't make this distinction, that's not on me.

**Comment by MadeByMike** [comment] 2019-11-21 02:46
I remember this one time the internet gave me close to 100 thumbs down in a GitHub issue. So I doubled-down on a being jerk to open-source maintainers and it really changed the way everyone saw things.

**Comment by mdhenriksen** [comment] 2020-08-17 18:21
I know this might not be the ideal solution, but a workaround would be to set the `value` to be an object and extracting the values from the event and passing it to the onChange method:
```javascript
value={{ "valueOne": object.id, "valueTwo": "Another value" }}
```
And then
```javascript
onChange={(event) => onChangeMethod(event.target.valueOne, event.taget.valueTwo)} // or just the whole event
```

**Comment by stfenjobs** [comment] 2020-10-20 08:32
i want to get value , not object 
v3:


```
 const handleChange =(value)=>{
    console.log(value.map(v => v.id));
  }
```

you will get  ` [1,2,3,4,5]`

**Comment by tronganhnguyenthanh** [comment] 2021-06-11 04:36
Do we have any way to save the data in react-select? I mean that when we got the data already and we press F5 to reload it, it can't be lost.

**Comment by Andrii-Velhan** [comment] 2021-06-18 12:05
this option helped me:class MyComponent extends Component{
 state={
  firstSelect: null,
  secondSelect: null
 }
 handleSelectChange = (selectedOption, { name }) => {
   this.setState({ [name]: selectedOption.value });
 }
 render() {
      return (
          <>
           <Select name="firstSelect" onChange={this.handleSelectChange} {...}/>
           <Select name="secondSelect" onChange={this.handleSelectChange} {...}/>
          </>
      )
 }
}

**Comment by ebonow** [comment] 2021-06-19 00:40
@tronganhnguyenthanh ,

You would need to implement a client-side storage solution if you want data to persist beyond the lifecycle scope of the application.

[There's](https://usehooks.com/useLocalStorage/)
[a](https://github.com/beautifulinteractions/) 
[plethora](https://github.com/hacknlove/usestorage) 
[of](https://github.com/ugenc/useStorage) 
[different](https://github.com/alex-cory/use-react-storage) 
[solutions](https://github.com/capacitor-community/react-hooks) 
out there for this kind of thing...

**Comment by tronganhnguyenthanh** [comment] 2021-06-19 01:06
Dear Mr Eric Bonow,
I would like to say a big thank you for your support and I would like to
take your facebook account or any other social media you are using to take
the advantage in learning new things.
Thank you and best regards,
Trong Anh

Vào Th 7, 19 thg 6, 2021 vào lúc 07:40 Eric Bonow <
***@***.***> đã viết:
