### ISSUE TITLE
When first option is disabled it does not appear when the pulldown is first opened

### ISSUE THREAD

**Issue by boriswexler** [JedWatson/react-select#1294] opened 2016-10-10 23:40 UTC
If the first option is disabled, the pulldown will start scrolled down at the second option - meaning the user will not see the first (disabled option) unless they think of scrolling up.

**Comment by enf0rc3** [comment] 2017-01-16 20:14
https://github.com/JedWatson/react-select/blob/master/src/Select.js#L212 

Is where the issue is, The offset doesn't take into account disabled options.

**Comment by boriswexler** [comment] 2017-01-19 03:14
awesome thanks! Would you create a PR with your change and list it [here](https://github.com/JedWatson/react-select/issues/1481)? Thanks again!

**Comment by jooseptame** [comment] 2017-02-01 14:20
+1

**Comment by florentdestremau** [comment] 2017-02-08 10:02
Is there a current workaround ? I'm experiencing this right now :confused:

**Comment by brentoneill** [comment] 2017-05-05 15:48
+1

**Comment by brentoneill** [comment] 2017-05-05 16:08
@enf0rc3 - tried applying that commit to my local react-select and it broke the component. Are there additional commits or a branch I can look at?

**Comment by mtlewis** [comment] 2017-11-27 10:18
This should be fixed by https://github.com/JedWatson/react-select/pull/2170.

**Comment by bladey** [comment] 2020-05-27 06:31
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.

**Closed by bladey** 2020-05-27 06:31 UTC
