### ISSUE TITLE
Feature request: Support select all lable.

### ISSUE THREAD

**Issue by shenghou** [JedWatson/react-select#3860] opened 2019-11-20 15:05 UTC
Hi, thanks to the react-select lib for helping me  at work.  I want to add a feature request.  

When you click "select all" button,  all selected label will be displayed. But if all of  them are displayed, it seems too much. I want to use the "Select All" label or other lable to represent all that are selected.

Thanks !

eg:
![image](https://user-images.githubusercontent.com/24260845/69248949-1de3ad80-0be8-11ea-9699-848b896fb596.png)

**Comment by fantonangeli** [comment] 2019-11-21 19:10
Duplicate of #3543

**Comment by bladey** [comment] 2020-05-28 04:32
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Closed by bladey** 2020-05-28 04:32 UTC
