### ISSUE TITLE
Z-Index Problems?

### ISSUE THREAD

**Issue by bradennapier** [JedWatson/react-select#1085] opened 2016-07-13 03:44 UTC
![image](https://cloud.githubusercontent.com/assets/15365418/16791191/406f57ca-4871-11e6-8f5b-9b7f7e105e8b.png)

I had this problem with a default install of react-select ?  I can't seem to figure it out, I have spent hours on this.  It appears near impossible to get the dropdown to be above everything... perhaps some sort of portal solution should be used for this ?

**Comment by ufukomer** [comment] 2016-07-14 14:36
+1

**Comment by theopolisme** [comment] 2016-07-14 18:48
We fixed this (temporarily, hopefully!) by manually setting a higher index on the Select-menu-outer component.

```css
.Select-menu-outer {
  z-index: 999 !important;
}
```

**Comment by bradennapier** [comment] 2016-07-26 15:45
This doesnt work for me because I have items in another stacking context which will go over the other divs.  A portal solution is needed otherwise it is impossible to guarantee the results of the dropdown not being affected by the other styles.

**Comment by benjiwheeler** [comment] 2016-11-27 18:43
+1 same problem, jQueryUI elements showing up on top

**Comment by Augustin82** [comment] 2016-11-29 10:43
I came looking for an answer to that.
Found it there, putting it here in case others like me stop at this issue and don't see the other one ;)
https://github.com/JedWatson/react-select/issues/1076#issuecomment-253629943

**Comment by evgeniiteterin** [comment] 2017-02-13 15:15
anyone solved this problem? menuContainerStyle={{ zIndex: 5 }} not work.

**Comment by mduleone** [comment] 2017-02-21 23:44
:+1: having this issue as well. Neither the suggested `Select` api

```javascript
menuContainerStyle={{'zIndex': 999}}
```

nor the css

``css
.Select-menu-outer {z-index: 999 !important;}
```

worked. Any thoughts would be great!

**Comment by turnerniles** [comment] 2017-03-05 18:28
See prateekjahead's comment: https://github.com/JedWatson/react-select/issues/1010
"HubSpot's [react-select-plus](https://github.com/HubSpot/react-select-plus) takes in dropdownComponent as a prop which solves the issue."

**Comment by prototypos** [comment] 2017-03-08 14:40
z-Index did not work for me because I have jQueryUI items.  When I set the opacity to 0.99 of the <div/> that contained these items, the dropdown appears in the front.

**Comment by NatashaKSS** [comment] 2017-03-17 02:44
I've also tried setting `z-index: 999 !important` on the div with the `.Select-menu-outer` class and on subsequent parent divs, but it still doesn't work

**Comment by turnerniles** [comment] 2017-03-17 04:59
@NatashaKSS Have you tried [react-select-plus](https://github.com/HubSpot/react-select-plus) with the same css?

**Comment by JedWatson** [comment] 2017-03-17 05:39
If anybody can isolate why it works with react-select-plus I'd be very happy to port the fix back upstream :+1:

The explanation on #1010 about being inside a parent element with certain styles applied sounds like it may be the culprit, in which case injecting the menu into the body would be a potential fix, but I'm pretty sure that causes other unexpected behaviours with positioning.

Alternatively if someone can point me at an example I can hack that replicates the issue either @jossmac or I can take a look!

**Comment by bartekwitczak** [comment] 2017-03-28 06:58
Hey,

I also had an issue with z-index and components not properly displaying. Walking through the code I've noticed that LESS & SCSS versions of variables have different values: 

https://github.com/JedWatson/react-select/blob/master/less/select.less#L32
https://github.com/JedWatson/react-select/blob/master/scss/select.scss#L29

I don't know if that is by design or not, @JedWatson?  In case of LESS z-index value is set to 1 and in case of SCSS it's set to 1000 !default. 

Please remember how z-index really works and z-index is not global for whole site. You should take care of proper nesting in order to work as required. If you need any good explanation, take a look here https://css-tricks.com/almanac/properties/z/z-index/

eat broccoli & workout,

**Comment by nicolasotten** [comment] 2017-04-06 09:18
Hey,

I ran into some some issues with the stacking context as well and I managed to fix them by changing the z-index of open Select elements:
`.Select.is-open {
    position: relative;
    z-index: 1000;
}`

I don't know if this is the best solution but I hope it can help :)

**Comment by LinuCC** [comment] 2017-05-22 15:29
If you use an animations-lib (e.g. GSAP) it is possible that it adds `transform` to the style attribute of the node in which you use react-select.
As long as that attribute is set setting `z-index` will not work.
In that case you need to remove the transform after your animation is done (Some animation libs support that).

**Comment by schuchowsky** [comment] 2017-06-12 21:12
@bartekwitczak A bit of reviewing how z-index works and I could solve my problem with this. I'd suggest everyone reading https://css-tricks.com/almanac/properties/z/z-index/

Basically what I needed to do is to set the z-index higher on the **parent** component, who contained the select, not the select itself. Because it's z-index needed to be greater than his elements "brothers".

**Comment by mustafawm** [comment] 2017-06-30 06:04
this worked for me
```
.Select-menu {
    position: fixed !important;
}
```

then I had to give fixed width to both the `input` and the `dropdown`, here is the css I changed:

```
.Select {
    width: 444px !important;
    margin-right: 5px;
    z-index: 0 !important;
}

.Select.is-open {
	z-index: 1 !important;
}

.Select-menu {
    position: fixed !important;
    width: 440px !important;
    margin: 1px;
}

```

**Comment by DavidDionise** [comment] 2017-08-02 17:28
My problem was that my select box was the child of an element that was using a transformation (Animate.css to be exact), and that creates a new stack context. Once I got rid of that, react-select played nicely with it's DOM siblings. 
There are work-arounds for dealing with z-index issues with transformations. Check out [this] (http://katydecorah.com/code/z-index-and-transform/) article for some slick css tips.

**Comment by agirton** [comment] 2017-08-03 00:33
Since there are quite a few answers that handles this, closing this out.

**Closed by agirton** 2017-08-03 00:33 UTC

**Comment by bradennapier** [comment] 2017-08-09 17:56
Running into this problem again.  I think the main solution is to have the dropdown render itself in a portal-like context.  This would resolve any issues with z-index with the dropdown.  In almost all cases I can imagine this is desired effect.  Perhaps in the minimum as a prop?

**Comment by nreese** [comment] 2017-11-10 14:57
@JedWatson Any way that the dropdown could be rendered with https://reactjs.org/docs/portals.html to avoid overflow problems hiding menu?

**Comment by VD17593** [comment] 2018-02-05 08:30
Had a similar problem: two mdl-cards (div) one below the other, with each a select inside.
When opening the select in the upper card, the dropdown appeared below the lower card, even is I changed the z-index on the select.
As work around, I had to give the two mdl-cards (outer div) a different z-index : the first one a higher **z-index** than the next.

**Comment by zhm12359** [comment] 2018-04-13 17:32
.Select-menu-outer {
    z-index: 1000;
    position:relative;
}

solved my problem. I am using this as a column in react bootstrap table.

**Comment by Slapbox** [comment] 2018-04-17 03:02
Oh my lord, @schuchowsky your solution works! I had all but given up hope! This is still an issue for overlapping other elements that require the same z-index unfortunately, but very close now.

**Comment by adamsenn** [comment] 2018-08-22 17:45
For anyone late to this thread (like me), I solved a similar issue in 2.0 using the https://react-select.com/styles prop:

`const reactSelectStyles = base => ({ ...base, zIndex: 999 })`

and

`return <Select styles={reactSelectStyles} />`

**Comment by cancit** [comment] 2018-08-22 18:28
I solved with jss. 
works for the example [here](https://material-ui.com/demos/autocomplete/#react-select)
```
const styles = theme =>
  createStyles({
    root: {
        flexGrow: 1,
        height: 250,
        '& div':{
            zIndex:1
        }
      },
})
```
```
 <div className={classes.root}>
        <Select
          classes={classes}
          textFieldProps={{
            label: "Filter",
            InputLabelProps: {
              shrink: true
            }
          }}
          options={suggestions}
          components={components}
          value={this.state.multi}
          onChange={this.handleChange("multi")}
          placeholder="Select multiple countries"
          isMulti
        />
      </div>
```

**Comment by cescoferraro** [comment] 2018-11-28 13:21
This works for me
```
const Menu = (props) => {
  return (
    <div style={{ position: "fixed", width: "300px" }} >
      <components.Menu {...props} >
        {props.children}
      </components.Menu>
    </div>
  )
}

    <Select
      components={{ Option: CustomOption, Menu }}
      className={props.classes.select}
      value={currentClub}
      onChange={(option) => {
        props.actions.dispatch({ type: UNSET_PARTIES_LOADED })
        props.actions.club({ token: props.auth.userclub.token, id: option.value })
      }}
      options={allClubs}
    />

```

**Comment by strap8** [comment] 2018-12-14 20:00
This worked for me.  
```
container: (base, state) => ({
    ...base,
    opacity: state.isDisabled ? ".5" : "1",
    backgroundColor: "transparent",
    zIndex: "999"
  }),
```

**Comment by jossmac** [comment] 2018-12-17 04:54
@lucasfcosta explained part of the issue (cheers mate!) but there's more at play here. If your select is inside of an element with a lower "stacking context" than whatever's over the top of it, no matter how high you set the `z-index` it won't matter -- it'll never escape it's stacking context.

MDN have a great page explaining [the stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context); please check it out.

**Comment by alecmolloy** [comment] 2019-02-27 09:28
Very surprised to not see this mentioned, but a 2.0 feature **solves all of this elegantly** with React Portals. All you need to do is add a portal div outside of your react root, and reference target in your Select control:

```
menuPortalTarget={document.getElementById('portal-target')}
```

For more on understanding React Portals: https://reactjs.org/docs/portals.html

PR for react Portals: https://github.com/JedWatson/react-select/pull/2439

(Perhaps this would be good to put into the docs? This is a pretty great solution to a clearly common problem.)

**Comment by derekcannon** [comment] 2019-03-21 21:13
@alecmolloy Thanks, your solution was helpful. For anyone having issues with thing still showing through the popup (for me it was Material UI `TextField` labels), you can explicitly set the zIndex of the portal using the `menuPortal` key:

```
<Select
  menuPortalTarget={document.getElementById('portal-target')}
  styles={{ menuPortal: styles => ({ ...styles, zIndex: 1000 }) }}
  {...yourOtherProps}
/>
```

**Comment by d3mp** [comment] 2019-03-28 15:09
@strap8, thanks! Your suggestion works but it has a disadvantage, if you have under your first select another select it won't be overlaid.

Solution is to use `menu` instead of `container`:

`const selectStyles = {
  menu: styles => ({
    ...styles,
    zIndex: 999
  })
};`

**Comment by javinc** [comment] 2019-04-17 16:48
already solved on v2 https://react-select.com/advanced#portaling

**Comment by erfansamieyan** [comment] 2019-05-28 13:18
Mine was solved using this comment:

https://github.com/JedWatson/react-select/issues/404#issuecomment-433608100

**Comment by colidarity** [comment] 2019-07-31 19:03
Fixed this temporarily by using

#3230  > span ~ div:nth-of-type(2) {
    z-index: 999 !important;
  }

**Comment by AndreyZavarin** [comment] 2019-09-16 11:46
Сheck overflow-y at parent elements.

**Comment by selensr** [comment] 2019-12-27 10:22
Yes, check parents overflow if it's hidden delete it, then make select is-open overflow visible. Don't use z-index if it's not necessary, it causes problems when you scroll

**Comment by 1nfility** [comment] 2020-01-05 16:22
`
styles={{
    container: (base) => ({
        ...base,
        zIndex: 500
    })
}}
`

**Comment by timaivanov** [comment] 2020-01-17 07:19
For me work this
<Select
  styles={{
    // Fixes the overlapping problem of the component
    menu: provided => ({ ...provided, zIndex: 9999 })
  }}
  value={selectedOption}
  onChange={evt => onSelectChange(evt, index)}
  options={options}
/>

**Comment by glenkitchen** [comment] 2020-02-17 14:09
This worked for me , 
styles={{ menuPortal: base => ({ ...base, zIndex: 9999 }) }}
 
As per example in documentation 
https://react-select.com/advanced#portaling

**Comment by JeffEmery** [comment] 2020-03-04 22:01
Using the example breaks isMenuOpen={true}
When you add menuPortalTarget={document.body}, you can no longer render the Select with the Menu open.

**Comment by shahedmahmoudi** [comment] 2020-04-19 20:53
This worked for me ,
```
styles={{ menuPortal: base => ({ ...base, zIndex: 9999 }) }}
              menuPortalTarget={document.body}     //important
```

As per example in documentation
https://react-select.com/advanced#portaling

**Comment by Nicolas-Medina-Teracode** [comment] 2020-05-22 14:22
> For me work this
> <Select
> styles={{
> // Fixes the overlapping problem of the component
> menu: provided => ({ ...provided, zIndex: 9999 })
> }}
> value={selectedOption}
> onChange={evt => onSelectChange(evt, index)}
> options={options}
> />

This one works best for server-side rendering, the solutions that use `document.body` don't work with SSR. Thanks!

**Comment by jaketrimble** [comment] 2020-06-06 01:56
react-select: 1.0.0-rc.5

```
*scss*

:global(.Select-menu-outer) {
   z-index: 999 !important;
 }
```

**Comment by mathiaswillburger** [comment] 2020-08-05 17:54
> This worked for me ,
> 
> ```
> styles={{ menuPortal: base => ({ ...base, zIndex: 9999 }) }}
>               menuPortalTarget={document.body}     //important
> ```
> 
> As per example in documentation
> https://react-select.com/advanced#portaling

@shahedmahmoudi  your solution fixed it also for me, where react-select is used with [react-bootstrap-table2](https://github.com/react-bootstrap-table/react-bootstrap-table2) and was hidden behind some header and footer elements. Thx!

**Comment by xXDeonoXx** [comment] 2020-08-18 02:54
> This worked for me ,
> 
> styles={{ menuPortal: base => ({ ...base, zIndex: 9999 }) }}
>               menuPortalTarget={document.body}     //important
> As per example in documentation
> https://react-select.com/advanced#portaling
i just had to add a negative marginTop, somehow the dropdown showed down bellow it should

**Comment by er-parag91** [comment] 2020-10-14 22:57
This fixes for me

Define following style object and change menu dropdown z index
```
  const customStyles = {
    menu: (base) => ({
      ...base,
      zIndex: '5',
    }),
  };
```

```
  <Select
     styles={customStyles}
     { ...other props }
   />
```

**Comment by markcunninghamuk** [comment] 2020-11-03 11:17
this worked for me (Embedded in Dynamics 365 form)

	 const selectStyles = { menuPortal: (zzz: any) => ({ ...zzz, zIndex: 9999}) };

        return (			
			<AsyncSelect
			isMulti={true}
			menuPortalTarget={document.body}
			styles={selectStyles}
			loadOptions={this.loadOptions}
			defaultOptions
			onChange={this.onChange}		
			/>
        );

**Comment by afrancht** [comment] 2020-12-14 19:55
@shahedmahmoudi solution worked for me! If you have access to 'document' in the browser.

**Comment by mvfsillva** [comment] 2021-01-17 07:53
Thanks for the share, worked for me

> This worked for me ,
> 
> ```
> styles={{ menuPortal: base => ({ ...base, zIndex: 9999 }) }}
>               menuPortalTarget={document.body}     //important
> ```
> 
> As per example in documentation
> [react-select.com/advanced#portaling](https://react-select.com/advanced#portaling)


**If using SSR, just use the react life cycle:**

```jsx
useEffect(() => {
  setBodyElement(document.body)
},[])

menuPortalTarget={bodyElement} 
```

**Comment by LucasCaixeta** [comment] 2021-07-01 01:12
> This worked for me ,
> 
> ```
> styles={{ menuPortal: base => ({ ...base, zIndex: 9999 }) }}
>               menuPortalTarget={document.body}     //important
> ```
> 
> As per example in documentation
> https://react-select.com/advanced#portaling

This one worked for me!!! thanks a lot!

**Comment by sikandarchishty** [comment] 2021-08-23 22:07
**CSS Solution:**

add _**classNamePrefix**_ prop to select
 ````
<Select
    classNamePrefix="your-selector"
/>
 ````

then simply in css target like this:

````
.your-selector__menu {
  z-index: 10 !important;
}
````
z-index value depends on the z-index value of item underneath Select Dropdown. Add higher value than item below.

**Comment by IttzyTT** [comment] 2022-12-13 15:54
> styles={{ menuPortal: base => ({ ...base, zIndex: 9999 }) }}
>               menuPortalTarget={document.body}     //important

works but the options are fixed while you can scroll the body

**Comment by Udit-takkar** [comment] 2023-01-18 18:06
@IttzyTT did you find any fix ?

**Comment by IttzyTT** [comment] 2023-01-18 18:08
Kinda, it's look nice but I can't scroll while the select is open

**Comment by Udit-takkar** [comment] 2023-01-18 18:10
yeah same
