### ISSUE TITLE
onBlurResetsInput not working with Async?

### ISSUE THREAD

**Issue by mmahalwy** [JedWatson/react-select#751] opened 2016-02-01 09:05 UTC
I cannot get it to work, I think it's due to it looking for options async

**Comment by joan-smith** [comment] 2016-02-01 23:13
It's not released in v1.0.0-beta8, just exists on master.

Hopefully there's a release coming soon.

**Comment by mmahalwy** [comment] 2016-02-03 00:32
@joan-smith I am using beta8....

**Comment by scags9876** [comment] 2016-10-13 23:50
I'm having the same problem.

onBlurResetsInput resets the input value, but for async it does not reset the options.  This results in the following behavior:

1. Click on the dropdown arrow for an async select with onBlurResetsInput true
1. As expected, loadOptions is called and options are displayed
3. Type some search text and options are filtered down to match the text
4. Do not select an option but click outside the select.  Observe as expected the search text gets blanked out since nothing was selected.
5. then click the dropdown arrow for the async select again

Expected behavior would be for loadOptions to be called and to see the full set of options

Observed behavior is that the filtered set of options from the previous interaction is shown.

**Comment by bladey** [comment] 2020-05-27 06:12
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.

**Closed by bladey** 2020-05-27 06:12 UTC
