### ISSUE TITLE
Add state modifiers (like isFocused) to MultiValueRemove component state

### ISSUE THREAD

**Issue by mmarchuk-jama** [JedWatson/react-select#3953] opened 2020-02-28 00:23 UTC
Hi, it would be great to have a little more control over the `MultiValueRemove` component in react-select. Most components get the `<component>-is-focused` classes applied, but it seems like this one doesn't. My guess is that it's slightly more complex than others because of the left/right arrow key navigation to delete selected options, but not having access to these various properties makes it difficult to override the styles. 

Here's the hack I have to resort to for overriding the styles:

**Create custom component for MultiValueRemove**
```
const CustomMultiValueRemove = ({ ...props }) => {
  return (
    <components.MultiValueRemove {...props}>
      <span className="multi-value-remove-button">
        <div className="multi-value-remove-icon" />
      </span>
    </components.MultiValueRemove>
  )
```

**Omit the styles from the style function that I want to override**

```
    const styleOverrides = {
      multiValueRemove: (base, state) => ({
        ...omit(base, [':hover', 'color', 'backgroundColor']),
      }),
    }
```

Not the prettiest solution, since I'm basically nuking the default functionality and injecting my own custom markup just to have more control. 

Anyway, let me know if there's a better way of doing this or if this is planned for the future!

**Comment by ebonow** [comment] 2020-12-05 03:30
Greetings @mmarchuk-jama 

MultiValueRemove is a div with no tabIndex and therefore is not focusable. It would also likely cause complications even if it was focusable because it would then blur the input. 

It's more likely you are interested in the hover event. It's not clear to me what kind of "control" you would like when a user does hover over it but you do have two options available to you for styling.

1. You can use a styled component with the styles api
``` JS
const styles = { 
  multiValueRemove: css => ({ ...css, ':hover': { /* your styles here */ } })
}
```

2. You can use the `classNamePrefix` prop and target it 
``` CSS
.[classNamePrefix]__multi-value__remove:hover { /* your styles here */ }
```

Both of these examples can be seen [here at this codesandbox](https://codesandbox.io/s/react-select-styling-multi-remove-hover-itwwt?file=/src/App.js
<img width="1634" alt="Screen Shot 2020-12-03 at 9 45 38 PM" src="https://user-images.githubusercontent.com/1007579/101231977-b5853400-3663-11eb-8f28-99261d2783c6.png">

If you require more control for some other purpose, you would be able to add `onMouseOver`, `onMouseOut`, or even overwrite/append to the className in the innerProps as you can see here in the props passed to the MultiSelectRemove
https://github.com/JedWatson/react-select/blob/998c979b4ed51ee39b87c9b2f0f03da440017dcf/packages/react-select/src/components/MultiValue.js#L77

Here could be one possible iteration, given the above solution.

``` JS 
const MultiValueRemove = ({ innerProps, ...props }) => {
  const [ isHovered, setIsHovered ] = useState(false);
  const onMouseOver = () => setIsHovered(true);
  const onMouseOut = () => setIsHovered(false);
  const className = `${innerProps.className} ${isHovered ? 'multi-value__remove--is-hovered' : ''}

  const newInnerProps = {
    ...innerProps,
    onMouseOver,
    onMouseOut,
    className
  }
    
  return <components.MultiValueRemove {...props} { ...newInnerProps } />
```

Again, without knowing the use-case, this should provide a good starting point. Let me know if you have any other questions. I will close this for now, but will gladly reopen this if you feel as though I have missed something in your request.

**Closed by ebonow** 2020-12-05 03:30 UTC
Labels: issue/enhancement, issue/reviewed

**Comment by Slapbox** [comment] 2021-01-15 22:16
@ebonow is there some way to detect whether the general React-Select component instance `isFocused`? I'm trying to style `SingleValue` based on whether the user has the React-Select component focused, but it's proving (seemingly) impossible?

**Comment by ebonow** [comment] 2021-01-15 22:43
@Slapbox there is an easy way and some more complex ways.
1) Use classNames and target `.[prefix]__control--is-focused .[prefix]__single-value`
2) You could pass the isFocused prop from the Control to the SingleValue
  - You could target the SingleValue by filtering the children of the Control component and apply the prop that way
  - You could create your own state and pass it to the select so that Control applies `setIsFocused` from selectProps based on value sent to it, so that the state value is then passed to the SingleValue through the selectProps as well.
  
While neither may not be ideal, I wanted to share that we did have an internal discussion about this and Jed's concerns were about the existing semantics, but mostly about him lamenting the naming scheme. The PR is marked for v3.3 so this is something likely to be released, though we have no date set yet on a followup for v4 or v3.3

**Comment by ebonow** [comment] 2021-01-16 01:22
@Slapbox the issue is mostly semantics at this point as `isFocused` (or isDisabled) could potentially refer to the specific component or the Select. That is the main reason why it wasn't originally included in all of the components and it's likely that a future version will contain something like `inputIsFocused` to provide more context of what's focused.
