### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by dominhtri1995** [JedWatson/react-select#3704] opened 2019-08-04 18:02 UTC
Hi ,

It looks like this library doesn't work with React 16.8.0. A simple example would crash the app with this error: unable to find node on an unmounted component.

Anyone knows how to fix this ? Thanks

**Comment by Rall3n** [comment] 2019-08-05 00:15
"Doesn’t work" is not very much to work with.

What version of `react-select` are you using? What was the code that caused this issue?

I recommend reading and using the issue template to provide all the information needed to help solving this issue.

**Comment by aej11a** [comment] 2019-08-05 19:55
I think you're right. I'm on React 16.8.6 and react-select 3.0.4, event the simplest example from the docs like this doesn't work. This code from the docs:

```
    const options = [
        { value: 'blues', label: 'Blues' },
        { value: 'rock', label: 'Rock' },
        { value: 'jazz', label: 'Jazz' },
        { value: 'orchestra', label: 'Orchestra' }
    ];
    return (
        <Select options={options}/>
    )
```
gives `serialize.esm.js?fc1b:141 Uncaught TypeError: Cannot read property 'length' of undefined`

**Comment by cutterbl** [comment] 2019-08-09 19:21
@aej11a @dominhtri1995 Really? It's working fine for me. v3.0.4 w/ React 16.8.6

[Codesandbox](https://codesandbox.io/s/react-select304-7z2xs)

**Comment by jrivax** [comment] 2019-08-21 13:07
Same issue here with React 16.8.6 and react-select 3.0.4
serialize.esm.js?7f34:141 Uncaught TypeError: Cannot read property 'length' of undefined
    at serializeStyles (serialize.esm.js?7f34:141)
    at css (css.browser.esm.js?8989:8)
    at keyframes (core.browser.esm.js?a8ab:252)
    at eval (chunk-5d200a41.browser.esm.js?ec81:810)
    at Object../node_modules/react-select/dist/chunk-5d200a41.browser.esm.js (<anonymous>:76754:1)
    at __webpack_require__ (<anonymous>:21:30)
    at eval (react-select.browser.esm.js?0ace:20)
    at Object../node_modules/react-select/dist/react-select.browser.esm.js (<anonymous>:76790:1)
    at __webpack_require__ (<anonymous>:21:30)

Any clue?

**Comment by Rall3n** [comment] 2019-08-22 06:26
@jrivax Error without code that caused the error is not that helpful. Would you mind providing a small reproducable example?

**Comment by jrivax** [comment] 2019-08-22 07:26
Hi @Rall3n , the problem seems that is not in my code, I use the simplest definition of the example and is not working. The problem is that the function **_serializeStyles_** in **_serialize.esm.js_** is getting only one argument so then args is undefined.

`var serializeStyles = function serializeStyles(registered, args, mergedProps) {
  if (args.length === 1 && typeof args[0] === 'object' && args[0] !== null && args[0].styles !== undefined) {
    return args[0];
  }`

This breaks because is getting only one argument from **_css.browser.esm.js_**

`import { serializeStyles } from '@emotion/serialize';

function css() {
  for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++) {
    args[_key] = arguments[_key];
  }

  return serializeStyles(args);
}

export default css;`

Even more, if I call the component `import Select from 'react-select';` even without making any use of this is crushing.

I don´t if this can help you to figure it out what is going on. I tried in some sandboxes and as @cutterbl said and is working find.

Thanks a lot in advice.

**Comment by jrivax** [comment] 2019-08-22 11:21
Never mind guys, the error was for other dependencies in the project. Other dependencies from the project were using react 15 and prop types was crushing. Not understanding well why was causing the serialize error, but was a false error, the error was about react version.

I'm explaining this in case it helps anyone. Have a deep look in all dependencies you use.

**Comment by aej11a** [comment] 2019-08-22 14:47
Hi @jrivax, when you say “other dependencies in THE project,” do you mean react-select or your own project?

Did the issue only start when you added react-select?

**Comment by Edmond-XavierCollot** [comment] 2019-09-06 13:54
In my case, the issue was a version mismatch with the emotion dependency in the package-lock.
`emotion` has recently changed the params order of `serializeStyles`, causing the issue.
`rm -r ./package-lock.json node_modules` + `npm i` resolved the issue.

**Comment by aaronlna** [comment] 2019-10-18 23:29
My issue was another dependency pulling in **`"@emotion/serialize": "^0.9.XX"`**, back when `serializeStyles` was defined as @jrivax detailed.

To play nicely with the version of emotion react-styles is using I specified my own devDependency on **`"@emotion/serialize": "^0.11.11"`**. The issue has been resolved for me. I'll need to see if the original authors can upgrade their emotion dep in the future.

**Comment by bladey** [comment] 2020-05-29 07:18
Hi all,

In an effort to sustain the `react-select` project going forward, we're closing old issues such as this one.

However, if you feel it is still relevant and you're still having issues - and you'd like us to review it - please provide a Codesandbox link and we'll look into it.

**Closed by bladey** 2020-05-29 07:18 UTC
