### ISSUE TITLE
onBlur doesn't work in custom component

### ISSUE THREAD

**Issue by Flakelf** [JedWatson/react-select#3595] opened 2019-05-29 17:28 UTC
hi, a thousand apologies for post this here, but this crash my mind

i don't understand why onBlur doesn't work

what i expect: when i choose some checkboxes with options and click whatever at the page - select will collapse

what i get: select collabes only when i click on arrow

pls help me and sorry for my poor english

you can check code here - https://codesandbox.io/s/elegant-mestorf-7rvl8

and i past it here

```import React from "react";
import ReactDOM from "react-dom";

import Select, { components } from "react-select";

const styles = {
  option: styles => ({
    ...styles,
    backgroundColor: "#ffff",
    color: "black"
  })
};

const Option = props => (
  <components.Option {...props}>
    <input type="checkbox" checked={props.isSelected} readOnly />
    <label>{props.data.label}</label>
  </components.Option>
);

const ValueContainer = ({ children, selectProps, ...props }) => {
  console.log(selectProps);
  const { getValue, hasValue } = props;
  const countSelectedVal = getValue().length;
  if (!hasValue) {
    return (
      <components.ValueContainer {...props}>
        {children}
      </components.ValueContainer>
    );
  }
  return (
    <components.ValueContainer {...props}>
      {`${selectProps.messages.orderPageAnySelectPreText}: ${countSelectedVal}`}
    </components.ValueContainer>
  );
};

const OrderSelectMulti = ({ options, ...props }) => {
  const components = { ValueContainer, Option };
  const messages = {
    orderPageAnySelectPreText: "Selected"
  };
  return (
    <Select
      styles={styles}
      isMulti
      messages={messages}
      components={components}
      hideSelectedOptions={false}
      options={[
        { value: "Status1", label: "Status1" },
        { value: "Status2", label: "Status2" },
        { value: "Status3", label: "Status3" }
      ]}
      placeholder="BlaBla"
      {...props}
    />
  );
};

const rootElement = document.getElementById("root");
ReactDOM.render(<OrderSelectMulti />, rootElement);

**Comment by rabbit0321** [comment] 2019-06-15 15:13
I have the same issue. blur is not working and remain the blue border style on the element 'sometimes' after selecting an option if I have customized the component.
* I customized <components.Control>

**Comment by fameriks** [comment] 2019-07-24 18:42
Hello guys, I faced with the same issue as described here. Not sure that it is exactly the same, since it is not enough info in comments. But in my case the root cause was in usage of HOC for custom component which replaced built-in. HOC creates new component each time you render it and destroy/unmount previous. So input that was created and focused on first render is replaced by completely new one - this leads to loosing focus/blur DOM state.

Similar case was asked here, it is not related to react-select, but describes the issue:
https://stackoverflow.com/questions/39120494/react-higher-order-component-forces-re-render-of-wrapped-component

My solution was not the same as you can see by link, because I still need to use HOC to make a closure for some variable. Instead I created local cache for parent component to update HOC only when variable was changed. It could be too specific for most people and probably you will be just fine to use answer from stackoverflow.

**Comment by bladey** [comment] 2020-06-23 04:57
Thanks for providing some insights @fameriks.

@Flakelf and @rabbit0321 I wanted to check in and see if @fameriks's answer has helped you.

**Comment by bladey** [comment] 2020-06-29 04:49
This issue will now be closed due to inactivity as there has been no response for further information. If anyone has further feedback please let me know and the issue will be re-opened.

**Comment by j-funk** [comment] 2020-07-31 19:49
@bladey this is still happening and has been happening for awhile, please reopen - I think @fameriks has correctly identified the issue (though I am still working it out), but this is still an issue with react-select, since imo the API should naturally preserve `onFocus` and `onSelect` without complicated workarounds.

https://github.com/JedWatson/react-select/issues/625

**Comment by effectivetom** [comment] 2020-08-04 22:23
I'm also experiencing this issue. In my case, I need to recompute `ValueContainer` each render so it can utilise the parent component's props to apply some custom formatting.

**Comment by barrychapman** [comment] 2020-08-31 20:52
i also have this issue - will it be fixed? or no? I will need to move to another library if this is not on the radar

**Comment by bladey** [comment] 2020-10-01 05:41
Thanks for the feedback @j-funk and @effectivetom!

**Comment by Rall3n** [comment] 2020-10-02 15:19
I believe the problem here is the same as in #4193.

My [solution there](https://github.com/JedWatson/react-select/issues/4193#issuecomment-686691429) should also be applicable here.

**Comment by ebonow** [comment] 2020-12-05 07:43
@fameriks  has identified that it is a composition issue and not a react-select issue. Creating a new functional component in the render cycle will cause this to happen not because of how react-select works, but because of how React works. React cannot reconcile the new component from the previous component. 

https://stackoverflow.com/questions/22573494/react-js-input-losing-focus-when-rerendering

To answer individual queries: 
@Flakelf I have a [working fork of your sandbox here](https://codesandbox.io/s/serverless-tdd-80nql?file=/src/index.js):
It works as expected if you render the same valueContainer but with different children. See below and compare with your original example.
``` JS
const ValueContainer = ({ children, selectProps, ...props }) => {
  console.log(selectProps);
  const { getValue, hasValue } = props;
  const countSelectedVal = getValue().length;
  return (
    <components.ValueContainer {...props}>
      {!hasValue
        ? children
        : `${selectProps.messages.orderPageAnySelectPreText}: ${countSelectedVal}`}
    </components.ValueContainer>
  );
};
```

@rabbit0321 I am unsure why you are running into those issues. I would likely compose it differently as putting the error message in the SelectContainer would still keep the error message and Control as sibling nodes. 

One guess I would make regarding the styling issues you are seeing may be related to overriding the className passed into the control that emotion or styledComponents would have otherwise provided.
``` JS
const SelectContainer = ({ children, ...props }) => (
  <component.SelectContainer {...props} >
    {children}
    {props.selectProps.error && (
        <span className="invalid-feedback">
          <ErrorMessage name={name} />
        </span>
    )}
  </component.SelectContainer>
);

const Control = ({ className, ...props }) => {
  // keep the existing className
  const newClassName = classnames(className, {
     'custom-react-select': true,
     'is-invalid': props.selectProps.error,
  });
  return  <components.Control {...props} className={newClassName} />
);
```

@j-funk @barrychapman @effectivetom 
I would be happy to take a look at your code and see where it could be made such that the react reconciler acts in a way that you expect that it should. I've rarely shied from looking at anyone's codesandbox.

The argument being made is that react-select should handle the reconciliation of a user trying to render two different components as if it's the same instance.  

The documentation could perhaps mention good practices and dangers of not being careful about this. Perhaps someone would be willing to take a look at writing a PR implementation that ensures a unique key is created for critical components like ValueContainer and Input? In the meanwhile, understand that there is some responsibility assumed for writing custom components.

**Comment by ebonow** [comment] 2020-12-14 21:11
I will be closing this for us to continue working through existing issues. If you have any specific questions or concerns, this can be reopened if necessary.  Again, the team is very willing to work through individual code implementations so long as there is an example for us to review as the ability to compose and replace internal components also creates a lot of different use cases.

**Closed by ebonow** 2020-12-14 21:11 UTC
Labels: issue/bug-unconfirmed, issue/reviewed

**Comment by colinscruggs** [comment] 2021-02-05 18:23
I was facing the same issue you were, where you could only close the menu by clicking the arrow. I got around this with a deceptively simple workaround: render the children of the ValueContainer, but just style them to have opacity: 0. This will maintain the original ValueContainer's functionality, but allow you to render whatever you want in the ValueContainer. Here's my code:

`const ValueContainer = props => {
  const {
    children,
    getValue,
    innerProps: { ...restInnerProps }
  } = props;

  const length = getValue().length;

  return (
    <components.ValueContainer
      ref={children[1].ref}
      {...restInnerProps}
      {...props}
    >
      <div style={{ opacity: 0 }}>{...children}</div>
      {length === 0
        ? `Select...`
        : `${length} item${length != 1 ? 's' : ''} selected`}
    </components.ValueContainer>
  );
};`
