### ISSUE TITLE
[v3.0.5] Old life cycle warning - AutosizeInput

### ISSUE THREAD

**Issue by devlemire** [JedWatson/react-select#3773] opened 2019-09-23 12:54 UTC
I'm aware that this is an active issue that many users are aware of. However, from what I read it looks like one last warning got swept under the carpet while celebrating the release of 3.0.5. Which by the way, thank you for this, it cleared up a TON of warnings in my Unit Tests. 

However... there is one last warning that wasn't taken care of. It occurs in the AutosizeInput component and it uses "componentWillReceiveProps" This is the last warning that is clogging my tests and my console in my dev tools. I would really love to see a fix for this. 

Again thanks for everything you've done thus far, I'm very grateful. Here's what my console says:

```
console.warn node_modules/react-dom/cjs/react-dom.development.js:11494
      Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

      * Move data fetching code or side effects to componentDidUpdate.
      * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
      * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

      Please update the following components: AutosizeInput
```

**Comment by mpopv** [comment] 2019-09-23 14:51
Duplicate of #3720

**Comment by julien51** [comment] 2019-09-23 16:09
This is not quite a duplicate and more like a regression as this issue #3720 should have indeed been fixed by the `3.0.5`?

**Comment by ranneyd** [comment] 2019-09-23 20:08
https://github.com/JedWatson/react-input-autosize/pull/166

**Comment by gwyneplaine** [comment] 2019-09-24 06:59
@devlemire  I don't have publishing rights to react-input-autosize, but I'll have a chat with @JedWatson to get this sorted ASAP, thanks for bringing this to our attention

**Comment by ranneyd** [comment] 2019-09-24 14:27
Gonna drop this guy here, since it's necessary for getting this lib fixed.

https://github.com/JedWatson/react-input-autosize/pull/167

**Comment by ranneyd** [comment] 2019-09-25 17:10
https://github.com/JedWatson/react-select/issues/3720#issuecomment-535120385

**Comment by devlemire** [comment] 2019-09-27 11:48
@gwyneplaine Were you able to get in contact? Sorry for the constant annoyance. It looks like a PR is available to solve the issue.

**Comment by erwanriou** [comment] 2019-09-30 18:45
+1 
Awaiting feedback. Go the exact same issue now that i started update all my react libraries

**Closed** 2019-10-01 04:59 UTC
