### ISSUE TITLE
Korean(non-English) characters are input weirdly on Firefox browser or Edge. 

### ISSUE THREAD

**Issue by starrybleu** [JedWatson/react-select#3162] opened 2018-11-01 05:11 UTC
Hi, this is Terry Lee.

My application is objected for Korean.

For your information, single Korean character is composited of each partial character. (that is not friendly to the non-Korean)

I tested typing Korean characters on your official [example site](https://react-select.com/home) on Firefox (v63.0 62bit), but there is strange thing on input text : when I typed next character, it seems that input occurs twice (unwanted appending).

For other browsers :
So does edge browser.
Chrome broswer is working well.

If I use `AutosizeInput` component in 'react-select` individually, there's no problem.

Does anyone guess what problem is?

**Comment by gwyneplaine** [comment] 2019-02-06 02:38
@starrybleu this should be resolved in the latest version of react-select (2.3.0).
Once this is confirmed I'll close this issue.

**Comment by starrybleu** [comment] 2019-02-10 11:19
@gwyneplaine Wow, Thank you for your works. I'll let you know whether it works or not after tests.

**Comment by Jonir227** [comment] 2019-03-15 09:41
@gwyneplaine 
I think this issue does not fixed.
when I type '도깨비불', it's input value turn into '돆깹빕불'.

korean input composes character one by one.
so in this case, korean input value changes like this.
ㄷ => 도 => 돆 => 도깨 => 도깹 => 도깨비 => 도깨빕 => 도깨비부 => 도깨비불.
and react select records all it's value change
ㄷ => 도 => 돆 => 돆ㄲ => ... etc

I hope this can help you!

**Comment by JedWatson** [comment] 2019-04-16 17:28
Should be fixed by #3442 (not released yet, will be soon)

**Comment by gwyneplaine** [comment] 2019-05-28 01:25
Thanks for raising this issue @starrybleu . This is resolved as part of #3563 which has since been merged and published. Please update to the latest version react-select to see this in effect.

**Closed by gwyneplaine** 2019-05-28 01:25 UTC
