### ISSUE TITLE
react select required property

### ISSUE THREAD

**Issue by SrinikaPuppala** [JedWatson/react-select#2016] opened 2017-09-20 06:39 UTC
how to add required property to react-select

**Comment by pavanshinde47** [comment] 2018-02-27 12:08
Someone please ansswer :)

**Comment by chubbsMcfly** [comment] 2018-03-07 17:37
Bump, I've tried both passing it directly as well as through inputProps, neither option is working for me.

**Comment by IanVS** [comment] 2018-11-20 18:10
Looks like a duplicate of https://github.com/JedWatson/react-select/issues/1453

**Comment by donlequy** [comment] 2019-06-02 18:56
> Bump, I've tried both passing it directly as well as through inputProps, neither option is working for me.

and could you show us :((

**Comment by bladey** [comment] 2020-05-29 06:11
Hello -

As @IanVS has mentioned, this issue is similar to #1453 which will be left open.

In an effort to sustain the `react-select` project going forward, we're closing old issues or issues that may be duplicates.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Closed by bladey** 2020-05-29 06:11 UTC
