### ISSUE TITLE
non-passive event listener in scroll blocking events

### ISSUE THREAD

**Issue by gugurete** [JedWatson/react-select#2729] opened 2018-06-19 23:16 UTC
chrome warnings popping up about non-passive event listeners

react-select.es.js:571 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by gwyneplaine** [comment] 2018-06-20 02:15
hello @gugurete thanks for raising this, which version of react-select are you using? 
Could you also supply us with a [codesandbox](https://codesandbox.io/s/new) with your select configuration, just so we can debug/ reason about this a bit easier.

**Comment by gugurete** [comment] 2018-06-20 05:28
It is version: 2.0.0-beta.6, and the offending code is in react-select.es.js starting with line 564
I believe it should be something like  **el.addEventListener('wheel', this.onWheel, {passive: true});**
to avoid chrome warning messages.

    key: 'startListening',
    value: function startListening(el) {
      // bail early if no scroll available
      if (el.scrollHeight <= el.clientHeight) return;

      // all the if statements are to appease Flow 😢
      if (typeof el.addEventListener === 'function') {
        el.addEventListener('wheel', this.onWheel, false);
      }
      if (typeof el.addEventListener === 'function') {
        el.addEventListener('touchstart', this.onTouchStart, false);
      }
      if (typeof el.addEventListener === 'function') {
        el.addEventListener('touchmove', this.onTouchMove, false);
      }
    }

**Comment by gugurete** [comment] 2018-06-20 05:29
https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md

**Comment by zike-Q** [comment] 2018-08-09 13:44
I am getting the same warnings on Chrome with "react-select 2.0.0-beta.7":

> Added non-passive event listener to a scroll-blocking 'wheel' event.
> Added non-passive event listener to a scroll-blocking 'touchstart' event.
> Added non-passive event listener to a scroll-blocking 'touchmove' event.

**Comment by xakep139** [comment] 2018-08-15 01:46
Same problem with `react-select` 2.0.0, Chrome version is 68.0.3440.106 (64-bit)

**Comment by jossmac** [comment] 2018-08-15 02:26
@gugurete looks good, would you mind submitting a PR?

**Comment by xakep139** [comment] 2018-08-15 04:03
@jossmac #2933

**Comment by jossmac** [comment] 2018-08-16 04:44
Re-opened due to #2940

**Comment by Ericnr** [comment] 2019-05-07 00:55
I'm still having this issue, any update on it?

**Comment by misarfraz** [comment] 2019-06-19 19:15
I'm having the same issue as well. 
`react-select: 3.0.4`
`Chrome: 74.0.3729.169`

**Comment by chrisnorwood** [comment] 2019-10-17 00:31
Still happening to me!

**Comment by jeltehomminga** [comment] 2019-12-16 11:51
> I'm having the same issue as well.
> `react-select: 3.0.4`
> `Chrome: 74.0.3729.169`

same issue for me on 

react-select: 3.0.8
Chrome: 78.0.3904.108

**Comment by tainefreitas** [comment] 2020-01-14 21:16
Same here!
react-select:3.0.8
Chrome for macOS: Version 79.0.3945.117 (Official Build) (64-bit)

**Comment by tainefreitas** [comment] 2020-01-16 21:02
The cause is the flag "menuIsOpen" in my case. 
About this tag, I have other problem (when I go back home, I create the issue and link here): I have multiple components in the page, but somehow always goes to the end of the page, where's the react-select is, and when I deactivate the flag, all the problems goes away...

**Comment by danielanjos** [comment] 2020-08-29 21:54
I have the same problem when I click for open or set menuIsOpen = true. I'm using the last version. 

![image](https://user-images.githubusercontent.com/32075081/91646776-11b73700-ea29-11ea-8c22-44bf0d5cf24f.png)

**Comment by b3rg3t** [comment] 2020-09-02 07:23
> I have the same problem when I click for open or set menuIsOpen = true. I'm using the last version.
> 
> ![image](https://user-images.githubusercontent.com/32075081/91646776-11b73700-ea29-11ea-8c22-44bf0d5cf24f.png)

Same here!!
react-select: 3.1.0
chrome: Version 84.0.4147.135 (Official Build) (64-bit)

**Comment by KevinDangVN** [comment] 2020-10-09 07:23
Same problem here. When I click to open menu which has items for scrolling.
Using the latest version.
React-select: 3.1.0
Chrome ver: 86.0.4240.75 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/52498580/95554814-05b49100-0a3b-11eb-97bf-a8beb6fdcad6.png)

**Comment by Methuselah96** [comment] 2020-11-14 16:41
I've started [a fork](https://github.com/react-select-oss/react-select) of react-select. Feel free to resubmit this issue on the fork and/or submit a PR to resolve this issue on the fork and we can get it merged and released.

**Comment by sgarchavada** [comment] 2021-01-07 07:56
Any solution yet?

**Comment by ebonow** [comment] 2021-01-07 17:40
This appears for me as well now with every mount/unmount of the Menu.

There appear to be some use cases that we want to interrupt scrolling, but these might be conditional so that we could potentially use the passive event listener. I think this would certainly be worth investigating.

**Comment by ebonow** [comment] 2021-01-07 17:51
@danielanjos @b3rg3t @KevinDangVN @sgarchavada 

It appears that this has been addressed here: https://github.com/JedWatson/react-select/pull/2940

Since reaching top or bottom of the menu list can cause the entire screen to scroll, `react-select` needs to be able to cancel the scroll event which means that the listener cannot be passive.

This behavior is enabled by the default prop value of: 
```js
export const defaultProps = {
   // ...
  captureMenuScroll: !isTouchCapable(),
  //...
}

To disable this behavior and remove the warnings, set the Select prop `captureMenuScroll` to `false`.

**Comment by rp-websites** [comment] 2021-01-14 05:53
@ebonow This solution worked for me. Thanks!

**Comment by Jezternz** [comment] 2021-02-08 09:42
Correct me if I am wrong, but surely `{passive: false}` would be a clear enough indicator to chrome that it is understood what the consequences of this are, and they are acceptable so please stop warning me. From very basic testing, this appears to tbe the case. understandable Select can't use `{passive: true}`, but surely `{passive: false}` is acceptable and will get rid of this warning?

**Comment by ebonow** [comment] 2021-02-08 15:37
@Jezternz, thanks. This was on my list of things to test. I just took a look into it and it does appear to disappear the warnings that are showing up in chrome. I will submit a PR to add in the passive: false

**Closed** 2021-03-04 22:37 UTC
Labels: issue/bug-unconfirmed, issue/has-pr, issue/reviewed
