### ISSUE TITLE
onMenuOpen or onMenuClose is not triggered from the mobile or tablets

### ISSUE THREAD

**Issue by ruthirlekar92** [JedWatson/react-select#3973] opened 2020-03-17 06:55 UTC
_No details provided_

**Comment by daschi** [comment] 2020-06-18 00:59
I can also confirm seeing this bug in `"react-select": "^3.0.8"`, when adding `onMenuOpen` and `onMenuClose` callbacks to the `Select` component, I'm not able to open the menu on mobile.

**Comment by elliotbonneville** [comment] 2020-10-05 19:23
We are seeing this as well. Any progress towards a fix?

**Comment by ebonow** [comment] 2021-01-17 07:13
Greetings @ruthirlekar92 , @daschi , @elliotbonneville 

I am not able to reproduce the described behavior. I have created the following codesandbox...
Codesandbox url: https://codesandbox.io/s/react-select-onmenuopen-onmenuclose-s6hoo 
Mobile demo url: https://s6hoo.csb.app/

<img width="462" alt="Screen Shot 2021-01-16 at 10 58 11 PM" src="https://user-images.githubusercontent.com/1007579/104833685-57956000-584f-11eb-8094-1ae96ac4cd0b.png">

Based on the number of issues and that there is no verifiable example, I will be closing this ticket. If you are experiencing issues opening the menu in the provided codesandbox or if you can provide a codesandbox example which demonstrates the described faulty behavior, please feel free to reply so we can reopen this ticket.

**Closed by ebonow** 2021-01-17 07:13 UTC

**Comment by PDenis98** [comment] 2025-01-21 08:51
> Greetings [@ruthirlekar92](https://github.com/ruthirlekar92) , [@daschi](https://github.com/daschi) , [@elliotbonneville](https://github.com/elliotbonneville)
> 
> I am not able to reproduce the described behavior. I have created the following codesandbox... Codesandbox url: https://codesandbox.io/s/react-select-onmenuopen-onmenuclose-s6hoo Mobile demo url: https://s6hoo.csb.app/
> 
> <img alt="Screen Shot 2021-01-16 at 10 58 11 PM" width="462" src="https://user-images.githubusercontent.com/1007579/104833685-57956000-584f-11eb-8094-1ae96ac4cd0b.png">
> 
> In an effort to work through the backlog of existing react-select issues and given that there is no verifiable example, I will be closing this ticket. If you are experiencing issues opening the menu in the provided codesandbox or if you can provide a codesandbox example which demonstrates the described faulty behavior, please feel free to reply so we can reopen this ticket.

Your codesandbox example works because you are only changing the label message on top of the select. I am trying to determine the state of the dropdown so i can add some custom styling like this 
 ```
 const [isOpen, setIsOpen] = useState(false);

   <UCSelect
      styles={isOpen ? { ...tabsSelectOpen } : { ...tabsSelect }}
      onMenuOpen={() => setIsOpen(true)}
      onMenuClose={() => setIsOpen(false)}
  </>
```
And in doing so, the dropdown opens only when i click on the icon.
