### ISSUE TITLE
Screen reader support for only english text

### ISSUE THREAD

**Issue by mohit181191** [JedWatson/react-select#4001] opened 2020-04-09 14:05 UTC
I'm using 3.0.8 version of react select. I was looking for multiple language support for strings used in aria tag in the component. Is there any way I can use localized string in aria-live tag. I can see the strings hard coded in English text and no way to pass into the component.

Below is the code snippet from the select component

```
export const instructionsAriaMessage = (
  event: string,
  context?: InstructionsContext = {}
) => {
  const { isSearchable, isMulti, label, isDisabled } = context;
  switch (event) {
    case 'menu':
      return 'Use Up and Down to choose options${isDisabled ? '' : ', press Enter to select the currently focused option'}, press Escape to exit the menu, press Tab to select the option and exit the menu.';
    case 'input':
      return '${label ? label : 'Select'} is focused ${
        isSearchable ? ',type to refine list' : ''
        }, press Down to open the menu, ${
        isMulti ? ' press left to focus selected values' : ''
        }';
    case 'value':
      return 'Use left and right to toggle between focused values, press Backspace to remove the currently focused value';
  }
};
```

**Comment by ebonow** [comment] 2020-12-12 06:05
Greetings, 
Thank you for reporting this and your patience. It is on our radar and I believe this is a duplicate of #3352 and additionally will be resolved by https://github.com/JedWatson/react-select/pull/4161

Closing this as a duplicate and addressing with the cited issue and PR. Thank you for reporting this and feel free to follow either the issue or PR for updates.

**Closed by ebonow** 2020-12-12 06:05 UTC
Labels: category/accessibility, category/question, issue/reviewed
