### ISSUE TITLE
Showing Ellipsis in Multi Select Mode

### ISSUE THREAD

**Issue by abhitechdojo** [JedWatson/react-select#752] opened 2016-02-02 19:55 UTC
Hello,

I am using React Select in Multi Select mode. Everything works well when user selects 3/4 items but the select component begins to look bad when the user selects more items.

the reason is that the component begins to grow vertically and horizontally.

What I want is that the box should remain of fixed width and if the user selects more items then we just show Ellipsis.

How can I do this in multi select mode?

**Comment by granteagon** [comment] 2016-02-04 14:35
You'll probably have to build a solution yourself and do a pull request.  It's either that or wait until someone else builds it.

**Comment by jimmed** [comment] 2016-03-10 14:41
@abhitechdojo I've actually just implemented this on a private codebase. My solution is not complete, however.

Essentially you can use [`text-overflow: ellipsis`](https://developer.mozilla.org/en/docs/Web/CSS/text-overflow#Examples) with a `max-width` on the `Select-item` elements. The difficulty then comes with deciding on a 'correct' behaviour as the Select grows vertically.

I would be very interested in any solutions others have come up with for this.

**Comment by granteagon** [comment] 2016-03-10 14:53
@JedWatson should this be an enhancement implemented through configuration?  Seems like a common use case.  Maybe adding maxWidth and maxHeight options, then overflow ellipsis would be a good first step.  If you agree, I can implement and do a PR.

**Comment by dennis-kayser** [comment] 2016-11-22 09:36
@granteagon Did you ever build a solution for this? 
We have the exact same problem with a multi select that's in a fixed height container. Another option would be to have a parament to limit the number of options shown e.g. 3 and then all selected after that are ellipsed.

**Comment by abhitechdojo** [comment] 2016-11-25 00:52
Use a different component. This one has this limitation.

________________________________

**Comment by sidewayskumara** [comment] 2017-10-26 03:15
Has anyone found a workaround for this?

**Comment by sidewayskumara** [comment] 2017-10-26 03:52
As an alternative  `.Select-multi-value-wrapper {
        white-space: nowrap;
        overflow-x: scroll;
        width: 250px;
    }`

**Comment by JedWatson** [comment] 2017-10-26 03:55
Thanks for the solution @sidewayskumara 

I'm going to close this as resolvable with user-styling, since we don't have a clear design on how it could be implemented in the default Select. Happy to review any design proposals and implementations, but otherwise I think this is really hard to do in a generic way but it's easy for users to customise / override the stylesheet.

**Closed by JedWatson** 2017-10-26 03:55 UTC

**Comment by sht5** [comment] 2019-01-02 18:46
i've managed to achieve both the ellipsis effect and leaving the display at one row,
here is a working example
https://codesandbox.io/s/v638kx67w7
hope this helps

**Comment by upender7270** [comment] 2019-03-09 16:37
@sht5 i have changed your code(only data input) according to my requirement
https://codesandbox.io/s/xo4qrvvoqo
but on click expand selected options are not getting visible in value container.
can you help me asap.

Thanks in advance

**Comment by sht5** [comment] 2019-03-09 16:45
![image](https://user-images.githubusercontent.com/1850193/54074470-73b33800-429b-11e9-8174-2e98a8063a9e.png)
I don't understand what the problem is...

**Comment by upender7270** [comment] 2019-03-10 05:21
@sht5 click the dropdown to open menu and see.Attachment below
![image](https://user-images.githubusercontent.com/43287621/54080979-2ded8280-4322-11e9-8e9b-5831cf9582f5.png)

**Comment by sht5** [comment] 2019-03-10 06:30
ok i see the problem. i've tried to dig into it, don't really understand why this is happening. The truth is this is a hack...

**Comment by upender7270** [comment] 2019-03-10 06:52
Ya i tried to but no luck. I guess its problem with default value selection, because once we clear all selected options and start selecting again its looking fine.

**Comment by randerson57261** [comment] 2022-05-24 20:39
I didn't implement an ellipse solution, but I did restrict it to just overflow the box with some css:
```
.react-select__value-container{
  flex-wrap: nowrap !important;
}

.react-select__multi-value{
  min-width: 40% !important;
}
```
in JS the classNamePrefix needs to be set:
```
    <Select
      classNamePrefix="react-select"
      value={selectedFloats}
      options={floatOptions}
      isMulti
    />
```
Looks like:
![image](https://user-images.githubusercontent.com/74583143/170127858-921017df-d72a-4a94-a53f-18fa97ebc38a.png)

**Comment by MalyanaSkyrim** [comment] 2022-07-29 02:45
@sht5 I used your code and solved the issue of options disappearing when we focus on selector input
```
const ValueContainer = ({ children, ...props }) => {
    const isInputExpanded = children[1]?.props["aria-expanded"];
    return (
      <components.ValueContainer key={isInputExpanded} {...props}>
        {props?.hasValue ? (
          <Text overflow="hidden" textOverflow={isInputExpanded ? "unset" : "ellipsis"} whiteSpace="nowrap">
            {children}
          </Text>
        ) : (
          children
        )}
      </components.ValueContainer>
    );
};
```

**Comment by mdmathewdc** [comment] 2022-08-30 23:52
Toggle between `display: flex` and `display: initial` depending on whether an element is selected or not and @sht5's solution should work perfectly!

```
styles={{
        indicatorSeparator: () => ({ display: 'none' }),
        valueContainer: (base: CSSObjectWithLabel, state) => {
          console.log('Current state :  ', state);
          return {
            ...base,
            textOverflow: 'ellipsis',
            maxWidth: '90%',
            whiteSpace: 'nowrap',
            overflow: 'hidden',
            display: `${state.hasValue ? 'initial' : 'flex'}`,
          };
        },
      }}
```

**Comment by neeraj123ved** [comment] 2022-11-30 13:29
`import { useEffect, useState } from 'react';
import Select, { components } from 'react-select';
import { option, TypeReactMultiSelectDropdownProps } from './TypeReactMultiSelectDropdown';
import './react-multiselect-dropdown.scss';

const ReactMultiSelectDropdown = () => {

  const [optionSelected, setOptionSelected] = useState([] as option[]);
  const [ismenu, setIsmenu] = useState(true);

  const handleSelected = (selected: option[]) => {
    const filterOption = selected.reduce((a, b) => (a ? `${a},${b.value}` : b.value), '');
    const filterLabel = selected.reduce((a, b) => (a ? `${a},${b.label}` : b.label), '');
    document.querySelector('.multiple-select-element__placeholder').textContent =
      filterLabel;
    setOptionSelected(selected);
  };

  const handleMenuOpen = () => {
    setIsmenu(true);
    openMenu();
  };

  const handleMenuClose = () => {
    setIsmenu(false);
  };

  useEffect(() => {
    if (!ismenu) {
      closeMenu();
    }
  }, [ismenu]);

  const OptionsList = (props: { isSelected: boolean; label: string }) => (
    <components.Option {...props} key={props.label}>
      <input
        key={`check-${props.label}`}
        type="checkbox"
        checked={props.isSelected}
        onChange={() => null}
        id={props.label}
      />{' '}
      <label
        key={`label-${props.label}`}
      >
        {props.label}
      </label>
    </components.Option>
  );

  return (
    <Select
      className="multiple-select"
      classNamePrefix="multiple-select-element"
      options={options}
      isMulti
      blurInputOnSelect={false}
      closeMenuOnSelect={false}
      hideSelectedOptions={false}
      onMenuOpen={handleMenuOpen}
      onMenuClose={handleMenuClose}
      placeholder=""
      components={{
        Option: OptionsList,
      }}
      isSearchable={false}
      onChange={handleSelected}
      allowSelectAll
      controlShouldRenderValue={false}
      value={optionSelected}
    />
  );
};
export default ReactMultiSelectDropdown;`

**Comment by polixisNG** [comment] 2024-01-18 08:31
> ![image](https://user-images.githubusercontent.com/1850193/54074470-73b33800-429b-11e9-8174-2e98a8063a9e.png) I don't understand what the problem is...

we would like it to work like this
<img width="415" alt="Screenshot 2024-01-18 at 12 30 18" src="https://github.com/JedWatson/react-select/assets/75425051/479cfce6-b6f5-42d4-8af2-7e99314c9de7">

**Comment by polixisNG** [comment] 2024-01-18 08:32
> ![изображение](https://user-images.githubusercontent.com/1850193/54074470-73b33800-429b-11e9-8174-2e98a8063a9e.png) Я не понимаю, в чем проблема...

we would like it to work like this

<img width="415" alt="Screenshot 2024-01-18 at 12 30 18" src="https://github.com/JedWatson/react-select/assets/75425051/d3a80b53-df06-48d5-bb3f-f33a78738fa0">

**Comment by jreynolds13** [comment] 2024-02-15 22:35
Has anyone been able to solve the issue with @sht5's example where after selecting all options and closing/unfocusing the menu, when you re-open the menu the label content shifts to the left to make space for the text that is hidden by `text-overflow: ellipsis;`?

@MalyanaSkyrim's extra step of applying `text-overflow: unset` when the menu is open doesn't really fix that issue. It allows the full label to be visible while the menu is open, but as soon as you close the menu again the layout shift and empty space becomes noticeable again.
