### ISSUE TITLE
Programmatically focus select component

### ISSUE THREAD

**Issue by radar** [JedWatson/react-select#856] opened 2016-03-30 20:52 UTC
I'm looking to write an integration test for a form that uses a react-select component. This is the Ruby code that I have for it now:

``` ruby
find(".Select").click
find(".Select .Select-input input").native.send_key("Text goes here")
find(".Select-option", text: option_value.presentation).click
```

I would believe this would:
1. Open the input field
2. Send the phrase "text goes here" into the field.
3. Find the option that matches that text, and then click it.

However, I'm getting this error in my tests:

```
Capybara::Poltergeist::MouseEventFailed:
       Firing a click at co-ordinates [356.5, 384] failed. Poltergeist detected another element with CSS selector 'html.js.touch body#en-AU-be.loggedin div.wrapper div.main div div.form--flat div.AdvertForm div.DisplayPanel div div.row div#option_type_wrapper_1.span6.error span.select div.Select.is-focused.is-open.is-searchable div.Select-control div.Select-placeholder' at this position. It may be overlapping the element you are trying to interact with. If you don't care about overlapping elements, try using node.trigger('click').
```

I would consider documentation for how to integration test a react-select (even if it is with some jQuery functions) would be something that this library should provide. I am considering this a "bug" with the documentation for this component, which is why I'm filing this issue.

Please add some examples of programatically triggering / filling in this element with jQuery.

**Comment by mipearson** [comment] 2016-03-31 02:21
I've also looked at this, I work with Ryan.

The problem is that the placeholder element sits above the input element.

Sending keys to the placeholder element crashes PhantomJS 2.0 and 2.1, so that won't work.

Setting the value of the input element does not do anything. Using `send_keys` _used_ to work, but no longer does.

I consider this a bug with react-select and not our testing as react-select is doing strange things to do the DOM that break how input elements are supposed to work.

**Comment by mipearson** [comment] 2016-03-31 02:23
Oh, and we're using 1.0.0-beta5

**Comment by rzane** [comment] 2016-04-27 21:05
Anybody figure this out?

**Comment by mipearson** [comment] 2016-04-28 03:01
Unfortunately, we ended up rolling our own autocomplete instead.

**Comment by rzane** [comment] 2016-04-28 15:11
I think I figured it out. I think it's something like:

```javascript
```

**Comment by ilantc** [comment] 2016-05-05 08:51
From what I saw when firing mousedown on the select the input.focus() is called, but the render is not (until I actually click on the screen). 
It seems that setState is not being called when programmatically clicking the select.
Is there a way to fix this?

**Comment by AlanFoster** [comment] 2016-05-13 00:58
@radar Can confirm this is awkward using Selenium too - 

```
Selenium::WebDriver::Error::UnknownError: Element is not clickable at point (341, 45). Other element would receive the click: <div class="Select-placeholder" data-reactid=".0.1.1.0:$placeholder"></div>
```

The overlaying of elements is confusing the web driver it seems.

For what it's worth, this works completely fine with Capybara and the `javascript_driver` set to `webkit`, using the `rack_test` web driver. I'm not sure if you're in a position to switch that configuration though, but it helped unblock me.

**Comment by timsheng** [comment] 2017-04-17 13:33
@ilantc have you found a solution to fix that issue?

**Comment by ilantc** [comment] 2017-04-18 06:52
@timsheng 
What we ended up doing is firing focus on the hidden input before dispatching the click events on the select.
Not ideal, but it works

**Comment by liorbentov** [comment] 2017-05-29 19:07
@ilantc, can you write here that piece of code that worked?

**Comment by AlanFoster** [comment] 2017-05-30 10:53
@liorbentov If you're using the `react-addons-test-utils`, something similar to:

```js
const input = yourElement.querySelector('input');
TestUtils.Simulate.focus(input);

const selectArrow = yourElement.querySelector('.Select-arrow');
TestUtils.Simulate.mouseDown(selectArrow, { button: 0 });
```

It is possible to use enzyme etc, the important thing is that you need to focus on the input, then mouse down on the Select-arrow with button 0 set.

**Comment by liorbentov** [comment] 2017-05-30 21:34
@AlanFoster thanks!
But I'm actually trying to do this on selenium (or chrome), and can't seem to get it right

**Comment by AlanFoster** [comment] 2017-05-30 22:22
@liorbentov Unfortunately I was only able to trigger the component to open with selenium/capybara with JavaScript directly, due to the component's DOM structure and how it's styled on the page.

**Comment by kwnccc** [comment] 2017-08-25 09:55
@JedWatson any update on this? is there any way that we can actually trigger programmatically the selection dropdown? I'm currently using NightmareJS and cannot see any working solution.

**Comment by nathanielescribano** [comment] 2017-09-01 22:49
Looking for a similar thing. trying to write integration tests using zombiejs but unable to find the best way to programmatically trigger the dropdown.

**Comment by vzkr** [comment] 2017-10-09 07:25
see also #603 _Document how to test with selenium_

**Comment by sidewayskumara** [comment] 2017-12-01 05:36
This worked for me using Selenium: 
``` 
const getSelect = () =>
  driver
  .findElement({
    className: 'Select-placeholder'
  })
  .findElement({'xpath': '//*[@id="react-select-2--value"]/div[2]/input'});

await driver.wait(until.elementLocated(getSelect));
const select = await getSelect();
await select.sendKeys(query);
```

The xpath there is to the input element

**Comment by volkanunsal** [comment] 2018-02-22 14:20
Does anyone know how to simulate selection on this component using just Javascript? The code samples above did not work for me. 

```js
$('.Select-input input').trigger('mousedown');
$('div.Select-option').first().trigger('mousedown');
```

I need a solution I can use in my integration tests. 

I'm using React 15.6.2 and react-select 1.2.1.

**Comment by aterreno** [comment] 2018-04-16 13:41
@volkanunsal after a few failed tentatives, I ended up doing 'brute force' by tabbing, going down with the arrow key and then sending an enter.

```
    const TAB = '\u0009';
    const ARROW_DOWN = '\uE015';
    const ENTER = '\uE007';
    browser.keys([TAB, ARROW_DOWN, ENTER]);
```

**Comment by nachikethashu** [comment] 2018-05-11 21:33
I was able to get the menu opened with following code:
`this.mouseEvent('mousedown', '.Select .Select-arrow-zone');`

Note that this is casperJS syntax. However I feel you can extend this to any other framework.

**Comment by sad148** [comment] 2018-05-23 18:46
Was anyone able to find a fix for selenium?

**Comment by arhtudormorar** [comment] 2018-05-26 09:18
I'm also not able to solve it - I am trying with jQuery but no solution until now...

**Comment by abidvf** [comment] 2019-02-12 12:17
I am also not been able to trigger it with jasmine.

**Comment by seclace** [comment] 2019-03-29 14:01
It seems to changes in library itself, so we need to trigger event `touchend` on svg icon or its wrapper to open options list to be able to select one.

This link may be helpful to testing in chrome (presumably puppeteer for integration tests): https://stackoverflow.com/a/42447620

**Comment by natew** [comment] 2019-04-04 22:31
A `forceOpen` property would be really nice -- right now I have a z-index issue where the menu is hidden on open, but I can't debug it easily, because it goes away once I try and inspect it.

**Comment by bladey** [comment] 2020-06-05 05:31
Hi all,

Thank you everyone who had a part in addressing this question.

In an effort to sustain the `react-select` project going forward, we're closing issues that appear to have been resolved via community comments.

However, if you feel this issue is still relevant and you'd like us to review it, or have any suggestions regarding this going forward - please leave a comment and we'll do our best to get back to you!

**Closed by bladey** 2020-06-05 05:31 UTC
Labels: enhancement, testing

**Comment by josias-r** [comment] 2022-11-03 09:50
Tried all the options above, nothing worked in plain js for me.
But after a while I figured out, this works:

```js
selectContainer.querySelector("input").focus(); // focus select component
selectContainer
  .querySelector(".YOUR_CUSTOM_CLASS__dropdown-indicator")
  .dispatchEvent(
    new MouseEvent("mousedown", {
      button: 0,
      bubbles: true, // this is key, otherwise it wont work
    })
  ); // open the menu by "clicking" dropdown indicator
```

**Comment by zukilover** [comment] 2023-01-19 11:01
Using Katalon Chrome Extension, I've successfully triggered opening a dropdown by using these anchors:

`xpath=//div[@class="fs-r-select__indicators"]`, this is to trigger the dropdown, and then
`id=react-select-${id}-option-${optionId}`, this is to select a certain option, e.g. `id=react-select-1-option-0`

<img width="663" alt="Screen Shot 2023-01-19 at 18 00 26" src="https://user-images.githubusercontent.com/371291/213425551-e54bb460-97b1-43bc-ac6a-5e6fbb15406b.png">

**Comment by laurentiu-lese-collinson** [comment] 2023-03-01 11:10
if we want to do it via react test library I would always recommend to check the actual tests from this library, they are the key to understand what needs to be triggered.
e.g.
```
  // Re-open Menu
  fireEvent.mouseDown(
    container.querySelector('div.react-select__dropdown-indicator'),
    {
      button: 0,
    }
  );
```
If we are talking about vanilla js, we can do it like this:
(notice the selector that uses a pattern for class selection, you should replace the value with whatever class you have in your project for dropdown indicator)
```
const element = document.querySelector('div[class*=dropdown-indicator]')
element.dispatchEvent(new MouseEvent('mousedown', {
  bubbles: true,
  cancelable: true,
  view: window
}));
```
