### ISSUE TITLE
v.3.1 -> v3.2, cursor no longer stays focused when entering multi

### ISSUE THREAD

**Issue by stickfigure** [JedWatson/react-select#4418] opened 2021-02-02 20:37 UTC
I recently tried upgrading from 3.1.1 to 3.2.0 and the cursor focus behavior changed when doing multi select.

Video is probably easiest to demonstrate:
Here's how 3.1 behaves: https://monosnap.com/file/W0lXOkKpvniLhmZhsK3MNi7syBQwlO
Here's how 3.2 behaves: https://monosnap.com/file/VBOejT6q0nGoB1huj2of77cRyXDiA8

No code changes on my end, just changed the react-select version.

Is this intentional? Is there a workaround? 

Thanks in advance.

**Comment by ebonow** [comment] 2021-02-03 00:15
Greetings @stickfigure,

Would you mind sharing a codesandbox or at least source of your implementation? 

I am unable to reproduce the described behavior using the multi example (2nd example) provided in the [documentation](https://react-select.com/creatable) and building it against version 3.2 in this [codesandbox](https://codesandbox.io/s/codesandboxer-example-forked-qu0rc).

A few places to look at causing the input to blur:
- `onChange` prop
- `handleCreate` prop
- The render and scope of custom `Control` or `ValueContainer` components being rendered relative to the Select.

**Comment by ebonow** [comment] 2021-02-17 20:35
Closing due to inability to reproduce and no reply. Happy to revisit if issue persists and can be verified.

**Closed by ebonow** 2021-02-17 20:35 UTC
Labels: awaiting-author-response, category/question
