### ISSUE TITLE
How to keep value in textbox search after choosing it

### ISSUE THREAD

**Issue by cnits** [JedWatson/react-select#1826] opened 2017-06-26 09:14 UTC
I saw option onBlurResetsInput to set whether to clear input on blur or not.

And I also want to do that after choosing a value. Please show me how to do?

Thanks in advance!

**Comment by DigitalFlow** [comment] 2017-07-23 10:50
Hey there,

just had this issue myself.
You'll have to save the selected value somewhere (preferably in your state) and then pass it as value element to the Select on the next render.

Kind Regards,
Florian

**Comment by mshwery** [comment] 2017-08-06 04:21
This would be useful – sometimes with a searchable Select the user may want to place the cursor in the currently selected value to alter it, or select part of the text to change/remove it.

The display value is misleading because it _appears_ as though you can do this ^, but in fact you cannot. It might be worthwhile to add a `keepInputValue`.

Another way to potentially go about this would be to provide a custom renderer for the _input_ itself.

Either way you'd want to use the input as the display for the selected value instead of the ValueRenderer. Although, there might be a clever way to approach this that supports both the `ValueRenderer` prop as well as keeping the selected value in the input.

**Comment by jeremymarc** [comment] 2017-10-19 00:10
any update on this?

**Comment by jeremymarc** [comment] 2017-10-19 15:45
#2075

**Comment by mcpolandc** [comment] 2017-10-20 20:04
@jeremymarc See my comment on #2075

**Comment by mcpolandc** [comment] 2017-10-20 20:25
@mshwery 

`This would be useful – sometimes with a searchable Select the user may want to place the cursor in the currently selected value to alter it, or select part of the text to change/remove it.`

I think the ability to re-edit the input after selecting a value would be an excellent enhancement to the project. I will put up a PR to this effect if you don't mind.

**Comment by jeremymarc** [comment] 2017-12-07 12:14
@mcpolandc  @gwyneplaine I don't think "backspaceRemoves" is what we are talking about ; I want, when clicking  in the search field, to select the current value so you can delete it by typing any key, something like that:

Input field without focus
https://www.dropbox.com/s/6u5nl8cfu02ay41/Screenshot%202017-12-07%2013.12.44.png?dl=0

Input field with focus:
https://www.dropbox.com/s/k3ic6h4slxe41cl/Screenshot%202017-12-07%2013.13.05.png?dl=0

That was the purpose of my PR #2075

**Comment by magdalko** [comment] 2018-01-16 10:02
anything changed to this issue? It would be awesome to have options to edit the selected text to make new search (doesnt have to write from scratch the names to search)

**Comment by hollandmatt** [comment] 2018-02-06 18:55
I've been having a similar issue to @jeremymarc - here's an example app: https://codesandbox.io/s/q27lnon96

And here's the behaviour:

![feb-06-2018 10-44-11](https://user-images.githubusercontent.com/10201979/35878086-15c0810a-0b2c-11e8-8800-92b64f0a3153.gif)

Whether `backspaceRemoves` is set to false or true, the value still vanishes when `Select` loses focus (Although it's clearly still preserved in the state of the component, as it re-appears when `Select` gets focus back).

**Comment by davidcalhoun** [comment] 2018-04-04 19:35
Also running into this issue - the behavior right now creates some usability issues.  `backspaceRemoves` doesn't really address the problem.

Some use cases:

1. User clicks into text field that has a value already set and sees a blinking cursor, indicating it's an editable text field.  Then user presses the backspace key.
    * Expected behavior: the last character of the string should be deleted (normal behavior with a blinking caret)
    * Actual behavior: the entire string is deleted (if `backspaceRemoves` is set to `true`), or nothing happens (if `backspaceRemoves` is set to `false`).  Both of these behaviors are unexpected.
3. The user clicks into the text field, sees a blinking cursor, and presses the back arrow.
    * Expected behavior: the blinking caret should shift one character to the left
    * Actual behavior: no response
4. The user clicks into text field, sees the blinking caret at the end of the line, and then tries to click in the middle of the string to change the caret location.
    * Expected behavior: the blinking caret changes to the middle of the string, where the user clicked.
    * Actual behavior: no response

**Comment by DaveOdden** [comment] 2018-04-24 13:51
I am also in need of this feature. The blinking cursor is causing an illusion of a text input interaction, degrading the usability of this component. The intent for my use case is to emulate the behavior of a text input with autocomplete.

**Comment by speedo-sp7** [comment] 2018-07-30 09:20
Any update here?

**Comment by huttj-liveperson** [comment] 2018-08-09 15:54
>When I select a value in the dropdown, which appears to clear the input, but in actuality sets the opacity to 0. For that, I had to set opacity: 1 !important; in my own CSS for .myContainer input.

I ran into this, too. Wondering why this is, and what the intended way of turning it off is.

**Comment by dehghani-mehdi** [comment] 2018-09-21 09:30
I believe it's a bug, not a question, so please remove `question` tag and add `bug` tag to this issue!

**Comment by m-apsolon** [comment] 2018-09-28 09:08
+1

**Comment by TITAN9389** [comment] 2019-01-10 20:11
> @DaveOdden (and others) For V2- I was able to enable editable text by setting the `inputValue` prop on the `Select` to be whatever text I wanted to show in the input, which works, except for when I select a value in the dropdown, which appears to clear the input, but in actuality sets the opacity to 0. For that, I had to set `opacity: 1 !important;` in my own CSS for `.myContainer input`. It took days to figure this out but the input now behaves much better as you can click on the text, highlight it, the cursor appears at the end of the input like a normal text field.
> 
> The other thing I had to do was to make sure not to set blank text on the input when the input is focused- the current behavior just clears the input when you click on it, because there is a `menu-close` action happening which unintentionally sets a blank string on the input. For that, in my `onInputChange` handler, I do not set my local react state value when `!value && action === 'menu-close`, and simply `return` out of the callback so my component is not setting the inputValue to be an empty String.

can you show a code please , i couldn't do the !value && action part , where should i get the action ?
@lusa

**Comment by TITAN9389** [comment] 2019-01-10 21:35
> > @DaveOdden (and others) For V2- I was able to enable editable text by setting the `inputValue` prop on the `Select` to be whatever text I wanted to show in the input, which works, except for when I select a value in the dropdown, which appears to clear the input, but in actuality sets the opacity to 0. For that, I had to set `opacity: 1 !important;` in my own CSS for `.myContainer input`. It took days to figure this out but the input now behaves much better as you can click on the text, highlight it, the cursor appears at the end of the input like a normal text field.
> > The other thing I had to do was to make sure not to set blank text on the input when the input is focused- the current behavior just clears the input when you click on it, because there is a `menu-close` action happening which unintentionally sets a blank string on the input. For that, in my `onInputChange` handler, I do not set my local react state value when `!value && action === 'menu-close`, and simply `return` out of the callback so my component is not setting the inputValue to be an empty String.
> 
> can you share example code please , i couldn't do the !value && action part
> 
> ```
> handleSearch = (e, action) => {
> if (!e && action === 'menu-close') {return} 
> else { this.setState({searchValue: e})}
> };
> ```
> here is how i'm doing but still setting my input value to empty string.
> @lusa

I fixed it by this way

1- onInputChange:
```
handleSearch = (value, {action}) => {
if (action === 'menu-close' || action === 'input-blur' || action === 'set-value') {return} 
else { this.setState({searchValue: value})}
};
```

2- onChange: (so it sets the value of your input same as you selected)
```
handleSelect = ({label, value, ...rest}) => {
this.setState({ searchValue: e.value })
}
```

**Comment by croxluis** [comment] 2019-01-24 16:13
@TITAN9389 could you please post an example, I can not fix it.

**Comment by TITAN9389** [comment] 2019-01-24 22:17
@croxluis here is example , a little bit messy but what you ask is in index.js
https://codesandbox.io/s/rroxqy2nlo

**Comment by Alatius** [comment] 2019-04-07 12:32
@TITAN9389 Great, exactly what I was looking for, thank you! One thing though that I noticed is that this solution does not seem to work well with the isClearable property: that is, the clear button is never displayed. Ideally, it would be nice if a clear button could be displayed as long as something is shown in the entry box.

**Comment by TITAN9389** [comment] 2019-04-07 14:26
> @TITAN9389 Great, exactly what I was looking for, thank you! One thing though that I noticed is that this solution does not seem to work well with the isClearable property: that is, the clear button is never displayed. Ideally, it would be nice if a clear button could be displayed as long as something is shown in the entry box.

You're Welcome @Alatius 
umm i'm not sure about that i need to try and see it, in case if you find a way to do it before me, feel free to share :) (i'm bit busy these days)

**Comment by Alatius** [comment] 2019-04-07 17:55
@TITAN9389 I sort of solved it. The problem was that no option actually was selected: I had to modify the handleSearchSelection function, to set searchSelection to the selected object, not just its value. See https://codesandbox.io/s/346918zzp1
So once an option is selected, the clear button will appear. This is a partial solution to what I wanted, but to make the clear button appear when just something is entered (but nothing actually selected in the menu) will demand hacking the Select component code, so I'll leave that for now.

**Comment by robinlestagiaire** [comment] 2019-05-23 08:46
Everything works fine for me but I have one more problem, I can't display the options at the **top** of the bar, I tried everything with the z-index and positioning, but _menuPlacement="top"_  just don't want to work. Does this problem comes from the integration with material-ui ? Should I create a new bug ?

**Comment by abrahamrhoffman** [comment] 2020-07-21 20:21
@TITAN9389 This really deserves a +1! Thank you so much, this finally finally fixed my problem. onblur! Should have thought of that.

**Comment by ebonow** [comment] 2020-12-02 20:03
Greetings all, I have addressed this in several other places and [started a discussion](https://github.com/JedWatson/react-select/discussions/4302) about making this potentially easier but the approach is fairly straight forward to roll on your own.

1. Create a custom Input to ensure isHidden is always false
``` JS
const Input = props => <components.Input {...props, isHidden: false } />
```

2. Make the input controlled so we can override the inputValue when an option is selected or the input is blurred.
``` JS
  const [value, setValue] = useState();
  const [inputValue, setInputValue] = useState("");

  const onInputChange = (inputValue, { action }) => {
    // onBlur => setInputValue to last selected value
    if (action === "input-blur") {
      setInputValue(value ? value.label : "");
    }

    // onInputChange => update inputValue
    else if (action === "input-change") {
      setInputValue(inputValue);
    }
  };

  const onChange = (option) => {
    setValue(option);
    setInputValue(option ? option.label : "");
  };
```

3. Hide the rendered value component with the prop `controlShouldRenderValue`

Putting this all together looks like this...
``` JS
const Input = props => <components.Input {...props, isHidden: false } />

const [value, setValue] = useState();
const [inputValue, setInputValue] = useState("");

const onInputChange = (inputValue, { action }) => {
    // onBlur => setInputValue to last selected value
    if (action === "input-blur") {
      setInputValue(value ? value.label : "");
    }

    // onInputChange => update inputValue
    else if (action === "input-change") {
      setInputValue(inputValue);
    }
};

const onChange = (option) => {
    setValue(option);
    setInputValue(option ? option.label : "");
};

return (<Select
  value={value}
  inputValue={inputValue}
  onInputChange={onInputChange}
  onChange={onChange}
  controlShouldRenderValue={false}
  components={{ Input }}
  ...
/>)
```
[Here is the corresponding sandbox](https://codesandbox.io/s/react-select-editable-and-selectable-6nfdv?file=/src/App.js) which allows the user to freely type and edit into the input as would be expected behavior of an input.

That said, there is a dedicated discussion to share more thoughts if this were to be an internal prop to manage this, but in lieu of that, it is possible to accomplish this nonetheless.

As such, I will be closing this issue as more discussion about this can be had in the discussions channel with the provided link above.

**Closed by ebonow** 2020-12-02 20:03 UTC
Labels: category/question, issue/reviewed

**Comment by alnepravskaya** [comment] 2021-01-07 22:12
save custom value + clear 'x' work for  custom value
https://codesandbox.io/s/async-violet-j81f2?file=/src/App.js

**Comment by temanisparsh** [comment] 2021-04-19 15:46
> @DaveOdden (and others) For V2- I was able to enable editable text by setting the `inputValue` prop on the `Select` to be whatever text I wanted to show in the input, which works, except for when I select a value in the dropdown, which appears to clear the input, but in actuality sets the opacity to 0. For that, I had to set `opacity: 1 !important;` in my own CSS for `.myContainer input`. It took days to figure this out but the input now behaves much better as you can click on the text, highlight it, the cursor appears at the end of the input like a normal text field. 
> 
> The other thing I had to do was to make sure not to set blank text on the input when the input is focused- the current behavior just clears the input when you click on it, because there is a `menu-close` action happening which unintentionally sets a blank string on the input. For that, in my `onInputChange` handler, I do not set my local react state value when `!value && action === 'menu-close`, and simply `return` out of the callback so my component is not setting the inputValue to be an empty String.

This worked for me, Thanks
