### ISSUE TITLE
Cleaning control showed only when one of the options is selected 

### ISSUE THREAD

**Issue by DioNNiS** [JedWatson/react-select#3094] opened 2018-10-04 23:42 UTC
subj

Steps to reproduce:
1. Open page - https://codesandbox.io/s/m7220vl7jp
2. type "test" into input element
Expectations: cleaning element should be shown
Actual result: cleaning control not shown

initial state:
`isClearable` true
`isSearchable` true

**Comment by Chopinsky** [comment] 2018-10-08 19:53
I think here, "clearable" means for clearing a selected option, instead of clearing the input text

**Comment by DioNNiS** [comment] 2018-10-22 23:06
This seems strange

**Comment by gwyneplaine** [comment] 2018-10-24 05:51
@DioNNiS  as above this is not a bug, the isClearable prop is for clearing the selected values from state, not for clearing the inputValue. There is no mechanism for clearing the inputValue through the UI, as there are already native mechanisms in place for you to do so easily (cmd + backspace).

Closing this issue

**Closed by gwyneplaine** 2018-10-24 05:51 UTC
