### ISSUE TITLE
v0.6.2: The latest changes from src are not included in lib or dist

### ISSUE THREAD

**Issue by burtyish** [JedWatson/react-select#387] opened 2015-08-18 13:46 UTC
Looks like build needs to be updated

**Comment by brianreavis** [comment] 2015-08-18 15:15
Duplicate of https://github.com/JedWatson/react-select/issues/386.

**Closed by brianreavis** 2015-08-18 15:15 UTC

**Comment by JedWatson** [comment] 2015-08-18 16:28
As per #386, very sorry about this! Just published a new version with the correct build (0.6.3)
