### ISSUE TITLE
Links to codesandbox example code do not work

### ISSUE THREAD

**Issue by garrettmaring** [JedWatson/react-select#3718] opened 2019-08-15 00:44 UTC
It looks like none of the [CodeSandbox](https://codesandbox.io) links work.

![Screen Shot 2019-08-14 at 5 42 53 PM](https://user-images.githubusercontent.com/8270120/63065501-24f97200-bebb-11e9-8adf-1d9f6f3b0fde.png)

**Comment by Eugenijus** [comment] 2019-08-30 12:02
True, I reproduced.
Right hand side screen doesn't render and shows Error on first visit:
`Could not find module in path: 'react-syntax-highlighter/prism-light' relative to '/docs/styled-components.js'`

Then in styled-components file, for code `{ Tag?: string })` the error says:
`'types' can only be used in a .ts file.`

in example.js for code `type State = {` error says:
`'type aliases' can only be used in a .ts file.`

...for `Component<*, State>` the error says:
`'type arguments' can only be used in a .ts file.`

**Comment by Eugenijus** [comment] 2019-08-30 12:09
Fixed by removing Note and Checkbox components, because I can do without them while learning how to use react-select. :)
Here is the link:
https://codesandbox.io/embed/react-codesandboxer-example-mqtof

**Comment by bladey** [comment] 2020-05-28 03:55
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Closed by bladey** 2020-05-28 03:55 UTC
