### ISSUE TITLE
Bug, npm fails to minify with create-react-app

### ISSUE THREAD

**Issue by Geczy** [JedWatson/react-select#1974] opened 2017-09-10 13:21 UTC
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

```
You may occasionally find a package you depend on needs compiled or ships code for a non-browser environment.
This is considered poor practice in the ecosystem and does not have an escape hatch in Create React App.

To resolve this:

Open an issue on the dependency's issue tracker and ask that the package be published pre-compiled (retaining ES6 Modules).
```

**Comment by Geczy** [comment] 2017-09-10 13:24
https://github.com/facebookincubator/create-react-app/issues/984

**Comment by Geczy** [comment] 2017-09-10 13:32
https://github.com/JedWatson/react-select/issues/966

**Comment by Geczy** [comment] 2017-09-10 13:38
```
Failed to minify the code from this file: 

        ./node_modules/react-select/lib/Select.js:39 

```

https://github.com/JedWatson/react-select/blob/master/lib/Select.js#L39

**Comment by Geczy** [comment] 2017-09-10 13:40
https://github.com/ionic-team/ionic-app-scripts/issues/1032

**Comment by Geczy** [comment] 2017-09-10 15:08
`import Select from 'react-select/dist/react-select'`

Am able to bypass error by doing this import instead for now

**Comment by scoumbourdis** [comment] 2017-09-10 21:11
Thanks @Geczy,

At least now I can try it :)

**Comment by agirton** [comment] 2017-09-11 02:54
Closing as a duplicate of #1971

**Closed by agirton** 2017-09-11 02:54 UTC
