### ISSUE TITLE
Cannot select menu items on mobile

### ISSUE THREAD

**Issue by vitaminwater** [JedWatson/react-select#1036] opened 2016-06-18 16:20 UTC
I got on a bug preventing me from selecting any menu items on mobile only.
Turns out, selecting an item would trigger `handleInputFocus` with `Select-input` as target.

Removing the call to `renderInput` for non-searchable select fixed it.

**Comment by Moeface** [comment] 2016-06-20 06:16
Also having this same issue, though only on iOS devices - both Chrome and Safari. Works fine on Android phones.

**Comment by adamwan92** [comment] 2016-06-27 03:39
Same bug here. Have to hold the item on mobile for it to work, pretty annoying!

**Comment by adamwan92** [comment] 2016-06-27 04:16
@vitaminwater Can you explain what you did when you said 

> Removing the call to renderInput for non-searchable select fixed it.

**Comment by vitaminwater** [comment] 2016-06-27 10:30
@adamwan92 I got it to work by changing something in there code, did not make a pull request because of lack of time, and because I don't really know if I'm not breaking anything else.

Maybe @JedWatson got what I was talking about ? Interested in a PR for this ?

**Comment by adamwan92** [comment] 2016-06-27 13:17
@vitaminwater A PR or even a copy past of the code that you changed would help very much!

It's weird cause running the demo (jedwatson.github.io/react-select) works very well on mobile.

**Comment by vitaminwater** [comment] 2016-06-27 14:35
@adamwan92 ok thats' really dirty for now: in `node_modules/react-select/lib/Select.js`, line 938, replace `this.renderInput(valueArray)` with `this.props.searchable ? this.renderInput(valueArray) : null,`.

But honestly I can't really encourage you to do this, the change will be lost as soon as you update the package.

**Comment by adamwan92** [comment] 2016-06-27 15:22
@vitaminwater thanks so much for the help, but I'm afraid that doesn't solve the issue for me.

**Comment by peterkuiper** [comment] 2016-07-12 09:33
Same problem here, is there a PR already? If not I can create one. Not sure if the fix by @vitaminwater is good enough

**Comment by NekR** [comment] 2016-07-26 09:49
I don't know, but I cannot select even on desktop right now (Chrome/macOS)

**Comment by NGuldager** [comment] 2016-11-07 12:18
Anyone know the status of this? I have a similar issue but when using the solution @vitaminwater supplied, then it works fine.

**Comment by idanwe** [comment] 2017-01-02 20:25
Fast click has a disable hook, add `needsclick` class to option element https://github.com/ftlabs/fastclick#ignore-certain-elements-with-needsclick

**Comment by mpigsley** [comment] 2017-03-16 19:37
Any update on this? @peterkuiper did you get a PR ready?

**Comment by peterkuiper** [comment] 2017-03-17 09:52
@mpigsley Well, at the time we decided to go with a different solution and currently we have rolled on our solution for it. Looking at the open issues and the open PRs, I assume the author is having quite a big backlog. So sorry, no, I did not get a PR ready.

**Comment by mpigsley** [comment] 2017-03-20 14:52
For anyone else who runs into this, you can [disable fastclick](https://github.com/ftlabs/fastclick#ignore-certain-elements-with-needsclick) on the option elements by adding the prop `optionClassName="needsclick"` instead of removing it entirely.

**Comment by JedWatson** [comment] 2017-10-27 04:45
I'm pretty confident this has been addressed in the latest version, if anyone can still reproduce it please let me know with steps explaining how. Thanks!

**Closed by JedWatson** 2017-10-27 04:45 UTC

**Comment by alexeykozlov07** [comment] 2017-11-01 15:46
react select is still not work on iPhone. I use latest version of react-select

**Comment by Shadowman4205** [comment] 2018-01-11 12:50
@JedWatson 
Hello,  i tried toggle device with chrome dev tool,
and cannot select option

**Comment by Under-Warz** [comment] 2018-01-23 15:34
@alexeykozlov07 / @JedWatson add `optionClassName="needsclick"` worked for me (thx @idanwe )

**Comment by mlukjanska** [comment] 2019-03-02 00:26
For me in react-select v.2.4.0 it works, but might have been a conflict due to having react-select-simplevalue included as well.

**Comment by CharlieBreval** [comment] 2019-04-02 10:21
Make sure not to use a button in your option Component if you want the handleChange to be triggered     when selecting an option.

**Comment by florentdestremau** [comment] 2019-07-09 16:06
Using Firefox 67.0.4, with iPhone 6/7/8 Plus simulator, I can't use the examples on https://react-select.com/home with the mouse. Whenever I hover the dropdown elements the menu closes

**Comment by MrYou0** [comment] 2020-03-07 11:55
> @ alexeykozlov07 / @JedWatson添加`optionClassName="needsclick"`对我有用（thx @idanwe）

what can i do?, it seems don't support optionClassName property

**Comment by leonardobork** [comment] 2020-04-02 13:19
@MrYou0 @florentdestremau same as you guys

**Comment by georgiosgiatsidis** [comment] 2020-11-09 15:53
It seems like `optionClassName` is not a supported property. I overrided Option component instead.

`import ReactSelect, { components } from 'react-select';`

`const CustomOption = props => <components.Option className="needsclick" {...props} />;`

`<ReactSelect components={{
                Option: CustomOption
            }}
/>`

**Comment by ziaulrehman40** [comment] 2022-02-01 18:47
optionClassName seems to work in latest versions, but this should not be needed.
