### ISSUE TITLE
Cannot open dropdown after value was selected

### ISSUE THREAD

**Issue by enheit** [JedWatson/react-select#1887] opened 2017-07-24 13:05 UTC
I have found an issue which is not allow you to re-open dropdown after value selecting.

Create component `<Select options={ ... } value={ ... } />`. Add additional property to prevent dropdown resizing `autosize={ false }`. Click on the dropdown body `->` select value `->` try to click on the body again... Component is not opening anymore, cuz input took some size of component and this occupied area is not clickable anymore. You can re-open input by clicking on the arrow button, click out of component and click on the body again, click at some side of component (not at the middle).  

Images (GIFs) are shown in related post: https://github.com/JedWatson/react-select/issues/1886
Codesandbox: https://codesandbox.io/s/qx4v3k2py

P.S. Temporary workaround is to add `autoBlur` to the component which do the same click outside.

**Comment by agirton** [comment] 2017-07-24 16:42
HI @enheit thank you for reporting the issue with a reproducible case. Will take a look.

**Comment by dariuszpaluch** [comment] 2017-08-30 09:27
+1

**Comment by cbergmiller** [comment] 2017-09-01 12:10
I think this is a duplicate in respect to:
https://github.com/JedWatson/react-select/issues/1316

See also the discussion here:
https://github.com/JedWatson/react-select/pull/1746

**Comment by ls-guillaume-lambert** [comment] 2017-09-13 18:09
So the fix in #1746 won't be merged for this I presume? For now the only workaround is to set `autoBlur` to `true`? This breaks accessibility as I have to re-focus in the field now to change the value.

**Comment by ls-guillaume-lambert** [comment] 2017-09-14 14:22
Found a workaround for this in the mean time, in the CSS:

```css
.has-value.is-pseudo-focused .Select-input {
  // Always show the input even on pseudo-focused. This fixes an issue
  // when `autosize` is set to `false`, an option is chosen, and we
  // try to re-open the menu by clicking on the current option.
  // The `opacity: 0;` below makes it that we can't click to open the
  // menu unless we focus out, or click on the "clear" or "arrow".
  // More on this here: https://github.com/JedWatson/react-select/issues/1887
  // opacity: 0;
}
```

Not the best as it always shows the blinking cursor even if its in pseudo-focused state, but we thought its much better than not being able to re-open the menu by clicking. Also, even in pseudo-focused mode you can type, so having the `text` cursor clearly shows the user he can still type to change the value.

I'll keep an eye on this issue and if I have time try to find a fix and submit a PR.

**Comment by ls-guillaume-lambert** [comment] 2017-09-14 14:34
Another finding, again for https://github.com/JedWatson/react-select/blob/49b12b06b98b046cff923b9a5dd4689506ef07ac/less/control.less#L98:

If I put `visibility: hidden;` instead of `opacity: 0;` then I can re-open the menu on click successfully. @agirton would you see any possible issues down the road if it was changed like this?

**Comment by ls-guillaume-lambert** [comment] 2017-09-14 14:48
Nevermind https://github.com/JedWatson/react-select/issues/1887#issuecomment-329501853, this makes the Select blur since its not visible, I'd rather keep the focus and have the `text` cursor 😉

**Closed** 2017-11-24 05:07 UTC
Labels: bug blocker

**Comment by JedWatson** [comment] 2017-11-24 05:08
I've been able to reproduce this and resolved it, see the referenced commit for more information

**Comment by tudiantuan** [comment] 2019-10-23 12:20
I use version "react-select": "^2.3.0"  is still cannot open dropdown after value was selected.
