### ISSUE TITLE
AutoSize Input throwing warning for minWidth prop

### ISSUE THREAD

**Issue by Suzanna-Manoj-Williams** [JedWatson/react-select#1080] opened 2016-07-11 10:58 UTC
Warning: Unknown prop `minWidth` on <input> tag. Remove this prop from the element.
    in input (created by AutosizeInput)
    in div (created by AutosizeInput)
    in AutosizeInput (created by Select)

**Comment by gabrielenosso** [comment] 2016-07-11 11:58
+1.
It's a warning that React added in its last release (15.2.1).
https://facebook.github.io/react/warnings/unknown-prop.html

**Comment by gabrielenosso** [comment] 2016-07-11 11:58
Anyway the issue is a duplicate of https://github.com/JedWatson/react-select/issues/1063

**Comment by sandroweb** [comment] 2017-01-30 21:02
Ok, that is an unknown prop, I seen that in various places, but for me use this plugin, you know any form?

Or this plugin need a fix?

**Comment by bladey** [comment] 2020-05-27 06:17
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.

**Closed by bladey** 2020-05-27 06:17 UTC
