### ISSUE TITLE
Add alwaysDisplayPlaceholder prop (a Floating Label theme)

### ISSUE THREAD

**Issue by carlosbensant** [JedWatson/react-select#2152] opened 2017-11-17 20:42 UTC
Thank you for this library!

**Floating Label:**
I'd like to create a Floating Label theme for this package (just using CSS), but it expects the placeholder to persist along with the current value.

The **alwaysDisplayPlaceholder** prop would be an outstanding option for what I'm expecting to see.

Here is my use case:

- Initially, in my form, [labels are everywhere](https://memegenerator.net/img/instances/500x/60263440/labels-labels-everywhere.jpg).
<img width="636" alt="initial" src="https://user-images.githubusercontent.com/3604917/32965366-a32f1e94-cbac-11e7-9db4-ac20b24b8ef6.png">

- Then it floats the inline label up above the input after the user focuses the select.
<img width="636" alt="choosing an option" src="https://user-images.githubusercontent.com/3604917/32965365-a31cec92-cbac-11e7-9240-17ca8c18f285.png">

- Finally, when an option is selected, the inline label disappears entirely.
<img width="636" alt="an option selected" src="https://user-images.githubusercontent.com/3604917/32965364-a30854bc-cbac-11e7-98da-03083c3c423e.png">

Cheers!

**Comment by carlosbensant** [comment] 2017-11-17 20:46
Also see - #2143 #1126

**Comment by tiffwu** [comment] 2018-01-09 16:42
I'd love this too, please! I don't want to have to fork this repo.

**Comment by carlosbensant** [comment] 2018-01-09 18:51
To leave an update, I just created a component wrapper which contains the label, then removed the Select built-in label and finally listened to the Select events 'onBlur', 'onChange', 'onFocus' to style the label as desired.

If needed I could share a CodePen with a better explanation, just let me know.

**Comment by tiffwu** [comment] 2018-01-10 15:28
Yes, a CodePen would be fantastic @carlosbensant

**Comment by tiffwu** [comment] 2018-01-10 15:41
Just to clarify, my issue is slightly different from yours - I need the placeholder specifically to stick around, not the label:

![image](https://user-images.githubusercontent.com/11621425/34781050-ae08a96e-f5d9-11e7-8231-adeeee496395.png)

**Comment by kccmcck** [comment] 2018-02-08 22:55
@carlosbensant, I'd also greatly appreciate a CodePen with your working example!

**Comment by Alonmeytal** [comment] 2018-02-12 22:41
@carlosbensant a CodePen would be greatly appreciated!

**Comment by clovis1122** [comment] 2018-02-23 17:06
@carlosbensant , that's fantastic! I would like to see the codepen as well.

**Comment by MaximeNoulin** [comment] 2018-08-09 08:45
@carlosbensant That would be great! Could you please share it with us?

**Comment by Code-Crash** [comment] 2018-08-09 16:40
+1

**Comment by sahilchopra** [comment] 2018-10-11 04:47
+1

**Comment by dzbiku** [comment] 2018-12-03 08:50
Please, share it! ;) +1

**Comment by duftwatterson** [comment] 2019-01-07 00:40
@carlosbensant Would love to see the codepen for this!

**Comment by philibea** [comment] 2019-01-28 16:45
> To leave an update, I just created a component wrapper which contains the label, then removed the Select built-in label and finally listened to the Select events 'onBlur', 'onChange', 'onFocus' to style the label as desired.
> 
> If needed I could share a CodePen with a better explanation, just let me know.

@carlosbensant Hi! Please share it ? thank you !

**Comment by c-moss-talk** [comment] 2019-03-04 19:18
Here's what we do as a [gist](https://gist.github.com/c-moss-talk/b9b6f267a9f658f5bd1d7e115495e0aa)

If anyone wants to try and make this possible without a wrapper, I think it should be a part of the library. Let me know, with some help, I think we can work out a better solution.

**Comment by Rall3n** [comment] 2019-03-08 10:57
@c-moss-talk Done. [Here is the example](https://codesandbox.io/s/6x9405rlqk).

All I did was using the [Components Framework](https://react-select.com/components) `react-select` provides to customize the `ValueContainer` in which `Placeholder` resides.

**Comment by c-moss-talk** [comment] 2019-03-08 16:33
@Rall3n yup, that's perhaps the best approach. Might be a nice example for the docs but I think we can close this (I don't have a role on this repo).

**Comment by FlavyP** [comment] 2019-03-27 09:32
> @c-moss-talk Done. [Here is the example](https://codesandbox.io/s/6x9405rlqk).
> 
> All I did was using the [Components Framework](https://react-select.com/components) `react-select` provides to customize the `ValueContainer` in which `Placeholder` resides.

Hi @Rall3n, thanks for the codesandbox! I have tried adding it to my project, but I noticed it's not working on the latest version of react-select (2.4.2 at the time of this comment). As you can see, the placeholder stays inside the container itself and not overriding it.

![sandbox](https://user-images.githubusercontent.com/9482352/55065142-9a36e880-507b-11e9-91bb-4932a533c64e.PNG)


Do you have any idea how we can modify it to continue working?

Thanks!

**Comment by Rall3n** [comment] 2019-03-27 10:25
Seems the sandbox was still on a very old version of the library. This [commit](https://github.com/JedWatson/react-select/commit/efaa25e2f0a365708de9bad5a1dd282497bf1e30) added `overflow: hidden` to the `ValueContainer` which is the cause for your problem. Changing the style to remove overflow should make it work again.

**Comment by FlavyP** [comment] 2019-03-28 12:44
> Seems the sandbox was still on a very old version of the library. This [commit](https://github.com/JedWatson/react-select/commit/efaa25e2f0a365708de9bad5a1dd282497bf1e30) added `overflow: hidden` to the `ValueContainer` which is the cause for your problem. Changing the style to remove `overflow: hidden` should make it work again.

Thank you, managed to fix it by adding `overflow: "visible"`

**Comment by chromale** [comment] 2019-09-17 10:05
I’ve created a solution for floating input using `styled-components` and `react-select` components API. 

Feel free to check it:
https://github.com/purple-technology/phoenix-components/blob/master/src/SelectBox/index.tsx

Result look like this:
![image](https://user-images.githubusercontent.com/10242446/65032386-5397bc00-d943-11e9-9aaa-4e328416950b.png)

Thanks @c-moss-talk for inspiration 👍

**Comment by chrisgem** [comment] 2020-03-10 23:23
Came to a solution with a co-worker based on @Rall3n and @c-moss-talk comments 

`
import Select, {components} from 'react-select';

const styles = {
  placeholder: (base, state) => ({
    ...base,
    display: 
      state.isFocused || state.isSelected || state.selectProps.inputValue
      ? 'none'
      : 'block',
  }),
}

export default ({ placeholder }) => {
  const NewValueContainer = (props) => {
    const shouldFloatLabel = props.selectProps.menuIsOpen || props.hasValue;

    <components.ValueContainer {...props}>
      {shouldFloatLabel && <p>{placeholder}</p>}
      {props.children}
    </components.ValueContainer>
  };

  return (
    <Select 
      ...
      styles={styles}
      placeholder={placeholder}
      components={{ ValueContainer: NewValueContainer }}
    />
    );
}
`

**Comment by Cammac7** [comment] 2020-05-19 05:34
I have tried all of the above but somehow can't keep the placeholder in the DOM. It is removed from the HTML as soon as I choose a value for the select. Which, I assume means somewhere it is being made `display: none`
I've tried everything to keep the placeholder, but it won't stay. Given the below, any thoughts?
```
placeholder: (provided, state) => ({
        position: "absolute",
        marginTop: '-30px',
        display: 
      state.isFocused || state.isSelected || state.selectProps.inputValue || state.value
      ? 'block'
      : 'block',
      }),
```

**Comment by bladey** [comment] 2020-05-28 05:10
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Closed by bladey** 2020-05-28 05:10 UTC

**Comment by cseas** [comment] 2020-09-29 10:42
You can add a floating label without needing to modify the placeholder at all. Just add a label to a custom control component. [This comment](https://github.com/JedWatson/react-select/issues/4221#issuecomment-700617916) explains how.

I was inspired by [Rall3n's solution](https://github.com/JedWatson/react-select/issues/2152#issuecomment-470889515) but that only made the placeholder float when we type something and not on click as is expected in most floating labels.

**Comment by longvd89** [comment] 2022-02-15 04:26
> To leave an update, I just created a component wrapper which contains the label, then removed the Select built-in label and finally listened to the Select events 'onBlur', 'onChange', 'onFocus' to style the label as desired.
> 
> If needed I could share a CodePen with a better explanation, just let me know.

Could you share it please ?

**Comment by EliasSalom** [comment] 2023-01-31 09:00
> > I’ve created a solution for floating input using `styled-components` and `react-select` components API.
> > Code is here: https://github.com/purple-technology/phoenix-components/blob/master/src/SelectBox/index.tsx
> > It’s a version with outlined border, but it’s easy to change it to any other type. The result look like this: ![image](https://user-images.githubusercontent.com/10242446/65032386-5397bc00-d943-11e9-9aaa-4e328416950b.png)
> > Thanks @c-moss-talk for inspiration 👍
> 
> Your link is 404ing. Can you share the relevant code or a sandbox of a small example?

the link doesn't work !!!

**Comment by peterqliu** [comment] 2023-05-16 07:02
❗ we can also achieve this with **only CSS**!  

the `styles` param gives us access to the inner `input` element. By adding CSS `content` after this element, we can mimic placeholder behavior by keying the text content off of whether there's text in the input (`state.value`). fade it out a bit and it'll look pretty dang close.

```
<Select
  isMulti={true}
  styles={{
    input: (baseStyles, state) => {
            "&:after": {
              content: !state.value.length ? '"Placeholder!"' : '""',
              opacity: 0.5,
       }
    }
  }}
/>
```

<img width="280" alt="Screenshot 2023-05-15 at 11 59 50 PM" src="https://github.com/JedWatson/react-select/assets/4551508/813354e1-34b5-4ec6-b9db-2d5b736e420c">

For some reason the input goes to near zero width after the first tag, so alignment isn't really a problem.
