### ISSUE TITLE
no way to set primitive value(s) directly

### ISSUE THREAD

**Issue by mysuf** [JedWatson/react-select#4462] opened 2021-02-24 03:42 UTC
First, I tried to find similar issue here, but without luck. You can find this on stackoverflow in number of forms, but the root cause is still the same. react-select produces value as ValueType `{value: any, label: string}`(or with custom props), but it actually represents option used by component. Value is a property of this object, not an object itself. The result is that form with primitive field f.e. ` user_id: int` can not be set as integer directly, it is always ValueType. I saw only workarounds with onSubmit and mapping options back to values which is..well..ugly. Also it seems that getOptionValue is used only to stringify and compare value, not to actually get/set value.. If I missed some simple approach, I appreciate any advice, otherwise it looks like serious drawback..

**Comment by ebonow** [comment] 2021-02-24 05:43
Greetings @mysuf ,

Agreed, `value` is probably one of the most confusing terms used within react-select.

Each option is represented as an object consisting of a defined or derived "value" as you stated above. When an option is "selected" it is said to be the "value" of the react-select. So as is, it represents the selected "option" or "options".

This is both confusing and frustrating for many people because it does deviate from the expected behavior of a native select. As such, it is being discussed as something that may be reconsidered in a future version.

Until then, please consider the value prop more as "selected" and that the real value will likely be something like `value.value`

I am not sure if this clears anything up, but was hoping to provide any context that may have been missed.

**Comment by mysuf** [comment] 2021-02-24 11:09
Hi @ebonow
I'm react newbie, but isn't there way to make a wrapper that will map option to value? I mean creating one layer within custom component that will transform value <-> ValueType (considering that value is always present within fieldProps.options). Thanks

**Comment by mysuf** [comment] 2021-02-24 13:36
I think I've figured it out:

```
import React from "react";
// components
import { Controller, useFormContext } from "react-hook-form";
import Form from "react-bootstrap/Form";
import Select from 'react-select';

function SelectField({ label, labelKey, getOptionLabel, formatValueLabel, ...fieldProps }) {
	const { control, setValue, getValue } = useFormContext();
	const isMulti = 'isMulti' in fieldProps;

	const getSelectedOption = (value) => {
		if (!value && value !== 0) {
			return null;
		}
		if (!getOptionLabel) {
			if (isMulti) {
				return fieldProps.options.filter(opt => value.includes(opt.value)).map(opt =>
					(formatValueLabel ? {value: opt.value, label: formatValueLabel(opt.label)} : opt)
				)
			}
			const opt = fieldProps.options.find(opt => value === opt.value);
			if (formatValueLabel) {
				return {value: opt.value, label: formatValueLabel(opt.label)}
			}
			return opt;
		}
		if (isMulti) {
			return value.map(val => ({
				value: val,
				label: formatValueLabel ? formatValueLabel(getOptionLabel(val)) : getOptionLabel(val),
			}));
		}
		return {
			value: value,
			label: formatValueLabel ? formatValueLabel(getOptionLabel(value)) : getOptionLabel(value),
		}
	}

	const getSelectedValue = (options) => {
		return (isMulti ? options.map(opt => opt.value) : options.value)
	}

	const renderSelect = ({ onChange, onBlur, value }) => {
		return (
			<Select
				onChange={option => onChange(getSelectedValue(option))}
				onBlur={onBlur}
				value={getSelectedOption(value)}
				{...fieldProps}
			/>
		)
	};

	return (
		<Form.Group controlId={`select-field-${fieldProps.name}`}>
			{label && <Form.Label>{label}</Form.Label>}
			<Controller control={control} render={renderSelect} {...fieldProps} />
		</Form.Group>
	);
}

export default SelectField;
```

**Comment by ebonow** [comment] 2021-02-24 15:19
It's probably worth adding that if you specify a name, it will add a hidden field that gets set to the value of the selected options. This makes its value natively accessible to the form.

In case you were looking for an example of how to integrate react-select into react-hook-form, here is an example from RHF using react-select (among many other libraries) [demo example](https://codesandbox.io/s/react-hook-form-controller-079xx)

Let me know if you have any further questions but it would seem that you have a working solution and on the right direction so it seems safe to close this now.

**Closed by ebonow** 2021-02-24 15:19 UTC

**Comment by mysuf** [comment] 2021-02-24 15:38
I got the name property within fieldProps passed to custom SelectField. You can see fieldProps destructed into react-select props above - name is one of them. Thank you.

**Comment by ivanov-v** [comment] 2023-01-11 13:37
> I think I've figured it out:
> 
> ```
> import React from "react";
> // components
> import { Controller, useFormContext } from "react-hook-form";
> import Form from "react-bootstrap/Form";
> import Select from 'react-select';
> 
> function SelectField({ label, valueIdKey, formatValueLabel, ...fieldProps }) {
>   const { control, setValue, getValue } = useFormContext();
>   const isMulti = 'isMulti' in fieldProps;
> 
>   if (valueIdKey) {
>     fieldProps.getOptionValue = (opt) => opt && opt.value ? opt.value[valueIdKey] : null;
>   }
> 
>   const getSelectedOption = (value) => {
>     if (value === undefined || value === null) {
>       return value;
>     }
>     if (isMulti) {
>       return fieldProps.options.filter(opt => 
>         (valueIdKey ? value.some(val => val && val[valueIdKey] === opt.value[valueIdKey]) : value.includes(opt.value))
>       ).map(opt =>
>         (formatValueLabel ? {value: opt.value, label: formatValueLabel(opt.label)} : opt)
>       )
>     }
>     const opt = fieldProps.options.find(opt => 
>       (value && valueIdKey ? value[valueIdKey] === opt.value[valueIdKey] : value === opt.value)
>     );
>     if (opt && formatValueLabel) {
>       return {value: opt.value, label: formatValueLabel(opt.label)}
>     }
>     return opt;
>   }
> 
>   const getSelectedValue = (options) => {
>     return (isMulti ? options.map(opt => opt.value) : options.value)
>   }
> 
>   const renderSelect = ({ onChange, onBlur, value }) => {
>     return (
>       <Select
>         onChange={option => onChange(getSelectedValue(option))}
>         onBlur={onBlur}
>         value={getSelectedOption(value)}
>         {...fieldProps}
>       />
>     )
>   };
> 
>   return (
>     <Form.Group controlId={`select-field-${fieldProps.name}`}>
>       {label && <Form.Label>{label}</Form.Label>}
>       <Controller control={control} render={renderSelect} {...fieldProps} />
>     </Form.Group>
>   );
> }
> 
> export default SelectField;
> ```

this only way to solve the problem?

**Comment by GrayYoung** [comment] 2025-01-20 06:32
I want the feature, it's a big pain.
