### ISSUE TITLE
[V2] Creatable not aware of getOptionLabel/Value

### ISSUE THREAD

**Issue by torava** [JedWatson/react-select#2673] opened 2018-06-04 23:52 UTC
Following part of Creatable is crashing because it doesn't find option label or value which I have defined in getOptionLabel and getOptionValue.

```
var compareOption = function compareOption(inputValue, option) {
  var candidate = inputValue.toLowerCase();
  return option.value.toLowerCase() === candidate || option.label.toLowerCase() === candidate;
};
```

**Comment by sabotag** [comment] 2018-06-06 14:37
I have the same problem, I need prepare options with strict structure like `{id: 1, value: 'test'}` for Creatable select

**Comment by jprosevear** [comment] 2018-06-08 11:49
Duplicate of #2630

**Comment by bladey** [comment] 2020-05-27 07:01
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue / pull request is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Closed by bladey** 2020-05-27 07:01 UTC
Labels: v2-deprecated
