### ISSUE TITLE
Dropdown goes outside of screen if used on either left or right side of window.

### ISSUE THREAD

**Issue by shahlav** [JedWatson/react-select#3491] opened 2019-03-29 19:35 UTC
I am using react-select to be on right end of the window. I've no other option to relocate it to any where else. When I click on it the dropdown goes outside of the window and it looks as below image.

![image](https://user-images.githubusercontent.com/45399472/55258154-0c7c1880-5288-11e9-8b7e-f4d19053b8da.png)

Is there any work around or a prop available to avoid this kind of situations.

**Comment by ClementeSerrano** [comment] 2019-08-02 15:52
Any update on this issue? Im having the same problem guys

**Comment by Dan-Wood** [comment] 2019-08-05 23:53
+1

**Comment by Rall3n** [comment] 2019-08-06 05:38
Could anyone provide a minimal reproducible example, and the versions of `React` and `react-select`?

**Comment by bladey** [comment] 2020-05-28 06:12
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by SuperMari0o** [comment] 2020-07-06 09:22
The current issue is still exist (even in the latest version 3.1.0). It would be great if you took a look on it.

**Comment by Rall3n** [comment] 2020-07-06 11:11
@SuperMari0o Could you provide a minimal reproducible example of the issue?

**Comment by SuperMari0o** [comment] 2020-07-07 09:00
@bladey, @Rall3n Here is the example of reproduction current issue: https://codesandbox.io/s/react-select-v3-sandbox-6kcol?file=/example.js

**Comment by tylercaceres** [comment] 2020-08-05 14:32
This would definitely be nice. Having the same issue right now as well.
Anyone have a work around?

**Comment by aleksey-selyavkin** [comment] 2020-08-06 14:59
+1

**Comment by aleksey-selyavkin** [comment] 2020-09-07 08:51
@bladey, @Rall3n Will this ticket be in progress, and should we wait for the desired behavior for the @SuperMari0o example (https://github.com/JedWatson/react-select/issues/3491#issuecomment-654706668)?

**Comment by Methuselah96** [comment] 2020-11-14 16:44
I've started [a fork](https://github.com/react-select-oss/react-select) of react-select. Feel free to resubmit this issue on the fork and/or submit a PR to resolve this issue on the fork and we can get it merged and released.

**Comment by ebonow** [comment] 2020-12-19 05:07
@SuperMari0o 
> We have dropdown on the right side of the page, also with fixed width and want to open options in one line. We expect the options menu to align on the right side.

Maybe I am missing something, but if you want the menu to align on the right side, then why not just position the Menu: `right: 0`?

Working demo: [codesandbox](https://codesandbox.io/s/react-select-v3-sandbox-menu-portal-right-812b9)

```js
const styles = {
  menu: () => ({
    position: "absolute",
    right: 0
  })
}

return <Select styles={styles} {...otherProps} />
```

This seems to be working. If no one has objections on this I will close this out, but in case I am missing something, please let me know and I can re-open this.

**Closed by ebonow** 2020-12-19 05:07 UTC
Labels: issue/bug-unconfirmed, issue/reviewed

**Comment by aleksey-selyavkin** [comment] 2020-12-19 12:05
Thank you for your advice but in our case, we have a floating layout and we don't know where the dropdown will appear.

**Comment by ebonow** [comment] 2020-12-19 16:18
@aleksey-selyavkin 

A menu by default is set to constrain the width of the menu to the same width as the Select to avoid this.

In the provided example, the Option has `white-space: nowrap` preventing line-wrapping and thus causing the MenuList to be wider than expected. Because this width is wider than the Select, the positioning no longer appears to work. I suspect that is what is happening as well in your case or the original posters case, (though I have no idea what I am looking at in that screenshot because of the cropping).

**How can you solve this?** 
Ensure that the width of your options and menuList are not touched so that they naturally fit in the assigned width of the menu.

**What if you want a bigger menu than your select?** 
If someone is going to be responsible for putting the Menu in a portal, increasing the width beyond the default setting, and then moving that portal target anywhere between the left to right edges of the screen, then it seems reasonable that the user needs to be responsible for positioning the menu.

Fortunately, the styles api provides you this kind of flexibility, but not without having to do the calculation to determine where it should go. So, how do you calculate this? 

Not sure it's worth the effort to you, but you'd likely want to use an IntersectionObserver, 
1. create a ref or use a class variable. 
2. `onMenuOpen`, setTimeout 1ms, getMenuListRef from selectRef, create callback function for Intersection observer, set ref to intersectionobserver with callback
3. IntersectionCallback should compare to ensure intersectionRect.width >= boundingClientRect.width and if not, set a state variable indicating alignMenuRight
4. use state variable in styles api to conditionally add right: 0
5. `onMenuClose`, remove intersectionobserver (assuming ref is still available which it might not be) and clear ref

I could and still may put up a codesandbox example, but this is likely how I would approach it. This is a lot of heavy lifting for an edge case which seemingly can be avoided. I am also willing to consider that there may be simpler ways to identify if a component has wrapped to a new line and should be positioned left or right. 

I hope this answers your question or concern, but end of the day, just make sure the option width isn't being stretched beyond the menu width and this should be avoidable. It is possible I am missing something and there might be other use cases, so feel free to include a codesandbox and I can take a look.

**Comment by ebonow** [comment] 2020-12-19 18:10
@aleksey-selyavkin 
Here is a working solution for edge detection using IntersectionObserver. I'd likely use some hide/show mechanism to avoid the UX visual experience of the edge snapping taking place, but that's fairly straightforward. 

Working demo: [codesandbox](https://codesandbox.io/s/react-select-v3-intersection-observer-menu-position-pfly8)

```jsx
const EdgeAligningMenuSelect = (props) => {
  const [alignRight, setAlignRight] = useState(false);

  const menuObserver = useRef({});
  const selectRef = useRef();

  const onMenuOpen = () => {
    const observeOnscreen = (entries = []) => {
      const { boundingClientRect, intersectionRect } = entries[0];
      const isOffscreen = boundingClientRect.width < intersectionRect.width;
      setAlignRight(!isOffscreen);
    };

    setTimeout(() => {
      const menuList = selectRef.current.select.menuListRef;
      //console.log("menu opened", menuList);

      menuObserver.current = new IntersectionObserver(observeOnscreen);
      menuObserver.current.observe(menuList);
      //console.log(menuObserver.current);
    }, 1);
  };

  const onMenuClose = () => {
    //console.log("menu closed");

    setAlignRight(false);
    menuObserver.current.disconnect();
    //console.log(menuObserver.current);
  };

  const customStyles = {
    menu: () => ({
      position: "absolute",
      boxShadow: "0 20px 54px 0 rgba(0,0,0,0.5)",
      top: "2.5rem",
      ...(alignRight && { right: 0 })
    }),
    option: (provided) => ({
      ...provided,
      whiteSpace: "nowrap"
    })
  };

  return (
    <div style={{ width: "150px" }}>
      <Select
        ref={selectRef}
        menuPortalTarget={document.getElementById("portal")}
        className="basic-single"
        classNamePrefix="select"
        name="color"
        options={stateOptions}
        styles={customStyles}
        menuPlacement="auto"
        menuShouldBlockScroll={false}
        onMenuOpen={onMenuOpen}
        onMenuClose={onMenuClose}
      />
    </div>
  );
};
```

**Comment by aleksey-selyavkin** [comment] 2020-12-19 20:52
@ebonow Many thanks for your effort.

**Comment by deepaknxt** [comment] 2024-12-30 10:18
> @SuperMari0o
> 
> > We have dropdown on the right side of the page, also with fixed width and want to open options in one line. We expect the options menu to align on the right side.
> 
> Maybe I am missing something, but if you want the menu to align on the right side, then why not just position the Menu: `right: 0`?
> 
> Working demo: [codesandbox](https://codesandbox.io/s/react-select-v3-sandbox-menu-portal-right-812b9)
> 
> ```js
> const styles = {
>   menu: () => ({
>     position: "absolute",
>     right: 0
>   })
> }
> 
> return <Select styles={styles} {...otherProps} />
> ```
> 
> This seems to be working. If no one has objections on this I will close this out, but in case I am missing something, please let me know and I can re-open this.

That is fine, but it should automatically adjust its position if the options' width exceeds the select width and there is available container space on the right side.
