### ISSUE TITLE
Typescript build error 

### ISSUE THREAD

**Issue by KaySchneider** [JedWatson/react-select#3665] opened 2019-07-03 14:14 UTC
Hi,
actually i implemented react-select into an typescript application and after adding the needed components for an auto-suggest Element with material-ui, i get this build error from typescript:

`````
ERROR in ./node_modules/react-select/src/components/Menu.js 5:7
Module parse failed: Unexpected token (5:7)

You may need an appropriate loader to handle this file type.
| import {
|   Component,
>   type Element as ReactElement,
|   type ElementRef,
|   type Node,
`````

**Comment by HellBrick** [comment] 2019-07-10 16:09
I've encountered a similar issue when TS tooling auto-imported `Select` from `react-select/src/Select`, it can be fixed by importing from `react-select` instead. But the fact that the tooling can be confused like that is somewhat inconvenient =(

**Comment by tvedtorama** [comment] 2019-07-31 08:05
I ran into something similar, as:

```
ERROR in ./node_modules/react-select/src/Select.js
Module parse failed: Unexpected token (3:32)
```

Had to switch from the auto imported thing to:

```typescript
import {default as Select} from 'react-select'
```

For those using Babel, this could maybe also be resolved by adding a flow-preset to babel?

**Comment by ford04** [comment] 2019-08-01 18:41
@types/react-select package should not have types under a `src` folder. If I want `GroupType` or `GroupedOptionsType` from `@types\react-select\src\types.d.ts`, the sources from react-select\src\types.js are instead selected (higher lookup priority for typescript), and then flow types are collected, which break my webpack build that can only handle typescript and complains about unexpected token.

**Comment by pbadenski** [comment] 2019-09-26 16:27
Is there any plan to fix this?

**Comment by IronSean** [comment] 2019-10-30 20:26
![image](https://user-images.githubusercontent.com/1960190/67896012-47a23b00-fb3a-11e9-9cf0-de3b210228f6.png)
Typescript would appear to be the higher priority to get right.

**Comment by wezleytsai** [comment] 2019-11-12 00:33
Poorly documented, but the components are exported as such:

```
import { components } from 'react-select';

// somewhere else
<components.Option {...props} />
```

All the files under `src` are written in Flow and cannot be imported unless your build configuration supports Flow (which worth it to note, CRA does, so this issue is not reproducible in the sandbox).

**Comment by asfernandes** [comment] 2019-11-14 11:23
I was using awesome-type-script loader without a problem and had this error when switching to ts-loader.

I had: `import { Props } from 'react-select/src/Select';` while using `"@types/react-select": "^3.0.5"`.

Updating to `"@types/react-select": "^3.0.8"` it exports Props in `index.d.ts` so I could change the import to `import { Props } from 'react-select';` and had the problem gone.

So I think this bug is not from this project. It was in definitively type and it was fixed.

**Comment by boyskila** [comment] 2020-08-19 13:56
I had the same problem specifically with ```Async``` and ```Creatable``` components and I found how to properly import them from the docs [examples](https://github.com/JedWatson/react-select/blob/master/docs/examples/AsyncCallbacks.js)

Importing from 'react-select' solved the issue partially for me because types were missing

![Screenshot (1)](https://user-images.githubusercontent.com/10514821/90643035-c5efdb00-e23b-11ea-9733-2f2808467193.png)

So instead of ```import Async from 'react-select/src/Async'``` or ```import Async from 'react-select'```  import from the dedicated folder  ```import Async from 'react-select/async'```

![Screenshot (4)](https://user-images.githubusercontent.com/10514821/90643992-e66c6500-e23c-11ea-890c-a1be11e02e6b.png)


I'm using ```@types/react-select: 3.0.13```  and ```react-select: 3.1.0```

**Comment by Methuselah96** [comment] 2020-12-22 01:40
Looks like this is resolved. I'm going to close this for now in an effort to clean up the issues. Feel free to comment if you think this issue is still unresolved.

**Closed by Methuselah96** 2020-12-22 01:40 UTC
Labels: issue/bug-unconfirmed, issue/reviewed
