### ISSUE TITLE
ERROR in Flow validation

### ISSUE THREAD

**Issue by sv-db** [JedWatson/react-select#3816] opened 2019-10-17 15:20 UTC
I'm creating a react-select component as follows:
`<Select
  options={this.days}
  onChange={this.handleSelect}
  className={`col-4`}
  placeholder={`Day`}
/>`

When it using it with flow, im getting the following two errors:

ERROR in Flow validation
Error -- node_modules/react-select/src/Select.js:446:23
Cannot assign defaultComponents(...) to this.components because:
 - property children is missing in props [1] but exists in object type [2] in property Menu.
 - property innerRef is missing in props [1] but exists in object type [2] in property Menu.

Error -- node_modules/react-select/src/components/Input.js:49:3
All branches are incompatible:
 - Either property selectProps is missing in PropsWithStyles [1].
 - Or property selectProps is missing in object type [2].

**Comment by craigdallimore** [comment] 2019-10-30 02:59
Looks like a duplicate of #3612 ?

**Comment by bladey** [comment] 2020-06-18 05:53
Closing as this appears to be a duplicate of #3804.

Further details at #3804.

It appears this will be resolved when PR #3626 is merged.

Please let me know if this is incorrect!

**Closed by bladey** 2020-06-18 05:53 UTC
Labels: bug/unconfirmed
