### ISSUE TITLE
uncaught error.

### ISSUE THREAD

**Issue by pgee70** [JedWatson/react-select#2542] opened 2018-04-23 02:27 UTC
using version v2.0.0-beta.1 / 2018-04-20
installed using command: 
       `yarn add react-select@next`

i have code:
  

    import Select from 'react-select'; 
     .... 
    render() {
      const o = [
        { value: 'chocolate', label: 'Chocolate' },
        { value: 'strawberry', label: 'Strawberry' },
        { value: 'vanilla', label: 'Vanilla' },
      ];
      return (
          <Select options={o} />
      );
    }

the javascript console reports this error:

Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `Select`.
    at invariant (invariant.js:44)
    at instantiateReactComponent (instantiateReactComponent.js:72)
    at Object.updateChildren (ReactChildReconciler.js:115)
    at ReactDOMComponent._reconcilerUpdateChildren (ReactMultiChild.js:204)
    at ReactDOMComponent._updateChildren (ReactMultiChild.js:308)
    at ReactDOMComponent.updateChildren (ReactMultiChild.js:295)
    at ReactDOMComponent._updateDOMChildren (ReactDOMComponent.js:944)
    at ReactDOMComponent.updateComponent (ReactDOMComponent.js:758)
    at ReactDOMComponent.receiveComponent (ReactDOMComponent.js:720)
    at Object.receiveComponent (ReactReconciler.js:122)

**Comment by gwyneplaine** [comment] 2018-04-23 02:40
@pgee70  thanks for reporting this, could you give us a little more information? Which version of react and react-dom are you running? 

If you could also reproduce  and share this in a [codesandbox](https://codesandbox.io/s/) that would be ideal

**Comment by pgee70** [comment] 2018-04-23 04:16
I am using react boilerplate for my project template, and it has my react versions at:

react-dom version = 15.6.2
react version = 15.6.2

i tried upgrading react to version 16, but that caused my project to fail and i simply don't have the experience or time to fix it.

a sample is here: https://codesandbox.io/s/vvqxo1pw83

The error occurs when the component has focus.

**Comment by gwyneplaine** [comment] 2018-04-23 06:48
@pgee70 thanks for this, this is a duplicate of #2522, a fix for this has been applied in #2544, please keep track of the progress on this bug in the issue linked above (closed to dedupe)

**Closed by gwyneplaine** 2018-04-23 06:48 UTC
Labels: v2
