### ISSUE TITLE
Cannot select option when a textarea is under the dropdown

### ISSUE THREAD

**Issue by UserSina** [JedWatson/react-select#4403] opened 2021-01-23 23:15 UTC
The cursor transforms into a text cursor when I hover over the `second_test` and `third_test` because there is a textarea under them.

On click, the react-select closes (without the option selecting) and the textarea is entered.

![trouble_select](https://user-images.githubusercontent.com/44204957/105616612-a0619180-5dd8-11eb-84bd-770b940cfbb5.jpg)

**Comment by ebonow** [comment] 2021-01-23 23:28
Greetings @UserSina,
I am not able to reproduce the issue you are describing. 

test: [codesandbox](https://codesandbox.io/s/amazing-sea-hc6ze?file=/src/App.js)

Would you kindly provide a codesandbox that reproduces the issue you are describing.

**Comment by UserSina** [comment] 2021-01-24 01:04
Unable to reproduce, feel free to close the issue.

However I should note that I'm using react-codemirror2 and not a simple textarea.

**Comment by ebonow** [comment] 2021-01-24 02:31
Thanks for replying. I will close this for now, but feel free to reply or repost if you come across this again and have an example for us to look at.

**Closed by ebonow** 2021-01-24 02:31 UTC
Labels: awaiting-author-response

**Comment by UserSina** [comment] 2021-02-11 11:42
It was apparently an issue with the zIndex, my `textarea` had a higher zIndex than the `Select`

I've added the following and it works!

```JAVASCRIPT
<Select
  menuPortalTarget={document.body} // To make the options display directly under the body element
  styles={{ menuPortal: (base) => ({ ...base, zIndex: 9999 }) }}
  ...
/>
```

Here's the [stackoverflow source](https://stackoverflow.com/a/63898744/10543130).
